= Configuring a Proxy for the Mule Agent
:keywords: agent, mule, esb, servers, monitor, notifications, external systems, third party, get status, metrics

This page details how to configure the Mule agent to send websocket messages through an HTTP proxy.

By default, the Mule agent reads its proxy configuration from the same file that Anypoint API Gateway uses for its proxy configuration. This file is `wrapper.conf`, located under Mule's `conf/` directory. However, you can override the values stored in this file with values specific to the Mule agent, by editing the agent's configuration file.

== Default wrapper.conf File

`$MULE_HOME/conf/wrapper.conf`.

In this file the properties that define proxy configuration are:

* `anypoint.platform.proxy_host`
* `anypoint.platform.proxy_port`
* `anypoint.platform.proxy_username`
* `anypoint.platform.proxy_password`

== Agent-specific mule-agent.yml File

`$MULE_HOME/conf/mule-agent.yml`.

To define proxy configuration specific to the Mule agent, edit the configuration properties in this file as shown below. The properties in this file override those stored in the default `wrapper.conf` file.

[source, yaml, linenums]
----
transports:
  websocket.transport:
    proxyConfiguration:
      host: "http://exampleHost"
      port: 9999
      user: "exampleUser"
      password: "examplePassword"
----


For details on the Mule agent's configuration file, see *Configuring the Agent* in Installing Mule Agent.
