= HL7 ACK Component Reference

The HL7 protocol specifies that when an application receives an HL7 message, it must return a message of type `ACK` (general acknowledge) to the sender. Before generating the ACK message, the receiving application must first check the original HL7 message that it received for formatting errors, missing data and other errors. Then, the receiving application generates the ACK message according to the results.

The *Mule HL7 ACK Component* processes the received HL7 message and automatically generates the appropriate ACK message.

[TIP]
The HL7 ACK Component is part of the link:http://www.mulesoft.org/documentation/display/33X/Mule+HealthCare+Toolkit[Mule Healthcare Toolkit], which also includes transformers and components for receiving, processing and sending HL7 messages. For details and a full list of available tools, consult the Toolkit's link:http://www.mulesoft.org/documentation/display/33X/Mule+Healthcare+Toolkit[documentation main page] .

<<Configuration For Studio and Mule ESB>>

=== Configuration

**Minimum required configuration:** None

==== XML Element

[source, code, linenums]
----
hl7:ack-component
----

==== Sample Complete XML

[tabs]
------
[tab,title="Studio"]
....
[source, xml, linenums]
----
<hl7:ack-component ackCode="AA" validation="WEAK" doc:name="HL7 ACK"/>
----
....
[tab,title="ESB"]
....
[source, xml, linenums]
----
<hl7:ack-component ackCode="AA" validation="WEAK"/>
----
....
------

==== Configuration For Studio and Mule ESB

[tabs]
------
[tab,title="STUDIO Visual Editor"]
....
 General
image:/docs/plugins/servlet/confluence/placeholder/unknown-attachment?locale=en_GB&version=2[image,title="ACK-2.png"]

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Name |Description |XML
|*Display Name* |Name of the building block as it appears in the flow a|`doc:name="HL7 ACK"`
|*ACK / NACK Code* a|
The ACK or NACK (Negative ACK) code for the MSA-1 field of the ACK message. HL7 supports the following codes:

** `AA`: Application Accept
** `AE`: Application Error
** `AR`: Application Reject
a|`ackCode="AA"`
|*Strong / Weak Validation* a|
Allows you to select between STRONG or WEAK HL7 message validation (leave blank for no validation).

** `STRONG`: Checks that all message structure components are present, and that the message is well-formed
** `WEAK`: Only checks that the message is well-formed
a|`validation="STRONG"`
|===
....
[tab,title="XML Editor"]
....
To access the Studio XML Editor, click the *Configuration XML* tab under the canvas.

For details, see link:http://www.mulesoft.org/documentation/display/33X/Mule+Studio+Essentials#MuleStudioEssentials-XMLEditorTipsandTricks[XML Editor trips and tricks].

The table below describes all configurable parameters for this building block.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Name |Description |XML
|*Display Name* |Name of the building block as it appears in the flow a|`doc:name="HL7 ACK"`
|*ACK / NACK Code* a|
The ACK or NACK (Negative ACK) code for the MSA-1 field of the ACK message. HL7 supports the following codes:

** `AA`: Application Accept
** `AE`: Application Error
** `AR`: Application Reject
a|`ackCode="AA"`
|*Strong / Weak Validation* a|
Allows you to select between STRONG or WEAK HL7 message validation (leave blank for no validation).

** `STRONG`: Checks that all message structure components are present, and that the message is well-formed
** `WEAK`: Only checks that the message is well-formed
a|`validation="STRONG"`
|===
....
[tab,title="Standalone"]
....
===== HL7 ACK Component Attributes

[width="100%",cols="20%,20%,20%,20%,20%",options="header",]
|===
a|
Name

 |Type/Allowed values a|
Required

 a|
Default

 a|
Description

|`ackCode` |string |yes |`AA` |ACK code to send to the originating application.
|`validation` |`WEAK / STRONG` |yes |`WEAK` |Allows you to select between STRONG or WEAK HL7 message validation.
|===

===== Namespace and Syntax

[source, code, linenums]
----
http://www.mulesoft.org/schema/mule/hl7
----

===== XML Schema Location

[source, code, linenums]
----
http://www.mulesoft.org/schema/mule/hl7/mule-hl7.xsd
----
....
------

==== Example Message Flow

To send an ACK message to the originating application, place the ACK Component before an HL7 Outbound Endpoint configured with the host name and listening port of the originating application. Consult the link:/mule-healthcare-toolkit/v/3.3/testing-with-hapi-testpanel[example] page to see a simple flow that sends an ACK message using the link:/mule-user-guide/v/3.3/all-flow-control-reference[All Flow Control] and the link:/mule-user-guide/v/3.3/cache-scope[Cache Scope], as well as a more complex link:/mule-healthcare-toolkit/v/3.3/hl7-examples[example] showing how to create and send a custom ACK message.
