= HL7 Mule Expression Language Support

[TIP]
This feature is part of the http://www.mulesoft.org/documentation/display/33X/Mule+HealthCare+Toolkit[Mule Healthcare Toolkit], which also includes transformers and components for receiving, processing and sending HL7 messages. For details and a full list of available tools, consult the Toolkit's http://www.mulesoft.org/documentation/display/33X/Mule+Healthcare+Toolkit[documentation main page] .

The Mule Healthcare toolkit includes two link:/docs/display/33X/HL7+Mule+Expression+Language+Support[Mule Expression Language] (MEL) functions:

* `hl7segment()` allows access to a segment in an HL7 message
* `hl7()` allows access to values within a segment

The functions use the  http://hl7api.sourceforge.net/[HAPI]  (HL7 Application Programming Interface) http://hl7api.sourceforge.net/apidocs/ca/uhn/hl7v2/util/Terser.html[Terser] to provide access to HL7 fields. You can use MEL to access HL7 message contents in any message processor that supports MEL.

=== Examples

[cols=",",options="header"]
|===
2+|Obtaining values
|`hl7('/PID-5-1')` |Returns the value of the `PID-5-1` field of the current message
|`hl7segment('AL1')` |Returns the value of the `Al1` segment of the current message
|===

[cols=",",options="header"]
|===
2+|Modifying values
|`hl7('/PID-5-1', 'Joe')` |Sets the value of the `PID-5-1` field of the current message to `Joe`
|`hl7segment('AL1','AL11^Penicillin Produces hives')` |Sets the value of the `AL1` segment of the current message
|===

=== Usage Examples

Use a link:/docs/display/33X/Variable+Transformer+Reference[Variable Transformer] to initialize the variable `HL7event` with the value of the `EVN` segment of the HL7 message:

[source, xml, linenums]
----
<set-variable variableName="HL7event" value="#[hl7segment('EVN')]"/>
----

Use a link:/docs/display/33X/Set+Payload+Transformer+Reference[Set Payload Transformer] to obtain a string composed of the fields `PID-5-1` and `PID-5-2`:

[source, xml, linenums]
----
<set-payload value="#[hl7('/PID-5-1') + ' ' + hl7('/PID-5-2')]"/>
----

Use an link:/docs/display/33X/Expression+Component+Reference[Expression Component] to set modify fields `PID-5-1` and `PID-5-2`:

[source, xml, linenums]
----
<expression-component>
        hl7('/PID-5-1', 'John');
        hl7('/PID-5-2', 'Doe');
</expression-component>
----
