= Compatibility

Users run Mule ESB on many different operating systems in combination with a variety of messaging platforms and application servers. This page describes the platform software compatible with the current version of Mule ESB.

See link:/docs/display/current/Hardware+and+Software+Requirements[Hardware and Software Requirements] for information about hardware, operating systems, JDEs, and other software required to run Mule ESB, Mule Management Console, or Anypoint™ Studio.

== Application Servers

The current release of Mule ESB supports the following application servers:

* Eclipse Jetty 8
* JBoss 6.1 (Enterprise)
* JBoss 7 (Community)
* Apache Tomcat 7
* IBM WebSphere 8
* Oracle WebLogic 12c

Additionally, users have reported success deploying Mule ESB with the following application servers:

* Geronimo +

== Java Virtual Machines

The current release of Mule ESB supports the following Java Virtual Machines:

* Oracle Hot Spot 7


== Operating Systems

The current release of Mule ESB supports the following operating systems:

* Ubuntu Server 12.04.2
* Red Hat RHEL 5.8
* Red Hat RHEL 6.5
* Oracle Solaris 11 (Solaris Sparc and Solaris Intel)
* Raspberry Pi Raspbian raspberry 3.6.11
* Apple Mac OS 10.9
* Apple Mac OS 10.8
* Apple Mac OS 10.7
* IBM AIX
* HP HP-UX 11i V3
* Microsoft Windows 7
* Microsoft Windows 2008 Server

== Messaging Platforms

The current release of Mule ESB supports the following messaging platforms:

* Apache ActiveMQ 5.9.0
* IBM WebSphere MQ 7
* Oracle AQ

Additionally, users have reported successful integration via the following messaging platforms:

* Open MQ 
* TIBCO EMS
* TIBCO Rendezvous
* Hornet MQ +

== Database Servers

The current release of Mule ESB supports the following database servers:

* Oracle Database11g
* Microsoft SQL Server 2012
* MySQL 5.5
* IBM DB2 10.1
* PostgreSQL 9.6
* Apache Derby 10.9.1.0

== Browsers

API Manager supports the following browsers:

* Firefox (latest)
* Chrome (latest)
* IE 10 and later

CloudHub supports the following browsers:

* Firefox (latest)
* Chrome (latest)
* Safari (latest)
* IE 10 and later

Mule Management Console supports all http://www.gwtproject.org/doc/latest/FAQ_GettingStarted.html#What_browsers_does_GWT_support?[browsers supported by GWT].

== See Also

* See link:/docs/display/current/Hardware+and+Software+Requirements[Hardware and Software Requirements] for information about hardware, operating systems, JDEs, and other software required to run Mule ESB, Mule Management Console, or Anypoint Studio.
* Learn how to link:/docs/display/current/Downloading+and+Installing+Mule+ESB[download, install, and launch] Mule ESB.
* Learn more about installing an link:/docs/display/current/Installing+an+Enterprise+License[Enterprise license].
* link:/docs/display/current/First+30+Minutes+with+Mule[Get started] with Anypoint Studio.
* Already an Eclipse user? Find out about installing link:/docs/display/current/Studio+in+Eclipse[Studio as an Eclipse plug-in].
