= Salesforce Analytics Cloud Connector Release Notes

The Anypoint Connector for Salesforce Analytics Cloud lets you connect to the Salesforce Analytics Cloud application using SOAP API. The connector exposes convenient methods for creating data sets in Salesforce Analytics Cloud from different data sources, such as XML, CSV, and a list of Map objects.

*Release Notes*: link:/docs/display/current/Salesforce+Analytics+Cloud+Connector+Release+Notes[Salesforce Analytics Cloud Connector Release Notes].

== Version 1.1 - April 17, 2015

=== Version 1.1 Compatibility

The Salesforce Analytics Cloud connector is compatible with:

[cols=",",options="header",]
|===
|Application/Service |Version
|*Mule Runtime* |3.5.0 or later
|*Salesforce API* |v31
|*SOAP API* |v31
|===

=== Version 1.1 Features

Added the following operations

** *Create data set*: Create a new data set in the Salesforce Analytics Cloud system.
** *Upload external data*: Upload data into an existing data set in the Salesforce Analytics Cloud system.
** *Start processing data*: Start processing the data in a data set.
** *Upload external data into new data set and start processing*: Create a new data set, upload data into it, and start processing the data, all in one step.


=== Version 1.1 Fixes

None.


=== Version 1.1 Known Issues

None.

== See Also

* Learn about the link:/docs/display/current/Datamapper+User+Guide+and+Reference[DataMapper] transformer, the most efficient way to assign mappings to data.
* Learn abut link:/docs/display/current/Batch+Processing[Batch Processing]. 
* Read more about link:/docs/display/current/Anypoint+Connectors[Anypoint Connectors].
