= Running Mule ESB 3

Now that you have installed Mule, you can run it per the requirements of your specific installation. This page describes the various ways in which you can run Mule.

[NOTE]
If you are using the 30-day trial version of Mule Enterprise, you will no longer be able to start the trial version after the 30 days has expired unless you purchase a license. (This does not affect the Community edition of Mule.) For information on purchasing Mule Enterprise, click http://www.mulesource.com/buynow/[here].


* link:/documentation-3.2/display/32X/Running+Mule+From+the+Command+Prompt[Running Mule From the Command Prompt]
* link:/documentation-3.2/display/32X/Alternate+Ways+of+Running+Mule[Alternate Ways of Running Mule]
* link:/documentation-3.2/display/32X/Controlling+Mule+From+Startup[Controlling Mule From Startup]
* link:/documentation-3.2/display/32X/Running+Multiple+Mule+Instances[Running Multiple Mule Instances]
* link:/documentation-3.2/display/32X/Updating+a+Running+Application[Updating a Running Application]
