= Extending Connector Functionality
:keywords: devkit, extend, connector

Improve the efficacy, efficiency and reliability of your connector by implementing the following DevKit-supported features.

* link:/anypoint-connector-devkit/v/3.8/adding-datasense[Adding DataSense]
** Learn how to add DataSense to your connector so it can sense dynamic and static metadata, making Mule application design more intuitive and less burdensome.
* link:/anypoint-connector-devkit/v/3.8/adding-datasense-query-language[Adding DataSense Query Language]
** Familiarize yourself with the query language and libraries that your connector can use to query data from a service
* link:/anypoint-connector-devkit/v/3.8/caching-metadata[Caching Metadata]
** Improve the user experience with Datasense when developing connectors with large metadata payloads to retrieve
* link:/anypoint-connector-devkit/v/3.8/adding-query-pagination-support[Adding Query Pagination Support]
** To avoid processing all records in memory at once, use pagination, which allows the connector to ingest the records in chunks, thus improving connector performance. Note that your service's API must support pagination if you want to use the feature in your connector.
* link:/anypoint-connector-devkit/v/3.8/building-a-batch-enabled-connector[Building a Batch Enabled Connector]
** Handle large batches of messages and discover the records easily by adding two classes to your connector's code
* link:/anypoint-connector-devkit/v/3.8/shading-libraries[Shading Libraries]
** Add support for shading (renaming) JAR files in scenarios where multiple versions of dependencies are required that may collide with those in Mule

'''''

*link:/anypoint-connector-devkit/v/3.8[Return to Anypoint Connector DevKit]*
