= Audit Logging
:keywords: anypoint platform, configuring, logs, auditing

[NOTE]
The Audit Logging service is currently limited to change events made within the API management and platform services capabilities of the Anypoint Platform. Changes made within the CloudHub and Anypoint Runtime Management of the platform are not currently audited. These changes will be audited as part of a future release.

Changes within an Anypoint Platform organization (e.g. the application of a policy or the creation of a new user) are logged through an audit logging service. The historical audit events for an organization can be accessed by users belonging to the Organization Administration role within a business unit.

Currently, access to this data is available through the Anypoint Platform’s link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/24562/versions/26089/pages/39846[Audit Logging Query API]. The information will also be made available within a dedicated UI page within the Anypoint Platform as part of a future release.
