= MuleSoft Documentation

Welcome to the new MuleSoft documentation site. The following pages help you start using Mule Runtime, Anypoint Studio, Anypoint Platform for APIs, and CloudHub:

* link:/mule-fundamentals/v/3.7/index[Mule Fundamentals]
* link:/anypoint-platform-for-apis/anypoint-platform-for-apis-walkthrough[Anypoint Platform for APIs Walkthrough]
* link:/cloudhub/getting-started-with-cloudhub[Getting Started with CloudHub]
* link:/release-notes/index[Release Notes]

== Making a Contribution

MuleSoft welcomes community contributions to our documentation! To make a contribution, simply click any page’s "Edit on GitHub" link, which takes you to the source page on GitHub. To provide your change as a Git pull request, *first* accept our link:http://www.mulesoft.org/legal/contributor-agreement.html[contributor’s agreement] so that we can acknowledge your contribution. The repository’s link:https://github.com/mulesoft/mulesoft-docs/blob/master/README.adoc[readme file] provides more information about how you can make a positive difference in improving MuleSoft documentation, and be recognized for your contribution.
