= CloudHub R40 Migration Guide
:keywords: release notes, cloudhub, cloud hub


For CloudHub release 40 in October 2014, the Anypoint Platform for APIs and CloudHub will have a unified single sign-on experience and user interface. Please read the following migration guide to understand how you might be impacted by these changes.

== Accessing the Management Console

CloudHub will now be accessible from the https://anypoint.mulesoft.com/[anypoint.mulesoft.com] URL. Going forward, if you visit http://cloudhub.io[cloudhub.io] to sign in, you will be redirected to https://anypoint.mulesoft.com/[anypoint.mulesoft.com]. All applications will still be available at their respective domains on cloudhub.io.

== Account Migration

If you have a user with the same username for Anypoint Platform for APIs and CloudHub, your username may be changed.

If you have a CloudHub organization and an Anypoint Platform for APIs organization with the same set of administrators, we will merge your accounts so you have a completely unified account.

However, if they do not match, then we will not merge accounts because that could result in inadvertently granting access to parts of your organization to unauthorized users. In this case, we will create a second account for you with the postfix `_cloudhub`. For example, if your username was `joe` and you have accounts in both Anypoint Platform for APIs and CloudHub, a second account will be created with the username `joe_cloudhub`. If this condition applies to your username, you will receive an email notifying you of this change.

If you have two organizations because of the condition above (e.g. `joe` and `joe_cloudhub`), you can merge these organizations by inviting all the users into a single organization and migrating your CloudHub applications or APIs manually. If you are a customer and would like to do this, please contact support so that the old organization can be disabled.

== Roles & Permissions

The underlying roles and permissions model in the platform has become much more powerful. Because of this, users will notice that they now have individual roles for each environment.

For example, if you had two environments in CloudHub, Production and QA, then you will end up with the following set of roles: CloudHub Admin (Production), CloudHub Admin (QA), CloudHub Developer (Production), CloudHub Developer (QA), CloudHub Support (Production), and CloudHub Support (QA).

For more information on how roles and permissions work, see the http://www.mulesoft.org/documentation/display/current/Anypoint+Platform+Administration[Anypoint Platform Administration] guide.

== Further Information

In addition to the above, please read the http://www.mulesoft.org/documentation/display/current/CloudHub+Release+Notes[release notes] to see a complete list of new capabilities and errata.
