= Mule 0.9.1 Release Notes
:keywords: release notes, esb


Mule 0.9.1 ESB server sees the introduction of the http://www.muleumo.org/extras/index.html[Mule Extras] module that hosts all the Spring Framework, PicoContainer and other extensions, webbapp support, improved Test compatibility Kit for your own extensions and numerous bug fixes and other improvements.


*New Mule-Extras Module*
Mule Extras contains all the framework extensions that are not part of the mule core server. These include: +
Spring Extensions - Spring container component resolver and Spring configuration builder +
Pico Extensions - Pico container component resolver and Pico component pool support +
XStream transformers - Java to xml and xml to Java transformers +
Tyrex transaction factory


*Webapp Support*
Mule can now eaisly be embedded inside a webapp so that your webapps can use Mule for their network communication to other applications.


*Tck Improvements*
New http://www.muleumo.org/tck.html[Tck] test cases have been added to provide almost complete coverage of all Mule's extensible objects.


*Distribution Restructure*
The Mule server jars are now broken down into +
mule-core-0.9.1.jar - The Mule core server and UMO api +
mule-tck-0.9.1.jar - The Mule Test compatibility kit api +
mule-provider-xxx-0.9.1.jar - The individual Mule providers, where xxx is jms, email, file etc. +
mule-extras-xxx-0.9.1.jar - The individual Mule Extras subprojects, where xxx is spring, picocontainer, xstream etc. +
mule-0.9.1.jar - An aggregation of all of the above jars


== Bug fixes and other Improvements

http://mule.mulesource.org/jira/browse/MULE-37[MULE-37@JIRA] TCK: project.xml does contain wrong version information (Tck refactoring) +
http://mule.mulesource.org/jira/browse/MULE-36[MULE-36@JIRA] TransactionCounter can fall below zero +
http://mule.mulesource.org/jira/browse/MULE-35[MULE-35@JIRA] Remove the ExceptionStrategy on the UMOComponent +
http://mule.mulesource.org/jira/browse/MULE-34[MULE-34@JIRA] Remove selector methods from UMODescriptor +
http://mule.mulesource.org/jira/browse/MULE-33[MULE-33@JIRA] Rename Jms provider deliveryMode to Acknowledgement mode +
http://mule.mulesource.org/jira/browse/MULE-32[MULE-32@JIRA] Interceptors are initialised in reverse order using MuleXmlconfigurationBuilder +
http://mule.mulesource.org/jira/browse/MULE-31[MULE-31@JIRA] Duplicate class XmlToBean and BeanToXml +
http://mule.mulesource.org/jira/browse/MULE-30[MULE-30@JIRA] Define UMODescriptorAware inversion interface +
http://mule.mulesource.org/jira/browse/MULE-28[MULE-28@JIRA] Embedding Mule in a webapp +
http://mule.mulesource.org/jira/browse/MULE-27[MULE-27@JIRA] Provider Override properties in the connector are still using namespaces +
http://mule.mulesource.org/jira/browse/MULE-26[MULE-26@JIRA] MuleXmlConfigBuilder doesn't set properites on a provider +
http://mule.mulesource.org/jira/browse/MULE-25[MULE-25@JIRA] Make programmatic event dispatching a bit more intuitive +
http://mule.mulesource.org/jira/browse/MULE-23[MULE-23@JIRA] Set up Mule Extras sub project for Mule extensions +
http://mule.mulesource.org/jira/browse/MULE-22[MULE-22@JIRA] setProperties on UMOProviderDescriptor doesn't work when using spring configuration +
http://mule.mulesource.org/jira/browse/MULE-21[MULE-21@JIRA] Support for specifying what port the SMTP and POP3 connectors use +
http://mule.mulesource.org/jira/browse/MULE-18[MULE-18@JIRA] expose the provider to the transformer
