= Siebel Connector Release Notes
:keywords: release notes, siebel, connector

_Premium_

The Anypoint Connector for Siebel lets you access connections between Mule integration applications and the Oracle Siebel customer relationship manager (CRM).

The connector provides these options to connect to Siebel applications:

* *Oracle Siebel Business Objects*: Create, update, upsert, query, and delete Siebel business components.
* *Oracle Siebel Integration Objects*: Create, update, upsert, query, delete, query page, execute, and synchronize Siebel integration objects.
* *Oracle Siebel Business Services*: Execute Siebel business services.

*Guide:* link:/documentation/display/current/Siebel+Connector[Siebel Connector]

link:#SiebelConnectorReleaseNotes-SeeAlso[See Also]

== Version 2.1.0 - April 13, 2014

=== Version 2.1.0 Compatibility

The Siebel connector is compatible with:
[width="100%",cols="50%,50%",options="header",]
|===
|Application/Service a|
Version

|*Mule Runtime* |v3.6.1 or higher
|*Siebel* |v8.1
|===

[CAUTION]
The Siebel v2.1.0 connector is built and tested using Oracle Siebel 8.1. Because the Java Data Bean interface is generic, the Siebel v2.1.0 connector works with Siebel versions 7.7, 7.8, and 8.0. However, the compatibility of the connector with any other version beside 8.1 has not been tested. The connector is not compatible with Siebel v7.5 and earlier.

=== Version 2.1.0 Features

* Added native library support for Mule projects created in Anypoint Studio without Maven. This lets you add the required Siebel JAR files from the Global Element configuration without using Maven, or installing the JAR locally and adding the dependency to the Project Object Model (POM).
* Migrated to Anypoint Connector DevKit v3.6.1. 

[NOTE]
Learn how to link:/documentation/display/current/Anypoint+Exchange[Install Anypoint Connectors] using Anypoint Exchange. If you are already using a previous version of the Siebel connector, learn how to work link:/documentation/display/current/Working+with+Multiple+Versions+of+Connectors[with multiple versions of the connector].

=== Version 2.1.0 Fixes

* Previously, the Accounts records in Siebel were not mapped to the Contact records. This issue has been fixed.

=== Version 2.1.0 Known Issues

* None. 

== Version 2.0 - October 17, 2014

=== Version 2.0 Compatibility

The Siebel v2.0 connector is compatible with the following:

[cols=",",options="header",]
|===
|Software |Version
|MuleSoft Runtime |3.5.1
|Anypoint Studio |October 2014
|Oracle Siebel |8.1
|===

=== Version 2.0 Features and Functionality

The following functionality has been added in this version of the connector:

[width="100%",cols="50%,50%",options="header",]
|===
|Object |Operation
|Integration Objects |Create, Update, Delete, Upsert, Query, Query page, Execute, Synchronize
|Business Services |DataSense support
|===

Apart from the above, we have made improvements to the  Sort support for the query operation on Business Components. 

=== Version 2.0 Fixed in this Release

There are no bug fixes in this release.

=== Version 2.0 Known Issues

[width="100%",cols="50%,50%",options="header",]
|===
|Issue |Description
|Creating hierarchical objects functionality is not complete |The functionality to create hierarchical objects is not built entirely. We are working on improving Studio DataSense features and the corresponding support in the connector.
|DataSense could slow down Studio |If the “DataSense Query Filter” is not set in the configuration, DataSense could slow down the performance of Studio due to a large number of objects in Siebel installations.
|Caching |Some caching has been made inside Siebel connector to avoid load on the Siebel server.
|===

== See Also

* Learn how to http://www.mulesoft.org/documentation/display/current/Anypoint+Exchange#AnypointExchange-InstallingaConnectorfromAnypointExchange[Install Anypoint Connectors] using Anypoint Exchange.
* Access MuleSoft’s http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log into MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal].
