= Deploying Mule ESB 3

As of version 3.1, Mule standalone can run multiple applications. This means you can include the same name spaces within different applications and they will neither collide nor share information.

* In effect, it's now an app server.
* In addition, Mule checks for new apps (in the apps directory) and will start them.
* It will also restart apps if it detects that they have changed, meaning you can drop a revised version of an existing, running application into the /apps directory, Mule will stop the existing app and restart using the new files.
* This results in one fewer reason to run Mule inside a container.

* link:/docs/display/33X/Deployment+Scenarios[Deployment Scenarios]
* link:/docs/display/33X/Mule+Deployment+Model[Mule Deployment Model]
* link:/docs/display/33X/Configuring+Logging[Configuring Logging]
* link:/docs/display/33X/Mule+Server+Notifications[Mule Server Notifications]
* link:/docs/display/33X/Profiling+Mule[Profiling Mule]
* link:/docs/display/33X/Hardening+your+Mule+Installation[Hardening your Mule Installation]
* link:/docs/display/33X/Configuring+Mule+for+Different+Deployment+Scenarios[Configuring Mule for Different Deployment Scenarios]
