= Working with Maven

[WARNING]
Note that this page is intended for developers who are *contributing to the Mule source code*. If you are looking for documentation on how to use Maven to work with Mule applications, please visit link:/mule-user-guide/v/3.4/mule-and-maven[Mule and Maven].

http://maven.apache.org/[Maven] is a project management utility that you can use to develop projects in Mule.  Though highly recommended, Maven is not strictly necessary to develop applications in Mule.  However, to modify or add to Mule source code, we insist on using Maven to keep the source code project's hierarchy organized and intact. 

You can use Maven to quickly set up and configure your Mule ESB project. To help you get productive quickly, Mule provides five archetypes that create template files, including all the necessary Java boilerplate content and detailed implementation instructions in comments:

* use the link:/mule-user-guide/v/3.4/creating-project-archetypes[Project Archetype] for creating a Mule application
* use the link:/mule-user-guide/v/3.4/creating-module-archetypes[Module Archetype] for creating a new module, such as XML or scripting support
* use the link:/mule-user-guide/v/3.4/transport-archetype[Transport Archetype] for creating a new transport, such as JMS 
* use the link:/mule-user-guide/v/3.4/creating-example-archetypes[Example Archetype] for creating a new example to help other users get up and running quickly
* use the link:/mule-user-guide/v/3.4/creating-catalog-archetypes[Catalog Archetype] for creating a new configuration pattern catalog and its patterns 

Note that if you run an archetype on an existing project or module that you created, it _updates_ rather creates a new project file. For example, if a project included File and VM transports, and now you want it to include the File and JMS transports, you can re-run the project archetype specifying the same project name. When you specify the transports you want to use in the project, the archetype updates your project files, adding the JMS namespace and removing VM. Access the http://maven.apache.org/guides/index.html[Maven documentation] for more details about Maven.

[WARNING]
*Maven default local repository location on Windows* +
 +
In Windows, Maven stores the libraries in the .m2 repository in your home directory.  For example, `C:\Documents and Settings\<username>\.m2\repository`.  Because RMI tests fail where a directory name includes spaces, you must move the Maven local repository to a directory with a name that _does not_ include spaces, such as `%M2_HOME%/conf` or `%USERPROFILE%/.m2`

== Mule Source Code Sub-projects

The Mule source code project is neatly organized into a hierarchy of sub-projects. (Sub-projects are sometimes referred to as "modules," but to avoid confusion with Mule modules, we use "sub-projects".) Each sub-project generally produces one Maven artifact, usually a JAR file. The Mule build is structured using intermediate project object models (POMs) to group common sub-projects together. These intermediate sub-projects are sub-folders of the source code's `mule` folder, and are described in the table below.

[width="100%",cols="50%,50%",options="header",]
|===
|Sub-project |Description
|buildtools |tools to build Mule, scripts, and checkstyle configuration
|core |Mule's core API and functionality that is required by all transports
|distributions |builds the various distributions (refer to the <<Distributions>> section below for further details)
|examples |examples that come with the full Mule distribution
|modules |non-transport extensions to Mule, such as XML processing, Spring extras, or scripting support
|tests |integration tests that can be run as part of the Mule build
|tools |tools for Mule, such as the transport and project Maven archetypes
|transports |Mule transports such as the JMS, VM, and TCP transports
|===

== Building Mule

The following table lists common goals to execute for building Mule.

[cols=",",]
|================
|`mvn clean` |purges any built artifacts or intermediate files (such as `.class`) from the target directory +
_Default_ : `target`
|`mvn install` |installs the artifact to your local repository +
_Default_: `~/.m2/repository`
|`mvn test` |runs any unit tests for this sub-project
|`mvn -DskipTests install` |By default, Maven runs all unit tests for each project for each build which, depending on the project, can take a long time to complete. If you wish, you can skip the tests using this command.
|================

=== Distributions

When you package Mule for distribution, all distributions and related resources are located in the `distributions` sub-project. 

For performance's sake, the distributions are *not* built from the project's top-level directory by default. You may either build a distribution from its own directory, or enable the `distributions` profile by adding `-Pdistributions` to your Maven command line.

The table below offers a brief description of each type distribution.

[cols=",,,",]
|=========
|Type |Sub-project |Description |Breadth
|Full Standalone Server |`/distributions/server/full` |Packages Mule as a stand-alone server application. Includes all transports, extras and all dependencies. Includes the http://wrapper.tanukisoftware.org[Java Service Wrapper] for starting/stopping/restarting Mule from the native OS. |heavyweight
|Custom Standalone Server |`/distributions/server/custom` |Packages Mule as a standalone server application _without_ any dependencies. If the user's project is based on Maven, this distribution can easily provide the exact libraries it depends upon because of m2's intelligent resolution of transitive dependencies.   |lightweight
|JCA Resource Adapter |`/distributions/jca` |Packages Mule as a JCA-compatible Resource Adapter for deployment into a J2EE application server. Includes all transports, extras and all dependencies. |heavyweight
|Embedded (Composite) JAR File |`/distribution/embedded` |Packages Mule as a single JAR file containing all Mule classes, including all transports and extras). This distribution is useful when embedding Mule into another application, or when using Mule with a non-Maven-based build. Note that when you use this approach, you are responsible for providing any needed Mule dependencies, as described in the next section. |lightweight
|=========

=== Dependencies

As with all Maven projects, you must add dependencies to the `.pom` file for your Mule application. 

If using the Enterprise Edition of Mule ESB, you must add dependencies for the Enterprise features you use in your application code. The following lists the Mule ESB Enterprise Edition dependencies.

[source, xml, linenums]
----
<dependency>
    <groupId>com.mulesoft.muleesb</gropuId>
    <artifactId>mule-core-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-batch-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-boot-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-bti-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-cache-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-cluster-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-multi-tx-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-plugin-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-saml-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-spring-config-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-throttling-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-tracking-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.modules</gropuId>
    <artifactId>mule-module-xa-tx-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.transports</gropuId>
    <artifactId>mule-transport-ftp-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.transports</gropuId>
    <artifactId>mule-transport-jdbc-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.transports</gropuId>
    <artifactId>mule-transport-jms-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.transports</gropuId>
    <artifactId>mule-transport-jms</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.transports</gropuId>
    <artifactId>mule-transport-msmq-ee</artifactId>
    <version>${version}</version>
</dependency>
 
<dependency>
    <groupId>com.mulesoft.muleesb.transports</gropuId>
    <artifactId>mule-transport-wmq-ee</artifactId>
    <version>${version}</version>
</dependency>
----

== Troubleshooting Maven

This section describes some problems you might experience using Maven and how to resolve or work around them.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Problem |Description |Solution
|Files could not be retrieved |You are behind a firewall and get an error stating that repository metadata for `org.mule.tools` could not be retrieved from the central repository. |Check the proxy settings in your Maven `settings.xml` file to confirm that they are configured correctly.
|OutOfMemory Error |You encounter `OutOfMemoryError` exceptions when attempting a full build of Mule. |Increasing the max heap *and* the PermGen space sizes. To do so, either export a `MAVEN_OPTS` variable in your shell, or add the variable to the original mvn script. Use the following: +
`MAVEN_OPTS=-Xmx512m -XX:MaxPermSize=256m`
|Slow build |- |If you know your downloads are up-to-date, you can use the offline option using the following command: +
`mvn -o`
|Conflicting transitive dependencies |Transitive dependencies in m2 are both powerful and problematic at times. For example, you many have conflicting library versions or when unwanted libraries are in your classpath. |Use the debug option to display the effective classpath in a tree format, making it easy to see where each library is coming from: +
`mvn -x`
|Running a goal for a specific project |By default, Maven execute a goal for a project and all sub-projects in its hierarchy. |If you want to run the goal for a specific project only (and not its children), you can use the non-recursive option: +
`mvn -N` 
|Debugging test failures |Surefire, the default Maven test runner, outputs all reports as a set of XML and text files. Any test failure details and stack traces are written to those files instead of the console, so it can be time consuming to open files to find problems. |You can redirect the output to the console temporarily by adding the following option: +
`mvn -Dsurefire.useFile=false` This option skips creation ofthe text report, but still makes the XML report available for transformation by tools. 
|===
