= Anypoint Platform Administration
:keywords: cloudhub, manage, administration

Your https://anypoint.mulesoft.com/#/signup[Anypoint Platform account] gives you access to both the services in the Anypoint Platform for APIs – for creating and managing APIs through their entire lifecycle – and to CloudHub – for deploying and managing applications.

[NOTE]
As of November 2014, accounts in both the Anypoint Platform for APIs and CloudHub have been merged.

* link:/docs/display/current/Troubleshooting+Anypoint+Platform+Access[Troubleshooting Anypoint Platform Access]
* link:/docs/display/current/Setting+Up+External+Identity[Setting Up External Identity]
* link:/docs/display/current/Managing+CloudHub+Specific+Settings[Managing CloudHub Specific Settings]
** link:/docs/display/current/Managing+CloudHub+Environments[Managing CloudHub Environments]
* link:/docs/display/current/Creating+an+Account[Creating an Account]
* link:/docs/display/current/Managing+Accounts+Roles+and+Permissions[Managing Accounts Roles and Permissions]
* link:/docs/display/current/Manage+your+Organization+and+Business+Groups[Manage your Organization and Business Groups]

If you have any questions about your account, visit the  http://www.mulesoft.org/documentation/display/current/Community+and+Support#CommunityandSupport-Support[support portal] for assistance.
