= CloudHub FAQ
:keywords: cloudhub, faq, ipaas, paas

== General

=== What is an iPaaS?

As the name suggests, iPaaS is a development platform for building integration applications. It provides a set of services and capabilities for integrating applications in the cloud and within the enterprise. The core tenets of iPaaS are the same as PaaS, except the services on the platform are geared towards integration. In addition to some base expectations such as multi-tenancy, elasticity and reliability, iPaaS also provides intermediation of data and events, orchestration, a service container for publishing REST and SOAP services, strong security capabilities, and monitoring and developer tooling.

For more information, see link:http://blogs.mulesoft.org/introducing-integration-paas-ipaas/[here].

=== What is CloudHub?

CloudHub a cloud-based integration platform as a service (iPaaS) that enables developers to integrate and orchestrate applications and services while giving operations the control and visibility they require for mission-critical demands, all without the need to install or manage middleware or hardware infrastructure. Read more about the CloudHub link:/cloudhub/cloudhub-architecture[architecture].

=== Where can I get Anypoint Studio?

Anypoint Studio can be link:https://www.mulesoft.com/lp/dl/studio[downloaded here]. From Studio, you have ability to deploy directly to CloudHub or run your applications locally on an embedded Mule runtime.

=== How much does CloudHub cost?

For specific pricing, please reach out to your account executive, your account development representative or contact us at cloudhub-support@mulesoft.com.

== Concepts

=== What is a Worker?

Applications that expose real time services or APIs run on one or more "workers". Each worker is an instance of Mule that runs your integration applications. See link:/cloudhub/cloudhub-fabric[CloudHub Fabric] for details of how workers can be shared or doubled to scale your application and provide high availability.

=== What is an Integration Application?

An integration application is one that integrates two or more applications or services. This may be as simple as synchronizing Salesforce.com data to a local database to creating a mashup using Google Apps, Facebook, and Salesforce.com. These applications perform functions by grabbing data from different sources and publishing it to a new location or as a REST or Web Service. In the traditional 3 tier application model an integration app represents the data tier through connectivity to application data and the service tier through logic used to combine, transform and route this data to consumers.

=== What is an Anypoint Connector?

Anypoint Connectors provide a simple and easy way to integrate with SaaS and Cloud APIs such as Salesforce, Facebook, AWS, Paypal, and then to use them as services within Mule. With these connectors you are then able to create orchestration that spans both SaaS and on-premises applications, using Mule.

=== What is a Mule Flow?

A Mule flow defines how Mule  processes messages between different applications. A flow defines a series of processors that  act on a message triggered by an event in an application, a request to a Web or REST service or a scheduled trigger.

== Technical / Troubleshooting

=== What Java version are you using?

* Workers that use Mule 3.7.0 and newer run on JDK 8.
* Workers that use Mule 3.5.1 and newer run on JDK 7.
* Workers that use Mule 3.5.0 and older run on JDK 6.

=== How much storage does each worker have?

Each worker has 2 GB of storage for applications to use.

=== What are environment variables?

Environment variables are properties you can set to pass in configuration to your Mule application. For example, you could create a JDBC connector where the username is set to `${db.username}`. In the environment variables you could then set the name to `db.username` and the value to the actual username when you add or update your application.

=== Can I deploy my application to a different region?

Yes!  link:/cloudhub/community-and-support[File a support case] to enable global deployments for your account. CloudHub applications can be deployed to: US (East), US (West), Europe (Ireland), and Asia-Pacific (Sydney). Administrators can  link:/anypoint-platform-administration/managing-cloudhub-specific-settings[set the default region] on the Organization tab in Account Settings, but that region can be adjusted here when the application is deployed, if necessary.

Note that applications deployed to Europe  automatically have their domain updated to `http://myapplicationdomain.eu.cloudhub.io`. Similarly, applications deployed to Australia  automatically have their domain updated to `http://myapplicationdomain.au.cloudhub.io`. 

=== I get "Failed to bind to uri" when my application starts

If you're seeing messages like this:

[source,bash, linenums]
----
INFO 11-04-06 20:13:50 [DefaultSystemExceptionStrategy] Failed to bind to uri "http://foo.cloudhub.io:8081/"
----

It's because you're trying to bind to a specific host instead of "0.0.0.0". Change your HTTP Connector to use "0.0.0.0" instead of your CloudHub domain name and redeploy.

=== How do I stop my application?

In the CloudHub Console, select your application, and click *Deployment* in the left navigation bar. Click *Stop application*.

=== Why can't I deploy more than one application?

We're limiting the Free accounts to one worker, which allows you to deploy one application. You can upgrade to a link:http://www.mulesoft.com/cloudhub/cloudhub-pricing[paid subscription] to deploy more applications or scale your single application across more than one worker.

=== My application has deployed successfully, but when I go to mysubdomain.cloudhub.io, I see "you need to change the configuration of your docroot."

If you are seeing this message, that means that your application's endpoint could be configured to show up in a different path. If you would like to make it show up at mysubdomain.cloudhub.io, please reconfigure your endpoint to remove the path variable. If you are using generic endpoints, you should change the address (not the path).

=== How long is the HTTP read timeout?

Our load balancers  timeout after 5 minutes if no data is read.

=== Can I get a static IP for my application?

Yes! Visit link:/cloudhub/community-and-support[our support] to enable this for your application. You need to provide the full name of the application.

=== How do I know what my static IP is?

The IP address of your worker is displayed in the Cloudhub Console, on the right hand side of the Dashboard for the chosen application. The static IP is also listed on application startup, in the Cloudhub Application Log. Look for a string similar to : _"Applying static IP(x.x.x.x) to your application.”_

=== Can I modify my application after it has been assigned a static IP?

Yes, you can stop and start the application, you may upload a new project zip file, you may change its settings and redeploy it.

=== In what situations could my static IP change?

There are some specific scenarios where your static IP may be removed or reassigned. You should be aware of the following scenarios:

* Deleting an application  also removes its Static IP. If you create a new application with the same name, it has a new dynamically assigned IP address.
* Adding a new application by moving it from Sandbox to Production. This requires a new application name, hence a new Static IP
* If a Virtual Private Cloud (VPC) is built for your organization, any existing applications   not already in the VPC   receives a new IP address when it is restarts inside the VPC.
* An application is re-deployed to a different geographic region
* An application is deployed to multiple Cloudhub workers (such as Fabric). Fabric deployments do not support Static IPs. 
* A formal request to Mulesoft Support to remove the Static IP is completed.

=== Can I request a specific Static IP?

No. Cloudhub utilizes a pool of Static IP’s, which are only assigned to a Cloudhub Application upon first deployment. If/when that application releases that static IP, that IP address returns to the pool, and is available to other applications.

=== I am running in a Cloudhub Virtual Private Network, how do I assign a Static IP to my internal private IP?

Cloudhub is able to set the worker's public IP address to Static. However, the internal private IP address always remains Dynamic. The private IP address is assigned from the range specified in the Cloudhub Worker's Address Space, which was determined at the creation of your VPC.

=== What are the possible IP ranges that can be assigned to Static IPs?

As CloudHub deploys on Amazon EC2, IP addresses are chosen from the Amazon EC2 IP pool. For a list of these ranges,  see Amazon EC2 Public IP Ranges: link:https://forums.aws.amazon.com/ann.jspa?annID=1701.
