= Getting Started with CloudHub
:keywords: cloudhub, connectors

CloudHub is an integration platform as a service (iPaaS). With the Anypoint Runtime Manager, it allows you to deploy sophisticated cross-cloud integration applications in the cloud, and on premises to servers, groups of servers, and clusters, create new APIs on top of existing data sources, integrate on premises applications with cloud services, manage servers and server groups on premises, and much more. With Anypoint Studio – the user-friendly development tool – you can quickly build integration applications and deploy to CloudHub with just a few clicks. This guide helps you learn the basics, and get started developing your first application.

[NOTE]
====
In the cloud version of the link:anypoint.mulesoft.com[Anypoint Platform], your Mule deployments to the cloud and to servers on premises are managed through the *CloudHub* section. In the downloadable link:/anypoint-platform-on-premises/v/1.1.0[Aynpoint Platform On Premises Edition], the section that manages your deployments to on premise servers is named *Anypoint Runtime Manager*.

The topics in this document deal with app deployments on both these scenarios. See link:/cloudhub/cloudhub-and-runtime-manager[CloudHub and Runtime Manager] for a better understanding of the differences between both.
====

== Learn CloudHub Basics

. Download link:https://www.mulesoft.com/lp/dl/studio[Anypoint Studio].
. Read our link:/cloudhub/cloudhub-at-a-glance[CloudHub at a Glance] guide to learn the basic concepts.
. Follow our easy link:/cloudhub/hello-world-on-cloudhub[Hello World on CloudHub] tutorial to get your first integration application up and running with Anypoint Studio and CloudHub.
. link:/cloudhub/getting-started-with-connectors[Get started with connectors] to connect to external services like Twitter.
. Ready to deploy an application?  See link:/cloudhub/deploying-a-cloudhub-application[Deploying a CloudHub Application].

Still don't understand how CloudHub can be of use to you? Read more about link:http://www.mulesoft.com/cloudhub/ipaas-cloud-based-integration-demand[things you can do with CloudHub].

== Build CloudHub Applications

Follow one of our tutorials to learn how to build CloudHub applications.

* link:/cloudhub/building-an-https-service[Building an HTTPS Service on CloudHub]  
* link:/cloudhub/custom-application-alerts[Custom Application Alerts] 

Want to learn more? Check out all the examples in link:/mule-fundamentals/v/3.7/anypoint-exchange[Anypoint Exchange].

== Deploy Applications to the Cloud or On Premises

The Runtime Manager enables you to:

* link:/cloudhub/deploying-a-cloudhub-application[Deploy applications] to the cloud
* link:/cloudhub/managing-applications-in-the-cloud-and-on-premises[Manage applications and servers running on premises] from the cloud
* link:/cloudhub/creating-and-managing-clusters[Create and manage clusters] from the cloud

== Building Connectors

Are you interested in building your own connector? Use the link:/anypoint-connector-devkit/v/3.7/[Anypoint Connector DevKit] to rapidly build connectors and drop them inside of Studio.

== Other Resources

* link:/cloudhub/managing-cloudhub-applications[Managing CloudHub Applications] 
* link:/cloudhub/reference-materials[Reference Materials]
* link:/cloudhub/community-and-support[Community and Support]
* There are tons of APIs available. Check our MuleSoft Blog for a list of the link:http://blogs.mulesoft.org/top-10-weird-apis/[TOP 10 of the weirdest APIs] out there.
