= Introducing CloudHub
:keywords: cloudhub, cloud, saas, applications, servers, clusters, sdg

Integrate SaaS applications, Cloud services, and Enterprise applications in real-time. CloudHub is the world's first integration Platform as a Service (iPaaS). CloudHub is built on top of Mule, the most widely used integration platform. CloudHub lets you manage applications in the cloud and manage servers located in your organization.

link:/docs/current/Getting+Started+with+CloudHub[*Get Started With CloudHub*]


== Why CloudHub?

=== Start Small, Think Big

CloudHub is an elastic cloud that scales on demand. You can start small and grow as your needs grow, all without changing your application. CloudHub provides you with a scalable architecture – one you can build integration applications on, publish REST APIs or Web Services, and much more. You can also manage servers in your organization from CloudHub and organize servers into groups that run an application.

=== Rock Solid Platform

Built on our battle-tested Mule integration platform, Mule ESB is used by thousands of companies for mission-critical applications. It's the world's most widely used platform for integration.

=== Integrate Cloud and Enterprise Applications

The Secure Enterprise Gateway (SDG) provides a secure pipe to the enterprise, breaking down the "cloud silo." CloudHub allows you to integrate and orchestrate applications, data sources, and services across the enterprise and cloud.

=== Unrivaled Connectivity

Easily integrate with popular SaaS, cloud, and social media platforms such as Salesforce.com, Intuit, Authorize.net, Amazon, Twitter, Facebook, and PayPal using our predefined connectors – then orchestrate data between these services and the enterprise. Plus, our development kit allows developers to create new connectors easily. You don't even need knowledge of the underlying integration infrastructure.

=== Don't Change the Way You Code

Create CloudHub applications with the development tools you are already familiar with. Download https://www.mulesoft.com/ty/dl/studio[Anypoint Studio], it's free! Anypoint Studio is an Eclipse-based graphical environment that allows developers to easily choose to code in a visual environment with a palette of components, or in a familiar XML code view. You can even switch between the visual and code views as you build your application. Or, if you would rather use the command-line, we support Maven, as well as a command line tool.

=== Visibility and Control with the Anypoint Management Center Console

With CloudHub, you also get our intuitive cloud console where you can manage your applications and servers, scale up and scale down, view event traffic, and much more. The Anypoint Management Center Console allows you to manage every aspect of your CloudHub applications from one place. In addition, with link:/docs/current/Managing+Applications+and+Servers+in+the+Cloud+and+On+Premises[application and server management] and link:/docs/current/Creating+and+Managing+Clusters[cluster management] you can manage your on-premise servers, server groups, and clusters, plus applications from your CloudHub console, giving you a single management pane of glass for all your applications and servers.

=== Behind a Great Platform is a Great API

Do you need to automate tasks, or build CloudHub into your deployment process? CloudHub has a link:/docs/display/current/CloudHub+API[REST API] with which you can perform tasks such as manage and monitor your applications, scale your applications up or down, and more.
