= List Log Messages
:keywords: cloudhub, cloudhub api, example

Use the GET operation on `/applications/{application}/logs` resource to list all log messages. This call returns a maximum of 10,000 lines of log data for each invocation. However, using repeated calls with contiguous time windows as search criteria, the entire log may be downloaded.

The following query parameters are supported:

[width="100%",cols="34a,33a,33a",options="header",]
|===
|Name |Default |Description
|limit |0 |The number of rows to return.
|offset |0 |The row to start listing log messages at.
|startDate |  |The start date to search for log messages. In ISO-8601 format.
|endDate |  |The end date to search for log messages. In ISO-8601 format.
|search |  |The text that messages must match.
|priority |  |The log level priority to return - DEBUG, INFO, WARN, ERROR, SYSTEM, CONSOLE.
|worker |  |The worker to return logs for, starting from 0.
|===

*Example Request:*

[source,json, linenums]
----
GET https://anypoint.mulesoft.com/cloudhub/api/applications/exampleapp/logs?limit=1
----

*Example Response:*

[source,json, linenums]
----
200 OK
Content-Type: application/json
Server: Apache-Coyote/1.1
Date: Sun, 18 Jan 2015 00:12:55 GMT
 
{
  "data": [
    {
      "message": "Deploying application to 1 workers.",
      "priority": "SYSTEM",
      "sequenceNumber": 1343797858127,
      "timestamp": 1344872571834
    }
  ],
  "total": 528
}
----

[TIP]
Check out the link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal] of the CloudHub API to see an interactive reference of all the supported resources, methods, required properties, and expected responses.
