= List All Notifications
:keywords: cloudhub, cloudhub api, example, get, json

The GET operation specified with the /api/notifications resource returns a list of all notifications for your account. The resulting JSON contains a list of notification objects.

The following query parameters are supported:

[width="100%",cols="34a,33a,33a",options="header",]
|===
| Name | Default | Description
|limit |25 |The number of notifications to return.
|offset |0 |The row to start listing notifications messages at.
|domain |  |The application to find notifications for.
|status |  |"read", "unread" or "all"
|search |  |Searches the message of the notification for the specified text.
|tenantId |  |The id of the tenant to find notifications for.
|===

*Example Request:*

[source,json, linenums]
----
GET https://anypoint.mulesoft.com/cloudhub/api/notifications
----

*Example Response:*

[source,json, linenums]
----
200 OK
Content-Type: application/json
Date: Sun, 18 Jan 2015 00:12:55 GMT
 
{
  "data" :
  [
    {
      "domain": "myapp",
      "username": "joecloud",
      "priority": "INFO",
      "message": "Something happened",
      "createdAt": "2015-01-10T23:42:53.010Z",
      "read": false,
      "href": "https://prod.anypoint.mulesoft.com/cloudhub/api/notifications/518d85fde4b00795a6ec3394"},
      "transactionId": "2a097804-f0d5-11e2-b4d2-9dd46521a02d",
      "properties": {
         "recordId" : "1234"
      }
  ],
  "total": 1
}
----

[TIP]
Check out the link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal] of the CloudHub API to see an interactive reference of all the supported resources, methods, required properties and expected responses.
