= Maintenance and Upgrade Policy
:keywords: cloudhub, support, upgrade, subscription

All maintenance to the CloudHub console, platform services, and worker cloud (see link:/cloudhub/cloudhub-architecture[CloudHub Architecture]) is performed during the maintenance windows specified in the link:http://www.mulesoft.com/terms/msa/current[subscription agreement], except for critical security issues which are fixed immediately.

MuleSoft's policy is to perform all maintenance transparently and without any downtime to your integration(s) running in the worker cloud wherever possible. In cases where downtime for the console, platform services, or workers is unavoidable, MuleSoft communicates these maintenance windows at least 8 hours in advance and typically 7 days in advance, with the exception of critical security patches which may be fixed immediately.

View the live status and detailed service history for the CloudHub console, CloudHub platform services, and the CloudHub worker cloud on link:http://status.mulesoft.com/[status.mulesoft.com].

For our versioning and back support policy, please see link:https://www.mulesoft.com/legal/versioning-back-support-policy[here].
