= Penetration Testing Policies
:keywords: cloudhub, testing, audit, workers

If you are deploying applications to link:/cloudhub[CloudHub] or the link:/anypoint-platform-for-apis[Anypoint Platform for APIs] and your company's security policies require that you run penetration testing on them, there is a way for you to run these. Given that such tests can interfere with other tenants, penetration testing is only allowed on your own workers. It is not allowed for any other services in the Anypoint Platform.

To perform such testing, you must provide a written request 5 business days in advance to security@mulesoft.com along with:

* Start and end time of testing.
* Hosts to include in the test.
* Source IP address or range.
* Contact information, including a phone number and email, for the individual or team conducting the test.
* Agree to only audit CloudHub workers, and not audit any other platform services which are common to all tenants.
* Agree not to audit shared workers.
* Send an email to security@mulesoft.com upon start and completion of tests.
* Notify security@mulesoft.com of any vulnerabilities found immediately.
* You may only audit once a quarter.

After you submit your request, you receive a written authorization from of the MuleSoft team, at which point you may proceed with testing according to your proposed plan.
