= Anypoint Studio January 2015 with 3.6.0 Runtime - Update Site 1 Release Notes
:keywords: release notes, anypoint studio

May 4, 2015

This May 2015 release is a second update to the Studio March 2015 with 3.6.1 runtime.

== Current Release Versions

[cols="3*", options="header"]
|===
|
| Enterprise Runtime
| Community Runtime

| ESB Runtime
| 3.6.1 EE
| 3.6.1 CC

| Studio
2+<| Version: Anypoint Studio January 2015 Release
5.1.0
Build Number:  201503171252

| Management Console
| n/a
| n/a

| Mule DevKit
2+<| 3.6.1

| Mule APIkit
2+<| 3.6.1

|===


== New Features and Functionality

* DataSense in background: DataSense now retrieves metadata for your connectors in the background, enabling you to keep working without interruption.
* Unified Login to for Anypoint Platform: sign in once for both CloudHub and the Anypoint Exchange, save your login information and manage your accounts via Anypoint Studio preferences.
* Choice router features an improved experience and now supports MEL auto-completion
* Support for deploying applications with version 2.0 of the Siebel connector.
* Undo is now supported in script component editors.
* Field labels now correctly render in the DataSense explorer.

[TIP]
Upgrading from an existing instance of Anypoint Studio or previous Mule runtime version? Refer to the Migration Guide.

This release also supports the Mule ESB 3.6.1 runtime which addresses a critical security issue.

== Migration Guide

This section presents configuration considerations you may want to adjust when migrating from a previous version of a Mule runtime, or previous version of Studio. Contact MuleSoft if you have a question about a specific migration activity or concern.

[NOTE]
====
Because the base version of Eclipse used by Anypoint Studio has changed from 3.8 to 4.4 (Eclipse Luna) in the January 2015 release of Studio, Studio *cannot be updated* from versions that are older than the January 2015 release. If that's the case, you must download and install the latest version.

If you already have the last version of Studio (January 2015) no special migration considerations are needed, use *Help > Check for Updates*.
====

* If you are upgrading from Studio 5.0.0 to 5.1.0, you can update Studio. If you are upgrading from an earlier version, you will need to download the latest version and create a new version. This step is required because of the changes to Eclipse, as described in the note above.

[NOTE]
If you are using Studio as a plugin to Eclipse, it will only work with Eclipse version 4.3 or 4.4 due to a dependency on Maven SWT.

* APIkit 1.5.1 only works in runtimes whose versions are older than 3.6.0. APIkit 1.6.0 works in the 3.6.0 runtime and above (see JIRA STUDIO-5955).
* http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html[Java 7] is required for Anypoint Studio. If you are deploying to Java 6 runtimes, you can continue to configure Java 6 as the Java runtime for your project.

[TIP]
To replace the deprecated HTTP connector for the new http://www.mulesoft.org/documentation/display/current/HTTP+Connector[high-performance HTTP Connector], refer to http://www.mulesoft.org/documentation/display/current/Migrating+to+the+New+HTTP+Connector[Migrating to the New HTTP Connector].

If you wish to install a previous runtime or a community runtime, follow the instructions to add additional runtimes to your new instance of Studio.

== APIkit Considerations

[IMPORTANT]
This version of Anypoint Studio requires Java 7. Java 6 is not supported, and Java 8 is not supported by the Mule 3.6.0 Runtime or later.

For most use cases, Anypoint Studio January 2015 with 3.6.0 Runtime does not change the hardware and software system requirements established by Anypoint Studio October 2014 with 3.5.2 Runtime. MuleSoft recommends a minimum of 4 GB RAM on a developer workstation. As applications become complex, consider adding more RAM. Please contact MuleSoft with any questions you may have about system requirements.

== Deprecated in this Release

Nothing has been deprecated in this release.

== Hardware and Software System Requirements

[NOTE]
====
*Important*

This version of Anypoint Studio requires Java 7. Java 6 is not supported, and Java 8 is not supported by the Mule 3.6.0 Runtime or later.
====

For most use cases, Anypoint Studio March 2015 with 3.6.1 Runtime does not change the hardware and software system requirements established by Anypoint Studio October 2014 with 3.5.2 Runtime. MuleSoft recommends a minimum of 4 GB RAM on a developer workstation. As applications become complex, consider adding more RAM. Please contact MuleSoft with any questions you may have about system requirements.

== JIRA Issue Reference

=== New Feaatures and Functionality

* [STUDIO-5956] - [DataSense in Background] Improve cache locking.
* [STUDIO-5957] - [DataSense in Background] Create a serial background process queue for DataSense jobs
* [STUDIO-5959] - [DataSense in Background] Error handling
* [STUDIO-5960] - [DataSense in Background] UI feedback
* [STUDIO-6013] - Sign in to platform for exchange and cloudhub
* [STUDIO-6025] - Labels for fields don't render in DataSense explorer

=== Bug Fixes

* [STUDIO-459] - Unable to add a response when creating a second flow in the same mflow
* [STUDIO-3092] - "Message Chunk Splitter" description is from "Collection Splitter"
* [STUDIO-5553] - [New Launcher] Re-deploy fails
* [STUDIO-5859] - 3.6 Studio Help provides incorrect info
* [STUDIO-5870] - Deploy to CloudHub :: Some fields are not cleaned after changing project
* [STUDIO-5872] - Deploy to CloudHub :: Environment behaviour is not clear
* [STUDIO-5876] - HTTP connector configuration is reset when changing display name by using the direct edit
* [STUDIO-5946] - New Containers: I can drag and drop a flow inside of the Source are of another flow
* [STUDIO-5948] - Undo doesn't work in script editors
* [STUDIO-5968] - Datamapper is not being added automatically to the pom file when project is maven based
* [STUDIO-5971] - When adding dependencies automatically to the pom file the <inclusion> element is not added
* [STUDIO-5973] - src/main/api directory isn't being added as resource folder in maven projects with APIkit
* [STUDIO-5984] - HTTP request :: RAMLs with custom baseUriParameters are not supported. Only {version} is correctly processed
* [STUDIO-5985] - HTTP request :: Set RAML fields to blank when changing RAML
* [STUDIO-5993] - Subflows are not given unique names when dragged to canvas
* [STUDIO-5995] - HTTP request :: NPE when clicking OK in configuration without filling any field
* [STUDIO-6001] - Debugger :: When deleting a MP with breakpoints, they end up in the next MP
* [STUDIO-6007] - Poll :: No Polling option selected by default when opening the editor the first time
* [STUDIO-6010] - Debugger :: Evaluate Mule expression window :: Remember Location and Size do not work
* [STUDIO-6017] - HTTP request :: Default Host and Port only populated after clicking in BROWSE button
* [STUDIO-6023] - "Refresh metadata" throws NullPointerException
* [STUDIO-6040] - Studio deletes all SQL queries in a project
* [STUDIO-6049] - Support deploying new Siebel connector
* [STUDIO-6052] - Global configuration :: Connector config is not created in the selected project
* [STUDIO-6055] - Cannot launch applications using Maven deployment
* [STUDIO-6098] - Import/Export :: Last Export destination path saved in the exported project
* [STUDIO-6102] - [DataSense in Background] Query builder :: Empty first time is opened before fetching metadata
* [STUDIO-6105] - [DataSense in Background] NPE when Changing Operation
* [STUDIO-6118] - [DataSense in Background] When an editor is opened error message is displayed in wrong place
* [STUDIO-6119] - [DataSense in Background] Error message is displayed more than once
* [STUDIO-6120] - [DS in Background] Fix SAP Metadata retrieval
* [STUDIO-6121] - NPE when launching an application with old server
* [STUDIO-6123] - [Datamapper] Generating wrong input metadata for datasense when using a collection of Pojos as input.
* [STUDIO-6126] - [Studio Login] Register Now link doesn't work
* [STUDIO-6129] - [DataSense in Background] Domain xml config changed to project xml config after editing connector from error message
* [STUDIO-6133] - Metadata propagation isn't working across sub flows
* [STUDIO-6135] - Studio UI contains dialog to add interceptors but json schema validator doesn't support them
* [STUDIO-6139] - [DataSense in Background] Error notifications dialog loses buttons when the message is too long.
* [STUDIO-6145] - [DataSense in Background] When changing Metadata tree focus NPE is displayed
* [STUDIO-6146] - HTTP Inbound endpoint :: After editing configuration port is downloaded to XML
* [STUDIO-6153] - [Datasense] Problem when comparing Datatypes of actual and expected Metadata Propagation.
* [STUDIO-6154] - [Datasense] Problem when comparing Datatypes of actual and expected Metadata Propagation.
* [STUDIO-6155] - Import/Export NPE when exporting projects
* [STUDIO-6157] - [DataSense in Background] MP's that use metadata cache for autocompletion are not refreshed after fetching metadata
* [STUDIO-6162] - [Metadata Propagation] StackOverflow exception when filtering metadata coming from batch in the metadata tree
* [STUDIO-6163] - Query builder :: Fields not recognized after clearing metadata cache
* [STUDIO-6165] - cache TTL incorrectly noted as being in seconds
* [STUDIO-6177] - [Studio Login] NPE when deploying to CloudHub using a domain with 2 letters
* [STUDIO-6185] - [Login] Support for custom URLs in the preferences
* [STUDIO-6186] - Inbound endpoint API gateway: After editing configuration port is downloaded to XML
* [STUDIO-6193] - [Studio Login] Domain criteria is not displayed completely in CloudHub deploy
* [STUDIO-6195] - [Studio Login] Add a message to the URL preferences to prevent errors
* [STUDIO-6196] - [Studio Login] Login is requested several times in CloudHub dialog
* [STUDIO-6198] - [Studio Login] Remove support for custom URLs in preferences
* [STUDIO-6204] - [Studio Login] CloudHub preferences are not displayed anymore

=== Improvements

* [STUDIO-781] - Would save time to be given the option to create a class in addition to selecting an existing class inside a widget dialog box (e.g., Component)
* [STUDIO-2462] - The Service class field should be moved to the JAX-WS client group
* [STUDIO-3205] - Connections View usability improvements
* [STUDIO-3852] - Property editor should open for new components dropped into workspace
* [STUDIO-4227] - DataMapper: Deleting a filter in visual map leaves the folder collapsed
* [STUDIO-4493] - Flow Ref: Display name should display name of referenced flow.
* [STUDIO-5645] - WS Consumer support for the new HTTP connector
* [STUDIO-5804] - Feedback icon should be place over the arrow
* [STUDIO-5907] - Remove 'connector' word from global TCP Connector and WMQ XA Connector
* [STUDIO-5926] - Change response arrow color
* [STUDIO-5933] - Change icon for "Mule Properties View" Tab (unselected state)
* [STUDIO-5949] - Remove "View" from Properties and Debugger Tab Titles
* [STUDIO-5982] - HTTP request :: root RAML should be detected automatically
* [STUDIO-5998] - Add drag and drop functionality for ClassNameField editors.
* [STUDIO-6008] - Ability to select MP in visual editor and bring up its XML code
* [STUDIO-6035] - Studio should warn you or save automatically if you run an unsaved mule project
* [STUDIO-6041] - [DataSense in Background] Cancel all jobs if first one fails (for a given set of credentials)
* [STUDIO-6043] - [DataSense in Background] Automatically refresh DataSense explorer when the user changes the object type
* [STUDIO-6046] - [DataSense in Background] Show visual cue on types drop down if something fails
* [STUDIO-6071] - [Studio Login] Login Web Window
* [STUDIO-6072] - [Studio Login] Preference page
* [STUDIO-6073] - [Studio Login] Deploy to cloudhub
* [STUDIO-6140] - [DataSense in Background] Make error text selectable.
* [STUDIO-6149] - [DataSense in Background] Make the DataSense explorer tree refresh every time a job finishes.
* [STUDIO-6150] - [DataSense in Background] Make the DataMapper editor refresh on job completion


== Support Resources


* For further details on Anypoint Studio with 3.6.0 Runtime, see the link:/documentation/display/current/Anypoint+Studio+January+2015+with+3.6.0+Runtime+Release+Notes[Anypoint Studio January 2015 with 3.6.0 Runtime Release Notes]
* Refer to MuleSoft’s http://www.mulesoft.org/documentation/display/current/Home[MuleSoft Documentation] for instructions on how to use the new features and improved functionality in Anypoint Studio with 3.5.1 Runtime.
* Access MuleSoft’s http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal].
