= The Mule Agent
:license-info: Enterprise
:version-info: 3.6.0 and later
:keywords: esb, enterprise, agent, api

The Mule agent is a plugin extension for Mule which exposes the Mule API. Using the Mule agent, you can monitor and control your Mule ESB servers by calling APIs from external systems, and/or have Mule publish its own data to external systems. The agent has many features, including:

* Controlling applications, domains and services:
** List, deploy, undeploy, or redeploy domains
** List, deploy, undeploy, get status of, start or stop applications
* Publishing Mule metrics to external monitoring systems

The agent supports two communication protocols: REST and WebSockets. 

The agent is installed into your `$MULE_HOME/plugins` directory; it is configured via a single configuration file. For installation instructions and download links, see link:/mule-agent/installing-mule-agent[Installing the Agent].

Additionally, MuleSoft provides several open source agent modules. These are provided as is, and receive no support for MuleSoft. To access these modules, check the GitHub repositories:

* https://github.com/mulesoft/mule-agent-modules[Agent modules (general)]
* https://github.com/mulesoft/mule-agent-modules/tree/master/mule-agent-monitoring-publishers[JMX publisher modules]

[NOTE]
The Mule agent is only available for Mule Enterprise Edition (EE). Currently, the Mule agent supports Mule 3.6.0 or later.

== Assumptions

The pages link:#TheMuleAgent-pages[listed below] assume that you have the current version of Mule Enterprise already installed. Download it from the http://www.mulesoft.com/support-login[customer portal] if you need to upgrade to this version.

Additionally, it is assumed that your enterprise license is current. Please see link:/mule-user-guide/installing-an-enterprise-license[Installing an Enterprise License] for information on obtaining and installing an enterprise license.

== Mule Agent Documentation Pages

* link:/mule-agent/installing-mule-agent[Installing Mule Agent]
* link:/mule-agent/mule-agent-architecture[Mule Agent Architecture]
* link:/mule-agent/administration-service[Administration Service]
* link:/mule-agent/managing-applications-and-domains[Managing Applications and Domains]
* link:/mule-agent/event-tracking[Event Tracking]
* link:/mule-agent/jmx-service[JMX Service]
* link:/mule-agent/mule-agent-notifications[Mule Agent Notifications]
* link:/mule-agent/extending-the-mule-agent[Extending the Mule Agent]
* link:/mule-agent/internal-handler-buffering[Internal Handler Buffering]
