= Installing the Mule Agent
:keywords: agent, mule, esb, servers, monitor, notifications, external systems, third party, get status, metrics

_*Enterprise Edition*_

== Assumptions

This document assumes that you have installed one of the following:

* Mule Enterprise version 3.6.x or above
* API Gateway 2.0 or above

If your Mule version is 3.6.x, you have to download the agent separately (see below). If your Mule version is 3.7.0 and later, the agent is already bundled with Mule, and you can go directly to the installation section.

This document assumes that your enterprise license is current. Please see http://www.mulesoft.org/documentation/display/current/Installing+an+Enterprise+License[Installing an Enterprise License] for information on obtaining and installing an enterprise license.

[NOTE]
Mule Agent is only available for Mule 3.6.0 or later versions, and Anypoint API Gateway 2.0 or later.

[TIP]
It is recommended to run the latest version of Mule Enterprise. Download it from the http://www.mulesoft.com/support-login[customer portal] if you need to upgrade.


== Installing the Agent

You can install the Mule agent on Mule ESB or API Gateway. The installation procedure is the same for Mule 3.7 and for API Gateway; for Mule 3.6.x, you have to download the agent manually.

[tabs]
------
[tab,title="Mule 3.7 and above"]
....

In 3.7.0, the agent comes bundled with your Mule installation. You install it by running `$MULE_HOME/bin/amc_setup` (or `$MULE_HOME\bin\amc_setup.bat` if on Windows).

The install script provides you with several options, explained below.

....
[tab,title="Mule 3.6"]
....


If you are using **Mule 3.6.x**, you need to download the agent. The agent comes bundled in a .jar file with a quick-start script for easy installation.

* http://mule-agent.s3.amazonaws.com/1.1.0/agent-setup.jar[Download the Mule agent (3.6.x only)]

The agent download consists of a file called `agent-setup.jar`. This file is a script that installs the agent for you. To install the agent, you run this file on the server where your Mule installation resides.

The quick-start script installs the Mule agent plugin in the Mule instance of your choice. Additionally, it adds a default `mule-agent.yml` file to the `conf/` folder in your `MULE_HOME`.

After downloading `agent-setup.jar`, copy it to the server that hosts the Mule installation where you want to install the agent. You have two options for running the script:

*Option 1:*

Run the script from any directory, specifying the directory where Mule is located using the `--mule-home` parameter, as shown below.

----
java -jar agent-setup.jar --mule-home /Users/user/mule
----

*Option 2:*

Copy the `agent-setup.jar` into `MULE_HOME/bin`, then run it with no parameters as shown below.

----
java -jar agent-setup.jar
----

[NOTE]
After running the installation script, you will need to restart Mule for these settings to take effect.

....
[tab,title="API Gateway"]
....

_*API Gateway 2.0 and above*_

The Mule agent comes bundled with your API Gateway installation. You install it by running `$MULE_HOME/bin/amc_setup` (or `$MULE_HOME\bin\amc_setup.bat` if on Windows). In this case, `$MULE_HOME` is the root directory of the API Gateway installation).

The install script provides you with several options, explained below.

The Mule agent in API Gateway allows you to add the gateway's Mule runtime as a server to Anypoint Management Center. For more information, see the *Add a Server* section in link:/docs/display/current/Managing+Applications+and+Servers+in+the+Cloud+and+On+Premises[Managing Applications and Servers in the Cloud and On Premises].

....
------

=== Installation Options

Whether installing on Mule 3.6.x or 3.7.0, the options for the installation script are the same.

==== Example Installation Commands

===== Mule 3.6.x
----
java -jar agent-setup.jar --mule-home=/opt/mule/mule-3.6.1
----

===== Mule 3.7.0

If running from the `$MULE_HOME/bin` directory:

----
./amc_setup -I
----

If running from another directory, requires the `--mule-home` option:

----
bin/amc_setup --mule-home /opt/mule/mule-3.7.0 -I
----

[NOTE]
The `amc_setup` script in Mule 3.7.0 requires at least the `-I`, `-S` or `-H` options to run. If run with no options, the script returns a help message. For details on these options, see below.


[width="100%",cols="50%,50%",options="header",]
|===
|Parameter |Description
|`-H` a|
Configures the Mule agent to connect to the Anypoint Management Center (AMC). This option requires a token (provided by the AMC console) and a name for the Mule server as you want it to appear in AMC. For example:

----
-H 800644c019d3ef2a264e5f3a5c9569ce myserver
----

To obtain the token, you need to use the *Add Server* option in AMC. Once you have the token, copy-paste it as the `-H` parameter for your agent installation command.

For details, see the *Add a Server* section in link:/docs/display/current/Managing+Applications+and+Servers+in+the+Cloud+and+On+Premises[Managing Applications and Servers in the Cloud and On Premises].

|`-I` |Configures the Mule agent to use an unencrypted connection. It is valid for the REST transport only. You will be able to interact with the API using a browser or other tool for making HTTP requests.
|`-S` |Configures the Mule agent to establish a TLS connection with an on-premises administration console. You will need to provide the truststore and keystore in JKS format. This option enables a TLS channel for REST communications only. See <<Insecure Connection Channel (I)>>.
a|
`-P`

` --proxy`

 |When configuring Mule agent to connecto the Anypoint Management Center via a proxy, this option defines proxy details. See <<Installation Via Proxy (P)>>.
|`--mule-home` |Your `$MULE_HOME` directory. Use this option if you are not running the installation script from `$MULE_HOME/bin`.
|===

==== Secure Connection Channel (S)

----
Anypoint Mule Agent Installer ----------- Mode [Secure connection Channel(S) / Insecure Connection Channel(I) / Quit(Q)] (?):
----

This option configures the Mule agent to establish a TLS connection with an on-premises administration console. You will need to provide the truststore and keystore in JKS format. This option enables a TLS channel for REST communications only. Once you select the Secure connection Channel mode, you will see the following menu:

----
The communication channel for the agent will be encrypted using public/private key certificates. In the following steps you will be asked to provide the keystore and truststore. Both keystore and truststore format must be JKS.

Keystore location (?):
Truststore location (?):
Keystore Password (?):
Keystore Alias (?):
Keystore Alias Password (?):
INFO: Mule agent was successfully configured to use a TLS channel for REST communications.
----

_*Keystore location*_

The location of the keystore file to encrypt the communication channel. The keystore must be in JKS format. It is mandatory to provide one.

_*Truststore location*_

The location where of the truststore file to accept incoming requests from the administration console. The truststore must be in JKS format and must not have a password.

_*Keystore Password*_

The password to read the keystore. The password is used by the agent to open the keystore.

*_Keystore Alias_*

The alias of the key stored in the keystore.

*_Keystore Alias Password_*

The alias password in the keystore.

==== Insecure Connection Channel (I)

This option configures the Mule agent to use an unencrypted connection. It is valid for the REST transport only. You will be able to interact with the API using a browser or other tool for making HTTP requests.

==== Hybrid Management (H)

Configures the Mule agent to connecto to the Anypoint Management Center (AMC). This option requires a token (provided by the AMC console and an instance name. For further information, please http://www.mulesoft.com/support-login[contact us].

==== Installation Via Proxy (P)

If you are configuring the Mule agent to connect to the Anypoint Management Center via a proxy, use this option to define proxy details. User and password are optional and may be omitted if the proxy doesn't require authentication.

_*Proxy* *Host*_

The host of the desired proxy.

_*Proxy Port*_

The port of the desired proxy.

_*Proxy User*_

The user with which to authenticate against the proxy.

*_Proxy Password_*

The password with which to authenticate against the proxy.

[TIP]
If you have already installed the Mule agent and want to change its configuration to use a proxy, you can do so by editing the `wrapper.conf` file. For details, see Configuring a Proxy for the Mule Agent.

== Configuring the Agent

=== Configuring `mule-agent.yml`

At startup, the Mule agent reads its configuration from the file `$MULE_HOME/conf/mule-agent.yml`. You must manually add, then edit this file with your installation's configuration parameters.

 View a sample config file

==== Configuration File Structure

The `mule-agent.yml` file is structured in three levels:

* First level: Component types: transports, services, internalHandlers and externalHanders +
** Second level: Component name, e.g. `mule.agent.jmx.publisher.service` +
*** Third level: Component configuration. A component can have complex object configurations, including more than one recursive level

To learn more on how to configure the Mule agent, refer to the documentation of each component.

==== Configuring During Runtime

Some Agent components allow you to configure them during runtime. For further information, see link:/docs/display/current/Administration+Service[Administration Service].
