= JMX Service

The Mule agent JMX Service allows you to track specific JMX metrics and publish them to external services. The service can be configured to track specific beans and to change the frequency with which it publishes their value.

Additionally, MuleSoft provides several open source monitoring publishers as separate agent modules. These are provided as is, and receive no support for MuleSoft. For details, see link:#JMXService-os_pubs[Open Source Agent Modules] below. +

#JMXService-Operation:RetrieveConfiguration[Operation: Retrieve Configuration]

#JMXService-Operation:ModifyConfiguration[Operation: Modify Configuration]

link:#JMXService-AddingaNewJMXPublisher[Adding a New JMX Publisher]

* link:#JMXService-WritingYourJMXPublisher[Writing Your JMX Publisher]

link:#JMXService-OpenSourceAgentModules[Open Source Agent Modules]

* link:#JMXService-[``]

== https://github.com/mulesoft/mule-agent/blob/master/mule-agent-documentation/mule-agent-documentation-jmx-publishing/src/doc/asciidoc/2_mule-agent-jmx-service-overview.adoc#jmx-publishers[]JMX Publishers

The JMX service sends all the gathered metrics to publishers, which in turn publish the metrics to external monitoring tools. The service itself provides some example publishers for commonly-used tools; furthermore, you can create your own publisher to suit your specific needs.

== Configuring the https://github.com/mulesoft/mule-agent/blob/master/mule-agent-documentation/mule-agent-documentation-jmx-publishing/src/doc/asciidoc/2_mule-agent-jmx-service-overview.adoc#jmx-service-configuration[]JMX Service

=== https://github.com/mulesoft/mule-agent/blob/master/mule-agent-documentation/mule-agent-documentation-jmx-publishing/src/doc/asciidoc/2_mule-agent-jmx-service-overview.adoc#retrieving-configuration[]Operation: Retrieve Configuration

Retrieves the JMX service configuration.

*Request:*

*Example:*

*Response:*

The response contains a list of the publishers currently loaded, as well as the configurable fields of the service and their values (for more information on service configuration, see link:#[Administration Service]).

=== https://github.com/mulesoft/mule-agent/blob/master/mule-agent-documentation/mule-agent-documentation-jmx-publishing/src/doc/asciidoc/2_mule-agent-jmx-service-overview.adoc#modifying-configuration[]Operation: Modify Configuration

This operation modifies the current configuration of the service.

*Request:*

*Example:*

*Response (if successful):*

=== https://github.com/mulesoft/mule-agent/blob/master/mule-agent-documentation/mule-agent-documentation-jmx-publishing/src/doc/asciidoc/2_mule-agent-jmx-service-overview.adoc#removing-individual-beans-to-track[]Adding a New JMX Publisher

To add a new JMX publisher, you need to implement the Mule agent's `InternalMessageHandler` interface.

Your custom JMX publisher should meet the following requirements:

* It must be thread-safe
* It must implement all publishing logic in the handle method defined in `InternalMessageHandler`.

==== Writing Your JMX Publisher

The Metric class is a POJO that contains the following fields:

To add your new JMX publisher, just drop the jar containing your classes under the `lib` folder within the Mule agent plugin.

== Open Source Agent Modules

MuleSoft provides several modules for the Mule agent, including JMX publishers for Nagios, Zappix and others. These modules are an open source project, and are not supported by MuleSoft.

To access the Mule agent modules, check the GitHub repositories:

* https://github.com/mulesoft/mule-agent-modules[Agent modules (general)]
* https://github.com/mulesoft/mule-agent-modules/tree/master/mule-agent-monitoring-publishers[JMX publisher modules]

==== ``
