= Persisting MMC Data On External Databases

#*_Enterprise Edition_*#

#*_MMC Version 3.4.2 and Later_*#

By default, the Mule Management Console stores its persistent data on an embedded database on the local host. In this scenario, a catastrophic failure of the host would cause the loss of all data. You can avoid this situation by configuring MMC to store data on an external database, which ideally would reside on a dedicated server.

[NOTE]
This page and most of the pages linked here are intended for configuring data persistence on _fresh MMC installations_, i.e. installations that have not already been configured to persist data to an external database. If your MMC installation is already set up to persist data to an external database, and you are looking to upgrade to MMC 3.5.0, you will need to perform special steps, including some migration of old config data. To determine the exact procedure you need to follow in order to upgrade, see link:/mule-management-console/v/3.6/upgrading-the-management-console[Upgrading the Management Console].

There are two kinds of data that MMC can store on external databases:

* *Environment data*, such as created alerts, deployments, dashboard portlets configuration
* *Transaction data* (Business Events)

You can configure MMC to store its data on the following database servers:

* link:/mule-management-console/v/3.6/persisting-mmc-data-to-postgresql[PostgreSQL]
* link:/mule-management-console/v/3.6/persisting-mmc-data-to-oracle[Oracle]
* link:/mule-management-console/v/3.6/persisting-mmc-data-to-mysql[MySQL]
* link:/mule-management-console/v/3.6/persisting-mmc-data-to-ms-sql-server[MS SQL Server]_ _

Click the links above for details on setting up MMC to work with each of the listed database servers.
