= Deploying Mule ESB 3

As of version 3.1, Mule standalone can run multiple applications. This means you can include the same name spaces within different applications and they will neither collide nor share information.

* In effect, it's now an app server.
* In addition, Mule checks for new apps (in the apps directory) and will start them.
* It will also restart apps if it detects that they have changed, meaning you can drop a revised version of an existing, running application into the /apps directory, Mule will stop the existing app and restart using the new files.
* This results in one fewer reason to run Mule inside a container.

* link:/mule-user-guide/v/3.3/deployment-scenarios[Deployment Scenarios]
* link:/mule-user-guide/v/3.3/mule-deployment-model[Mule Deployment Model]
* link:/mule-user-guide/v/3.3/configuring-logging[Configuring Logging]
* link:/mule-user-guide/v/3.3/mule-server-notifications[Mule Server Notifications]
* link:/mule-user-guide/v/3.3/profiling-mule[Profiling Mule]
* link:/mule-user-guide/v/3.3/hardening-your-mule-installation[Hardening your Mule Installation]
* link:/mule-user-guide/v/3.3/configuring-mule-for-different-deployment-scenarios[Configuring Mule for Different Deployment Scenarios]
