= Extending Mule ESB 3

Mule ESB provides a great deal of default functionality that you can use in your implementation. If you need different functionality, you can extend Mule as described on this page.

== Creating Extensions

You can create five basic types of extensions to Mule: projects, modules, transports, examples, and enterprise patterns.

* A *project* is a stand-alone Mule application.

* A *module* is a package of related functionality in Mule, such as the XML module, which provides XML-based utilities like filters and routers. For a list of the available modules you can use, see link:/docs/display/33X/Modules+Reference[Modules Reference].

* A *link:/docs/display/33X/Connecting+Using+Transports[transport]* is a type of module that carries messages between Mule flows via a specific protocol. For a list of the available transports you can use, see link:/docs/display/33X/Transports+Reference[Transports Reference].

* An *example* is a sample application that you create to help users get up and running more quickly. Several link:/docs/display/33X/Mule+Examples[examples] are provided with Mule.

* A *catalog* is a Mule-created Maven archetype created to help Mule users create custom configuration patterns.

Mule provides Maven archetypes that create the templates for each of these types of functionality in seconds, including the configuration files, unit tests, and packages.

An archetype acts as a wizard, prompting you to provide input, and then creates template configuration, source, and unit test files. Furthermore, if you run an archetype on an existing project or module you created, Maven will update it for you.

When working with transports, note that you can link:/docs/display/33X/Configuring+a+Transport[configure an existing transport], or you can link:/docs/display/33X/Creating+Transports[create a new one]. The recommended approach is to try to use and configure an existing transport first.

* link:/docs/display/33X/Extending+Components[Extending Components]
* link:/docs/display/33X/Custom+Message+Processors[Custom Message Processors]
* link:/docs/display/33X/Creating+Example+Archetypes[Creating Example Archetypes]
* link:/docs/display/33X/Creating+a+Custom+XML+Namespace[Creating a Custom XML Namespace]
* link:/docs/display/33X/Creating+Module+Archetypes[Creating Module Archetypes]
* link:/docs/display/33X/Creating+Catalog+Archetypes[Creating Catalog Archetypes]
* link:/docs/display/33X/Creating+Project+Archetypes[Creating Project Archetypes]
* link:/docs/display/33X/Creating+Transports[Creating Transports]
* link:/docs/display/33X/Creating+Custom+Routers[Creating Custom Routers]

== Developing Your Extension

After using the Maven archetype to get started, the recommended practice is to use an integrated development environment (IDE) such as Eclipse or IntelliJ to develop your Mule project, transport, module, or example. The Mule IDE allows you to quickly get up and running developing with Mule in Eclipse. For more information, see Using IDEs.

== Promoting Your Extension on MuleForge

After you have created a new extension, you can submit it as a project on MuleForge. This allows you to share it with the Mule community so you can get feedback on the quality and design of the module before putting it into production. By submitting to MuleForge, you get the benefit of others trying out your module, and others get the benefit of your work.

== Internationalizing Mule

If you will use Mule in countries where English is not spoken, you can extend Mule by internationalizing the strings in the messages and exceptions. Additionally, there are guidelines you should take into consideration to make sure your code handles different locales. For more information, see link:/docs/display/33X/Internationalizing+Strings[Internationalizing Strings] and link:/docs/display/33X/Internationalization+Guidelines[Internationalization Guidelines].

== Creating Configuration Patterns

The creation of custom configuration patterns can allow you to reach new levels of productivity with Mule. Follow this tutorial for link:/docs/display/33X/Creating+Catalog+Archetypes[starting to create your own patterns now].
