= Schema Documentation

With Mule 3.0 comes a release of new Javadoc-style schema documentation, making it easier to familiarize yourself with all the elements and attributes permissible in xml configuration files.

== Recent Changes to Mule Schemas

If you are familiar with previous versions of Mule, you may want to consult this list of link:/mule-user-guide/v/3.3/notes-on-mule-3.0-schema-changes[schema changes].

== JavaDoc-Style HTML Output

Framed HTML documentation provides most detailed and easy accessible information about all Mule 3.0 schema components and interconnections between them.

http://www.mulesoft.org/docs/site/3.2.0/schemadocs

http://www.mulesoft.org/docs/site/3.1.0/schemadocs

http://www.mulesoft.org/docs/site/3.0.1/schemadocs

== UML Diagrams

Diagrams of many of the logical structures you will use to write Mule configurations.

== Elements, Attributes, Annotations, and Substitutions

Navigate among exploded views of Mule schemas, viewing all objects - inherited or native - in a single location.
