= Connecting SaaS, Social Media, and E-Commerce Using Mule Cloud Connect

== What is Mule Cloud Connect?

Mule Cloud Connect is a powerful, lightweight toolset for using a number of SaaS, Social Media and E-Commerce Services with Mule ESB. Because each Cloud Connector is self-contained, you do not need to install anything aside from the Cloud Connector itself. Each Mule Cloud Connector includes a Mule specific schema which provides code completion and inline documentation.

It has always been possible to connect Mule to these services in the past using specific link:/mule-user-guide/v/3.2/transports-reference[transports]. Mule Cloud Connect creates a layer on top of these services to simplify the use of these services even further.

When used with Flows users can create orchestration which can span multiple services and make use of all the functionality provided by Mule. This includes the ability to use Mule routing, exception handling, asynchronous execution abilities - just to name a few.

== Getting Started with Mule Cloud Connect

To find documentation on how to install and use each cloud connector, see our list http://www.mulesoft.org/muleforge/connectors[available cloud connectors] on the forge or learn how to use them inside link:/mule-user-guide/v/3.2/studio-cloud-connectors[Mule Studio]. You can also learn about some scenarios in which Cloud Connectors are useful by reading link:/mule-user-guide/v/3.2/integrating-with-cloud-connect[Integrating with Cloud Connect].

Once installed a Cloud Connect is used like any other feature in Mule. For example:

[width="99a",cols="99a"]
|===
^|Salesforce Query
|
[source, xml, linenums]
----
<salesforce:query query="SELECT Id, Name FROM Account WHERE Name = 'Sandy'"/>
----
|===

This uses the SalesForce connector to make a call to SalesForce's query API with the specified query. This will then return a query result from SalesForce which can then be easily referenced.

== When to use Mule Cloud Connect

Cloud Connect provide an alternative type of connector to a link:/mule-user-guide/v/3.2/transports-reference[Mule Transport]. Transports typically represent communication protocols whereas Cloud Connect are better suited for connecting Mule to an application API built on top of an underlying protocol already supported by Mule.

[TIP]
*Application API* - An application API allows you to create, query or modify data and services within a specific application. Some popular examples include Twitter, Facebook, LinkedIn, Amazon Web Services, Google, and SalesForce. Today most application APIs are commonly exposed through REST or SOAP web services.

== Available Cloud Connectors

A categorized list of http://www.mulesoft.org/muleforge/connectors[available cloud connectors] is available and the documentation for each connector will provide you with everything you need to know to successfully use the connector with Mule. This includes how and where to download the connector, details of how to obtain any keys for the service, and information on how to include and use the cloud services operations in your Mule flows.

If a connector is not available for a cloud service you wish to connect to, consider creating your own connector using our easy to follow link:/documentation-3.2/display/32X/How+to+Build+a+Cloud+Connector[How to Build a Cloud Connector] guide. This step by step guide includes examples and a tool to help speed up the creation of your cloud connector projects.
