[width="99a",cols="99a"]
|===
|
[TIP]
*Did you know . . .*

MuleSoft has released Studio GA, a powerful new interface for Mule ESB that can cut your development time by half or more. You can model, debug, and deploy your applications all within the rich, yet flexible Studio environment.

Studio provides two-way (i.e., graphical and code-based) editing, which means that developers no longer have to trade ease-of-use against fine-grained control over their development projects. Any changes you make in one mode appear instantly in the other.

Mule Enterprise and Mule iON developers can fine-tune their applications in the advanced Studio XML editor, then re-deploy them on whichever version of Mule those applications were originally developed.

Studio installation is almost instantaneous, and a pair of tutorials can get you up and running in less than 40 minutes.

Let’s get Kicking!

[width="99a",cols="40a,60a"]
|===
|
http://www.mulesoft.org/download-mule-esb-community-edition[Download Studio here.] |[Check out our Studio documentation here.]
|===

|===

= Essentials of Using Mule ESB 3

Mule is a flexible message processing and integration framework. The way you use it depends on the problem you are trying to solve. Mule 3 offers multiple configuration constructs that can be mixed and matched as required to implement your solution.

* link:/mule-user-guide/v/3.2/understanding-mule-configuration[Understanding Mule Configuration]
* link:/mule-user-guide/v/3.2/choosing-between-flows-patterns-or-services[Choosing Between Flows, Patterns, or Services]
* link:/mule-user-guide/v/3.2/message-sources-and-message-processors[Message Sources and Message Processors]
* link:/mule-user-guide/v/3.2/configuring-components[Configuring Components]
* link:/mule-user-guide/v/3.2/connecting-using-transports[Connecting Using Transports]
* link:/mule-user-guide/v/3.2/configuring-endpoints[Configuring Endpoints]
* link:/mule-user-guide/v/3.2/using-filters[Using Filters]
* link:/mule-user-guide/v/3.2/using-transformers[Using Transformers]
* link:/mule-user-guide/v/3.2/connecting-saas-social-media-and-e-commerce-using-mule-cloud-connect[Connecting SaaS, Social Media, and E-Commerce Using Mule Cloud Connect]
* link:/mule-user-guide/v/3.2/mule-query-language[Mule Query Language]
* link:/mule-user-guide/v/3.2/using-expressions[Using Expressions]
* link:/mule-user-guide/v/3.2/message-property-scopes[Message Property Scopes]
* link:/mule-user-guide/v/3.2/transaction-management[Transaction Management]
* link:/mule-user-guide/v/3.2/configuring-security[Configuring Security]
* link:/mule-user-guide/v/3.2/error-handling[Error Handling]
* link:/mule-user-guide/v/3.2/using-web-services[Using Web Services]
* link:/mule-user-guide/v/3.2/mule-application-architecture[Mule Application Architecture]
