= Team Development with Mule

Topics in these books have addressed your local workstation, and a single project with a single configuration file. When working on a team, the Mule project will increase in size, will increase in its number of developers, and must run in other environments, such as test and production. Here are some practices that will make such growth possible.

The different approaches to modularizing Mule configurations and applications are all opportunities for splitting work across teams, whether these teams work on the same overarching project or on different projects with an accent put on reuse.

Download a PDF version of this section link:/documentation-3.2/download/attachments/33163047/Team+Development+with+Mule.pdf?version=1&modificationDate=1303431731496[MULE3USER:here].

* link:/mule-user-guide/v/3.2/modularizing-your-configuration-files-for-team-development[Modularizing Your Configuration Files for Team Development]
* link:/mule-user-guide/v/3.2/using-side-by-side-configuration-files[Using Side-by-Side Configuration Files]
* link:/mule-user-guide/v/3.2/using-parameters-in-your-configuration-files[Using Parameters in Your Configuration Files]
* link:/mule-user-guide/v/3.2/using-modules-in-your-application[Using Modules In Your Application]
* link:/mule-user-guide/v/3.2/sharing-custom-code[Sharing Custom Code]
* link:/mule-user-guide/v/3.2/sharing-custom-configuration-fragments[Sharing Custom Configuration Fragments]
* link:/mule-user-guide/v/3.2/sharing-custom-configuration-patterns[Sharing Custom Configuration Patterns]
* link:/mule-user-guide/v/3.2/sharing-applications[Sharing Applications]
