= Upgrading CXF from Mule 2

Mule 3 completely revamps the CXF support. CXF no longer exists as a transport, but rather a module which is a series of message processors.

This has the following benefits:

* Flexibility - it is now much easier to intermix CXF with transformers, filters and other message processors. You simply insert a CXF message processor in the flow where you wish it to be executed.
* Easier configuration - there are a number of configuration elements, e.g. jaxws-service, simple-service, proxy-service, etc, which each have their own syntax targeted to their specific use cases.
* Increased robustness - with the improved property scoping and message processor model, the CXF module property is more robust and rigorous in it's behavior.

To learn more about the new syntax, see:

* link:/documentation-3.2/display/32X/Building+Web+Services+with+CXF[Building Web Services with CXF] - Information on how to build JAX-WS code first, JAX-WS WSDL first, and simple frontend services.
* link:/documentation-3.2/display/32X/Consuming+Web+Services+with+CXF[Consuming Web Services with CXF] - Information on how to consume JAX-WS services and simple frontend services.
* link:/documentation-3.2/display/32X/Proxying+Web+Services+with+CXF[Proxying Web Services with CXF] - Information on how to create web service proxies, e.g. if your CXF endpoint had proxy="true" before.
