= Using Mule with Spring

Mule ESB and Spring can integrate on different levels. You can can choose as much or little Mule in your Spring application or Spring in your Mule application. The following pages describe in detail how you can use Mule and Spring together.

* link:/mule-user-guide/v/3.2/about-the-xml-configuration-file[About the XML Configuration File] +
The default way to configure Mule is via a Spring 2.0 XML file.

* link:/mule-user-guide/v/3.2/spring-application-contexts[Spring Application Contexts] +
Describes different options for how Mule creates and manages Spring Application Contexts.

* link:/mule-user-guide/v/3.2/using-spring-beans-as-service-components[Using Spring Beans as Service Components] +
How to configure Spring beans as service components in Mule.

* link:/mule-user-guide/v/3.2/sending-and-receiving-mule-events-in-spring[Sending and Receiving Mule Events in Spring] +
A really easy way for your beans to send and receive Mule events via the Spring Application Context without any code changes.

* #[Spring Remoting]# +
An example of accessing Mule from an external application using Spring remoting.

Additionally, there are two Spring-related projects in the #[Developer Sandbox]#.
