= Getting Started with Mule Studio

Let's get started with Mule! This page and the pair of accompanying tutorials put you on the fast track to developing Mule ESB applications with Studio's drag-and-drop visual interface.

In less than fifteen minutes, our link:/documentation-3.2/display/32X/Basic+Studio+Tutorial[basic tutorial] can help you:

* master Studio's building-block configuration process +
* create and deploy your first Mule application

If you have an extra half-hour after that, our link:/documentation-3.2/display/32X/Intermediate+Studio+Tutorial[intermediate tutorial] can show you how to create a more complex Mule application.

Both tutorials highlight Studio's simple, yet powerful development-test-deploy cycle. If, at some later point, you wish to learn more about Best Practices for designing Mule Flows or Tips and Tricks for leveraging the Studio interface, link:/mule-fundamentals/v/3.2/mule-studio-3.2.x[we have documentation for that too]. But first, let us guide you through your first couple of Mule applications.

[TIP]
====
If you haven't already installed Mule and set up your development environment, click link:/mule-user-guide/v/3.2/installing-mule-studio[here].

To reach the Mule Studio download page, click http://www.mulesoft.org/download-mule-esb-community-edition[here].
====

== Where Next?

Cloud computing is closer than ever before. Why not start by checking out our fifteen-minute link:/documentation-3.2/display/32X/Basic+Studio+Tutorial[Basic Tutorial]?

Let's get kicking!
