= Mule ESB 3.2.X User Guide

[WARNING]
This User Guide is for Mule ESB version 3.2.0 and 3.1.x. Information specific to Mule 3.2.0 is marked as **[Mule 3.2]**.


The User Guide describes how to use Mule for software development.

== link:/mule-fundamentals/v/3.2/how-mule-works[How Mule Works]

Have you ever wondered how Mule accomplishes its task as an Enterprise Service Bus? This topic explains how Mule works.

== link:/mule-fundamentals/v/3.2/using-mule-with-web-services[Using Mule with Web Services]

This topic, written by popular demand, provides a detailed overview of how to integrate Web services into your Mule application.

== link:/mule-fundamentals/v/3.2/mule-management-console-3.2.x[Using the Mule ESB Management Console]

Deploy applications, monitor your Mule ESB servers, get alerts, and perform admin server tasks using the Mule Management Console. Read about all the features of the console and how to use them.

== link:/mule-user-guide/v/3.2/connecting-saas-social-media-and-e-commerce-using-mule-cloud-connect[Connecting SaaS, Social Media, and E-Commerce Using Mule Cloud Connect]

Mule Cloud Connect is a powerful way to move data between different endpoints such as Salesforce.com, Twitter, and Amazon. Read here how to accomplish this.

== link:/mule-user-guide/v/3.2/creating-transports[Creating Transports]

If you're ready to extend Mule to create your own transport, read this topic, which explains how to accomplish this advanced task.

== link:/mule-user-guide/v/3.2/introduction-to-testing-mule[Introduction to Testing Mule]

Testing is part and parcel of getting ready to deploy your Mule application. Read this topic for an introduction into testing Mule.

== link:/mule-user-guide/v/3.2/team-development-with-mule[Team Development with Mule]

You may be working on a team that is developing a Mule application. Read this section for tips on how to structure your development effort to support team development.

== link:/mule-user-guide/v/3.2/reference-materials-for-mule-esb-3[Reference]

Everything you need to look up important information when developing with Mule.
