= Managing Users and Groups
:keywords: tcat, users, groups, permissions

Tcat Server uses the common permission scheme of users and user groups. Users are individuals who can log in to Tcat Server. User groups allow you to assign permissions collectively to a group of users.

You manage users and user groups on the Administration tab in Tcat Server. You can also use LDAP to enable authentication (see link:/tcat-server/v/7.1.0/enabling-authentication-through-ldap[Enabling Authentication Through LDAP]). Note that after enabling authentication through LDAP, the Users link is no longer available.

== Managing Users

This section describes how to create, edit, and delete a user in Tcat Server.

==== Create a User

. On the Administration tab, click *Users*, and click *New*.
. Enter the user name that the user enters when they log in to Tcat Server, as well as the user's full name, email address, and password (at least five characters).
. Select at least one user group that you want this user to have.
The default user groups are Administrator and User. If you need to create more user groups, see Managing User Groups below.
. Click *Save*.

==== Edit a User

. On the Administration tab, click *Users*, and  click the user name of the user you want to edit.
. Edit the user's name or email address if needed.
. If you need to reset the user's password, click *Reset Password*, enter the new password twice, and then click *OK*.
. To assign a user group to the user, select it in the Available User Groups list and click *>*. To remove that user group from the user, select it in the Joined User Groups list and click *<*.
. When you have finished editing this user, click *Save*.

==== Delete a User

. On the Administration tab, click *Users*, and  click the user name of the user you want to delete.
. Click *Delete*.
. Click *OK* to confirm that you want to delete this user.

== User Groups

Tcat comes with several pre-defined user groups with the following levels of permissions:

[width="100",cols="50,50",options="header"]
|===
|Name |Description
|Administrators |Users who have full control over a Tcat instance.
|Deployers |Users with the ability to view deployments, deploy, undeploy and redeploy them.
|Monitors |Users which have a read only view into the console.
|Server Administrators |Users who can manage servers and deployments, but not users, groups or anything else on the administration tab.
|===

== Managing User Groups

This section describes how to add, edit, and delete a user group in Tcat Server. Note that you cannot delete the Administrator user group.

There are two categories of permissions in Tcat - those which are global (displayed on the left) and those which can be applied to server groups (displayed on the right). For instance, the ability to view servers is a server group permission. A user can have that permission for all server groups or a particular server group.

Let's say you want to give a user the ability to only view servers in the all server groups. To do this, select the group All from the drop down box and select the "Server - View" permission. If you wanted this user to only have the ability to view servers for the Production group, then you would uncheck the permission for the All group, select Production from the server group drop down box, and then select the "Server - View" permission.

==== Create a User Group

. On the Administration tab, click *User Groups* in the left pane, and then click *New*.
. Enter a name for this user group and click *Save*.
The new user group appears in the user group list.
. Check the permissions you want users with this user group to have.
. When you finish creating the user groups you want, click *Save*.
. To assign this user group to a user, edit the user as described above.

==== Edit a User Group

. On the Administration tab, click *User Groups*.
. Edit the assigned permissions as needed.
. If you want to change the user group name, click its name, type the new name, and click *Save*.
+
*Note*: You cannot edit the Administrator user group.
+
. When you finish editing user groups, click *Save*.

==== Delete a User Group

. On the Administration tab, click *User Groups*, and  click the name of the user group you want to delete.
Note: You cannot delete the Administrator user group.
. Click *Delete*.
. Click *OK* to confirm that you want to delete this user group.

link:/tcat-server/v/7.1.0/user-group-permissions[<< Previous: *User Group Permissions*]

link:/tcat-server/v/7.1.0/enabling-authentication-through-ldap[Next: *Enabling Authentication Through LDAP* >>]
