= Managing the Repository
:keywords: tcat, repository, manage, artifacts, workspace

The Repository tab allows you to add and remove *artifacts*, such as configuration files and applications, and manage workspaces. A *workspace* is a location in the repository where artifacts are stored. You can upload all your artifacts into the default Applications workspace, or you can create new workspaces to organize your artifacts.

== Viewing the Repository Contents

When you first view the Repository tab, it displays the top-level workspaces, including the default workspace Applications. Click a workspace to see the artifacts and child workspaces it contains. You can use the navigation tree on the left to navigate through the workspace levels and select the workspace you want to work with.

== Modifying an Artifact or Workspace

When you click an artifact or workspace, its details appear in on four tabs:

* The Items tab displays any artifacts within this artifact, such as applications within a workspace or versions within an application.
* The Info tab displays the name, type, metadata (such as the default version or primary lifecycle), and comments for this artifact. Adding metadata allows you to specify values for properties you can use to search for artifacts in a future release. Adding comments allows you to enter freeform text that is for your own reference when viewing the object.
* The Policies tab displays any policies set at various stages in the lifecycle of an artifact
* The Security tab allows you to control access to this artifact

== Adding a Workspace

You add a workspace when you want to create logical groupings of your artifacts. This is useful as the number of artifacts in your repository grows. You can create workspaces within workspaces to further organize your applications.

To add a workspace:

. On the Repository tab, navigate to the workspace in which you want to add the new workspace, or just stay in the default view to add it to the root level.
. Click *New Workspace*.
. Enter a unique name for this workspace, and then click *Add*. Workspace names should be meaningful as well as unique. For example, when creating server profiles, you might want to create a parent workspace called ServerProfiles and then create workspaces under it called Production, LinuxDevelopment, and so on.

The workspace now appears in the navigation tree on the left, and the view changes to show the contents of the new workspace. You are now ready to add artifacts to this workspace.

== Adding Applications and Other Artifacts

You can add artifacts to the repository such as applications, configuration files, or any other type of file that you want to deploy to multiple Tomcat servers. The following steps describe how to add an artifact manually to the repository. You can also add an artifact to the repository when you are link:/tcat-server/v/7.1.0/deploying-applications[creating a package], or you can use the link:/tcat-server/v/7.1.0/maven-publishing-plug-in[Maven Publishing Plug-in] to cause applications to be uploaded to the repository every time they are built.

To add an artifact:

. On the Repository tab, navigate to the workspace where you want to add the artifact.
. Click *New Artifact*.
. Browse to the location of this file and select it, or just type its full path name in the File box.
. In the Name field, enter a unique name for this file. You can use the same name as the file name as long as it is unique within this workspace.
. In the Version field, leave *1* set if this is the first time you are uploading this file, or enter a higher number if there is already a previous version of this file. Having multiple versions of a file makes it easy to roll back to a previous version if needed.
. Click *Add*.

== Subscribing to Change Notifications

Tcat Server provides an RSS feed of changes to its repository. You can subscribe to this feed to be notified about changes to a specific artifact or all the artifacts in a workspace. To subscribe, click the artifact or workspace, click *Feed*, and then specify the options provided by your browser for subscribing to this feed. If you just want to subscribe to comments changes, click the Atom feed icon next to Comments.

== Removing an Artifact or Workspace

[IMPORTANT]
When you remove a workspace, all of its artifacts are also removed.

To remove an artifact or workspace, select it on the Repository tab, and then click *Delete*.

link:/tcat-server/v/7.1.0/troubleshooting[<< Previous: *Troubleshooting*]

link:/tcat-server/v/7.1.0/managing-users-and-groups[Next: *Managing Users and Roles* >>]
