= Monitoring Repository Activity
:keywords: tcat, monitor, repository, activity, log, artifacts

An important aspect of governance is the logging of all relevant changes inside the repository. Activities such as lifecycle transitions and the addition of new artifacts are all logged inside Tcat Server. You can easily search and view these updates by clicking the Activity link on the Administration tab.

You can filter the activity log by date, by the user who made the changes, and by artifacts containing specific text or of certain types. You can also type the name of a specific artifact in the Relating to box to see activity for just that item. Lastly, you can specify the maximum number of results you want to return. After specifying the filter conditions you want, click *Search*. To clear the filter and see all activity, click *Reset*.

link:/tcat-server/v/7.1.0/creating-remote-workspaces[<< Previous: *Creating Remote Workspaces*]

link:/tcat-server/v/7.1.0/applying-your-tcat-server-license[Next: *Applying Your Tcat Server License* >>]
