= Monitoring Applications
:keywords: tcat, monitor, applications, sessions, attributes, jsp, resources, jndi

When viewing a list of the applications on a server (in the administration console, click the Servers tab, click a server name, and then click the Applications tab), you can view further details about a specific application by clicking its name. The Summary tab displays runtime information about the application and statistics charts. You can click one of the side tabs in the left navigation bar to see more information as described in the following sections.

== Summary

The Summary tab provides runtime information about the application, such as the number of servlets, context attributes, and requests. It also displays charts showing the historical number of requests and average response time. You can click a chart to expand it, and you can click any of the blue numbers to display more detailed information. For example, clicking the number of servlets displays the Servlets tab. You can use the buttons at the top of the tab to go to the application (even if it's on a remote server) in the browser window, to stop the application, to reload it, or to undeploy it from the server. You can also estimate the sessions size.

== Sessions

The Sessions tab displays the current sessions for this application. You can click the session name to see more details, including the session attributes, and to access the option to destroy the session. You can also click an IP address to perform a WHOIS query on it and display details about its origin. To estimate the size of the sessions, click *Estimate Size*. To hide the Size column, click *Hide Size*.

== Attributes

The Attributes tab displays the servlet context attributes for this application. If you want to remove an attribute from the servlet context, simply click the trash icon next to the attribute.

== JSPs

The JSPs tab lists the JSPs deployed with this application. If any have not been precompiled, you can select them and compile them from this tab. To view the source code of a JSP, click its name. You can then click *View Generated Servlet* to view the auto-generated servlet code for this JSP or click *View JSP* to go back to the JSP code. You can also compile the JSP while viewing its code.

== Resources

The Resources tab lists the JNDI resources that are referenced by the application. The Type column displays the type of resource, and if it's a data source it also displays the URL, the maximum number of connections in the pool, the number of busy connections (cannot be reused), and the number of established connections (can be reused). The Link To column indicates whether this resource is a link on a globally defined resource (that is, a resource defined outside of the context that is shared by multiple applications). The Authentication column indicates whether resource authentication is handled by the container on behalf of the application (user name and password are specified on the resource definition) or programmatically by the application itself.

For information on working with JNDI resources in Tomcat, see link:https://tomcat.apache.org/tomcat-7.0-doc/jndi-resources-howto.html[JNDI Resources How-To] on the Apache site.

== Context Descriptor

The Context Descriptor tab displays the contents of the application's `context.xml` file. You can click the download link to download the file, which is renamed to the application's name.

== Deployment Descriptor

The Deployment Descriptor tab displays the contents of the application's `web.xml` file. You can click the download link to download the file.

== Servlets

The Servlets tab displays a list of the servlets in this application. For each servlet, the table displays the servlet's context path, the servlet class it implements, whether it's currently available, whether it's loaded on startup (and if so, its loading order), the time in milliseconds it took to load, the number of requests so far to this servlet, the total amount of time this servlet has spent processing requests, the number of errors, the minimum and maximum time spent on a single request, and, whether the servlet is multi-threaded. You can click *Servlet Mappings* to view the mappings between URLs and the servlets that handle them, and then click *Servlets* to return to viewing the list of servlets.

== Filters

The Filters tab displays a list of the filters used by this application. For each filter, the table displays the filter name, its implementation class, and a description (if available). You can click *Filter Mappings* to view the filters that are called for different URLs, which servlet implements the filter (if not specified by the application), which type of dispatchers apply the filter, and the filter class. Click *Filter Definitions* to return to viewing the list of filters.

== Parameters

The Parameters tab displays a list of the parameters that are used to initialize the context. Typically, these are taken from the application's `WEB-INF\web.xml` file.

link:/tcat-server/v/7.1.0/monitoring-a-server[<< Previous: *Monitoring a Server*]

link:/tcat-server/v/7.1.0/troubleshooting[Next: *Troubleshooting* >>]
