= Overview of Tcat Server
:keywords: tcat, server, tomcat

This page introduces Tcat Server and describes the underlying technologies. For more information, see link:https://www.mulesoft.com/tcat/understanding-apache-tomcat#tcat[Tcat Resources].

== What is New in Tcat Server?

Consult the link:/tcat-server/v/7.1.0/release-notes[Release Notes] for the latest release information.

== What is Tcat Server?

Tcat Server from MuleSoft provides a powerful enterprise solution for developing, deploying, managing, integrating, and troubleshooting your web applications in Apache Tomcat. It comprises one or more Apache Tomcat instances and an administration console.

Tcat Server makes Tomcat even more powerful and simple to use:

* Administration Console web application enables you to monitor and control all your Tomcat (and Tcat Server) instances on multiple servers. Unlike Tomcat's native manager application, the Tcat Server console allows you to quickly set up users and roles across all servers without having to edit the XML file in each instance separately
* Easily deploy and view both remote and local applications from the console instead of just local instances
* Monitor the health of the applications and the servers where you've deployed them
* Install multiple instances on a single machine
* Run Tcat Server instances as Windows Services
* Restart remotely (except for OS X)
* Use Admin Shell component to run custom groovy scripts, hook into deployment events, and automate restarts

Tcat Server is free to try out and use in development, so you can do a full proof of concept and test deployments before you go live. When you are ready to go into production, you purchase a subscription from MuleSoft at a fraction of what you would pay for a heavyweight application server.

== About Tomcat

Tomcat is a very popular web server and servlet container developed by link:http://www.apache.org[Apache Software Foundation]. Unlike the Apache Web Server, which is a C implementation of an HTTP web server, Tomcat is written in Java. Tomcat is free and is used in mission-critical environments around the world. If you are writing web applications in Java, Tomcat is a great choice for deploying and managing them.

Following are a few resources available to help you learn about Tomcat:

* http://tomcat.apache.org/tomcat-8.0-doc/index.html[Tomcat 8]
* http://tomcat.apache.org/tomcat-7.0-doc/index.html[Tomcat 7]
* http://tomcat.apache.org/tomcat-6.0-doc/index.html[Tomcat 6]
* http://wiki.apache.org/tomcat/GettingStarted[Apache's Getting Started Guide for Tomcat]
* http://oreilly.com/catalog/9780596101060/[Tomcat: The Definitive Guide] published by O'Reilly

link:/docs/display/TCAT/Home[<< Previous: *Home*]

link:/tcat-server/v/7.1.0/quick-start[Next: *Quick Start* >>]
