= Tcat Server 6 R2 Release Notes

This page describes the changes in Tcat Server 6 R2 and includes the known and fixed issues in this release.

== New Features

This release includes the following new features:

* *Server Profiles*: You can now use server profiles to set environment variables and configuration files on multiple Tomcat instances simultaneously. For more information, see link:/tcat-server/v/7.1.0/working-with-server-profiles[Working with Server Profiles].
* *Remote Server Restart*: You can now restart any Tomcat instance you manage with Tcat Server. For more information, see link:/tcat-server/v/7.1.0/working-with-servers[Working with Servers].
* *Remote File Monitoring*: The new Files tab allows you to view and manage the files on any server you manage with Tcat Server. For more information, see link:/tcat-server/v/7.1.0/monitoring-a-server[Monitoring a Server].

== Known Issues

This section describes the known issues in this release and how to work around each issue.

* When installing Tcat Server on Windows, the Start menu items are always installed in the group "Tcat Server 6" regardless of what Start menu group name you enter in the installer. Therefore, if you install multiple instances of Tcat Server on the same machine, you can only  use these Start menu items to start and stop the last instance installed. To work around this issue, use the `tcat6 start` command from the `bin` directory at the command prompt to start your other instances.
* If you are connected to a network via VPN, Tcat Server does not auto-detect unregistered servers. To work around this issue, disconnect from VPN before starting Tcat Server, or add the servers manually as described in link:http://www.mulesoft.org/display/TCAT/Working+with+Servers[Working with Servers].
* When servers are registered, they are registered with a specific IP address. If you are testing on a laptop with a wireless connection and you move from one location to another, your IP address might change, and the servers can no longer communicate with Tcat Server. In this case, you must unregister and reregister the servers with the current IP address.
* If you are running Internet Explorer 7 on Windows 2008, you can log in to Tcat Server, but the main screen does not appear. To work around this, choose *File > Add this site to... > Trusted Sites*.
* If you navigate to another tab while a package is being deployed, the deployment is interrupted. To work around this issue, wait for a package to be deployed before navigating elsewhere.
* If you increase the font size on Mozilla Firefox, the monitoring and diagnostic screens disappear. To work around this issue, leave the font size set to the default.
* When viewing the details of an application, the Session Search link on the Sessions sub-tab currently does not function properly.
* If you download the installer more than once, Firefox appends parentheses to the file name, which causes problems when you try to run the installer. If you must download the installer again, delete the original file first so that Firefox leaves the original name intact.
