= Troubleshooting
:keywords: tcat, troubleshoot, memory usage, applications, console

This page describes common problems and how you can troubleshoot them.

==== What Tools are available for Troubleshooting?

You can use Tcat Server to check memory usage, see which objects are in your session and how big they are, view deployment descriptors, view threads, and view JSPs and their generated code. You can view these details by clicking a server on the Servers tab and then navigating through the tabs that show the server details. To see details for a particular application on the server, click the Applications tab when viewing the server details, and then click the application name.

For more information, see link:/tcat-server/v/7.1.0/monitoring-a-server[Monitoring a Server] and link:/tcat-server/v/7.1.0/monitoring-applications[Monitoring Applications].

==== Problem: My Applications are no Longer Recognized

When servers are registered, they are registered with a specific IP address. If you are testing on a laptop with a wireless connection and you move from one location to another, your IP address might change, and the servers cannot communicate with Tcat Server. In this case, you must unregister and reregister the servers with the current IP address.

==== Problem: My Console is Unavailable and I Cannot Unregister its Servers

To manually unregister a server, you must delete its `webapps\agent\WEB-INF\truststore.jks` file. The server  then becomes available again for registering in another console.

==== Problem: My Newly Installed Tcat Server Instance is Running, but it Does not Appear in the Unregistered Group in the Console

If you are connected to a virtual private network (VPN), it can interfere with new Tcat Server instances appearing in the console. Disconnect from the VPN, restart the Tcat Server instance, and try again. You can verify that your Tcat Server agent is running by entering `http://<hostOrIPAddress>:<port>/agent` in your browser, such as http://localhost:8080/agent if it's on your local computer. If you get a message indicating the status of the agent, it's running.

After you have registered your servers, you can reconnect to your VPN.

==== Problem: My Newly Installed Tcat Server Instance is Running and Appears in the Unregistered group in the Console, But I Can't Register it

This can happen if you do not have an HTTP connector port set in the `conf\server.xml` file in your Tomcat installation, such as if you're just using the AJP port to connect via HTTPD. You must have an HTTP connector port configured so that Tomcat can communicate with Tcat Server.

==== Problem: Increased the Font Size and the Screen Went White

If you are using Firefox, and you press the Ctrl key with the plus (+) key to increase the magnification of the screen, some of the screens can become blank. To work around this issue, press Ctrl plus the minus key (-) to zoom back out.

==== Problem: I Want to Change Which Files can be Edited from the Files Tab when Viewing a Specific Server's Details

The Files tab provides you with access to files on the local server as well as remote servers. To restrict or enable write access to a directory on a specific server, you modify the `agent/WEB-INF/spring-services.xml` file on that server and add or remove directories from the `writeExcludes` property in the `accessControlFileService` bean.

link:/tcat-server/v/7.1.0/monitoring-applications[<< Previous: *Monitoring Applications*]

link:/tcat-server/v/7.1.0/managing-the-repository[Next: *Managing the Repository* >>]
