= Upgrading to Tcat Server 6 R3
:keywords: tcat, upgrade, server, r3

If you have Tcat Server 6.2.1 installed, the new installer  retains all paired servers, new web applications, user roles, server profiles, and environment variables you have saved.

If you are using an earlier version of Tcat Server, you need to follow the upgrade path to 6.2.1 first. 

Download the Tcat Server installer for Windows (.exe), Linux (.sh), and Mac OS (.dmg) from https://www.mulesoft.com/tcat/download.

== Run the Installer

. Run the Installer.
+
image:/docs/plugins/servlet/confluence/placeholder/unknown-macro?name=table-plus&locale=en_GB&version=2[image]
+
. Point to the existing application install directory.
. The installer retains all your existing settings.

== What the Installer Does

The Tcat Server 6 R3 installer performs the following tasks:

. Backs up the agent web application (copies webapp/agent to tcat-backup/agent) and unpack the new one
. Backs up the console web application (copies webapp/console to tcat-backup/console) and unpack the new one
. Preserves the old agent.properties file which defines the port the agent listens on
. Preserves agent truststore.jks used to provide security settings associated with the agent
. Renames the data repository used by the console from galaxy-data to tcat-data

link:/tcat-server/v/7.1.0/installation[<< Previous: *Installation*]

link:/tcat-server/v/7.1.0/installing-multiple-tcat-instances-on-a-single-machine[Next: *Multiple Instances on a Single Machine* >>]
