= Upgrading to Tcat 7.1.0
:keywords: tcat, upgrade, 7.1.0

The upgrade is done in three phases. 

. Back up the existing installation.
. Migrate tcat-data to newer schema using the migration-util.jar.
. Install Tcat Server and replace its tcat-data with the upgraded tcat-data (Step 2 above).

= Back Up the Existing Installation

. Stop Tcat Server.
. Take a complete backup of your existing installation of Tcat Server. This should include everything in your Tcat Server installation directory. 

= Migrate the Existing tcat-data to a Newer Schema

. Create a directory named *work*.
. Download migration-util-7.1.0.jar from the support portal and put it in the *work* directory.
. Make a copy of the tcat-data directory from the existing Tcat Server backup and put that tcat-data in the *work* directory.
. Download link:_attachments/repository.xml[repository.xml] and put it in the *tcat-data* directory.
. Download link:/_attachments/new-repository.xml[new-repository.xml] and put it in the *work* directory.
. If you have a large tcat-data,  make sure you have a directory with enough space which could be used as a _temp_ directory. Let's assume that the directory is /home/mulesoft/tmp. Also make sure you have at least 1 GB of memory available to allocate to the heap in the JVM
. Delete the following directories from tcat-data:
.. tcat-data/repository/index
.. tcat-data/workspaces/default/index
. In the *work* directory, make a new directory named _target-data_. This is where the upgraded database are stored
. Now run the following command to perform the migration (replace the value of -Djava.io.tmpDir with your temporary directory). _This step  takes a few minutes to complete. The larger your tcat-data, the longer it takes_:

`java -Xmx1g -Djava.io.tmpdir=/home/mulesoft/tmp -jar migration-util-7.1.0.jar --backup --repo tcat-data --conf tcat-data/repository.xml --backup-repo target-data/`

[NOTE]
====
*Error At The End of the Migration*

The following error appears when the migration finishes, ignore this error since it is expected:

`Import error on line 1 of file /var/folders/3b/wdmt1kyd0kd5gg0_112m7v8m0000gn/T/QRTZ_LOCKS.dat: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL140508230804700' defined on 'QRTZ_LOCKS'.`
====

== Install Tcat Server 7.1.0

. Start the installer and accept the defaults. Make sure to choose a different location for installation i.e. do not install over the existing Tcat Server.
. Start Tcat Server.
. *Important*: Clear your browser's cache.
. Open a browser and login to the admin console (*username:admin, password:admin*)
. When you are able to successfully log in, close the browser, and stop Tcat server (bin/tcat7 stop).
. Delete the tcat-data directory from the Tcat Server and replace it with the target-data directory.
. Rename target-data to tcat-data.
. Start Tcat Server again (use `tail` on the logs to see any errors) and log in using your credentials. 
. If you have large tcat-data, then the server start might take more than an hour because the newly migrated tcat-data's lucene indexes are being generated. 

[NOTE]
====
*Error compiling groovy scripts*

While tailing the logs, you might see errors while compiling groovy scripts. These are expected since some of your groovy scripts may be using an outdated API. Let the Tcat support team know about these scripts and they can work with you to update them or you may even no longer need them anymore.
====
