= Using Cloudcat with Amazon EC2
:keywords: tcat, cloudcat, amazon, ec2, gogrid, mysql


MuleSoft Cloudcat is enterprise Apache Tomcat in the cloud. Cloudcat is a fully supported virtual image (Amazon EC2 AMI) that allows you to deploy your Tomcat applications to the cloud. Cloudcat includes Apache Tomcat with a preconfigured MySQL database on Ubuntu Linux.

If you use MuleSoft Tcat Server, you can manage your Cloudcat instance(s) using the Tcat Server console. Cloudcat users get unlimited email-based support.


[TIP]
====
*Ready to get started?*
Just make sure you meet the prerequisites and then follow the four easy steps below!
====


If you want to use GoGrid instead of Amazon EC2, see link:/tcat-server/v/7.1.0/using-cloudcat-with-gogrid[Using Cloudcat with GoGrid]. If you want to upload your own version of Tomcat as an AMI to EC2 using the EC2 plug-in, see link:/tcat-server/v/7.1.0/deploying-to-amazon-ec2[Deploying to Amazon EC2].


== Prerequisites

Before you can use Cloudcat on Amazon EC2, you must meet the following prerequisites:

* Basic knowledge of Ubuntu commands
* Basic knowledge of http://aws.amazon.com/ec2/[Amazon EC2] and http://docs.amazonwebservices.com/AWSEC2/2007-08-29/DeveloperGuide/distributed-firewall-concepts.html[security groups]
* Amazon EC2 account
* If you  open ports manually instead of through security groups, download the link:https://aws.amazon.com/items/351?externalID=351[EC2 tools]

== Purchasing a Subscription to Cloudcat

If you have not yet purchased a subscription to Cloudcat, do the following:

. Purchase the Cloudcat subscription link:https://aws-portal.amazon.com/gp/aws/user/subscription/index.html?offeringCode=8667D160[here]. If prompted, enter your credentials and payment information and complete the purchase.
. On the registration page, enter your information and then click *Register*.

== Creating a Cloudcat Instance

To use Cloudcat, you create a new instance based on the purchased Cloudcat AMI. You will enter one of the following AMI IDs depending on how much memory you want to use for the instance:

* 32-bit AMI: `ami-adf01cc4`
* 64-bit AMI: `ami-61f71b08`

For example, you can create the instance using the AWS Management Console as follows:

. Launch the link:https://console.aws.amazon.com/ec2/home[AWS Management Console] to create one or more new instances.
. In the console, click *AMIs* in the left-hand navigation pane, and then enter the AMI ID into the text box and press *Enter*.
. Select the AMI and click *Launch*.
. Follow the instructions in the wizard to create your instance(s). When asked to specify a security group, you can select an existing group (such as Default) or create a new security group just for Cloudcat that opens your HTTP and TCP ports (8080 and 51443 by default). You could then create all your Cloudcat instances with this security group and automatically open the required ports for all of them. Note that you can change the default HTTP and TCP ports for Tomcat on the instance by modifying the `server.xml` file and restarting Tomcat. In this case, you must open the new ports instead of the defaults.

After you complete the instructions in the wizard, the instance is created, which can take several minutes. Tomcat will then start in `/opt/tomcat` on the instance. You are now ready to deploy applications to Tomcat in your Cloudcat instance. If you want to use Tcat Server to manage your instance and to deploy your applications, see the next section.

== Using Tcat Server to Manage Cloudcat Instances

Cloudcat includes the Tcat Server agent, so you can pair the Cloudcat instance with your Tcat Server instance and manage it via the Tcat Server console.

To enable access to Tcat Server:

. SSH into your remote Cloudcat instance using the following syntax: `ssh -i <your private key> ubuntu@ec2-<public address>` where `<your private key>` is the private key you set up for your EC2 account and `<public address>` is the address for the instance. In the Amazon console, the public address is displayed in the bottom pane when you click the instance.
. If your remote Tomcat server instance is stopped (it started automatically when you created the instance), start it now by entering the following command: `sudo /etc/init.d/tomcat start`
. If you did not open your HTTP and TCP ports via the security group, you must open them manually on the remote instance by entering the following command: `$ ec2-authorize -p <port> <securityGroup>` where `<securityGroup>` is the name of the group you specified when you created the instance.

To register the remote Tomcat:

. Start your local Tcat Server instance and console.
. On the Servers tab in the console, click *New Server*.
. Give the server a unique name, enter the URL `http://<public address>:8080/agent` (replace `<public address>` with the instance's public address), and then click *Register*.

You are now ready to manage the Cloudcat instance from your local Tcat Server console. For more information, see link:/tcat-server/v/7.1.0/monitoring-a-server[Monitoring a Server].

== Deploying Tomcat Applications to Cloudcat

After you have set up Cloudcat, you can start deploying your Tomcat applications in the cloud. You can manually deploy your current applications to Cloudcat by simply copying the application WAR files from your local Tomcat server and pasting them into the webapps directory of the Cloudcat instance on EC2 or GoGrid, or you can use the Tcat Server console to perform the deployments and configuration. For more information on using Tcat Server for deployment, see link:/tcat-server/v/7.1.0/deploying-applications[Deploying Applications].

Note that your web application may need specific configuration including configuring of MySQL drivers. You can use server profiles in Tcat Server to make configuration changes on Cloudcat instances. For details, see link:/tcat-server/v/7.1.0/working-with-server-profiles[Working with Server Profiles].

After you have deployed a web application to your Cloudcat instance, restart Cloudcat either manually or through Tcat Server console, and then test your application in the cloud.

== Getting Support for Cloudcat

Your subscription includes unlimited support via email. To request support, send your query to tcat-install@mulesoft.com, and a support representative will contact you.
