= Using Cloudcat with GoGrid
:keywords: tcat, cloudcat, gogrid

MuleSoft Cloudcat is enterprise Apache Tomcat in the cloud. Cloudcat is a fully supported virtual image that allows you to deploy your Tomcat applications to the cloud. Cloudcat includes Apache Tomcat with a preconfigured MySQL database on Ubuntu Linux.

If you use MuleSoft Tcat Server, you can manage your Cloudcat instance(s) using the Tcat Server console. Cloudcat users get unlimited email-based support.

[TIP]
====
*Ready to get started?*
Just make sure you meet the prerequisites and then follow the six easy steps below!
====

If you want to use Cloudcat with Amazon EC2 instead of GoGrid, see link:/tcat-server/v/7.1.0/using-cloudcat-with-amazon-ec2[Using Cloudcat with Amazon EC2].

== Prerequisites

Before you can get started with Cloudcat on GoGrid, you must meet the following prerequisites:

* Basic knowledge of Ubuntu commands
* Basic knowledge of using link:http://www.gogrid.com/[GoGrid]
* GoGrid account

== Creating a Cloudcat Instance

To use Cloudcat, you create a new instance based on the available 32-bit or 62-bit image, depending on how much memory you want to use for the instance.

To create the instance:

. link:http://www.gogrid.com/customer-login/[Log into GoGrid].
. Click **Add > Image Sandbox**, navigate to the Cloudcat images (you can type Cloudcat in the Name box to find them quickly), and then select the one you want to use.
. Enter a name and description for the instance you are creating, and then select the public IP address you want to use. You can start typing the IP address, and a list of valid addresses that were assigned to your account will appear.
. Click *Save*. GoGrid creates the instance (this can take a few minutes). When it is ready, the dot at the top of the instance turns from amber to red.
. Start the instance by right-clicking the instance and choosing *Start*. When the instance is ready, its dot turns green. Tomcat is started automatically in `/opt/tomcat` on the instance.
. Choose *Tools > Passwords* and note the password GoGrid assigned to the root user for this instance. You will need this password when using SSH to access the instance.

You are now ready to deploy applications to Tomcat in your Cloudcat instance. If you want to use Tcat Server to manage your instance and to deploy your applications, see the next section.

== Using Tcat Server to Manage Cloudcat Instances

Cloudcat includes the Tcat Server agent, so you can pair the Cloudcat instance with your Tcat Server instance and manage it via the Tcat Server console.

To enable access to Tcat Server:

. In your console, use the command `ssh root@<public address>`, where `<public address>` is the public IP address you specified for the instance, and then enter the password when prompted.
. Open port 51443 by entering the following command:

[source, code, linenums]
----
iptables -I INPUT 1 -i eth0 -p tcp -m tcp --dport 51443 -j ACCEPT
----

To register the remote Tomcat:

. Start your local Tcat Server instance and console.
. On the Servers tab in the console, click *New Server*.
. Give the server a unique name, enter the URL `http://<public address>:8080/agent` (replace `<public address>` with the instance's public address), and then click *Register*.

You are now ready to manage the Cloudcat instance from your local Tcat Server console. For more information, see link:/tcat-server/v/7.1.0/monitoring-a-server[Monitoring a Server].

== Deploying Tomcat Applications to Cloudcat

After you have set up Cloudcat, you can start deploying your Tomcat applications in the cloud. You can manually deploy your current applications to Cloudcat by simply copying the application WAR files from your local Tomcat server and pasting them into the webapps directory of the Cloudcat instance on EC2 or GoGrid, or you can use the Tcat Server console to perform the deployments and configuration. For more information on using Tcat Server for deployment, see link:/tcat-server/v/7.1.0/deploying-applications[Deploying Applications].

Note that your web application may need specific configuration including configuring of MySQL drivers. You can use server profiles in Tcat Server to make configuration changes on Cloudcat instances. For details, see link:/tcat-server/v/7.1.0/working-with-server-profiles[Working with Server Profiles].

After you have deployed a web application to your Cloudcat instance, restart Cloudcat either manually or through Tcat Server console, and then test your application in the cloud.

== Getting Support for Cloudcat

Your subscription includes unlimited support via email. To request support, send your query to tcat-install@mulesoft.com, and a support representative will contact you.
