= Working with Logs
:keywords: tcat, logs

Click the Servers tab, then the Logs tab to display the logs generated by Tomcat for each application and for the Tomcat instance itself. 

*Note*: Logs roll over at midnight daily.

The table displays the following:

* Log type (for example, JDK or Log4J)
* File name
* File size
* Last-modified timestamp
* Class used to create the log

Click a log file name to view its contents, or click the download icon to save the file locally. When viewing the log file contents, use the zoom buttons to make the font larger or smaller. You can also adjust the line wrapping and clear the log file.

*Note*: The log is updated as it is being written. To pause updating, click *Pause Tailing*. To resume watching it in real time, click *Resume Tailing*. To return to the list of logs, click *Back to log files list*.

== Monitoring Tcat Server Logs

You can monitor the logs for a Tcat Server instance by viewing the server's details on the Servers tab and then clicking the Logs tab.

Following are the logs generated by Tomcat for Tcat Server:

[width="99a",cols="50a,50a",options="header"]
|===
|This file... |Logs events related to...
|`tcat-agent-app.log` |Running the Tcat Server agent, such as starting the Quartz scheduler and loading bean definitions.
|`tcat-agent-exec-output.YYYY-MM-DD.log` |Output from commands and processes spawned by the agent. Includes STDOUT, STDERR, and info on when a command was executed and by which shell account. (As of Tcat Server 6 R2)
|`tcat-agent-sys.YYYY-MM-DD.log` |Running the Tcat Server agent in the container, such as initializing servlets.
|`tcat-console-app.log` |Running the Tcat Server console application, such as indexing, loading plugins, and starting the repository.
|`tcat-console-sys.YYYY-MM-DD.log` |Running the Tcat Server console in the container, such as initializing servlets.
|`tcat-file-audit.log` |File API operations on the server (see <<File Audit Log>> for details). (As of Tcat Server 6 R2)
|`tcat-shell-scripts.log` |Script activity on the server (see below for details).
|`mule-ibeans.log` |Mule iBeans activity.
|===

For information on logging in Tomcat, see the http://wiki.apache.org/tomcat/FAQ/Logging#Q1[Apache Logging FAQs].

== File Audit Log

(As of Tcat Server 6 R2) One of the logs listed is the file audit log `tcat-file-audit.log`, which logs every file API operation on the server. Entries in this log are prefixed by TOMCAT_FILE_AUDIT. For example, the following entries indicate that the `list()` and `download()` methods were called on files on this server:

[source, code, linenums]
----
[10-21 17:20:56] INFO  TOMCAT_FILE_AUDIT [http-51443-1]: list() |
C:\projects\galaxy-ee\trunk\tcat\provision\target\catalina-9003\.
[10-21 17:21:05] INFO  TOMCAT_FILE_AUDIT [http-51443-1]: download() |
C:\projects\galaxy-ee\trunk\tcat\provision\target\catalina-9003\.\webapps\agent\WEB-INF\agent.properties
----

== Shell Script Log

The Logs tab also displays the shell script log (`tcat-shell-scripts.log`) for any link:/tcat-server/v/7.1.0/automating-tasks[scripts you've created] in the Tcat Server administration console. The default logging level for the shell script log is INFO, which you can modify in the `webapps/console/WEB-INF/classes/log4j.properties` file. You can modify the `admin.shell.script` category to change the logging output for all admin console shell scripts, or to modify the output for a single script, modify the `admin.shell.script.[<scriptName>]` category, where `[<scriptName>]` is the name of the script surrounded by square brackets with any spaces escaped by a backslash, such as `admin.shell.script.[My\ Script]`.

*Note:* If you enter a script in the admin shell and click *Evaluate* before saving the script, the logging category for that script is `admin.shell.script.[$shell]`.

link:/tcat-server/v/7.1.0/scheduling-the-usage-statistics-script[<< Previous: *Scheduling the Usage Statistics Script*]

link:/tcat-server/v/7.1.0/automating-tasks[Next: *Automating Tasks* >>]
