= Getting Started with CloudHub
:keywords: cloudhub, connectors

CloudHub is an integration platform as a service (iPaaS). With the Anypoint Management Center, it allows you to deploy sophisticated cross-cloud integration applications in the cloud, and on premise to servers, groups of servers, and clusters, create new APIs on top of existing data sources, integrate on-premises applications with cloud services, manage servers and server groups on premises, and much more. With Anypoint Studio – the user-friendly development tool – you can quickly build integration applications and deploy to CloudHub with just a few clicks. This guide helps you learn the basics, and get started developing your first application.

== Learn CloudHub Basics

. Download https://www.mulesoft.com/lp/dl/studio[Anypoint Studio].
. Read our link:/docs/display/current/CloudHub+at+a+Glance[CloudHub at a Glance] guide to learn the basic concepts.
. Follow our easy link:/docs/display/current/Hello+World+on+CloudHub[Hello World on CloudHub] tutorial to get your first integration application up and running with Anypoint Studio and CloudHub.
. link:/docs/display/current/Getting+Started+with+Connectors[Get started with connectors] to connect to external services like Twitter.
. Ready to deploy an application?  See link:/docs/display/current/Deploying+a+CloudHub+Application[Deploying a CloudHub Application].

Still don't understand how CloudHub can be of use to you? Read more about http://www.mulesoft.com/cloudhub/ipaas-cloud-based-integration-demand[things you can do with CloudHub].

== Build CloudHub Applications

Follow one of our tutorials to learn how to build CloudHub applications.

* link:/docs/display/current/Building+an+HTTPS+Service[Building an HTTPS Service on CloudHub]  
* link:/docs/display/current/Custom+Application+Alerts[Custom Application Alerts] 

Want to learn more? Check out all the examples in link:/docs/display/current/Anypoint+Exchange[Anypoint Exchange].

== Deploy Applications to the Cloud or On-Premises

The Anypoint Management Center enables you to:

* link:/docs/current/Deploying+a+CloudHub+Application[Deploy applications] to the cloud
* link:/docs/current/Managing+Applications+and+Servers+in+the+Cloud+and+On+Premises[Manage applications and servers running on-premises] from the cloud
* link:/docs/current/Creating+and+Managing+Clusters[Create and Manage Clusters] from the cloud

== Building Connectors

Are you interested in building your own connector? Use the link:/docs/current/Anypoint+Connector+DevKit[Anypoint Connector DevKit] to rapidly build connectors and drop them inside of Studio.

== Other Resources

* link:/docs/display/current/Managing+CloudHub+Applications[Managing CloudHub Applications] 
* link:/docs/display/current/Reference+Materials[Reference Materials]
* link:/docs/display/current/Community+and+Support[Community and Support]
* There are tons of APIs available. Check our MuleSoft Blog to see a http://blogs.mulesoft.org/top-10-weird-apis/[TOP 10 of the weirdest APIs] out there.
