= Working with Logs
:keywords: cloudhub, cloudhub api, logs, json, get

The logs API allows you to search your logs. All resources or methods that return or accept a type (except where noted) use the application JSON type. As an example, here's an example of what the result from a log search looks like.

[source,json]
----
{
"data":
  [
    {
      "message": "Deploying application to 1 workers.",
      "priority": "SYSTEM",
      "sequenceNumber": 1343797858127,
      "timestamp": 1344872571834
    }
  ],
  "total": 528
}
----

== Log Object Properties

The following are the properties for applications.

[width="100%",cols="50a,50a",options="header",]
|====
|Property |Description
|message |The log message.
|priority |The priority - DEBUG, INFO, ERROR, SYSTEM, CONSOLE.
|timestamp |The timestamp in UTC when the log message occurred.
|sequenceNumber |A sequence number which determines the order of the log messages when they have the same timestamp.
|====

== Operations for Logs

The following is a summary of log related operations:

[width="100%",cols="34a,33a,33a",options="header",]
|====
|Operation |Resource |Description
|link:/docs/display/current/List+All+Logs[GET] |`/api/applications/{application}/logs` |Lists log messages.
|====

[TIP]
Check out the https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal] of the CloudHub API to see an interactive reference of all the supported resources, methods, required properties and expected responses.
