= Upgrading the Management Console
:keywords: mmc, debug, install, upgrade, update

*_Enterprise_*

MMC agent and .war files are available through the http://www.mulesoft.com/support-login[MuleSoft Customer Portal]. It is strongly recommended to upgrade to the latest version of MMC.

*Note*: MMC is now downloaded separately from Mule. Download MMC from link:https://www.mulesoft.com/dl/mmc[https://www.mulesoft.com/dl/mmc].

== Overview

The steps required to upgrade to the latest version of MMC depend on your current MMC version. If you are using MMC 3.5.0, you do not need to perform any special steps and can proceed directly with the upgrade. If you are upgrading from a version earlier than 3.5.0, read on for an overview of your upgrade path.

=== External Database and LDAP Configuration in MMC Older than 3.4.2

MMC 3.4.2 introduced a new, simplified configuration for persisting data on external databases and for managing users via LDAP. This means that if your current MMC version is earlier than 3.4.2, and you use an external database for data persistence and/or use LDAP to manage MMC users, you need to migrate your current configuration to the new config.

Additionally, if upgrading from MMC 3.4.0 or 3.4.1, you may need to upgrade your MMC agent.

=== Business Events Data in MMC Older than 3.5.0

MMC 3.5.0 introduced changes to one of the tables that store Business Events data. Before upgrading to a version of MMC greater than 3.5.0, you need to run a migration script on the database that persists Business Events data. This does not apply if your current MMC version is 3.4.2 and you persist Business Events data on MS SQL Server.

=== Upgrade Path Table According to Your MMC Version

The table below provides details for each MMC version.

[width="100%",cols="50%,50%",options="header",]
|===
|Your Current MMC version |Steps Required to Upgrade to the latest version
|*Clean install* a|
* If persisting MMC data on an external database, edit the MMC config files to include database connection information such as user, host, etc. See link:/mule-management-console/v/3.7/persisting-mmc-data-on-external-databases[Persisting MMC Data On External Databases] for details
* If managing MMC users via LDAP, edit the MMC config files to include LDAP information such as host, connection parameters, etc. See link:/mule-management-console/v/3.4/setting-up-and-managing-users-via-ldap[Setting Up and Managing Users via LDAP] for details

|*3.5.x and above* a|
* If persisting MMC data on an external database, copy the MMC config files containing database connection information to your new installation. See link:/mule-management-console/v/3.7/persisting-mmc-data-on-external-databases[Persisting MMC Data On External Databases] for details
* If managing MMC users via LDAP, copy the MMC config files containing the LDAP information. See link:/mule-management-console/v/3.7/setting-up-and-managing-users-via-ldap[Setting Up and Managing Users via LDAP] for details

|*Earlier than 3.4.x* a|
* Follow the steps required to upgrade your MMC agent
* If using an external database, follow the steps required to link:/mule-management-console/v/3.7/upgrading-to-mmc-with-an-external-database[upgrade to MMC with an external database]
* If persisting Business Events on MMC's H2 default internal database or an external database, run the relevant link:/mule-management-console/v/3.7/migration-scripts-for-business-events[migration scripts for Business Events]
* If managing MMC users via LDAP, migrate your MMC LDAP configuration as described in link:/mule-management-console/v/3.7/upgrading-to-mmc-with-ldap[Upgrading to MMC with LDAP]

|*3.4.0 and 3.4.1* a|
* If using an external database, follow the steps required to link:/mule-management-console/v/3.7/upgrading-to-mmc-with-an-external-database[upgrade to MMC with an external database]
* If persisting Business Events on MMC's H2 default internal database or an external database, run the relevant link:/mule-management-console/v/3.7/migration-scripts-for-business-events[migration scripts for Business Events]
* If managing MMC users via LDAP, migrate your MMC LDAP configuration as described in link:/mule-management-console/v/3.7/upgrading-to-mmc-with-ldap[Upgrading to MMC with LDAP]

|*3.4.1 for MS SQL Server* a|
* Follow the steps required to link:/mule-management-console/v/3.7/upgrading-from-mmc-3.4.1-for-ms-sql-server-to-latest-mmc-for-ms-sql-server[upgrade from MMC 3.4.1 for MS-SQL Server to the latest MMC for MS-SQL Server]
* If managing MMC users via LDAP, migrate your MMC LDAP configuration as described in link:/mule-management-console/v/3.7/upgrading-to-mmc-with-ldap[Upgrading to MMC with LDAP]

|*3.4.2* a|
* If persisting data on an external database, copy the files containing database connection information to your new installation
* If persisting Business Events on MMC's H2 default internal database or an external database other than MS SQL Server, run the relevant link:/mule-management-console/v/3.7/migration-scripts-for-business-events[migration scripts for Business Events]
* If managing MMC users via LDAP, copy the relevant config files to your new installation

|*3.4.2 for MS SQL Server* a|
* Copy the files containing database connection information to your new installation
* If managing MMC users via LDAP, copy the relevant config files to your new installation

|===

[TIP]
====
*If using LDAP or External DBs* +

If your current MMC version is <3.4.2, and you either:

* use LDAP to manage MMC users, or
* use an external database to persist MMC data,

you can access a quick guide describing link:/mule-management-console/v/3.7/configuration-files-for-ldap-and-external-dbs-in-mmc-before-and-after-3.4.2[configuration files for LDAP and external DBs in MMC 3.4.1 and MMC 3.4.2 or later]. Alternatively, you can access step-by-step instructions in:

* link:/mule-management-console/v/3.7/upgrading-to-mmc-with-an-external-database[Upgrading to MMC with an External Database]
* link:/mule-management-console/v/3.7/upgrading-to-mmc-with-ldap[Upgrading to MMC with LDAP]
====

== Determining Your MMC Version

You can determine what version of the MMC .war file  you are currently running by logging into the console and clicking *About Mule ESB Enterprise* at the bottom right of the screen.

[NOTE]
In all cases, it is strongly recommended to upgrade to the newest version of the Management Console.

=== Upgrading

This section contains upgrade information relevant for earlier versions of MMC:

* <<MMC 3.4.0 and 3.4.1 to latest MMC version>>
* <<MMC 3.4.1 for MS SQL Server to latest MMC version>>
* <<MMC 3.4.2 or 3.5.x for MS SQL Server to latest MMC version>>

==== MMC 3.4.0 and 3.4.1 to latest MMC version

If you are upgrading your .war to the latest MMC version, and your Mule ESB version is earlier than 3.4.1, you may need to upgrade your Management Console agent, as described below.

If you are upgrading your .war to the latest MMC version, and your Mule ESB version is 3.4.1 or later, you do not need to upgrade your Management Console Agent.

[cols=",,,",options="header",]
|===
|Your Mule ESB version |Your current MMC agent version |You need to upgrade your agent to at least |Agent file name
|3.1.x |3.1.x |3.1.4 |mmc-agent-mule3-app-3.1.4.zip
|3.2.x |3.2.x |3.2.4 |mmc-agent-mule3-app-3.2.4.zip
|3.3x |3.3.2 or above |No action necessary | 
|3.4.x |Any |No action necessary | 
|===

==== MMC 3.4.1 for MS SQL Server to latest MMC version

MMC 3.4.2 introduced a new and greatly simplified configuration for persisting data on external databases. So in order to upgrade from MMC 3.4.1 to the latest version, you need to first migrate your config files to the new format introduced in 3.4.2.

Migrating your config files is described in link:/mule-management-console/v/3.7/upgrading-to-mmc-with-an-external-database[Upgrading to MMC with an External Database]. The process is the same for upgrading to 3.4.2, for 3.5.x and later versions.

After migrating your config files, you need to run migration scripts on your target MS SQL database. This process is described in link:/mule-management-console/v/3.7/upgrading-from-mmc-3.4.1-for-ms-sql-server-to-latest-mmc-for-ms-sql-server[Upgrading from MMC 3.4.1 for MS-SQL Server to the latest MMC for MS-SQL Server].

Finally, if you are managing MMC users via LDAP, you need to migrate your MMC LDAP configuration as described in link:/mule-management-console/v/3.7/upgrading-to-mmc-with-ldap[Upgrading to MMC with LDAP].

The complete sequence of steps is:

. Download the latest version of MMC.
. Stop your MMC 3.4.1 for MS SQL server.
. In the new MMC, modify the configuration for external data persistence as described in link:/mule-management-console/v/3.7/upgrading-to-mmc-with-an-external-database[Upgrading to MMC with an External Database].
. If managing MMC users via LDAP, modify the configuration for LDAP as described in link:/mule-management-console/v/3.7/upgrading-to-mmc-with-ldap[Upgrading to MMC with LDAP]. If not managing MMC users via LDAP, skip this step.
. On your target database on MS SQL server, run the SQL migration scripts as described in link:/mule-management-console/v/3.7/upgrading-from-mmc-3.4.1-for-ms-sql-server-to-latest-mmc-for-ms-sql-server[Upgrading from MMC 3.4.1 for MS-SQL Server to the latest MMC for MS-SQL Server].
. Start the newly-installed MMC.

==== MMC 3.4.2 or 3.5.x for MS SQL Server to latest MMC version

You need to copy database connection information (database host, user credentials, etc.) from your old MMC installation to your new installation. For details, see <<MMC 3.4.2 or 3.5.x to latest MMC with an External Database>>.

=== MMC 3.4.2 to latest version

If upgrading from MMC 3.4.2, you need to run an SQL migration script on the database used to store Business Events data if one of two conditions are met:

* You are persisting Business Events data on MMC's internal H2 database (the default)
* You are persisting Business Events data on any external database except MS SQL Server

You must run this the migration script _before_ running the latest MMC for the first time. For instructions and the SQL scripts to run, see link:/mule-management-console/v/3.7/migration-scripts-for-business-events[Migration Scripts for Business Events].

=== MMC 3.4.2 or 3.5.x to latest MMC with an External Database

MMC 3.4.2 introduced a new configuration for managing users via LDAP. All MMC versions newer than 3.4.2 also use this configuration, so if upgrading to the latest version from a version later than 3.4.2, you do not need to migrate to a new configuration. However, you do need to perform two steps:

. Activate the Spring profile for your external database in `<MMC_HOME>/WEB-INF/web.xml`
. Copy the database connection information (host, user credentials, etc.) to the new installation. To do this, you can copy the file `<MMC_HOME>/WEB-INF/classes/META-INF/databases/<your_database_file>` from your old installation. The actual name of this file depends on the type of data you are persisting (environment or tracking) and the external database you are using. For example, if persisting environment data to Oracle, the correct file is `mmc-oracle.properties`.

For details on both files, see the following sections.

==== File:  <MMC_HOME>/WEB-INF/web.xml

This file defines, among other things, the internal or external databases used by MMC uses to store its data. The definition is stored in the `spring.profiles.active` section, whose default value is shown below.

[source, xml, linenums]
----
<context-param>
    <param-name>spring.profiles.active</param-name>
    <param-value>tracking-h2,env-derby</param-value>
</context-param>
----

To activate a profile for an external database in your new MMC, you can manually add the value to the section shown above, or copy the entire `web.xml` file from your old installation.

==== File: <MMC_HOME>/WEB-INF/classes/META-INF/databases/<type of data>-<database name>.properties

The type of data can be `mmc` (for MMC environment data) or `tracking-persistence` (for Business Events). The full list of available files is shown below.

[source, code, linenums]
----
mmc-db2.properties
mmc-derby.properties
mmc-mssql.properties
mmc-mysql.properties
mmc-oracle.properties
mmc-postgres.properties
tracking-persistence-db2.properties
tracking-persistence-h2.properties
tracking-persistence-mssql.properties
tracking-persistence-mysql.properties
tracking-persistence-oracle.properties
tracking-persistence-postgres.properties
----

So for example, the file `mmc-oracle.properties` defines the configuration for persisting MMC environment data on an external Oracle database; the file `tracking-persistence-postgres.properties` defines the configuration for persisting Business Events data on an external Postgres database, etc.

You can copy the entire relevant file(s) from your old installation to the new MMC.

=== MMC 3.4.2 or 3.5.x to latest MMC with LDAP

MMC 3.4.2 introduced a new configuration for managing users via LDAP. All MMC versions newer than 3.4.2 also use this configuration, so if upgrading to the latest version from a version later than 3.4.2, you do not need to migrate to a new configuration. However, you do need to perform two steps:

. Activate the LDAP Spring profile in `<MMC_HOME>/WEB-INF/web.xml`
. Copy the LDAP connection information (LDAP host, MMC credentials, etc.) to the new installation. To do this, you can copy the file `<MMC_HOME>/WEB-INF/classes/META-INF/mmc-ldap.properties` from your old installation

Details about the LDAP configuration are provided below.

*File:* `<MMC_HOME>/WEB-INF/web.xml`

This file defines, among other things, whether the LDAP profile is active or not. The definition is stored in the `spring.profiles.active` section, as shown below.

[source, xml, linenums]
----
<context-param>
...
    <param-name>spring.profiles.active</param-name>
    <param-value>tracking-h2,env-derby,ldap</param-value>
</context-param>
----

You can manually add the `ldap` parameter to this file in the ne MMC install, or copy the entire file from your old installation to the new one.

*File:* `<MMC_HOME>/WEB-INF/classes/META-INF/mmc-ldap.properties`

This is the LDAP configuration file for MMC. It is divided by sections such as `LDAP CONNECTION`, `MMC AUTHENTICATION`, etc. and contains extensive comments. When upgrading from MMC 3.4.2 or later to the latest version, you can simply copy the file to your new installation.

== See Also

* Access the link:/mule-management-console/v/3.7/configuring-mmc-for-external-databases-quick-reference[Quick Reference] for configuring MMC 3.4.2 and above for external databases
* Learn how to link:/mule-management-console/v/3.7/encrypting-ldap-and-database-passwords-in-mmc[encrypt LDAP and database passwords] in MMC 3.4.2 and above
