= Using the Management Console APIs

The management console provides REST APIs that you can use to programmatically access much of the console's functionality. Using these REST APIs, you can:

* Register new servers and manage existing servers, including restarting servers.
* Manage server groups.
* Access and manage files on servers.

For full details on all operations that are possible via REST, including usage and output examples, consult the link:/mule-management-console/v/3.7/rest-api-reference[REST API Reference].

In addition, you can use the REST APIs to:

* Create or remove a cluster and get information about a cluster, as well as start, stop, and restart applications on a cluster
* Find, upload, and delete applications inside the repository
* Deploy, undeploy, create, update, and delete deployments inside a server or cluster
* Manage flows, including finding, starting, and stopping flows as well as finding, starting, and stopping a flow's endpoints

For details on these operations, consult the link:/mule-management-console/v/3.7/rest-api-reference[REST API Reference].

== Overview

Representational State Transfer (REST) is a style of software architecture. An important concept in REST is the existence of resources, each of which can be referred to using a global identifier. Specifically, both data and functionality are considered resources. Using the REST APIs, you access functionality by specifying a URL, or link, to that functionality – this is also commonly referred to as a method. Data representation is passed to and from a REST API method in the form of a JavaScript Object Notation (JSON) object.

In brief, here's how you use the REST APIs:

* Set up any parameters that may need to be passed to the API. You set the parameter values in a JSON object.
* Build the request. The request consists of the full URL of the resource, plus the name of any parameters and their values.
* Invoke the request with the appropriate HTTP method: GET, PUT, DELETE, or POST.
* Get the response. If you retrieve information, parse the response for the data you need. You can use response data for further API requests, if needed.

You can use any HTTP client to access the APIs. Note that all management console APIs use JSON instead of XML for the data format.

If you are programming in Java, it is recommended that you use the link:https://wikis.oracle.com/display/Jersey/Main[Jersey client]. Or, for JSON support, use the http://hc.apache.org/httpclient-3.x/index.html[HttpClient] with http://jackson.codehaus.org/[Jackson], the high-performance JSON processor.

[TIP]
====
The link:/mule-management-console/v/3.7/rest-api-reference[REST API Reference] contains full details of all operations that available on the management console's REST API, including examples of input data and results.
====
