= Working with Logs

There are three types of logs you can view when working with the management console:

* *Mule ESB log*. To view the log file for a Mule ESB instance you're monitoring in the management console, follow these steps:
. Go to the *Servers* tab, then click the name of the server whose logs you want to view.
. MMC displays the Dashboard for the selected server. Click the *Files* tab.
. MMC displays the folder and file list. Click the *logs/* folder.
. In the list of files for the folder, click **mule_ee**. This log file provides details about the startup of the Mule server, any errors thrown, etc.
* *Management console logs*. The management console itself generates some log files specific to the console's functionality. For example, the `mmc-shell-scripts.log` file provides information about any shell scripts that you run in the management console (see below). These log files are located in the application server's logs directory, such as `<TomcatHome>/logs` when you deploy the management console to Tomcat.
* *Container logs*. The container in which you deployed the management console will produce its own log files that provide information such as the deployment success of the MMC WAR file. For information on these logs, see your container's documentation. For information on logging in Tomcat, see the http://wiki.apache.org/tomcat/FAQ/Logging#Q1[Apache Logging FAQs].

== Shell Script Log

The shell script log (`mmc-shell-scripts.log`) provides information on any link:/mule-management-console/v/3.7/automating-tasks-using-scripts[scripts you've created] in the management console. The default logging level for the shell script log is INFO, which you can modify in the `log4j2.properties` file (such as `webapps/console/WEB-INF/classes/log4j2.properties` in Tomcat). You can modify the `admin.shell.script` category to change the logging output for all console shell scripts, or to modify the output for a single script, modify the `admin.shell.script.[<scriptName>]` category, where `[<scriptName>]` is the name of the script surrounded by square brackets with any spaces escaped by a backslash, such as `admin.shell.script.[My\ Script]`.

*Note:* If you enter a script in the admin shell and click *Evaluate* before saving the script, the logging category for that script is `admin.shell.script.[$shell]`.
