= Setting Your API URL

On the API Version Details page, you can configure the inbound endpoint of your API so that the Anypoint Platform can manage it, either directly or via a proxy.

== Assumptions

This page assumes that you are an API Version Owner for the API version that you are trying to manage or that you are an Organization Administrator. This page also assumes your API is deployed and live.

== Setting the URL

On your API Version Details page, click Configure Endpoint to set the API type and an optional inbound endpoint for your deployed API. The endpoint that you provide here should be the actual inbound URL of your API. Do not use a placeholder URL.

[NOTE]
If your API is deployed on-premises and you are using a load balancer, include your load balancer endpoint here. See the link:/docs/display/current/Configuring+an+API+Gateway#ConfiguringanAPIGateway-ConfiguringaLoadBalancer[load balancer configuration instructions] for more information.

The platform asks you to identify your API Type as either HTTP, WSDL, or RAML Spec.

[width="100%",cols="50%,50%",options="header",]
|===
|API Type |Description
|*HTTP URL* |Select this option for non-RAML REST APIs. Provide the full URL of the inbound HTTP or HTTPS endpoint.
|*WSDL* |Select this option for SOAP APIs. Provide the the source where the Anypoint Platform can extract the URL. For example, you can set `http://myapiendpoint.com` if your WSDL is available at `http://myapiendpoint.com?wsdl`.
|*RAML Spec* |Select this option if you designed your API using RAML and your API is implemented using APIkit. Provide the baseUri from your RAML definition. If you wish, you can replace the version with a \{version} placeholder. For example, http://myapi.com/\{version}/myresource/\{version}
|===

Click *Configure*.

Note that the gray *Endpoint unregistered* indicator remains unchanged, unless you have declared an endpoint for an API that is running on an API Gateway configured with your organization credentials. If your API is running anywhere other than a configured API Gateway, you need to first proxy the endpoint, then deploy that proxy to your API Gateway. When you deploy the proxy application to the gateway, the Anypoint Platform recognizes which API is being proxied and automatically replaces the original endpoint that you declared on your API Version Details page with the proxy endpoint. For more information, see link:/docs/display/current/Proxying+Your+API[Proxying Your API] and link:/docs/display/current/Deploying+Your+API+or+Proxy[Deploying Your API or Proxy].

If necessary, you can click *Configure Endpoint* at any time to make an adjustment. If you move your API so that it has a new inbound endpoint, repeat the previous steps and re-proxy your API based on its new URL.

== Endpoint Status

After you declare your endpoint, the Anypoint Platform displays the state of that endpoint using a gray, green, or yellow status indicator.

[cols=",,",options="header",]
|===
|Endpoint Status |Color |Description
|*Endpoint unregistered* |Gray |The Anypoint Platform has never tracked the endpoint for this API version. Either you have entered a URL for an API or proxy that is not yet deployed to the gateway, or you have declared an endpoint that is hosted somewhere other than an API Gateway and need to proxy that endpoint to the gateway so that the platform can track it.
|*Endpoint active* |Green |The Anypoint Platform is actively tracking the endpoint. Note that the endpoint must be actively tracked by the Anypoint Platform in order for governance policies and SLA tiers to function.
|*Endpoint inactive* |Yellow |The Anypoint Platform previously was tracking this endpoint, but the API or proxy application is currently offline. Hover over the status indicator to view a tooltip that indicates the approximate time the endpoint was last tracked.
|===

== Troubleshooting Endpoint Tracking

If you deploy your API or proxy to an API Gateway and believe it should be tracked, check that all the following are true:

* Your endpoint is configured to adjust for the link:/docs/display/current/Localhost+Behavior+on+the+API+Gateway[localhost behavior limitations] on the API Gateway.
* Your endpoint, configured in your API or proxy, must not have any trailing slashes
* If you deploy your API or proxy to an on-premises API Gateway, check to ensure that you have correctly link:/docs/display/current/Configuring+an+API+Gateway[configured your API Gateway] for connection to your Anypoint Platform organization.
* If you deploy your API or proxy to a cloud API Gateway, ensure that you correctly entered the client ID and client secret of your Anypoint Platform organization as environment variables.

== See Also

* Learn more about link:/docs/display/current/Proxying+Your+API[proxying an existing API endpoint].
* link:/docs/display/current/Applying+Runtime+Policies[Apply runtime policies] to your endpoint.
* link:/docs/display/current/Defining+SLA+Tiers[Define SLA tiers] to manage access.
