= DataWeave

[WARNING]
====
DataWeave is a new feature of 3.7 runtime that replaces the link:/docs/display/33X/DataMapper+Transformer+Reference[DataMapper], which is a major component in previous versions. It's recommended than when possible you use DataWeave to avoid future obsolescence.
====

The http://mulesoft.github.io/weave/[DataWeave language] is a simple, powerful way to query and transform data inside of Mule. It provides JSON-like language that's purposefully built to make writing transformations as fast as possible and highly maintainable over the long term. It supports a variety of transformations, from simple 1 to 1 mappings, to more elaborate mappings including normalization, grouping, joins, partitioning, pivoting and filtering.

The language is tightly integrated with Mule ESB and Anypoint Studio. Use the *Transform Message* component, that allows you to use the language to query and transform data through DataWeave. It fully supports DataSense, allowing you to leverage metadata from connectors, schemas and sample documents to more easily design your transformations. DataSense provides content assist while you are coding and scaffolds your mappings to help make writing transformations fast and easy.

* link:/docs/display/current/Using+DataWeave+in+Studio[Using DataWeave in Studio]
* link:/docs/display/current/DataWeave+Reference+Documentation[DataWeave Reference Documentation]
* link:/docs/display/current/DataWeave+Tutorial[DataWeave Tutorial]
* link:/docs/display/current/DataWeave+Examples[DataWeave Examples]
