= MUnit Migration Guide
:version-info: 3.7.0 and later
:keywords: munit, testing, unit testing, migration

To upgrade to MUnit 1.2.0, you mostly need to modify the `pom.xml` file.

== New Maven groupId for MUnit Artifacts

The groupId `org.mule.munit` has changed to `com.mulesoft.munit`, so you must replace all occurrences of the groupId with the new name.

== MUnit Maven Plugin

Change the groupId for the MUnit Maven Plugin as shown below.

Original:
[source,xml,linenums]
----
<plugin>
  <groupId>org.mule.munit.tools</groupId>
  <artifactId>munit-maven-plugin</artifactId>
  <version>${munit.version}</version>
  ...
</plugin>
----

New value:
[source,xml,linenums]
----
<plugin>
  <groupId>com.mulesoft.munit.tools</groupId>
  <artifactId>munit-maven-plugin</artifactId>
  <version>${munit.version}</version>
  ...
</plugin>
----

== MUnit Dependencies

Past releases of MUnit required several artifacts in the `pom.xml` file. For the new version, the number of these artifacts is considerably less.

Artifacts in old MUnit versions:
[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.munit</groupId>
    <artifactId>munit-assert</artifactId>
    <version>${munit.version}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.mule.munit</groupId>
    <artifactId>munit-mock</artifactId>
    <version>${munit.version}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.mule.munit</groupId>
    <artifactId>munit-common</artifactId>
    <version>${munit.version}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.mule.munit</groupId>
    <artifactId>munit-runner</artifactId>
    <version>${munit.version}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-interceptor-module</artifactId>
    <version>${munit.version}</version>
    <scope>test</scope>
</dependency>
----

MUnit 1.2.0 requires only the following artifacts:

[source,xml,linenums]
----
<dependency>
   <groupId>com.mulesoft.munit</groupId>
    <artifactId>mule-munit-support</artifactId>
    <version>${mule.munit.support.version}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>com.mulesoft.munit</groupId>
    <artifactId>munit-runner</artifactId>
    <version>${munit.version}</version>
    <scope>test</scope>
</dependency>
----

Note that the groupIds have changed from `org.mule.munit` to `com.mulesoft.munit`, and that the `mule-munit-support` version artifact is new.

== Properties

MUnit 1.2.0 requires the following properties in the `pom.xml` file:

[source,xml,linenums]
----
<munit.version>1.2.0</munit.version>
<mule.munit.support.version>3.7.0</mule.munit.support.version>
----

Note that `${mule.munit.support.version}` should match the Mule ESB version:

* 3.6.0 for Mule 3.6.x
* 3.7.0 for Mule 3.7.x


== Mule ESB 3.7.x

For Mule ESB 3.7.x, add the following two Maven artifacts to the `pom.xml` file:

[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-module-extensions-support</artifactId>
    <version>${mule.version}</version>
</dependency>
<dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-module-extensions-spring-support</artifactId>
    <version>${mule.version}</version>
</dependency>
----
