= Introduction to Anypoint Partner Manager
:keywords: b2b, introduction, portal, partner, manager

[NOTE]
Anypoint Partner Manager is currently in beta. For access or more information, talk to your account executive.

== Anypoint Partner Manager

Anypoint Partner Manager (APM) provides a single user interface for viewing and configuring <<Trading Partner Management>> settings and B2B <<Message Tracking>> data.

=== Trading Partner Management

The Trading Partner Management (TPM) service provides the ability to edit, store and retrieve configuration settings for the transport and format of B2B messages. For example, EDI messages are often sent over the AS2 protocol in order to ensure security and integrity of the transmissions. Each trading partner may have AS2 different settings. In addition, different partners may use different format protocols such as EDI X12, EDIFACT, or XML; they may also use different options within those protocols. The TPM service allows this configuration data to be managed outside of your Mule applications, so that they can be reviewed without looking at the code and updated without re-deploying your Mule flows.

To use APM to configure settings for a B2B flow, complete the steps that follow.

==== In Anypoint Partner Manager

* Set up the home organization
* Set up an external trading partner

==== In AnyPoint Studio

* Build your flow
* Configure the B2B Connector
* Configure B2B-enabled Connectors to use the B2B Connector
* Complete the flow
* Use standard MuleSoft connectors and processors to complete the processing and integration of the message into downstream systems as required.

=== Message Tracking

Because B2B messages often communicate contractual obligations between companies, it is desirable (and sometimes necessary) to track all messages sent or received, storing the actual message content as well as metadata (such as data and time the message was sent or received, the identity of the partner, and success or failure of processing). The Anypoint B2B Message Tracking service provides a simple, secure, and integrated mechanism for message tracking within Mulesoft flows. This data can be used for non-repudiation, error correction, and auditing.

Currently the tracking metadata is stored in a database in CloudHub and the actual message content is saved to an S3 bucket provided by the customer.

== More information

link:/anypoint-b2b/anypoint-partner-manager-users-guide[Anypoint Manager User's Guide]
