= Anypoint B2B
:keywords: b2b, as2, edi, x12, edifact, portal, ftp

Anypoint B2B lets you connect to trading partners using EDI over AS/2, FTP, and other protocols using Mule. It integrates seamlessly into the Mule runtime.

Anypoint B2B includes the following:

* EDI Module:
** EDI message reading, validation and writing
** Integration with DataSense and DataMapper
** X12 message packs for 4010 and 5010
** EDIFACT message packs for D.93A, D.96A, D.98B, D.00A, D.01B, and D.02A versions
** The ability to define your own schemas or customize the base X12/EDIFACT schemas
* AS/2 Connector
* FTPS Connector
* B2B Portal:
** Trading Partner Management
** Message Tracking
* B2B Connector: Controls connectivity between B2B portal and the other connectors in the Mule runtime

Anypoint B2B requires Mule 3.6.0 and the March 2015 (5.0) release of Anypoint Studio (and newer versions of each).

== Prerequisites

This document assumes that you are familiar with Mule, link:/mule-user-guide/v/3.7/anypoint-connectors[Anypoint Connectors], and the link:/mule-fundamentals/v/3.7/anypoint-studio-essentials[Anypoint Studio Essentials]. To increase your familiarity with Studio, consider completing the link:b/mule-fundamentals/v/3.7/basic-studio-tutorial[Basic Studio Tutorial]. Further, this page assumes that you have a basic understanding of link:/mule-fundamentals/v/3.7/mule-concepts[Mule Flows] and link:/mule-fundamentals/v/3.7/global-elements[Global Elements]. 

This document describes implementation examples within the context of Anypoint Studio, Mule ESB’s graphical user interface, and, also includes configuration details for doing the same in the XML Editor.

== Getting Started

* link:/anypoint-b2b/x12-module[X12 Module] (http://mulesoft.github.io/edi-module/x12/[Reference])
* link:/anypoint-b2b/edifact-module[EDIFACT Module] (http://mulesoft.github.io/edi-module/edifact/[Reference])
* link:/anypoint-b2b/ftps-connector[FTPS Connector] (http://modusintegration.github.io/mule-connector-ftps/[Reference])
* link:/release-notes/anypoint-b2b-release-notes[123699530[AS/2 Connector 1.0.0 Release Notes]] (http://modusintegration.github.io/mule-connector-as2/[Reference])
* link:/anypoint-b2b/as2-connector-2.0.0-rc[AS2 Connector] (http://modusintegration.github.io/mule-connector-as2/[Reference])
* link:/anypoint-b2b/edi-x12-order-processing-example[EDI X12 Order Processing Example]
* link:/anypoint-b2b/supported-edi-document-types[Supported EDI Document Types]
* link:/anypoint-b2b/introduction-to-anypoint-b2b-portal[Introduction to Anypoint B2B Portal] (Trading Partner Management and Message Tracking)
** link:/docs/pages/viewpage.action?pageId=133267996[AS2 and EDI X12 Purchase Order Walkthrough]
** link:/docs/pages/viewpage.action?pageId=133267998[FTPS and EDI X12 Purchase Order Walkthrough]

== Release Notes

* link:/docs/pages/viewpage.action?pageId=132810265[X12/EDIFACT EDI Modules 1.0.0 RC2]
* link:/docs/pages/viewpage.action?pageId=123699530[AS/2 Connector 1.0.0]
* link:/release-notes/as2-connector-2.0.0-rc2-release-notes[AS2 Connector 2.0.0-RC2 Release Notes]
* link:/release-notes/ftps-connector-1.0.0-rc2-release-notes[FTPS Connector 1.0.0-RC2 Release Notes]
