= Introduction to Anypoint Partner Manager
:keywords: b2b, introduction, portal, partner, manager

////
[NOTE]
Anypoint Partner Manager is currently in beta. For access or more information, talk to your account executive.
////

== Anypoint Partner Manager

Anypoint Partner Manager (APM) provides a single web-based user interface for managing <<Partner Settings>> and viewing B2B <<Message Tracking>> data for all B2B transactions between you and your trading partners.

=== Partner Settings

APM provides the ability to edit, store and retrieve configuration settings for the transport and format of B2B messages. For example, EDI messages are often sent over the AS2 protocol in order to ensure security and integrity of the transmissions. Each trading partner may have AS2 different settings; for example, each partner will have their own certificate. In addition, different partners may use different format protocols such as EDI X12, EDIFACT, or XML, and they may use different options within those protocols. APM allows this configuration data to be managed outside of your Mule applications, so that they can be reviewed without looking at the code and updated without re-deploying your Mule flows.

=== Message Tracking

Because B2B messages often communicate contractual obligations between companies, it is desirable (and sometimes necessary) to track all messages sent or received, storing the actual message content as well as metadata (such as data and time the message was sent or received, the identity of the partner, and success or failure of processing). APM provides a simple, secure, and integrated mechanism for message tracking within MuleSoft flows. This data can be used for non-repudiation, correlation of acknowledgments, error correction, and auditing.

Currently the tracking metadata is stored in a database in CloudHub and the actual message content is saved to an S3 bucket or customer message persistence option provided by the customer.

=== Typical Use Case

To use APM to configure settings and track messages for a B2B flow, you will typically complete the steps that follow.

==== In APM

* Enter home organization settings
* Enter external trading partner settings

==== In AnyPoint Studio

* Create your flow
* Configure the Partner Manager Connector
* Configure Partner Manager-enabled Connectors to use the Partner Manager Connector
* Use standard MuleSoft connectors and processors to complete the processing and integration of the message into downstream systems as required.

==== Back in APM
Go to the B2B Transmissions area of APM to view tracked events and messages


== More information

* link:/anypoint-b2b/anypoint-partner-manager-users-guide[Anypoint Manager User's Guide]

* link:/anypoint-b2b/as2-and-edi-x12-purchase-order-walkthrough[AS2 and EDI X12 Purchase Order WalkThrough]
* link:/anypoint-b2b/ftps-and-edi-x12-purchase-order-walkthrough[FTPS and EDI X12 Purchase Order Walkthrough]
