= Anypoint B2B
:keyworkds: b2b, edi, portal

Anypoint B2B enables customers to connect to trading partners using EDI over AS/2, FTP and other protocols using Mule. It integrates seamlessly into the Mule runtime

Anypoint B2B includes the following:

* EDI Module:
** EDI message reading, validation and writing
** Integration with DataSense and DataMapper
** X12 message packs for 4010 and 5010
** EDIFACT message packs for D.93A, D.95B, D.96A, D.98B, D99A, D.99B, D.00A, D.01B, D.02A, and D03a versions
** The ability to define your own schemas or customize the base X12/EDIFACT schemas
* AS/2 Connector
* FTPS Connector
* B2B Portal:
** Trading Partner Management
** Message Tracking
* B2B Connector: Controls connectivity between B2B portal and enables message tracking for non-EDI message types

Anypoint B2B requires Mule 3.6.0 and the March 2015 (5.0) release of Anypoint Studio.

== Assumptions

This document assumes that you are familiar with Mule, link:/mule-user-guide/v/3.7/Anypoint-Connectors[Anypoint Connectors], and the link:mule-fundamentals/v/3.7/Anypoint-Studio-Essentials[Anypoint Studio interface]. To increase your familiarity with Studio, consider completing one or more link:/mule-fundamentals/v/3.7/Basic-Studio-Tutorial[Anypoint Studio Tutorials]. Further, this page assumes that you have a basic understanding of link:/mule-fundamentals/v/3.7/Mule-Concepts[Mule flows] and link:/mule-user-guide/v/3.7/Global-Elements[Mule Global Elements]. 

This document describes implementation examples within the context of Anypoint Studio, Mule ESB’s graphical user interface, and, also includes configuration details for doing the same in the XML Editor. 

== Getting Started

* link:/anypoint-b2b/x12-module[X12 Module] (http://mulesoft.github.io/edi-module/x12/[Reference])
* link:/anypoint-b2b/edifact-module[EDIFACT Module] (http://mulesoft.github.io/edi-module/edifact/[Reference])
* link:/anypoint-b2b/ftps-connector[FTPS Connector] (http://modusintegration.github.io/mule-connector-ftps/[Reference])
* link:/anypoint-b2b/as2-connector[AS/2 Connector - 1.0.0 GA] (http://modusintegration.github.io/mule-connector-as2/[Reference])
* link:/anypoint-b2b/as2-connector-2.0.0-rc[AS/2 Connector - 2.0.0-RC3] (http://modusintegration.github.io/mule-connector-as2/[Reference])
* link:/anypoint-b2b/edi-x12-order-processing-example[X12 Order Processing Example]
* link:/anypoint-b2b/supported-edi-document-types[Supported EDI Document Types]
* link:/anypoint-b2b/Introduction-to-Anypoint-B2B-Portal[B2B Portal 1.0.0 Beta (Trading Partner Management and Message Tracking)]
** link:/anypoint-b2b/as2-and-edi-x12-purchase-order-walkthrough[AS2 and EDI X12 Purchase Order Walkthrough]
** link:/anypoint-b2b/ftps-and-edi-x12-purchase-order-walkthrough[FTPS and EDI X12 Purchase Order Walkthrough]

== Release Notes

* link:/release-notes/x12-edifact-modules-1.0.0-release-notes[X12/EDIFACT EDI Modules 1.0.0]
* link:/release-notes/x12-edifact-modules-1.0.0-release-notes[AS/2 Connector 1.0.0]
* link:/release-notes/as2-connector-2.0.0-rc3-release-notes[AS2 Connector 2.0.0-RC3]
* link:/release-notes/ftps-connector-1.0.0-rc3-release-notes[FTPS Connector 1.0.0-RC3]
