= Configuring Cluster Nodes

*_Enterprise Edition_*

You can configure cluster node properties using the node's `mule-cluster.properties` file. Configuration items include use of multicast or unicast for node discovery, manual specification of cluster node IP addresses, and other properties.

== File: <MULE_HOME>/.mule/mule-cluster.properties

=== Syntax

Parameter=value pairs, separated by an equal sign, one per line.

[source, xml, linenums]
----
<parameter>=<value>
----

=== Example

[source, code, linenums]
----
...
mule.cluster.nodes=192.168.10.21,192.168.10.22,192.168.10.23
mule.cluster.multicastenabled=false
...
----

=== Parameters Table

[width="100%",cols=",",options="header"]
|===
|Property Name |Description
|`mule.cluster.networkinterfaces` a|Comma-seperated list of interfaces to use by Hazelcast. Wildcards are supported, as shown below:

[source, code, linenums]
----
192.168.1.*,192.168.100.25
----
|`mule.cluster.nodes` |Comma-seperated list of IP addresses of the nodes that belong to the cluster. Specifying just one IP address enables the server to join the cluster.
|`mule.cluster.multicastenabled` |*(Boolean)* Enable/disable multicast. Disable if `mule.cluster.nodes` is set.
|`mule.cluster.multicastgroup` |Multicast group IP address to use.
|`mule.cluster.multicastport` |Multicast port number to use.
|===

[TIP]
For more information about the `mule-cluster.properties` configuration file, see the instructions for link:/mule-management-console/v/3.4/creating-or-disbanding-a-cluster[creating a cluster manually]
