= Architecture of the Management Console

As an IT organization deploys Mule ESB into production, it becomes critical for the operations staff to be able to manage and monitor the ESB infrastructure and related services. With each additional system, application, or service introduced into the infrastructure, the level of complexity increases, along with the need to have visibility and control over system performance and up-time.

Using the management console for Mule ESB, administrators can manage all Mule ESB instances as well as deployed application bundles. The management console provides a convenient and intuitive web-based interface to centrally monitor, manage, and administer the runtime aspects of your enterprise service bus. With this high-performance and secure tool, administrators can save time and reduce errors by quickly identifying, diagnosing, and mediating problems from a central location.

== Architecture

There are several components required to use the management console:

* The correct version of Mule ESB
* The management console server
* The management console agent

The management console is available only with the enterprise edition of Mule ESB. For the 3.1.1 release, the management console works in conjunction with Mule ESB Enterprise 3.1.1. In addition, the management console is backward compatible with the previous version of Mule ESB.

The management console communicates with Mule ESB via the Management Console Agent. This agent is a Mule application; it is automatically installed in Mule ESB 3.1.

*[mmc:Mule 3.2]* For the 3.2.0 release, the management console works in conjunction with Mule ESB Enterprise 3.2.0. The Management Console Agent is automatically installed in Mule ESB 3.2.

At installation the agent bundle is placed in the Mule ESB \apps directory and is then automatically unzipped and deployed by the ESB instance at startup.

The management console can be deployed directly to Mule ESB, as done in the evaluation distribution; however, this is not recommended for deployments where you are monitoring multiple Mule ESB instances.

Once the Mule instance is authenticated and registered with the management console server, communication is secured through the use of certificates and HTTPS. Each Mule instance can be registered with a single management console server.

The management console server is a web application packaged as a WAR file that executes from within your web container. As such, it must be correctly deployed on the container, such as by placing the WAR file in the proper location within your web container installation. For example, for an Apache Tomcat installation, you deploy the mule management console WAR (`mmc.war`) file using link:https://www.mulesoft.com/tcat/download[MuleSoft Tcat Server], or by copying it to the Tomcat `/webapps` directory.

== Key Features

Following are key features of the management console:

*Centralized management and monitoring*

* Check the health of ESB resources from an easy-to-navigate view
* View at a glance how your system is performing and consuming resources via intuitive charts
* Manage multiple runtime environments, grouped by location, business function, or other criteria
* Define and subscribe to alerts for your Mule installation

*Fine-grained ESB control*

* Start, stop, and restart ESB resources
* Remotely access, update, or replace any file or configuration on a Mule ESB server
* View consumption of resources and dynamically tune services in real time
* Dynamic configuration of thread pools

*Enterprise-Level Security*

* Enterprise authentication (LDAP)
* Fine-grained role based access control
* Secure runtime communication using certificates and HTTPS

*Deep diagnostics and auditing*

* View detailed information on memory utilization, threads, system resources, and server configuration
* Audit message traffic and associated properties on both the inbound and outbound sides of services
* Turn service level auditing on and off to capture just enough data to diagnose an issue without impacting performance

*Intelligent alerting*

* Receive notifications when critical metrics cross thresholds
* Monitor events at the individual server or system level
* Escalate alerts to administrators or an external monitoring system
* Customize alerts using alert scripts

*[mmc:Mule 3.2]*
*Flexible cluster management*

* Create, disband, or add nodes to clusters as conditions dictate
* Monitor cluster status – get detailed information about cluster-based flows, services, and memory usage
* Deploy apps to a cluster for enhanced availability, scalability, and performance.

*[mmc:Mule 3.2]*
*In-Depth Event visualization*

* Track key events in the flow of business transactions
* Analyze the flow and disposition of particular messages within a business transaction
* Drill down into event data to identify failure points or bottlenecks
* Test flows for compliance to business procedures and standards

== Benefits

Benefits of the management console include:

* Lower management cost with groups-based management and control
* Simplify troubleshooting through quick access to the most relevant information
* *[mmc:Mule 3.2]* Enhance availability, scalability, and performance through clustering
* Improve visibility and understanding by analyzing real-time metrics views that highlight significant changes
* Increase service up-time and performance through intelligent, proactive alerting and remediation tools
* Reduce downtime and time-to-resolution with deep diagnostics and auditing capabilities
* Minimal impact on the runtime performance of your ESB infrastructure
* Improve collaboration between operations and development through controlled access to runtime diagnostic information
* *[mmc:Mule 3.2]* Gain visibility and understanding of key business-related events

link:/mule-fundamentals/v/3.2/mule-management-console-3.2.x[<< Previous: *Home*]

link:/mule-management-console/v/3.2/installing-the-management-console[Next: *Installing the Management Console* >>]

== See Also

* link:https://www.mulesoft.com/dl/mmc[MMC Download]
* link:https://www.mulesoft.com/tcat/download[Tcat Download]
* link:http://forums.mulesoft.com[MuleSoft's Forums]
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]
* mailto:support@mulesoft.com[Contact MuleSoft]
