= Common Tasks

The common tasks with Mule ESB and the Management Console are listed below. Each section describes how to accomplish a specific task, and, if needed, provides links to more information.

== Start the Mule ESB Server

Run the `mule` file located in the `\bin` directory beneath where you unzipped the Mule ESB EE software package. For example, on a Windows platform, open a command window, navigate to the Mule installation `\bin` directory. From the command line type in `mule` from within this `\bin` directory. (You can also type in `mule.bat` to start the server.)

The command window displays a series of start-up messages. When complete, you can login to the console.

== Open the Management Console and Login

Point your browser to the URL `http://localhost:8585/mmc` (if you are using the evaluation version of the software) to display the login screen. Otherwise, for a production version, point your browser to the URL `http://localhost:8080/mmc`. Login with the user name `admin` and the password `admin`. For more information, see link:/mule-management-console/v/3.2/how-to-run-the-management-console[How to Run the Management Console].

== Register a Server

For the evaluation version, the server is automatically registered with the console.

The simplest way to register a server, if you need to, is with the console's auto-discovery feature: the console automatically senses that a Mule server is running and makes it easy to register any "discovered" servers. Click the Servers tab, then click the Unregistered node in the left navigation pane. The window lists all servers that have come online and are not yet registered. Select the server to register, then click the Register button. You do not have to specify the URL for the server since the auto-discovery feature does this. (For more information, see link:/mule-management-console/v/3.2/working-with-mule-server-instances[Server Auto-Discovery for New Servers].)

To manually register a server, click the Servers tab, then the New Server button. In the dialog that opens, enter a name for the server and the URL address for the server. (See link:/mule-management-console/v/3.2/working-with-mule-server-instances[Registering a Server].)

== Find the Example Applications

[WARNING]
====
The sample applications are preloaded in the server repository in Mule 3.1.2 if you downloaded Mule and the management console as a bundle.

*[Mule 3.2]* The sample applications are also preloaded in the server repository in Mule 3.2 if you downloaded Mule and the management console as a bundle.
====

There are a set of example applications included with the Mule server package, located beneath the Mule installation folder in the `\examples` folder. When you open the `\examples)) folder you should see a set of folders, such as {{\hello`, `\loanbroker-simple`, `\stockquote`, and so forth.

Each folder in `\examples` contains all the files needed for that particular example application, plus a README.txt file with specific instructions for that example. The simplest example application is the `hello` application. If you are just getting started, you may want to try things out using this `hello` application. (See link:/mule-management-console/v/3.2/quick-start-guide-to-mule-esb-server-and-the-management-console[Find the Sample Applications].)

== Deploy an Application

To run an application, you must first deploy it to a registered server. You can deploy a sample application, such as the hello application, by clicking the console's Applications tab, then, in the All Deployments window, clicking New to create a new deployment.

If the application has not already been added to the server repository, click the Upload New Application button to upload the application to the server repository and deploy it. Note that you upload the archive, or zip, files for the sample applications. These archive files contain all the necessary files to deploy and run the sample applications.

For complete instructions, see link:/mule-management-console/v/3.2/deploying-applications[Deploying Applications].

== Run the Deployed Application

Once an application is deployed to the Mule server, you can run it from any browser window. You should refer to the README.txt files in each sample application folder for specific instructions for running that application.

For example, to run the hello sample application, open a new browser window or tab, and enter the URL `http://localhost:8888/?name=Simon`. (Feel free to use a name other than "Simon".)

The browser runs the deployed hello example application, which simply takes the name parameter and inserts it within a simple text line. The browser displays output from the application, such as: Hello Simon, how are you?

== Audit the Running Application

After running the application, use the Flows and Flow Analyzer tabs in the console to analyze the application's processing. Flows represent the sum of all the services and processing going on within an application, including routers, transformers, and filters. You can see high-level and detailed information about an application's flows and services, plus stop and start flows.

See link:/mule-management-console/v/3.2/working-with-flows[Working with Flows] for more information.

== Analyze the Application Message Flows

Click the Flow Analyzer tab to open the Flow Analyzer screen, which enables you to see details about message flows. For a given application, you can see the flow of messages and the message payloads, including before and after payloads at different points along a message's processing route.

The section link:/mule-management-console/v/3.2/quick-start-guide-to-mule-esb-server-and-the-management-console[Analyze the Flow of Messages on the Application] in the Quick Start guide illustrates how to use this console feature. See link:/mule-management-console/v/3.2/analyzing-flow-processing-and-payloads[Analyzing Flow Processing and Payloads] for complete details.

== Managing SLAs and Alerts

Alerts enable you to check for potential problems on your servers or to monitor situations that might later lead to server problems. You define conditions (referred to as SLAs) through the Alerts pane. These conditions may later trigger the console to display alert messages that warn or advise you about problem situations.

For a quick overview on working with alerts, see link:/mule-management-console/v/3.2/quick-start-guide-to-mule-esb-server-and-the-management-console[Adding and Managing Alerts and SLAs]. See link:/mule-management-console/v/3.2/working-with-alerts[Working With Alerts] for complete information on setting up and viewing alerts.

== Set Up Users

When you first set up the server and console, you log in with the user name `admin`. The `admin` user is provided by default with the package. You most likely will want to add additional users, especially if you are using Mule ESB in a production environment.

Use the Administration tab in the console to manage users and roles. You define users and assign these users to roles, which are referred to as groups. You can also create groups and give them permissions to perform certain tasks.

For complete information on setting up and managing users, see link:/mule-management-console/v/3.2/managing-users-and-roles[Managing Users and Roles].

== See Also

* link:https://www.mulesoft.com/dl/mmc[MMC Download]
* link:https://www.mulesoft.com/tcat/download[Tcat Download]
* link:http://forums.mulesoft.com[MuleSoft's Forums]
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]
* mailto:support@mulesoft.com[Contact MuleSoft]
