= Managing Mule High Availability HA Clusters

The management console gives you the ability to manage server clusters. A cluster is a group of linked servers that work closely together. Once servers are added to a cluster, they function in many ways as if they were a single server.

[NOTE]
For an overview of clusters, including benefits and best practices, see link:/documentation-3.2/display/32X/Mule+High+Availability+%28HA%29+Clusters[Mule High Availability (HA) Clusters].

You can perform the following cluster-related tasks with the console:

* link:/documentation-3.2/display/32X/Creating+or+Disbanding+a+Cluster[Create a cluster]
* link:/documentation-3.2/display/32X/Deploying%2C+Redeploying%2C+or+Undeploying+an+Application+To+or+From+a+Cluster[Deploy, redeploy, or undeploy an application to or from a cluster]
* link:/documentation-3.2/display/32X/Monitoring+a+Cluster[Monitor a cluster, including determine its status]
* link:/documentation-3.2/display/32X/Creating+or+Disbanding+a+Cluster["Disband" or delete a cluster]

You can also create and manage a cluster programmatically using REST APIs. See link:/documentation-3.2/display/32X/Managing+Clusters+Using+REST+APIs[Managing Clusters Using REST APIs].

Because clusters represent linked servers, you use functions available through the Servers tab to create and manage clusters. You also use functions available via the Applications tab to deploy applications to a cluster, in much the same way that you deploy applications to individual servers.

link:/documentation-3.2/display/32X/Mule+High+Availability+%28HA%29+Clusters[<< Previous: *Mule High Availability (HA) Clusters*]

link:/documentation-3.2/display/32X/Creating+or+Disbanding+a+Cluster[Next: *Creating or Disbanding a Cluster* >>]
