= Running the WebApp Example with WebLogic

You can use the following steps to get the Mule ESB `webapp` example working with the management console and WebLogic. These steps take you through the installation process.

* Set JAVA_HOME environment variable to the location of your `jdk1.6.0_1` installation.
* Execute the following file: `./wls1032_linux32.bin`.
* Follow the installation instructions. (Note that if you do not answer the Registry questions, after three tries the installation continues.)
* Run the following command to generate a configuration/domain: `/home/opt/Oracle/Middleware/wlserver_10.3/common/bin/config.sh`. Be sure to correctly specify the path to this command file.
* Start WebLogic. Use the `startNodeManager.sh` file to start WebLogic. You can find this command file in the directory: `/home/opt/Oracle/Middleware/user_projects/domains/admin/bin/startWebLogic.sh`.
* Use the same user id and password combination specified when you ran the `config.sh` process to log into the WebLogic console: `http://172.16.10.197:7001/console`.

link:/documentation-3.2/display/32X/Overview+of+the+Management+Console[<< Previous: *Overview of the Management Console*]

link:/documentation-3.2/display/32X/Getting+Started+with+the+Management+Console[Next: *Getting Started with the Management Console* >>]
