= Running the WebApp Example with JBoss

You can use the following steps to get the Mule ESB `webapp` example working with the management console and JBoss. These steps take you through the process of adding a set of `.jar` files needed for the console to the existing `.war` file.

* Download the JBoss installation package file. This may be a `.zip` file or some other archive file.
* Extract the contents of the installation package file to an empty directory.
* Add the following `.jar` files to the `mule-example.war` file:
** groovy-all-1.6.7.jar
** jetty-6.1.26.jar
** jetty-util-6.1.26.jar
** mmc-agent-mule3-impl-3.1.0.jar
** mule-core-ee-3.1.0.jar
** mule-module-scripting-3.1.0.jar
** quartz-all-1.6.0-osgi.jar
** spring-webmvc-3.0.3-RELEASE.jar
* Copy the `mule-examples.war` file into the directory `../server/all/deploy`.
* Switch to the JBoss `../bin` directory and execute the following line: `./run.sh -c all -b 172.16.10.197`
* Once JBoss is up and running, log into the management console and register the management console agent that is running in JBoss.

link:/documentation-3.2/display/32X/Overview+of+the+Management+Console[<< Previous: *Overview of the Management Console*]

link:/documentation-3.2/display/32X/Getting+Started+with+the+Management+Console[Next: *Getting Started with the Management Console* >>]
