= Working with Logs

There are three types of logs you can view when working with the management console:

* *Mule ESB log*. To view the log file for a Mule ESB instance you're monitoring in the management console, click the Mule ESB name on the Servers tab, click the Files tab, and then click the `mule.log` file. This log file provides details about the startup of the Mule instance, any errors thrown, and so on.
* *Management console logs*. The management console itself generates some log files specific to the console's functionality. For example, the `mmc-shell-scripts.log` file provides information about any shell scripts that you run in the management console (see below). These log files are located in the application server's logs directory, such as `<TomcatHome>/logs` when you deploy the management console to Tomcat.
* *Container logs*. The container in which you deployed the management console will produce its own log files that provide information such as the deployment success of the MMC WAR file. For information on these logs, see your container's documentation. For information on logging in Tomcat, see the http://wiki.apache.org/tomcat/FAQ/Logging#Q1[Apache Logging FAQs].

== Shell Script Log

The shell script log (`mmc-shell-scripts.log`) provides information on any link:/mule-management-console/v/3.2/automating-tasks-using-scripts[scripts you've created] in the management console. The default logging level for the shell script log is INFO, which you can modify in the `log4j.properties` file (such as `webapps/console/WEB-INF/classes/log4j.properties` in Tomcat). You can modify the `admin.shell.script` category to change the logging output for all console shell scripts, or to modify the output for a single script, modify the `admin.shell.script.[mmc:<scriptName>]` category, where `[mmc:<scriptName>]` is the name of the script surrounded by square brackets with any spaces escaped by a backslash, such as `admin.shell.script.[mmc:My\ Script]`.

*NOTE*:
If you enter a script in the admin shell and click *Evaluate* before saving the script, the logging category for that script is `admin.shell.script.[mmc:$shell]`.

link:/mule-management-console/v/3.2/customizing-the-dashboard[<< Previous: *Customizing the Dashboard*]

link:/mule-management-console/v/3.2/automating-tasks-using-scripts[Next: *Automating Tasks Using Scripts* >>]
