= HL7 Mule Expression Language Support
:keywords: hl7, mel, mule expression language, hl7segment

[NOTE]
This feature is part of the link:/documentation/display/current/Mule+Healthcare+Toolkit[Mule Healthcare Toolkit], which also includes transformers and components for receiving, processing and sending HL7 messages. For details and a full list of available tools, consult the Toolkit's link:/documentation/display/current/Mule+Healthcare+Toolkit[documentation main page].

The Mule Healthcare toolkit includes two link:/documentation/display/current/Mule+Expression+Language+MEL[Mule Expression Language] (MEL) functions:

* `hl7segment()` allows access to a segment in an HL7 message
* `hl7()` allows access to values within a segment

The functions use the http://hl7api.sourceforge.net/[HAPI] (HL7 Application Programming Interface) http://hl7api.sourceforge.net/apidocs/ca/uhn/hl7v2/util/Terser.html[Terser] to provide access to HL7 fields. You can use MEL to access HL7 message contents in any message processor that supports MEL.

=== Examples

.Obtaining values
[width="100%",cols="40a,60a"]
|===
|[source]
----
hl7('/PID-5-1')
----
|Returns the value of the `PID-5-1` field of the current message
|[source]
----
hl7segment('AL1')
----
|Returns the value of the `Al1` segment of the current message
|===

.Modifying values
[width="100%",cols="50a,50a"]
|===
|[source]
----
hl7('/PID-5-1', 'Polly')
----
|Sets the value of the `PID-5-1` field of the current message to `Polly`
|[source]
----
hl7segment('AL1','AL1\|1\|\|^Penicillin\|\|Produces hives')
----
|Sets the value of the `AL1` segment of the current message
|===

=== Usage Examples

Use a link:/documentation/display/current/Variable+Transformer+Reference[Variable Transformer] to initialize the variable `HL7event` with the value of the `EVN` segment of the HL7 message:

[source,xml]
----
<set-variable variableName="HL7event" value="#[hl7segment('EVN')]"/>
----

Use a link:/documentation/display/current/Set+Payload+Transformer+Reference[Set Payload Transformer] to obtain a string composed of the fields `PID-5-1` and `PID-5-2`:

[source,xml]
----
<set-payload value="#[hl7('/PID-5-1') + ' ' + hl7('/PID-5-2')]"/>
----

Use an link:/documentation/display/current/Expression+Component+Reference[Expression Component] to set modify fields `PID-5-1` and `PID-5-2`:

[source,xml]
----
<expression-component>
        hl7('/PID-5-1', 'Polly');
        hl7('/PID-5-2', 'Hedra');
</expression-component>
----
