= No Authentication
:keywords: devkit, authentication

When a connector does not use authentiation, you can use `@Connector` with `@Configuration`.

`@Configuration` adds a set of `@Configurable` fields to your connector as a connector configuration.

== Prerequisites

This document assumes you are familiar with the link:/anypoint-connector-devkit/v/3.6/_fixed[Anypoint Connector DevKit] and you are ready to implement a configuration in your connector.

== @Configuration Annotation

To implement a `@Configuration` on your Connector, create a new class and annotate it with @Configuration.

The following table describes the parameters for the `@Configuration` annotation:

[width="100%",cols="25a,25a,25a,25a",options="header",]
|===
|Parameter |Description |Required? |Default Value
|*friendlyName* |Defines the name that is going to be displayed in the connector configuration pop up. |✓ | 
|*configElementName* |Defines the name for the configuration  that is going to be used in the mule app. |  |config
|===

== Example

Ensure these instance variables have public getters and setters (not shown).

[source,java, linenums]
----
@Connector(name = "connector")
public class MyConnector
{
   @ConnectionStrategy
   private ConnectorConfiguration strategy;

/**
 * Processors
 */
}

@Configuration(friendlyName="Foo Configuration")
public class ConnectorConfiguration
{
   @Configurable
   private String property;

   @Configurable
   private String anotherProperty;
}
----
