= Expression Component Reference

This component evaluates an link:/documentation/display/current/Mule+Expression+Language+MEL[expression]. It accepts either a user-defined expression or a reference to a file.

*Minimum requirement:* The expression or file to evaluate.

== Configuration

Unlike the link:/documentation/display/current/Expression+Transformer+Reference[Expression Transformer], the expression component does not replace the message payload with the results of expression evaluation. See the *Implementing Business Logic* subsection in link:/documentation/display/current/Mule+Expression+Language+MEL[Mule Expression Language MEL] for an example illustrating the use of an expression component.

* **Display name*:* Type a useful name for the transformer to display in your flow (optional)
* *Expression:* The expression to evaluate
* *File:* Absolute path of the file containing the expression to evaluate. Click the ellipsis (**...**) button next to the *File* field to select the file with a browser
