= Message Processors

After Mule receives a message from a Message Source, it uses one or more message processors to process the message through a flow. 

Message Processors can be categorized by function as follows:

* *Components* are flexible tools which perform business logic implemented in Java and other scripting languages. 
* *Filters* only allow certain messages to continue to be processed in a flow.
* *Routers* control message flow to route, resequence, or split and aggregate messages in a flow.
* *Scopes* wrap other messages processors so as to enable them to perform together as a group.
* *Transformers* convert message payload type and data format to facilitate communication between systems. 

Browse the sections below for further details.

* link:/documentation/display/current/Components[Components]
* link:/documentation/display/current/Filters[Filters]
* link:/documentation/display/current/Routers[Routers]
* link:/documentation/display/current/Scopes[Scopes]
* link:/documentation/display/current/Transformers[Transformers]
* link:/documentation/display/current/Business+Events[Business Events]
