= Generic Endpoint Reference

The Generic Endpoint allows for a wide array of configuration options by allowing the user to code the protocol into the address of the endpoint. 

Mule supports numerous protocols which can be configured as endpoints. Many, but not all, of the protocols included with Mule are already configured as endpoint-based connectors and are available as building blocks in the Connectors category of the palette. These include FTP, HTTP, and Ajax, for example. The Generic Endpoint can also be used to specify these or additional endpoints. This is done by entering the full address in *Address* field, including the protocol designation within the address (ftp://foo, vm://foo, https://foo, etc).

== Configuration Reference

====
xslt: Unexpected program error: java.lang.NullPointerException

xslt: Unexpected program error: java.lang.NullPointerException
====

== Global Configuration Reference

In XML only, you can also define a global generic endpoint and reference it from specific endpoints within your flows.

====
xslt: Unexpected program error: java.lang.NullPointerException
====
