= Message Processors

After Mule receives a message from a Message Source, it uses one or more message processors to process the message through a flow. 

Message Processors can be categorized by function as follows

* *Components* are flexible tools which perform business logic implemented in Java and other scripting languages. 
* *Filters* only allow certain messages to continue to be processed in a flow.
* *Routers* control message flow to route, resequence, or split and aggregate messages in a flow.
* *Scopes* wrap other messages processors so as to enable them to perform together as a group.
* *Transformers* convert message payload type and data format to facilitate communication between systems.  +

Browse the sections below for further details.

* link:/docs/display/34X/Components[Components]
* link:/docs/display/34X/Filters[Filters]
* link:/docs/display/34X/Routers[Routers]
* link:/docs/display/34X/Scopes[Scopes]
* link:/docs/display/34X/Transformers[Transformers]
* link:/docs/display/34X/Datamapper+User+Guide+and+Reference[Datamapper User Guide and Reference]
* link:/docs/display/34X/Business+Events[Business Events]
