= Configuring Maven to Work with Mule ESB
:keywords: anypoint, studio, esb, maven

When working with Maven and Mule ESB outside of Anypoint Studio, you need to configure your Maven installation to work successfully with Mule. This page covers how to maintain your POM file to add or adjust dependencies and point to the correct MuleSoft repositories, and how to modify your Maven `settings.xml` file to include credentials and profiles for the Enterprise repository.

Once you have modified your Maven installation, you can install Mule plugins and develop applications that reference the Mule open source or Enterprise repositories.

Developing in Maven is greatly simplified by the link:/mule-user-guide/v/3.6/maven-tools-for-mule-esb[Maven Tools for Mule ESB] plugin, which provides Maven archetypes for building Mule applications.

== Assumptions

This document assumes that you are working with Maven outside of Anypoint Studio, and thus will be using archetypes to build Mule applications. See link:/mule-user-guide/v/3.6/using-maven-with-mule[Using Maven with Mule] for an overview of using Maven to manage your Mule projects.

[NOTE]
====
Note that you generally do not need to modify your settings.xml file if you are link:/mule-user-guide/v/3.6/using-maven-with-mule[working with Maven through Studio], as Studio keeps track of the dependencies you'll need and attempts to manage them for you in the application's associated POM file. If dependency errors occur, you may need to manually adjust your POM file, and, in some cases, in your settings.xml. Refer to the Maven documentation for the http://maven.apache.org/pom.html[pom.xml] and http://maven.apache.org/settings.html[settings.xml] for specific instructions.
====

== Setup Overview

Before you can start using Maven to create new Mule projects from the command line using archetypes, you need to: 

. Ensure that Maven is installed in a directory that does not include spaces.

. Create or maintain your already-created `pom.xml` files for your applications to include references to the MuleSoft open-source repositories and any connectors, modules, or other extensions that you need to include in each application.

. _Enterprise users only:_ Modify the `settings.xml` file to point to the Enterprise Customer repository and provide your credentials.

== Checking Your Maven Installation

By default, your local Maven installation stores configuration files in the directory `$HOME/.m2` ( `~/.m2` on Unix and Mac; `C:\Documents and Settings\<user>\.m2` on Windows). Keep in mind that in Linux or Mac `.m2` is a hidden folder.

If you are building your project outside Studio, you need to manually add some required JARs which cannot be accessed publicly through Maven. In Mule Enterprise Edition, the command line tool `populate_m2_repo`, which is available in your `$MULE_HOME/bin` directory, can fetch all the associated files. Note: Avoid duplicating jars in your project which causes classloading errors.

. Navigate to `%MULE_HOME%\bin`  directory (Windows), `$MULE_HOME/bin`  folder (Linux/Unix).

. Execute one of the following commands:

* `./populate_m2_repo <my-test-m2-repository>` (Linux/Unix)

* `populate_m2_repo.cmd <my-test-m2-repository>` (Windows)

(Note that `my-m2-test-repository` must not already exist in the current directory.)

Note that you may encounter errors if your `MULE_HOME` is set to a path containing spaces. It is recommended that you select a `MULE_HOME` location that does not contain spaces.

== Configuring Your Maven Installation for Mule

=== Enabling MuleSoft Plugins

To enable MuleSoft plugins, you can modify either your project file (POM) or your `settings.xml` file. Edit the desired configuration file to include the following:

[source, xml, linenums]
----
<settings>
    <pluginGroups>
        <pluginGroup>org.mule.tools</pluginGroup>
    </pluginGroups>
    ...
</settings>
----

=== Referencing the Open Source MuleSoft Repositories

Edit your `settings.xml` or project file to include the following:

[source, xml, linenums]
----
<repositories>
...
    <repository>
        <id>mulesoft-releases</id>
        <name>MuleSoft Repository</name>
        <url>http://repository.mulesoft.org/releases/</url>
        <layout>default</layout>
    </repository>
    <repository>
        <id>mulesoft-snapshots</id>
        <name>MuleSoft Snapshot Repository</name>
        <url>http://repository.mulesoft.org/snapshots/</url>
        <layout>default</layout>
    </repository>
...
</repositories>
----

If the dependencies that you need are not already present, add them as shown.

[source, xml, linenums]
----
<dependencies>
...
    <dependency>
        <groupId>GROUP ID OF DEPENDENCY</groupId>
        <artifactId>ARTIFACT ID OF DEPENDENCY</artifactId>
        <version>VERSION OF DEPENDENCY</version>
    </dependency>
...
<dependencies>
----

For example, if you were adding the dependency for the Salesforce connector:

[source, xml, linenums]
----
<dependencies>
...
    <dependency>
        <groupId>org.mule.modules</groupId>
        <artifactId>mule-module-sfdc</artifactId>
        <version>LATEST</version>
    </dependency>
...
<dependencies>
----

Not sure what the dependency details are for a connector that you need? Refer to the connector-specific Maven instructions on the http://www.mulesoft.org/documentation/www.mulesoft.org/connectors[connectors site].

=== Referencing MuleSoft's Enterprise Repositories

*_Enterprise_*

This section assumes that you have acquired an http://www.mulesoft.com/mule-esb-support-esb-license-subscription[Enterprise License] and credentials for the link:https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/[MuleSoft Enterprise Maven customer repository], which allows you to access Mule Enterprise modules, connectors, and other components not included in the trial or community versions. If you are a MuleSoft customer and do not have access to the repository, contact mailto:support@mulesoft.com[MuleSoft Support].

To configure Maven to access the MuleSoft Customer Repository, you need to make additions to the `settings.xml` config file. Your `.m2` directory may already contain a configuration file called `settings.xml`. Note that this file is not mandatory; Maven uses default parameters if the file is not present. If you don't have a `settings.xml` file at all, create it inside the `~/.m2` folder. Read more about the `settings.xml` file in the http://maven.apache.org/settings.html[Maven documentation].

. Open the file <`USER_HOME>/.m2/settings.xml` for editing.

. Add the following to the `servers` section.
+
[source, xml, linenums]
----
<server>
 
    <id>MuleRepository</id>
    <username>YOUR_ID</username>
    <password>YOUR_PASSWORD</password>
 
</server>
----

. Add the following to the `profiles` section:
+
[source, xml, linenums]
----
<profile>
 
    <id>Mule</id>
    <activation>
        <activeByDefault>true</activeByDefault>
    </activation>
    <repositories>
        <repository>
            <id>MuleRepository</id>
            <name>MuleRepository</name>
            <url>https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
 
</profile>
----

== See Also

* Learn about link:/mule-user-guide/v/3.6/maven-tools-for-mule-esb[Maven tools for Mule ESB], a Mule plugin to develop Mule applications in Maven.

* Control instances of Mule ESB using the link:/mule-user-guide/v/3.6/mule-esb-plugin-for-maven[Mule ESB plugin for Maven].
