= Schema Documentation
:keywords: anypoint studio, esb, schema

Mule 3.0 was released with new Javadoc-style schema documentation, making it easier to familiarize yourself with all the elements and attributes permissible in xml configuration files.

If you are familiar with versions of Mule older than v 3.0, you may want to consult this list of link:/mule-user-guide/v/3.6/notes-on-mule-3.0-schema-changes[schema changes].

== JavaDoc-Style HTML Output

Framed HTML documentation provides most detailed and easy accessible information about all Mule schema components and interconnections between them.

* http://www.mulesoft.org/docs/site/current/schemadocs/[Mule 3.4.0 and later]
* http://www.mulesoft.org/docs/site/3.3.0/schemadocs/[Mule 3.3.x]
* http://www.mulesoft.org/docs/site/3.2.0/schemadocs[Mule 3.2.x]
* http://www.mulesoft.org/docs/site/3.1.0/schemadocs[Mule 3.1.x]
* http://www.mulesoft.org/docs/site/3.0.1/schemadocs[Mule 3.0.x]

== UML Diagrams

Diagrams of many of the logical structures you will use to write Mule configurations.

== Elements, Attributes, Annotations, and Substitutions

Navigate among exploded views of Mule schemas, viewing all objects - inherited or native - in a single location.
