= Manipulating Requests Using Scripting

So far we have seen how we can write Java code to interact with Mule. This example introduces using scripting in Mule. Scripting is a powerful way to manipulate requests and create custom logic. The benefit of scripting is that you can use different languages in Mule namely, http://groovy.codehaus.org[Groovy], Ruby (using http://jruby.org[JRuby]), Python (using http://jython.org[Jython]) and server-side http://www.mozilla.org/rhino[JavaScript]. This example uses Groovy to transform an incoming message.

== What You Will Learn

* Using the Script Transformer and configuring it from Mule Studio
* Embedding script code in your configuration file, removing the need to create an external code file

10 minutes

== Building It Now!

=== Prerequisites

Ideally, you should be working through these tutorials in sequence and have completed the [MULE3EXAMPLES:Invoking a Component Method] lesson.

== Running the Example

== What Just Happened?

* You created a scripting transformer configured to use Groovy as the language
* You embedded a script in your Mule configuration file to perform a transformation on the incoming request
* The resulting behaviour was the same as [MULE3EXAMPLES:Working with Transformers] except you didn't need to create a separate Java class to perform the transformation.

== References

== Next Steps

[cols=",,",]
|===
|http://www.mulesoft.org/display/32X/Invoking+Component+Methods[« Invoking Component Methods] |http://www.mulesoft.org/display/32X/HOme[Back to Index] |http://www.mulesoft.org/display/32X/Using+Outbound+Endpoints+to+Publish+Data[Using Outbound Endpoints to Publish Data »]
|===

'''''



