= Anypoint Service Registry 3.0.0 Release Notes
:keywords: release notes, service registry

July 23, 2013

MuleSoft is pleased to announce the latest release of link:/documentation/display/current/Anypoint+Service+Registry[Anypoint Service Registry], a multitenant service registry/repository and SOA governance tool. 

== Document Revision History

July 23, 2013, v.1.0 initial publication.

== New Features and Functionality

Version 3.0.0 of the Anypoint Service Registry agent introduces the following new features and upgraded functionality:

* *Consumer Key:* Anypoint Service Registry consumers are now automatically assigned a unique identifier, determined by consumer version. This identifier, along with a serviceId, can then be used through the service virtualization component in Mule so that the lookup returns all endpoints associated with contracts between the specified consumer and service. This functionality allows service owners to upgrade the version of a service, at the same time retaining fine-grained control of the specific consumers that should start using the new version. Read more about link:/documentation/display/current/Contract+Management#ContractManagement-consumerkey[supporting dynamic lookup using consumer keys].
* *Support for endpoints other than HTTP:* You can now associate File and FTP endpoints with a service, and use the service virtualization lookup method of invocation on these endpoints. Note that out-of-the-box policies are only supported on HTTP endpoints.
* *Custom Policies Toolkit:* This feature enables the creation of policies beyond the ones packaged out-of-the-box with the Anypoint Service Registry. Contact mailto:support@mulesoft.com[MuleSoft professional services] if you would like to take advantage of this feature.
* *Announcements:* The Anypoint Service Registry Web interface now displays important overall and organization-specific information, allowing users to get early notifications about any relevant administrative news such as scheduled maintenance.
* *Support for network proxies:* We have tested and verified the Anypoint Service Registry’s latest agent to ensure that it is link:/documentation/display/current/Configuring+Proxy+Access+to+API+Manager[functional with network proxies] within the enterprise.
* *Self-service trials:* Anypoint Service Registry trials are now fully self-service-based; anyone can http://www.mulesoft.org/login/anypoint.php[request a trial] through our online process.
* *Enhanced email notifications:* Important events regarding account management are now tracked at a finer-grained level through email notifications to the appropriate organization, service, and consumer owners.
* *Backward Compatibility:* Older version of the Anypoint Service Registry agent running on Mule ESB versions 3.3.2, 3.3.3, and 3.4.0 will continue to work without any action on behalf of users.
* *Documentation additions and improvements:* New link:/documentation/display/current/API+Manager+System+Architecture[technical architecture] and link:/documentation/display/current/API+Manager+Agent+Compatibility+Matrix[agent compatibility matrix] documents. +

== Hardware and Software System Requirements

Please refer to the detailed setup instructions in the link:/documentation/display/current/Integrating+API+Manager+with+Mule+ESB[setup guide for ESB on-premise] or the link:/documentation/display/current/Integrating+API+Manager+with+CloudHub[setup guide for CloudHub].

The Anypoint Service Registry application (https://registry.mulesoft.com%29/[https://registry.mulesoft.com)] supports the following browsers:

* Firefox (latest version)
* Chrome (latest version)
* IE 9 (10 is preferred)

== Important Notes and Known Issues in this Release

[NOTE]
====
If you have services registered on Anypoint Service Registry with a previous agent version and upgrade to Mule 3.5.0 Andes with the 3.0.0 Anypoint Service Registry agent, please be aware that within the element `<service-lookup>`, the attribute `serviceName` has changed to `serviceId`. Please update your consumer applications that are performing dynamic lookup and replace any instances of `serviceName` with `serviceId`.

In addition, the attribute `serviceRoundRobin` has been removed and replaced with a new element: `<dynamic-round-robin>`. Please update your consumer applications that were performing dynamic lookup to delete any references to the deprecated attribute. To enable round robin routing strategy, use the new <`dynamic-round-robin`> element instead.
====

[width="100%",cols="34%,33%,33%",options="header",]
|===
|JIRA |Issue |Workaround
|HABITAT-247 |Once SLA tiers are defined for a service, the registry does not permit contracts unless a tier is selected. |Service owner can delete existing tiers, allow the contract to be requested while no tiers are defined, and then reinstate the tiers after the contract request has been made. Any contracts that were based on the tiers before their deletion will not be affected.
|HABITAT-333 a|
The registry does not recognize endpoints of http proxies using `inboundAddress` and `outboundAddress` elements.

 a|
Define a proxy using the following method:

|===

== Support Resources

Please refer to the following resources for assistance using Anypoint Service Registry.

=== Documentation

Refer to the link:/documentation/display/current/Anypoint+Service+Registry[documentation] for instructions on how to use Anypoint Service Registry.

=== Getting Help

To access MuleSoft’s expert support team, log in to the http://www.mulesoft.com/support-login[Customer Portal].

=== Sending Feedback

Send MuleSoft feedback about Anypoint Service Registry by clicking the *Send Feedback* link in the lower right corner of any screen in the application.
