= Anypoint Studio January 2015 with 3.6.0 Runtime - Update Site 1 Release Notes
:keywords: release notes, anypoint studio

January 30, 2015

This January 30 2015 release is an update to the Studio January 2015 with 3.6.0 runtime, and complement the link:/documentation/display/current/Anypoint+Studio+January+2015+with+3.6.0+Runtime+Release+Notes[Anypoint Studio January 2015 with 3.6.0 Runtime Release Notes].

== Current Release Versions

[cols="3*", options="header"]
|===
|
| Enterprise Runtime
| Community Runtime

| ESB Runtime
| n/a
| n/a

| Studio
2+>| Version: January 2015 with 3.6.0 Runtime - Update Site 1 +
Build Number:  201501301032
|

| Management Console
| n/a
| n/a

| Mule DevKit
2+>| n/a

|===


== Fixed Issues

* Problem importing from Library if the project was exported with Studio version 5.x.x (STUDIO-5961)
* Validation error for rollback-exception-strategy (name attribute as required) (STUDIO-5962)
* Debugger does not stop on breakpoint in APIkit flow (STUDIO-5964)
* Update RAML parser to latest version (STUDIO-5966)
* Studio erases attributes from <spring:beans> when switching between XML and graphical views (STUDIO-5967)
* Datamapper is not being added automatically to the pom file when project is maven based (STUDIO-5968)
* RAML metadata is not retrieved when focus is lost inside http:request editor (STUDIO-5970)
* When adding dependencies automatically to the pom file the <inclusion> element is not added (STUDIO-5971)
* Adding <http:listener> in the xml through autocompletion adds duplicated attributes path and config-ref (STUDIO-5972)
* src/main/api directory isn't being added as resource folder in maven projects with APIkit (STUDIO-5973)
* Maven repo population is installing groovy-all as commons-cli locally (STUDIO-5977)
* Authentication fields not marked as mandatory in http:request (STUDIO-5983)
* RAMLs with custom baseUriParameters are not supported, only \{version} is correctly processed in http:request global configuration (STUDIO-5984)
* Large flow files take too long to open (STUDIO-5990)
* DataMapper leaves out charset attribute when generating grf for WSC (XML) to \{type} (STUDIO-5994)
* Default exception strategy in Global Configuration doesn't offer the existing global exception strategies (STUDIO-6005)
* Invalid attributes in HTTP Request global configuration (STUDIO-6016)
* Error when trying to run a project with Mule 3.3.3 (STUDIO-6022) +

== Migration Guide

This section presents configuration considerations you may want to adjust when migrating from a previous version of a Mule runtime, or previous version of Studio. mailto:support@mulesoft.com[Contact MuleSoft] if you have a question about a specific migration activity or concern.

To migrate from a previous version of Studio, use *Help > Check for Updates.*


== Support Resources

* For further details on Anypoint Studio with 3.6.0 Runtime, see the link:/documentation/display/current/Anypoint+Studio+January+2015+with+3.6.0+Runtime+Release+Notes[Anypoint Studio January 2015 with 3.6.0 Runtime Release Notes]
* Refer to MuleSoft’s http://www.mulesoft.org/documentation/display/current/Home[MuleSoft Documentation] for instructions on how to use the new features and improved functionality in Anypoint Studio with 3.5.1 Runtime.
* Access MuleSoft’s http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal].
