= Mule 0.9.3 Release Notes
:keywords: release notes, esb


This latest release sees some important changes to mule. Configuration has been greatly simplified with the introduction of Uri endpoints. There are improved Jms features such as Jsm 1.1 support, client acknowledge transactions and jndi destinations. The Mule client API can now make remote requests and register objects as Mule managed objects directly. There are 3 new providers, namely Tcp, Udp and Multicast. And a whole load of bug fixes and enhancements. +

*Uri Endpoints*
Providers can be represented a uri's in the configuration. This greatly simplifies configuration as there is no need to explicitly configure providers or connectors.


*New Providers*

tcp, udp, and ip multicast providers are now available.

*Jms Enhancements*

* Jms 1.1 support
* Jms Client Acknowledge transaction type, so Clicnet acknowledges can be configured like local transactions
* Jndi Destinations support
* Jms performance and resource management improvements


*Persistent Queues*

The VM provider now supports persistent queues.
Also internal queue persistence is now configurable is useful for maining state for recovery. +


*JMX Statistics*

Routers and components can report differnt messaging statisics via Jmx.


*Improved Client API*

Can now start a zero configuration client/server. +
Can make requests locally or to remote Mule servers +
Can register/unregister Mule managed beans directly with the server via the client +
Proxy listener interface allows allows any observed/observerable bean to send and receive mule events. +


*Bugfixes, Tests and Documentation*

* Loads of new test cases and functional tests.
* Lots of bugs and enhancements, thanks to everyone who reported and/or fixed bugs.
* Lots of new and updated documentation


I would like to thank everyone who reported issues and ideas and helped fix bugs. Special thanks go to -

* link:/documentation/display/~stephane[Stéphane Peiry] for proving the Jmx statistics and xml filters and transformers.
* link:/documentation/display/~magnus_stattin[Magnus Stattin] for his input on mule configuration
* link:/documentation/display/~jeje[Jerome Bernard] for providing and setting up a continuous build server for Mule
