= Architecture of the Management Console

When an IT organization deploys Mule ESB to production, the operations staff must be able to manage and monitor the ESB infrastructure and related services. Each additional system, application, or service introduced into the infrastructure increases the level of complexity, along with the need for visibility into and control over system performance and up-time.

Using the Mule ESB management console, you can manage all Mule ESB instances as well as deployed application bundles. The management console provides a centralized, convenient, and intuitive web-based interface to monitor, manage, and administer the run-time aspects of your enterprise service bus. With this high-performance and secure tool, you can save time and reduce errors by quickly identifying, diagnosing, and mediating problems from a central location.

== Architecture

The management console requires the following components:

* The correct version of Mule ESB
* The management console server
* The management console agent

The management console is available only with the Enterprise Edition of Mule ESB and is backward compatible with previous versions of Mule ESB.

The management console communicates with Mule ESB via the Management Console Agent. This agent is a Mule application; it is automatically installed in Mule ESB 3.1.

Mule ESB Enterprise 3.3 automatically installs and interoperates with both the Management Console and the Management Console Agent.

At installation the agent bundle is placed in the Mule ESB \apps directory and is then automatically unzipped and deployed by the ESB instance at startup.

The management console can be deployed directly to Mule ESB, as happens with the evaluation distribution; however, this is not recommended for deployments where you are monitoring multiple Mule ESB instances.

Once the Mule instance is authenticated and registered with the management console server, communication is secured through the use of certificates and HTTPS. Each Mule instance can be registered with a single management console server.

The management console server is a web application packaged as a WAR file that executes from within your web container. As such, it must be correctly deployed on the container, such as by placing the WAR file in the proper location within your web container installation. For example, for an Apache Tomcat installation, you deploy the mule management console WAR (`mmc.war`) file using MuleSoft Tcat Server, or by copying it to the Tomcat `/webapps` directory.

== Key Features

Following are key features of the management console:

=== Centralized management and monitoring

* Checks the health of ESB resources and displays it in an easy-to-navigate visual interface
* Provides intuitive charts that reveal system performance and resource consumption
* Manages multiple runtime environments, grouped by location, business function, or other criteria
* Defines and subscribes to Mule alerts

=== Fine-grained ESB control

* Start, stop, and restart ESB resources
* Remotely access, update, or replace any file or configuration on a Mule ESB server
* View resource consumption and dynamically tune flows in real time
* Dynamically configure thread pools

=== Enterprise-Level Security

* Enterprise authentication (LDAP)
* Fine-grained role based access control
* Secure runtime communication using certificates and HTTPS

=== Deep diagnostics and auditing

* View detailed information on memory utilization, threads, system resources, and server configuration
* Audit message traffic and associated properties for both the inbound and outbound sides of flows
* Turn flow level auditing on or off to capture just enough data to diagnose an issue without impacting performance

=== Intelligent alerting

* Receive notifications when critical metrics cross thresholds
* Monitor events at the individual server level or system level
* Escalate alerts to administrators or an external monitoring system
* Customize alerts using alert scripts

=== Flexible cluster management

* Create, disband, or add nodes to clusters as conditions dictate
* Monitor cluster status – get detailed information about cluster-based flows and memory usage
* Deploy apps to a cluster for enhanced availability, scalability, and performance.

=== In-Depth Event visualization

* Track key events in the flow of business transactions
* Analyze the flow and disposition of particular messages within a business transaction
* Drill into event data to identify failure points or bottlenecks
* Test flows for compliance with business procedures and standards

== Benefits

The management console provides the following benefits:

* Lower management cost with group-based management and control
* Simplify troubleshooting through quick access to the most relevant information
* Enhanced availability, scalability, and performance through clustering
* Improve visibility and understanding by analyzing real-time metrics that highlight significant changes
* Increase application up-time and performance through intelligent, proactive alerting and remediation tools
* Reduce downtime and time-to-resolution with deep diagnostics and auditing capabilities
* Minimal impact on the runtime performance of your ESB infrastructure
* Improve collaboration between operations and development through controlled access to runtime diagnostic information
* Insight into key business-related events
