= Mule DevKit

The Web has introduced thousands of new applications for business, IT, collaboration, social media, e-commerce and productivity. Many Web apps expose web APIs to integrate and automate the use of these applications and the data they manage.

Mule ESB includes many http://www.mulesoft.org/muleforge/connectors[Cloud Connectors] make it easy to connect a Mule application to an external APIs. However, you might require connectivity to an application API that is not currently in Mule's arsenal. Therefore, we introduced the *Mule DevKit* to enable developers to build their own Cloud Connectors.

In addition to creating connectors, the DevKit can help you build transformers, filters, transports, and much more.

=== Where should I start?

Review link:/anypoint-connector-devkit/v/3.3/devkit-overview[DevKit Overview], then get starting by building link:/anypoint-connector-devkit/v/3.3/your-first-cloud-connector[Your First Cloud Connector].

=== Need Help?

If you need help while developing your Cloud Connector, visit the http://forum.mulesoft.org/mulesoft[MuleForge Forums] and post your question to the community.

=== Found a bug?

If you find a bug in one of the cloud connectors or the Mule DevKit itself, please report it with our https://github.com/mulesoft/mule-devkit/issues[bug tracker].

=== Reference Guide

Use the navigation tree in the left sidebar to explore documentation for the Mule DevKit. The materials in the list below are particularly relevant to new users.

* link:/anypoint-connector-devkit/v/3.3/writing-mule-extensions[Writing Mule Extensions] explains how to code, document, and package Mule extensions using the Mule DevKit.
* link:/anypoint-connector-devkit/v/3.3/publish[Publish] explains how people can submit Mule extensions to the http://www.mulesoft.org/muleforge[MuleForge] site for sharing with the entire Community.
* link:/anypoint-connector-devkit/v/3.3/contribute[Contribute] explains how the Community can help improve the Mule DevKit. The Mule DevKit project source code is open to the entire Mule Community.
* link:/anypoint-connector-devkit/v/3.3/how-the-devkit-works[How the DevKit Works] provides in-depth information about the Mule DevKit.
* link:/anypoint-connector-devkit/v/3.3/devkit-glossary[DevKit Glossary] defines key terms used in the Mule DevKit documentation.
