= Using the Cloud Connector Archetype

Mule DevKit provides a *Maven archetype* to simplify the creation of Mule extensions. Running the archetype sets up a new Maven project with all the necessary dependencies to create a custom Cloud Connector. It also creates a proper directory structure and class skeletons to help you start coding quickly.

[WARNING]
To use Mule DevKit's Maven Archetype, ensure that you are using **Maven 3.x**.

The archetype's group id, artifact id and version are listed in the table below. +

[width="100%",cols="50%,50%",options="header",]
|===
|Parameter |Value
|archetypeGroupId |org.mule.tools.devkit +
|archetypeArtifactId + |mule-devkit-archetype-cloud-connector +
|archetypeVersion + |3.3.1 +
|===

For the archetype to set up the new project correctly, you must set the properties listed in the table below.

[width="100%",cols="50%,50%",options="header",]
|===
|Parameter |Description
|groupId |group id of the new project
|artifactId |artifact id of the new project
|version |version of the new project
|muleVersion + |Mule version for which this Cloud Connector has been developed.
|muleConnectorName + |name of the Cloud Connector in camel case, first letter capitalized
|muleConnectorPackage + |base package of the project (for example: com.mycompany)
|===

== Example

The command that follows is an example that creates a custom Cloud Connector project.

----
 mvn archetype:generate -DarchetypeGroupId=org.mule.tools.devkit \-DarchetypeArtifactId=mule-devkit-archetype-cloud-connector -DarchetypeVersion=3.3.1 \-DgroupId=com.mycompany -DartifactId=cool-connector -Dversion=1.0-SNAPSHOT \-DmuleVersion=3.3.1 -DmuleConnectorName=CoolAPI \-Dpackage=com.mycompany.coolapi \-DarchetypeRepository=http://repository.mulesoft.org/releases
----
