= AES OAuth FAQ
:keywords: aes, oauth, policy
== What's New with AES OAuth?

Since its first release, our platform has provided two ways of protecting APIs with OAuth v2: Using an external OAuth provider (PingFederate and OpenAM) or by using MuleSoft’s own OAuth provider (known as the Anypoint Enterprise Security (AES) OAuth provider). For our support of AES OAuth provider, we have been using a policy based model described in link:/anypoint-platform-for-apis/oauth-2.0-provider-and-oauth-2.0-token-enforcement-policies[OAuth 2.0 Provider and AES 2.0 Token Enforcement Policies] for the configuration of OAuth servers.  

Nothing is changing about our support for external OAuth providers. However, with the release of API Gateway 2.0, we are deprecating the policy based model in favor of a manual configuration model.

== Why are we deprecating the policy based OAuth server model?

The policy model does not allow for the configuration of the server with customized login screens nor the configuration of the underlying security manager with non-LDAP based user repositories (such as for example an RDBMS based user repository). These are the reasons why we are deprecating the usage of the policy based OAUth server model in favor of a manual configuration model.

== What should I do if I am already using the older AES OAuth policy model?

If you are using the policy for non-production environments, the policy as-is is working for you,  and the fact that tokens are issued exchanged HTTP (and not HTTPS) is not an issue - then you don’t need to do anything. However, if you are using the policy in production *and* have a security concern around usage of HTTP, then you should migrate to the new model. To do this, you would simply configure an external OAuth server with similar configuration as the policy based one, then plan for the removal of the policies from the affected APIs and the application of the new policy being supplied for external AES providers. Note that all of your existing registered apps (and as such their client ID and secrets) will continue working.

== Where can I learn more about the Mule external AES OAuth server model?

See link:/anypoint-platform-for-apis/external-oauth-2.0-token-validation-policy[External OAuth 2.0 Token Validation Policy] .
