= API Gateway 101
:keywords: gateway, cloudhub, policy, connectors

This page covers some frequently asked questions about the API Gateway component of the link:http://anypoint.mulesoft.com/apiplatform[Anypoint Platform for APIs]. You can download the API Gateway link:http://www.mulesoft.com/ty/dl/api-gateway[on the MuleSoft downloads page]. See also link:/anypoint-platform-for-apis/api-gateway-domain[API Gateway Domain].

=== What is an API Gateway?

An API Gateway is a runtime designed and optimized to host an API or to proxy a connection to an API deployed to another runtime. The gateway performs a number of functions critical to running and managing APIs. First, the API gateway serves as a point of control over APIs. It allows you to control which traffic is authorized to pass through the API to backend services, to meter the traffic flowing through, to log all transactions, and to apply runtime policies to enforce governance like rate limiting, throttling, and caching. In addition to these core functions, some gateways do more than host or proxy APIs – they integrate APIs with the backend services that power them. An API is just an interface that calls functionality living in a service or application, and unless that functionality lives in a well-defined web service, integration and orchestration capabilities are required to connect it to the API.

=== What are the capabilities and limitations of the API Gateway?

As described above, the API Gateway is an optimized runtime for API use cases. The API Gateway’s capabilities are limited in the following ways:

[cols=",",options]
|===
|*Connectors* a|
* HTTP/S
* Jetty
* Web Services Consumer
* JDBC
File
|*Custom Connectors* |Not supported
|*Integration Capabilities* a|
* Message processors
* Transaction management
* Error handling
* Mule Expression Language (MEL)
* DataWeave (Transform Message)
* DataMapper
* DataWeave
|*Batch Processing* |Not supported
|===

[NOTE]
To use other connectors or components you must purchase a license for Mule ESB Enterprise. Contact a  mailto:info@mulesoft.com[sales representative]  for more information.

=== What is a policy?

A policy is a mechanism the gateway uses to enforce filters on traffic as it flows through the gateway. These filters generally control things like authentication, access, allotted consumption, and SLAs. The Anypoint Platform for APIs comes with a number of pre-built policies including Rate Limiting, Throttling, OAuth 2, Basic HTTP Authentication, and XML and JSON threat protection. Custom policies can be built to support needs not addressed by out-of-the-box policies.

=== Where is an API Gateway deployed?

An API Gateway can be deployed to the cloud or on premises. Deciding on the right environment for your use case depends on a number of factors including the location of backend endpoints, enterprise architecture, and corporate security policy. Gateways can be deployed as single nodes or in clusters to support HA and high throughput use cases.

=== Where can I get more information about configuring my API Gateway?

See link:/anypoint-platform-for-apis/configuring-an-api-gateway[Configuring an API Gateway] for more details.

=== Where can I download the on-premises API Gateway?

You can download it link:http://www.mulesoft.com/ty/dl/api-gateway[here].

=== Where can I access the cloud API Gateway?

You can access the cloud API Gateway via the link:https://anypoint.mulesoft.com[Anypoint Platform].
