= Browsing and Accessing APIs
:keywords: api, portal, sla, oath

This page is for application developers interested in browsing the available API versions in a particular Anypoint Platform for organizing APIs, exploring the details of those APIs, and requesting access for your applications.

== Assumptions

To view API Portals that are restricted to particular users and roles, log in with the account that grants Portal Viewer access for those APIs.

== Browsing the Developer Portal

Your organization's Developer Portal can be found here:

*http://apiplatform.anypoint.mulesoft.com/apiplatform/\{yourorgdomain}/#/portals*

Note that you can only see API Portals listed on the Developer Portal that are Public or to which you have been granted Portal Viewer access. You can browse the portals alphabetically, or search for APIs according to name, version, or tags. +

== Accessing API Portals

To access the API Portal for an API, click the name of the API (if there are multiple versions displayed, clicking the name takes you to the version at the top of the list) or click a specific version number.

Every API Portal is different, depending on what the API Owners expose for that API. You should see documentation for the API and links in the left navigation to further resources, such as an API Console. If the API you are browsing is implemented with RAML, you can use the API Console to explore the different calls and responses.

If you are browsing an API Portal for an API that already has an API URL set up for it by its API Owners, you see a *Request API Access* button at the top of the API. Click this button to register an application for access to this API. If you have previously registered an application for any API in the Developer Portal, that application appears in your drop-down menu. If you are registering an API for the first time, click *New Application*.

== Registering an Application

When you create a new application, the Anypoint Platform prompts you to provide key information about your application to help API owners identify the characteristics and needs of your application. This informations helps make good decisions when approving your for a particular SLA tier. The prompts also provide information to contact you, should they need to migrate your application to a new version of the API, for example.

When you create an application, you are prompted for a *Name*, *Description*, *Application URL*, and *Redirect URI*. If your organization is signed up to use PingFederate for identity management, you are also prompted to select an *OAuth Grant Type*. Click *Submit* to commit your application details.

If the API has link:/anypoint-platform-for-apis/defining-sla-tiers[SLA tiers], select one of them. Click *Request Access*. If the API does not define SLA tiers, or if the SLA tier you select is configured for automatic approval, the "Your API access request has been approved" message displays. If the access request requires manual approval, wait for the API owner to grant your request.

== Accessing Your Application Client ID and Client Secret

After you have create your application, you can access application information from the *My Applications* tab in the Developer Portal. Log in to see your application information, which is only visible to you. The My Applications display provides a unique client ID and client secret for your application, which you need to pass your API calls for APIs that are protected with policies. This display also lists the APIs your application is currently registered to use.

To edit the details of your application, click the pencil icon next to your application name.

== Changing SLA Tiers

The following options describe the various ways that you and/or an API Owner can change the SLA tier that your application is contracted to use.

* If you requested access to a tier and have not yet been approved for that tier, you can reapply for access to a different tier and your request for access is automatically updated to the new tier.
* If you have been approved for a tier, you can reapply for access to a different tier. If the new tier requires manual approval, you need to wait for the API Owner to change your tier per your request.
* If you were previously approved for an SLA tier and your access to that tier was revoked, you can reapply for access to a tier. The API Owner can then restore your access and adjust the tier.
* If you were approved for an SLA tier and that tier is deprecated by the API Owner, you can apply for access to a non-deprecated tier. The API Owner can then change your tier per your request.
* The API Owner can also change your tier without a change request from you.

== Accessing APIs Protected by PingFederate OAuth Token Enforcement

When you work in an organization that uses PingFederate for identity management, you need to supply additional information to develop your application. Register your application on the Anypoint Platform to obtain a client ID and client secret from PingFederate, and work with your Organization Administrator to get necessary OAuth information.

When you register applications for access to APIs in a federated organization, you need to provide an *OAuth Grant Type*, *Application URL*, and **OAuth 2.0 Redirect URI**.

== See Also

* Learn more about creating your own link:/anypoint-platform-for-apis/creating-an-api-notebook[API Notebooks].
* Want to create APIs of your own? Ask your organization administrator for API Creator access.
