= HTTP Basic Authentication Policy
:keywords: http, authentication, oauth

This page describes the configuration and runtime application instructions for the HTTP Basic Authentication policy for the Anypoint Platform for APIs. This policy verifies request credentials and enforces access according to your configuration.

== Assumptions

This document assumes that you are an API Version Owner for the API version that you want to manage, or that you are an Organization Administrator.

This policy requires a Security Manager policy in order to function. You can use the Simple Security Manager policy for testing, or else configure an LDAP Security Manager. See the link:/anypoint-platform-for-apis/ldap-security-manager[LDAP Security Manager] policy documentation for how to configure a security manager against which the HTTP Basic Auth policy can authenticate.

== Configuration

This policy doesn't require any configuration, as it enforces authentication according to the details configured in a security manager policy.

== Obtaining User Credentials

In some cases, you might want to have access to information about users are using your API. To do so, place the following script in any place between your proxy's inbound and outbound endpoints (it will be executed after the HTTP Basic Authentication Policy):

[source,xml,linenums]
----
<expression-component>
    message.outboundProperties.put('X-Authenticated-userid', _muleEvent.session.securityContext.authentication.principal.username)
</expression-component>
----

The script above stores the username in the mule message as an outbound-property named `X-Authenticated-userid`. The HTTP Connector –used to generate the proxy's output– transforms any outbound properties that reach it into HTTP message headers, so in this way the message that reaches your API after passing through your proxy will include an HTTP header named `X-Authenticated-userid`, containing the username.

[TIP]

You can modify this code to change the name of the header being created.


== See Also

* Return to the link:/anypoint-platform-for-apis/applying-runtime-policies[Applying Runtime Policies] page.
* Use the link:/anypoint-platform-for-apis/oauth-2.0-provider-and-aes-oauth-2.0-token-enforcement-policies[OAuth 2.0 Provider and AES OAuth 2.0 Token Enforcement Policies].
* If your organization uses PingFederate, see link:/anypoint-platform-for-apis/pingfederate-oauth-token-enforcement-policy[PingFederate OAuth Token Enforcement Policy].
