== Introducing CloudHub
:keywords: cloudhub, cloud, saas

Integrate SaaS applications, Cloud Services and Enterprise applications in real-time. CloudHub is the world's first integration Platform as a Service (iPaaS). CloudHub is built on top of Mule, the most widely used integration platform.


http://www.mulesoft.org/documentation/display/current/Use+Cases[*Use Cases*] https://anypoint.mulesoft.com/#/signup[*Sign Up*] http://www.mulesoft.org/documentation/display/current/Getting+Started+with+CloudHub[*Get Started*]


== Why CloudHub?

=== Start Small, Think Big

CloudHub is an elastic cloud that scales on demand. You can start small and grow as your needs grow, all without changing your application. CloudHub provides you with a scalable architecture – one you can build integration applications on, publish REST APIs or Web Services, and much more.

=== Rock Solid Platform

Built on our battle-tested Mule integration platform, Mule ESB is used by thousands of companies for mission-critical applications. It's the world's most widely used platform for integration.

=== Integrate your Cloud and Enterprise Applications

The Secure Enterprise Gateway (SDG) provides a secure pipe to the enterprise, breaking down the "cloud silo." CloudHub allows you to integrate and orchestrate applications, data sources, and services across the enterprise and cloud.

=== Unrivaled Connectivity

Easily integrate with popular SaaS, cloud, and social media platforms such as Salesforce.com, Intuit, Authorize.net, Amazon, Twitter, Facebook, and PayPal using our predefined connectors – then orchestrate data between these services and the enterprise. Plus, our development kit allows developers to create new connectors easily. You don't even need knowledge of the underlying integration infrastructure.

=== Don't Change the way you Code

Create CloudHub applications with the development tools you are already familiar with. Download https://www.mulesoft.org/download-mule-esb-community-edition[Anypoint Studio], it's free! Anypoint Studio is an Eclipse-based graphical environment that allows developers to easily choose to code in a visual environment with a palette of components, or in a familiar XML code view. You can even switch between the visual and code views as you build your application. Or, if you would rather use the command-line, we support Maven, as well as a command line tool.

=== Visibility and Control with the CloudHub Cloud Console

With CloudHub, you also get our intuitive cloud console where you can manage your applications, scale up and scale down, view event traffic, and much more. Use the CloudHub Cloud Console to manage every aspect of your CloudHub applications from one place.

=== Behind a Great Platform is a Great API

Do you need to automate tasks, or build CloudHub into your deployment process? CloudHub has a link:/documentation/display/current/CloudHub+API[REST API] with which you can perform tasks such as manage and monitor your applications, scale your applications up or down, and more.
