= Command Line Tools
:keywords: cloudhub, cloud

CloudHub provides a set of tools to help you deploy and manage your applications seamlessly from the command line.

Here's a summary of the commands:

[cols="2*" options="header"]
|===
| Command
| Description

| link:#CommandLineTools-cloudhub-list[cloudhub-list]
| List all your applications and their status

| link:#CommandLineTools-cloudhub-create[cloudhub-create]
| Create a new application

| link:#CommandLineTools-cloudhub-update[cloudhub-update]
| Update an application, its workers, and its environment variables

| link:#CommandLineTools-cloudhub-delete[cloudhub-delete]
| Delete an application

| link:#CommandLineTools-cloudhub-logs[cloudhub-logs]
| List the last lines (tails) of the logs from your application
|===

== Installation

To install the tools:

. Download the distribution from link:/documentation/download/attachments/122752486/cloudhub-cli-1.0.1.zip?version=1&modificationDate=1341700530210[here].
. Unzip/extract the distribution in a location on your local machine.
+
[source,bash]
----
$ unzip cloudhub-cli-1.0.1.zip
----
+
. Add the bin directory to your PATH.
+
[source,bash]
----
$ export PATH=/path/to/cloudhub-cli-1.0.1.zip/bin:$PATH
----
+
. You can optionally set the following environment variables to make invoking the commands easier:
+
[cols="2*"  options="header"]
|===
| Environment Variable
| Description

| CLOUDHUB_USERNAME
| Your CloudHub username

| CLOUDHUB_PASSWORD
| Your CloudHub password

| CLOUDHUB_DOMAIN
| Your CloudHub application domain
|===
+
This makes the domain, username, and password arguments optional in the commands below.

== Accessing Different Environments

Your username controls which environment you're accessing and is of the form `user@environment`. For example, if your username is joe and you have an environment called "Development", your username is `joe@Development`. If you don't specify an environment, it defaults to `production`.

== cloudhub-list

Example:

[source,bash]
----
$ cloudhub-list
hello: STARTED
----

Reference:

[source,bash]
----
Usage: cloudhub-list
 -h,--help             Print out help for this command.
 -p,--password <arg>   Password
 -u,--username <arg>   Username
----



== cloudhub-create

The first time you create your application, a `cloudhub.properties` file creates with additional parameters for location of your file, number of workers, and all system properties. Each time you update your application, these properties  automatically load from the `cloudhub.properties` file.

Example:

[source]
----
$ cloudhub-create -d test -f ../web/target/test-classes/hello.zip -w 1 -D foo:bar hello:test
Creating application...
Creating properties file...
Application created!
Uploading application...
Application uploaded!
----

Reference:

[source]
----
Usage: cloudhub-create
 -D,--properties <arg> A list of system properties for your application
 -d,--domain <arg>     The domain of your application
 -f,--file <arg>       The Mule application zip file
 -h,--help             Print out help for this command
 -p,--password <arg>   Password
 -u,--username <arg>   Username
 -w,--workers <arg>    The number of workers for your application
 -x,--url <arg>        CloudHub API URL
----


== cloudhub-update

Example:

[source]
----
cloudhub-update
----

Reference:

[source]
----
Usage: cloudhub-update
 -D,--properties <arg> A list of system properties for your application
 -d,--domain <arg>     The domain of your application
 -f,--file <arg>       The Mule application zip file
 -h,--help             Print out help for this command
 -p,--password <arg>   Password
 -u,--username <arg>   Username
 -w,--workers <arg>    The number of workers for your application
 -x,--url <arg>        CloudHub API URL
----

== cloudhub-delete

Example:

[source]
----
$ cloudhub-delete -d app
----

Reference:

[source]
----
Usage: cloudhub-delete
 -d,--domain <arg>     The domain of your application
 -h,--help             Print out help for this command
 -p,--password <arg>   Password
 -u,--username <arg>   Username
----


== cloudhub-logs

Lists the last lines (tails) of the log results from your application. Output continues to tail the logs until you press CTRL-C.

Example:

[source]
----
$ cloudhub-logs
...
INFO    11-04-05 07:21:41   [ApplicationServiceImpl] Successfully deployed [test]
----

Reference:

[source]
----
Usage: cloudhub-logs
 -d,--domain <arg>     The domain of your application
 -h,--help             Print out help for this command
 -p,--password <arg>   Password
 -u,--username <arg>   Username
----
