= Maintenance and Upgrade Policy
:keywords: cloudhub, support, upgrade, subscription

All maintenance to the CloudHub console, platform services, and worker cloud (see link:/documentation/display/current/CloudHub+Architecture[CloudHub Architecture]) is performed during the maintenance windows specified in the http://www.mulesoft.com/terms/msa/current[subscription agreement], except for critical security issues which are fixed immediately.

MuleSoft's policy is to perform all maintenance transparently and without any downtime to your integration(s) running in the worker cloud wherever possible. In cases where downtime for the console, platform services, or workers is unavoidable, MuleSoft communicates these maintenance windows at least 8 hours in advance and typically 7 days in advance, with the exception of critical security patches which may be fixed immediately.

View the live status and detailed service history for the CloudHub console, CloudHub platform services, and the CloudHub worker cloud on http://trust.mulesoft.com/[trust.mulesoft.com].

== Mule Version Upgrades

For the worker cloud, there are additional policies which apply to Mule version upgrades.  For each release type, there is a minimum deprecation period which starts after a new version is released. This is how long the previous version is supported. For example, now that the minor version 3.6 has released, support is provided for the previous minor version, 3.5, for at least 12 months after the release of 3.6.

Customers receive notices prompting them to upgrade their applications during this deprecation period. If after the specified time an application is not upgraded, the application is restarted using CloudHub Zero Downtime on the new Mule version.

[cols="2*" options="header"]
|===
| Release Type
| Minimum Deprecation Period

| *Mule bug fix release (such as 3.5.2)*
| 90 days

| *Mule minor version (such as 3.6.x)*
| 12 months

| *Mule major version (such as Mule 3.x.y)*
| 18 months

| *CloudHub Runtime Release (such as Jan 2015)*
| 4 months

|===
