= Working with an IDE

This document offers tips for importing and working on Mule source code in *Mule Studio*, *Eclipse* or *IntelliJ IDEA*. There are no restriction on the type of integration development environment you use to develop Mule, we simply chose to discuss the above-listed three as common IDEs.

== Mule Studio

*Mule Studio* is an open-source, Eclipse-based graphical user interface you can use to access Mule ESB's functionality. More than just a GUI interface for building projects with Mule, you can use Mule Studio as an IDE to work with Mule source code in Java.

=== Importing

. Follow the link:/mule-user-guide/v/3.4/downloading-and-launching-mule-esb[instructions] to download, install and launch Mule Studio.
. Follow link:/mule-user-guide/v/3.4/converting-maven-into-studio[the procedure] to add the *`studio:studio`* plug in in your Maven `settings.xml` file.
. Within the directory to which you cloned the Mule source code, resolve all library dependencies and generate IDE project files by running the following command:  `mvn studio:studio`
. In Studio, Select *File* > *Import*.
. In the *Import* wizard, click to expand the *General* folder, then select *Existing Projects into Workspace*, then click** Next**.
. In the *Select root directory* field, use the *Browse* button to navigate to the directory into which you downloaded the cloned fork of Mule source code from your Github account.
. Ensure all *Projects* are checked, then click *Finish*. Studio imports the mule source code.
. Open source code files as you need to edit or add content.
. Click the *Save* icon to save locally.

=== Debugging

. In Studio, select *Window* >  *Open Perspective* > **Other...** , then select *Java* to open the Java Perspective.
. Select *File* > *New* > *Java Project*. You are creating a new project just for launching Mule.
. In the *New Java Project* wizard, select a *Name* for your project, such as `Mule Launcher`, then click *Next*.
. In the *Java Settings* panel of the wizard, select the *Projects* tab, then click *Add*.
. Click *Select All*, then click *OK*, then** Finish**.
. In the Package Explorer, right click your launcher project's name, then select *Debug As* > *Debug Configurations...*
. In the *Debug Configurations* wizard, double-click *Java Application*.
. In the *Main class* field, enter the following content:  `org.mule.MuleServer`
. Click the *Arguments* tab. In the *Program Arguments* field, enter the following content: `-config <path to a Mule config>`
. Click *Apply*, then click *Debug*.
. Studio requests permission to switch to the *Debug Perspective*; click *Yes* to accept and open.

You can now set breakpoints anywhere in any of the Java files in any of the Mule projects in the workspace. link: *When you change java files and rebuild, the debugger hot swaps the rebuilt Java class file to the running Mule server.* Note that you only need to follow the procedure above to set your Debug configurations once; thereafter, simply right-click the project name, then select *Debug As* > *Java Application* for subsequent debugging.  

=== Debugging Remotely

. *From the command line, edit the `JPDA_OPTS` variable in the Mule startup script and specify the debugger port.*
. *Start the Mule server with the `-debug` switch. The server waits until a debugger attaches.*
. In the Package Explorer in studio, right-click your Mule source code project's name, then select *Debug* > *Debug Configurations...*
. Double-click *Remote Java Application*.
. Under *Connection Properties*, enter a value for *Host* and *Port*, then click *Apply*.
. Click *Debug*. Studio requests permission to switch to the *Debug Perspective*; click *Yes* to accept and open.

=== Testing

Use Maven to run unit test on your project using the following command: `mvn test`

In addition to the unit tests for each sub-project, the Mule parent project has a separate sub-project containing integration tests. These tests verify "macroscopic" functionality that could not be tested by any single sub-project alone.

== Eclipse

An open-source integration development platform, use Eclipse to modify or add to your cloned version of Mule source code.

=== Importing

. Download and install http://www.eclipse.org/downloads/[Eclipse] on your local drive.
. From the command line, in the directory into which you downloaded the Mule source code, enter the following command to generate the classpath and project files for each sub-project:  `mvn eclipse:eclipse`.
. _Before launching Eclipse_, make the Maven repository known in Eclipse using the following command:  +
`mvn -Declipse.workspace=/path/to/eclipse/workspace eclipse:configure-workspace`
. Launch Eclipse, selecting the workspace you just "mavenized".
. Under the *Project* menu, select *Build Automatically* to _disable_ it; this action speeds up the import process.
. Select *File* > *Import*.
. In the *Import* wizard, click to expand the *General* folder, then select *Existing Projects into Workspace*, then click** Next**.
. In the *Select root directory* field, use the *Browse* button to navigate to the directory into which you downloaded the cloned fork of Mule source code from your Github account.
. Ensure all *Projects* are checked, then click *Finish*. Eclipse imports the mule source code. 
. Select **Project > Build Automatically** once again to re-enable build automation.
. Open source code files as you need to edit or add content.
. Click the *Save* icon to save locally.

=== Debugging

. In Eclipse, select *Window* >  *Open Perspective* > **Other...** , then select *Java* to open the Java Perspective.
. Select *File* > *New* > *Java Project*. You are creating a new project just for launching Mule.
. In the *New Java Project* wizard, select a *Name* for your project, such as `Mule Launcher`, then click *Next*.
. In the *Java Settings* panel of the wizard, select the *Projects* tab, then click *Add*.
. Click *Select All*, then click *OK*, then** Finish**.
. In the Package Explorer, right click your launcher project's name, then select *Debug As* > **Debug Configurations...**
. In the *Debug Configurations* wizard, double-click *Java Application*.
. In the *Main class* field, enter the following content:  `org.mule.MuleServer`
. Click the *Arguments* tab. In the *Program Arguments* field, enter the following content: `-config <path to a Mule config>`
. Click *Apply*, then click *Debug*.
. Eclipse requests permission to switch to the *Debug Perspective*; click *Yes* to accept and open.

You can now set breakpoints anywhere in any of the Java files in any of the Mule projects in the workspace. *When you change java files and rebuild, the debugger hot swaps the rebuilt Java class file to the running Mule server.* Note that you only need to follow the procedure above to set your Debug configurations once; thereafter, simply right-click the project name, then select *Debug As* > *Java Application* for subsequent debugging. 

=== Debugging Remotely

. *From the command line, edit the `JPDA_OPTS` variable in the Mule startup script and specify the debugger port.*
. *Start the Mule server with the `-debug` switch. The server waits until a debugger attaches.*
. In the Package Explorer in studio, right-click your Mule source code project's name, then select *Debug* > **Debug Configurations...**
. Double-click *Remote Java Application*.
. Under *Connection Properties*, enter a value for *Host* and *Port*, then click *Apply*.
. Click *Debug*. Eclipse requests permission to switch to the *Debug Perspective*; click *Yes* to accept and open.

=== Testing

Use Maven to run unit test on your project using the following command: `mvn test`

In addition to the unit tests for each sub-project, the Mule parent project has a separate sub-project containing integration tests. These tests verify "macroscopic" functionality that could not be tested by any single sub-project alone.

=== Setting Eclipse Startup Parameters

The table below lists a number of command-line parameters you can use to alter Eclipse's startup behavior, if you wish. 

[width="100%",cols="50%,50%",options="header",]
|===
|Parameter |Action
|`-clean` |enables clean registration of plug-in (some plug-ins do not always register themselves properly after a restart)
|`-nosplash` |does not show Eclipse or plug-in splash screens
|`-showLocation` |puts the full path of the workspace in the window title
|`-vm` |allows you to explicitly set which JDK to use
|`-vmargs` |allows you to pass in standard VM arguments
|===

== IntelliJ IDEA

Use IntelliJ's IDEA integration platform to modify or add to your cloned Mule source code.

=== Importing

. http://www.jetbrains.com/idea/download/[Download] and install IntelliJ IDEA.
. Open IDEA, then select *File* > *Open...*
. Browse to the directory into which you downloaded the Mule source code, then select the `pom.xml` file. 
. Click *OK*. IDEA takes awhile to process all the `pom.xml` files.
. Set the correct source for the JDK on your local drive. Right click the **mule-transport-jdbc** directory, then select  *Module Settings* > *Sources* > **src > main > jdk6** or *jdk7*. Repeat this step for test sources, as tests.

*Troubleshooting* +
If you IDEA presents any compilation errors in test classes from the CXF module when you create the project, it is safe to ignore them. Those classes depend on some test classes generated by the Maven build during execution. Right click the error message, then select *Exclude from compile*.  Alternatively, you can run `mvn install` from the command line to fix the errors.

=== Debugging Remotely

. Start the Mule server with the `-debug` switch. The server waits until a debugger attaches.
. In IDEA, select *Run* > *Edit Configurations...* to open the *Run/Debug Configurations* window.
. Click *Add New Configuration* (plus sign), then select *Remote*.
. Enter a *name* for the configuration, then update the *host* and *port* values if required (You can use the default values, `localhost:5005`, for debugging a local mule instance).
. Click *OK* to start the debugging session.

=== Testing

Use Maven to run unit tests on your project using the following command: `mvn test`

In addition to the unit tests for each sub-project, the Mule parent project has a separate sub-project containing integration tests. These tests verify "macroscopic" functionality that could not be tested by any single sub-project alone.
