= MuleSoft Connector Certification Program Guidelines
:keywords: connector, certification, devkit, program guidelines


The sections below describe the specific details necessary for connector certification. For a full overview of the process, visit link:https://www.mulesoft.com/platform/cloud-connectors/certified[this page].

== What is MuleSoft connector certification program?

MuleSoft’s connector certification program guides you through the process of creating an enterprise-grade connector that is ready for certification by MuleSoft. Once certified, the connector will be made available through the Anypoint Exchange for discovery and use for our customers and developers.


== Before you begin
Before embarking on the certification program, please consider the following and make sure you can adhere to the below requirements:

* Connector must be kept current and secure, and re-certified at least once a year.
* Connector must be built and distributed for the enterprise version of the MuleSoft Software or MuleSoft Service.
* All transaction for the connector will take place between the customer and the partner, not through MuleSoft.
* Connector must be a fully-functional, production-ready, enterprise-grade application/protocol connector (i.e. it’s a connector that connects Mule with an external system)
* Code must be ready for deployment into a continuous integration environment. Code should be able to be compiled from command line without importing private repos. Credential should be provided separately and able to be set at compile time. In addition, sandbox credential for your connector is required for certification.
* Connector must only use third party libraries that are open source or owned by you. No third-party, non-distributable libraries will be accepted.
* If a similar connector already exists on link:https://www.mulesoft.com/exchange[Anypoint Exchange], you can still submit your connector granted that it provides additional functionality superior to the existing connector.



== Providing support
Partners or developers are required to provide *full support* for the connector(s) on Anypoint Exchange. For support inquiries received by MuleSoft, MuleSoft will provide a commercially reasonable level of first-tier telephone, web-based and/or email support directly to customers. MuleSoft will take and resolve any issues that are linked to commercial MuleSoft products. Any issues specific to the partner connector will be escalated to the partner.

* Partner will respond to all support queries escalated from MuleSoft within *one business day.*
* Partner will exercise best effort to resolve technical support issues for customers within *five business days.*

== Pricing for your connector
Partners or developers will have sole discretion to decide whether you make your connectors available for free or for a fee. However, all connectors must be available at no cost within Anypoint Studio. While not mandatory, we recommend providing a trial of your connector (for design and deployment) for customers.

[width="100%",cols="20%,80%",options="header"]
|===
a|
Category

 a|
Details

| Free |Connector will be available for download and use for free to customers through Anypoint Exchange.
| Paid |Connector will be available for download and use for free to customers through Anypoint Exchange only within Anypoint Studio. The connector will not run in deployment without credentials. Customers will need to purchase the connector directly from the partner. The pricing of the connector will be determined by the partner.
|===

== License Terms
Please add the following legal terms before your license terms in LICENSE.md
****
*About MuleSoft Certified Connectors*

MuleSoft Certified Connectors are developed by MuleSoft’s partners and developer community. These connectors have been reviewed and certified by MuleSoft. To purchase the connector or to get assistance or support for the _[Connector Name]_ Connector, please contact _[Partner Name]_ directly at _[Contact Information]_. MuleSoft disclaims any support obligation for MuleSoft Certified Connectors.

By installing this connector, you consent to MuleSoft sharing your contact information with the developer of this connector so that you can receive more information about it directly from the developer.

*Your own license terms*
****


== Development and certification
Please share with us which connector you want to develop and get certified by filling out link:https://www.mulesoft.com/platform/cloud-connectors/certified#certification[this form.] We will contact you with further information.
