#%RAML 0.8
title: External AES Tutorial
version: 1.0
baseUri: http://localhost:8080/api
/teams:
  displayName: Teams
  get:
    queryParameters:
      city:
        type: string
        required: false
        example: Barcelona
    responses:
      200:
        body:
          application/json:
            example: |
              [{
                "name": "Athletic Bilbao",
                "id": "ATH",
                "homeCity": "Bilbao",
                "stadium": "San Mames"
              },
              {
                "name": "Atletico Madrid",
                "id": "ATL",
                "homeCity": "Madrid",
                "stadium": "Vicente Calderon"
              }]