#%RAML 0.8
---
title: Leagues
version: 1.0
baseUri: http://localhost:8080/api
documentation:
  - title: Getting Started
    content: |
      This sample API has been created as part of your APIkit project. 
/teams:
  displayName: Teams
  #description: |
  # 
 A collection of teams that are participating in La Liga. Teams API 
allow you add, remove and retrieve individual team information from La 
Liga.
  get:
    description: Obtain information from a collection of teams simultaneously
    queryParameters:
      city:
        description: |
          Filter the list of teams by home city.
        type: string
        required: false
        example: Barcelona
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/teams-schema-input.json         
            example: !include examples/teams-example.json