= Customizing Mule Studio integration

The Mule DevKit allows you to integrate your Cloud Connector with Mule Studio out of the box by running:

----
mvn clean package -Ddevkit.studio.package.skip=false
----

By default names are inferred from Java method, parameter and instance variable names as well as JavaDoc comments. The following annotations can be used to customize Mule Studio dialogs and override the default inferred values.

== @Placement

This annotation can be applied to instance variables and method parameters. It has the following parameters:

* _order_: gives the annotated element a relative order within its group. The value provided may be repeated and in that case the order is not guaranteed. The value is relative meaning that an element with order 10 has higher predence than one with value 25.
* _group_: a group is a logical way to display one or more variables together. If no group is specified then a default group is assumed. To place more than one element in the same group, use the exact same values for this attribute.
* _tab_: a tab is a logical way to groups together. This attributes specifies the name of the tab in which the annotated element should be displayed. If no tab is specified then a default tab is assumed. To display more than one parameter or field in the same the tab then this value should be exactly the same for all of them.

== @FriendlyName

This annotation can be applied to instance variables and method parameters. It provides a way to override the default inferred short name for a @Configurable variable or a @Processor/@Source/@Transformer method parameter.

== @Summary

This annotation can be applied to instance variables and method parameters. It provides a way to override the default inferred description for a @Configurable variable or a @Processor/@Source/@Transformer method parameter.

== @Password

Identifies a field or method parameter as being a password or more generally as a variable which contains data that should not be displayed as plain text.

== @Icons

This is a class level annotation and it is used to override the default location of the icons. You may override the location of one or more of the required icons. The path needs to be relative to /src/main/java
