= Anypoint Connector DevKit

**Anypoint Connector DevKit **provides the tools and interfaces for building custom link:/mule-user-guide/v/3.4/anypoint-connectors[Anypoint Connectors] for use with Mule ESB. As reusable components that hide API complexity from the integration developer, custom connectors facilitate integration with SaaS and on-premise Web services, applications and data sources. Connectors built using DevKit function in Mule Studio and Mule ESB runtime environments as extensions of the core product. +

This documentation contains all the information you need to build custom Anypoint Connectors which:

* Access SOAP-based, RESTful, and Java client library-based APIs
* Support OAuth and basic authentication, as well as other authentication methods
* Provide advanced design-time functionality such as Mule link:/mule-user-guide/v/3.4/mule-datasense[DataSense] support
* Support runtime attributes like connection pooling, instance pooling, and multi-tenancy (needed to run in CloudHub) 

*link:/anypoint-connector-devkit/v/3.4/devkit-shortcut-to-success[Ready to Write Code?]*

== Assumptions

The DevKit documentation assumes that you have a working knowledge of Mule, Mule Studio, and Java development in general. It also assumes you have explored some http://www.mulesoft.org/documentation/www.mulesoft.org/connectors[existing connectors] and are familiar with how to use them. It also assumes that you have access to a sandbox environment for the target system or source, and documentation of the Web service it exposes. Though this documentation provides how-to information for tasks requiring Maven, you ideally have some familiarity with Java development using http://eclipse.org/[Eclipse] or http://www.jetbrains.com/idea/[IntelliJ], the http://maven.apache.org/guides/getting-started/maven-in-five-minutes.html[Maven] build manager, and basic Maven concepts. 

In addition to a general familiarity with the Java language, you specifically need to understand the use of Java annotations. DevKit's functionality is exposed to connector developers through Java annotations that inject code into your connector classes. The injected code provides the interface between the connector and Mule that would otherwise require each connector developer to include extensive boilerplate code. This documentation explains each DevKit-specific annotation in context with examples. If you are not familiar with annotations in general, refer to a brief explanation of http://en.wikipedia.org/wiki/Java_annotation[Java annotations].

== Get Started

* Begin at the beginning with the link:/anypoint-connector-devkit/v/3.4/anypoint-connector-concepts[Anypoint Connector Concepts].
* If you're eager to jump in and start writing code immediately, picking up the concepts as you go, begin with the link:/anypoint-connector-devkit/v/3.4/devkit-shortcut-to-success[DevKit Shortcut to Success].

[TIP]
====
*Problem already solved!*

Before digging into DevKit, take into account that there are already dozens of existing connectors built to integrate with Mule. Browse our http://www.mulesoft.org/connectors[library] of community-built and company-built connectors to see if someone has already tackled the integration challenge you're facing.  
====
