= Mule DevKit

The web has introduced thousands of new applications for business, IT, collaboration, social media, e-commerce and productivity and many of them now expose web APIs to integrate and automate the use of these applications and the data they manage.

Mule ESB supports a growing number of http://www.mulesoft.org/muleforge/connectors[Cloud Connectors] but you or your customers might require connectivity to a application API which is not currently listed. To help with this, there is the Mule DevKit which guides the developer though the setup and creation of a Cloud Connector.

In addition to creating connectors, the DevKit can help you build transformers, filters, transports, and much... much more.

=== Where should I start?

Look at our link:/anypoint-connector-devkit/v/3.2/your-first-cloud-connector[Your First Cloud Connector] section to get started.

=== Need Help?

If you need help while developing your Cloud Connector you can always visit the http://forum.mulesoft.org/mulesoft[Forums] and post your question to the community.

=== Found a bug?

If you have found a bug in one of the cloud connectors or the cloud connector development kit itself, please report it with our https://github.com/mulesoft/mule-devkit/issues[bug tracker].

=== Reference Guide

The document includes the following sections:

* link:/documentation-3.2/display/32X/Writing+Mule+Extensions[Writing Mule Extensions] explains how to code, document, and package Mule extensions using the Mule DevKit.

* link:/anypoint-connector-devkit/v/3.2/publish[Publish] explains how people can submit Mule extensions to the http://www.mulesoft.org/muleforge[MuleForge] site for sharing with the entire Community.

* link:/anypoint-connector-devkit/v/3.2/contribute[Contribute] explains how the Community can help improve the Mule DevKit. The Mule DevKit project source code is open to the entire Community.

* link:/anypoint-connector-devkit/v/3.2/how-the-devkit-works[How the Devkit Works] shows how the DevKit works under the covers.

* link:/anypoint-connector-devkit/v/3.2/glossary[Glossary] provides quick reference for key terms used in this documentation.
