= Promoting your module

After you have created a new extension, you can submit it as a project on MuleForge. This allows you to share it with the Mule community so you can get feedback on the quality and design of the module before putting it into production. By submitting to the MuleSoft.org site, you get the benefit of others trying out your module, and others get the benefit of your work.

Just as you make use of the available extensions in MuleForge that were submitted by others, the extension you have created can be very helpful for others.

== Submitting extensions

In order to make Mule extensions available to our entire community, fill in the form in the http://www.mulesoft.org/contribute-project[Contribute a Project] page. Enter as much details as possible since some of this data will be make public for people searching for Mule extensions and can help them decide whether your extensions is the right one for them.

You have to include a link the source code repository so make sure the latest code is available at the time you submit the form. The preferred source code repository is GitHub.

Also provide a link the documentation of the extensions. The documentation should be as complete as possible to help users to start using your extensions.

This form will be reviewed and you will receive an email shortly with a confirmation that your extensions has been made available in the http://www.mulesoft.org/[MuleSoft.org] site.
