[IMPORTANT]
It is required the use of Maven 3.x

= Using the Archetype

The DevKit provides a Maven Archetype to simplify the creation of Mule extensions. Running the archetype will set up a new Maven project with all the necessary dependencies to create a custom Module. It will also create a proper directory structure and class skeletons to quickly start coding.

The archetype's group id, artifact id and version are: 

[width="80",cols="50,50",options="header"]
|===
|Parameter |Value
|archetypeGroupId |org.mule.tools.devkit
|archetypeArtifactId |mule-devkit-archetype-generic 
|archetypeVersion |3.2 
|===

In order for the archetype to set up the new project correctly, the following properties have to set:

[width="80",cols="50,50",options="header"]
|===
|Parameter |Description
|groupId |The group id of the new project.
|artifactId |The artifact id of the new project
|version |The version of the new project.
|muleVersion |The Mule version for which this Cloud Connector been developed.
|muleModuleName |The name of the Module in camel case with first letter capitalized.
|muleModulePackage |The base package of the project. For example: com.mycompany
|===

*IMPORTANT*: It is required to use Maven 3.x

== Example

The following command is an example of how to create a custom Module project:

[source, code, linenums]
----
  mvn archetype:generate -DarchetypeGroupId=org.mule.tools.devkit \ -DarchetypeArtifactId=mule-devkit-archetype-generic -DarchetypeVersion=3.2 \-DarchetypeRepository=http://repository.mulesoft.org/releases/ \ -DgroupId=com.mycompany -DartifactId=cool-module -Dversion=1.0-SNAPSHOT \-DmuleVersion=3.2.1 -DmuleModuleName=CoolExtension \-Dpackage=com.mycompany.coolextension \-DarchetypeRepository=http://repository.mulesoft.org/releases
----
