[IMPORTANT]
It is required the use of Maven 3.x

= Using the Archetype

The DevKit provides a Maven Archetype to simplify the creation of Mule extensions. Running the archetype will set up a new Maven project with all the necessary dependencies to create a custom Cloud Connector. It will also create a proper directory structure and class skeletons to quickly start coding.

The archetype's group id, artifact id and version are: 

[width="80",cols="50,50",options="header"]
|===
|Parameter |Value
|archetypeGroupId |org.mule.tools.devkit
|archetypeArtifactId |mule-devkit-archetype-cloud-connector
|archetypeVersion |3.2 
|===

In order for the archetype to set up the new project correctly, the following properties have to set:

[width="80",cols="50,50",options="header"]
|===
|Parameter |Description
|groupId |The group id of the new project.
|artifactId |The artifact id of the new project
|version |The version of the new project.
|muleVersion |The Mule version for which this Cloud Connector been developed.
|muleConnectorName |The name of the Cloud Connector in camel case with first letter capitalized.
|muleConnectorPackage |The base package of the project. For example: com.mycompany
|===

== Example

The following command is an example of how to create a custom Cloud Connector project:

[source, code, linenums]
----
 mvn archetype:generate -DarchetypeGroupId=org.mule.tools.devkit \-DarchetypeArtifactId=mule-devkit-archetype-cloud-connector -DarchetypeVersion=3.2 \-DgroupId=com.mycompany -DartifactId=cool-connector -Dversion=1.0-SNAPSHOT \-DmuleVersion=3.2.1 -DmuleConnectorName=CoolAPI \-Dpackage=com.mycompany.coolapi \-DarchetypeRepository=http://repository.mulesoft.org/releases
----
