= Anypoint MQ Release Notes
:keywords: mq, release, notes

This is the first release of Anypoint MQ, MuleSoft’s cloud and enterprise messaging service.  This release you perform advanced asynchronous messaging scenarios between your applications and is fully integrated with Anypoint Platform, offering role based access control, client application management, and connectors.

This release includes the following capabilities:

* Queues and Exchanges: Send messages to queues, pull messages from queues, create a message exchange to perform pub/sub scenarios and send a message to multiple queues. Management console: monitor queue statistics, purge queues, and see how many messages are in flight via the management console.

* Anypoint MQ connector: Send/receive messages from any Mule application, whether it’s deployed in CloudHub or used in a hybrid scenario and deployed on-premises.

* Client management: Create client applications tokens

* Large payloads: Anypoint MQ supports payloads up to 10 MB in size.

* Disaster recovery and multi-data center availability: Anypoint MQ provides persistent data storage across multiple data centers, ensuring that it can handle data center outages and have full disaster recovery.

* Encrypted queues: Queue data can optionally be encrypted, ensuring that companies can be compliant with their data at rest policies.

== Compatibility

[width="100%",cols="50a,50a",options="header"]
|===
|Software|Version
|Mule Runtime |3.7.n
|Anypoint Studio |5.3.n
|===

== Known Issues

* If you are using Anypoint Platform for the first time and no environment is defined, the platform displays help information for how to create an environment. After viewing the help information, click your browser's refresh button to exit. Do not click the browser's back button as this displays a white screen.
* Queues created with the same name as a deleted queue or with different attributes are currently not supported.
* Queue or exchange names containing a dot are currently not supported.
* Anypoint MQ is not currently supported for use with Internet Explorer 11.

== See Also

* link:/anypoint-mq[Anypoint MQ]
* link:/anypoint-mq/mq-tutorial[Tutorial]
* link:/anypoint-mq/mq-access-management[Set user or role MQ access permission]
* link:/anypoint-mq/mq-studio[Create app in Studio]
* link:/anypoint-mq/mq-queues-and-exchanges[Create destinations or register client apps]
* link:/anypoint-mq/mq-understanding[Understand MQ concepts]
