= Anypoint MQ Release Notes
:keywords: mq, release, notes

This is the first beta release of Anypoint MQ, MuleSoft’s cloud, enterprise messaging service.  It is designed to enable customers to perform advanced asynchronous messaging scenarios between their applications and is fully integrated with Anypoint Platform, offering role based access control, client application management, and connectors.

This release includes the following capabilities:

* Queues and Exchanges: Send messages to queues, pull messages from queues, create a message exchange to perform pub/sub scenarios and send a message to multiple queues. Management console: monitor queue statistics, purge queues, and see how many messages are in flight via the management console.

* Anypoint MQ connector: Send/receive messages from any Mule application, whether it’s deployed in CloudHub or used in a hybrid scenario and deployed on-premises.

* Client management: Create client applications tokens

* Large payloads: Anypoint MQ supports payloads up to 10 MB in size.

* Disaster recovery and multi-data center availability: Anypoint MQ provides persistent data storage across multiple data centers, ensuring that it can handle data center outages and have full disaster recovery.

* Encrypted queues: Queue data can optionally be encrypted, ensuring that companies can be compliant with their data at rest policies.

== Compatibility

[width="100%",cols="50a,50a",options="header"]
|===
|Software|Version
|Mule Runtime |3.7.n
|Anypoint Studio |5.3.n
|===
