= Hardware and Software Requirements
:keywords: esb, mule, requirements, os, jdk, installation

This page lists the hardware, operating systems, Java, and other requirements to run Mule ESB, API Gateway, Mule Management Console, Anypoint Studio, and Anypoint Studio as Eclipse Plug-in.

== Mule ESB

[cols=",",options="header"]
|===
2+|*Hardware Requirements:* footnote:[This hardware requirements list is a recommendation and a starting point. Different applications have different requirements for the amount of latency (and thus raw CPU power) or the size and number of simultaneous messages that applications need to process (which in turn determines the amount of RAM Mule needs).]
|
a|* 2GHz, dual-core CPU, or 2 virtual CPUs in virtualized environments
* 2GB of RAM
* 4GB of storage
2+|*Software Requirements* footnote:[Because the only mandatory requirement for Mule ESB is Java, Mule ESB should also run on any later versions of the tested operating systems in the above list, as well as any other operating systems supported by the JREs.]
|*Java Runtime Environments*
a|

* Oracle JRE 1.8
* Oracle JRE 1.7.0 (recommended: JRE 1.7.0_79/80)
* IBM version 1.7

|*Operating Systems*
a|Mule validates against the following operating systems. 

* MacOS 10.10.0
* HP-UX 11i V3
* AIX 7.1
* Windows 2012 R2 Server
* Windows 8.1
* Solaris 11.2
* RHEL 7.0
* Ubuntu Server 14.04
|===

== API Gateway

[cols=",",options="header"]
|===
2+|*Hardware Requirements:* footnote:[This hardware requirements list is a recommendation and a starting point. Different applications have different requirements for the amount of latency (and thus raw CPU power) or the size and number of simultaneous messages that applications need to process (which in turn determines the amount of RAM Mule needs).]
|
a|* 2GHz, dual-core CPU, or 2 virtual CPUs in virtualized environments
* 2GB of RAM
* 4GB of storage
2+|*Software Requirements:* footnote:[Because the only mandatory requirement for the API Gateway is Java, the API Gateway should also run on any later versions of the tested operating systems in the above list, as well as any other operating systems supported by the JRE.]
|*Java Runtime Environments*
a|* API Gateway 1.3.n and earlier: Oracle JRE 1.7
* API Gateway 2.0.n and newer:
** Oracle JRE 1.8
** JRE 1.7.0 (recommended: JRE 1.7.0_79/80)
** IBM version 1.7
|*Operating Systems*
a|API Gateway validates against the following operating systems. 

API Gateway 2.0.n and newer:

* Mac OS 10.10.0
* HP-UX 11i V3
* AIX 7.1
* Windows 2012 R2 Server
* Windows 8.1
* Solaris 11.2
* RHEL 7
* Ubuntu Server 14.0.4

API Gateway 1.3.n and earlier:

The operating systems MuleSoft used to validate the current release are:

* Windows (32- and 64-bit) 2003, 2008, Windows 7, Windows 2012
* Mac OS 10.7, 10.8
* Linux RHEL (64-bit) 5.3, 6.1
* Ubuntu Server 12.04 (64-bit) footnote:[If you use SSL, MuleSoft recommends installing Ubuntu Server 12.14 (64-bit) and newer instead of 12.04.]
* Solaris OS 10
* HP-UX 11i V3
* AIX V7.1
|===

== Mule Management Console (MMC)

[cols=",",options="header"]
|===
2+|*Hardware Requirements:* footnote:[We strongly recommend running MMC on a separate server from the hardware that runs Mule Runtime.]
|
a|* 2GHz CPU
* 4 GB of RAM
* 10 GB of storage
2+|*Software Requirements:*
|*Java Runtime Environments*
a|* Mule 3.7: Oracle Java 1.7 and Oracle Java 1.8

* Mule 3.6: Oracle Java 1.7
|*Web Application Servers*
a|* JBoss 6 or 6.1
* Tomcat 6.x or 7.x
* Tcat 6.x or 7.x
* WebSphere Application Server 7.0 and 8.0
|*Operating Systems*
|MMC runs the operating systems supported by the above web application servers.
|*Browsers*
a|* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
* Internet Explorer 9 or later
|===

=== Compatible Databases for Persisting Data

* link:/mule-management-console/v/3.7/persisting-mmc-data-to-oracle[Oracle]
* link:/mule-management-console/v/3.7/persisting-mmc-data-to-postgresql[Postgres ]
* link:/mule-management-console/v/3.7/persisting-mmc-data-to-mysql[MySQL]
* link:/mule-management-console/v/3.7/persisting-mmc-data-to-ms-sql-server[MS SQL Server]

=== Run MMC as a Web Application

Mule Management Console should be run as a web application deployed on a web container such as JBoss or Tomcat, and NOT as a Mule application. We recommend configuring the web application server's memory areas with the following minimum sizes:

*  Heap: 2GB (3GB recommended) 
*  Permanent Generation: 512MB

== Anypoint Studio

[cols=",",options="header"]
|===
2+|*Hardware Requirements:*
|
a|* 3GB of RAM
* 2GHz CPU
* 4GB free hard drive space
2+|*Software Requirements:*
|*Java Environments*
a|
* Oracle JDK 1.8
* Oracle JDK 1.7.0 (recommended: JDK 1.7.0_79/80)
* IBM version 1.7

|*Operating Systems*

a|June 2015 and newer:

* MacOS 10.10.0
* HP-UX 11i V3
* AIX 7.1
* Windows 2012 R2 Server
* Windows 8.1
* Solaris 11.2
* RHEL 7.0
* Ubuntu Server 14.04

March 2015 and earlier:

* Windows (32- and 64-bit) Windows 7, Windows 8
* Mac OS (32- or 64-bit) 
* Linux (32- or 64-bit) 
|===

== Anypoint Studio as Eclipse Plug-in

[cols=",",options="header"]
|===
2+|*Hardware Requirements:*
|
a|* 3GB of RAM
* 2GHz CPU
* 4GB free hard drive space

2+|*Software Requirements:*

|*Eclipse*

a|* Eclipse 4.4.2 for Java Developers or Java EE Developers
* Spring Tool Suite (STS) versions that run on top of Eclipse 4.4.2

|*Java Runtime Environments*

a|* Studio June 2015 and newer: Oracle JDK 1.7 or Oracle JDK 1.8

* Studio March 2015: Oracle JDK 1.7

|*Operating Systems*

a|* Windows (32- or 64-bit) Windows 7, Windows 8
* Mac OS (32- or 64-bit) 
* Linux (32- or 64-bit) 
|===

Get more information about installing link:/mule-user-guide/v/3.7/studio-in-eclipse[Studio as an Eclipse plug-in].

== See Also

* Find out what platform software is link:/mule-user-guide/v/3.7/compatibility[compatible] with the current version of Mule ESB.
* Learn how to link:/docs/display/current/Downloading+and+Installing+Mule+ESB[download, install, and launch] Mule ESB.
* Learn more about installing an link:/mule-user-guide/v/3.7/installing-an-enterprise-license[Enterprise license].
* link:/mule-fundamentals/v/3.7/first-30-minutes-with-mule[Get started] with Anypoint Studio.
