= Including the DataMapper Plugin
:keywords: datamapper, migration

DataMapper is deprecated as of Mule runtime 3.7.0 and superseded by link:/mule-user-guide/v/3.7/using-dataweave-in-studio[DataWeave]. 

[WARNING]
DataMapper will continue to be fully supported in all current and future versions of Mule ESB 3.x, however it will be removed in Mule 4.0. We recommend that if you wish to take advantage of the new capabilities of DataWeave or if you start new projects, upgrade now. However, if you have no pressing need to take advantage of new functionality, we recommend you wait until Mule 4.0 is released.

If you want to deploy a Mule project that containst a DataMapper transformer in it, consider the following:

* When deploying through Anypoint Studio, it should still work normally
* When deploying to CloudHub, it should also work out of the box
* However, when using for Mule ESB Standalone 3.7.0, you must do the following before you can deploy your application: +

. Go to the customer portal
. Select the Downloads tab
. Download the DataMapper plugin
. Place the downloaded .zip file in the `/plugins` folder of Mule-Enterprise Standalone
