= MUnit
:keywords: mule, esb, tests, qa, quality assurance, verify, functional testing, unit testing, stress testing

== Overview

MUnit is a Mule testing framework which allows Mule developers to easily automate testing. It is an open-source project, created originally as a side project in Mule.

Currently, MUnit is not officially supported in Mule; however, it is fully used by several companies and in internal Mule projects.

With MUnit you can:

* Create your Mule test by writing Mule code
* Create your Mule test by writing Java code
* Disable flow inbound endpoints
* Disable endpoint connectors
* Mock outbound endpoints
* Mock message processors
* Spy any message processor
* Verify message processor calls
* Create not only unit tests but also integration tests in a local environment — MUnit allows you to start a local FTP/SFTP, DB server or mail server
* Call the Mule client from Mule code
* Assert flow exceptions
* Enable or disable particular tests
* See assertion/error reports with Mule stack trace
* Extend the MUnit framework with plugins
* Check visual coverage in Studio
* Debug your tests with Studio

== MUnit Versions

The current release of MUnit, 1.0-RC, includes some important changes from the earlier Beta version.

For an overview of the changes in syntax, see link:/docs/display/current/MUnit+1.0-RC+Migration+Guide[MUnit 1.0-RC Migration Guide]. For a list of bug fixes and new features, see the link:/docs/display/current/MUnit+1.0-RC+Release+Notes[MUnit 1.0-RC Release Notes].

== MUnit and Anypoint Studio

MUnit is fully integrated with Mule Studio, Maven and Surefire, so you can add your tests to a continuous integration environment.

This sets MUnit apart from the current Mule testing framework (MuleFunctionalTestCase), where this functionality is not possible.

Within the Studio environment, you can create, design and run MUnit tests just like you would Mule applications. You can even use Studio's link:/docs/display/current/Studio+Visual+Debugger[Visual Debugger] to debug your MUnit tests.

For an overview of MUnit in Studio, see link:/docs/display/current/Using+MUnit+in+Anypoint+Studio[Using MUnit in Anypoint Studio].

== What You'll Find in These Docs

The pages listed below provide an overview of MUnit features including simple examples. Topics include the MUnit message processors, the DB and FTP servers provided by MUnit, Maven support and more. For a short step-by-step guide to creating a test, see the link:/docs/display/current/MUnit+Short+Tutorial[MUnit Tutorial].

[TIP]
The examples you'll find in these pages are XML-only; however, as stated above, you can also use MUnit via Anypoint Studio's graphical interface. See link:/docs/display/current/Using+MUnit+in+Anypoint+Studio[Using MUnit in Anypoint Studio] for details.

* link:/docs/display/current/Using+MUnit+in+Anypoint+Studio[Using MUnit in Anypoint Studio]
* link:/docs/display/current/The+MUnit+Suite[The MUnit Suite]
* link:/docs/display/current/The+Mock+Message+Processor[The Mock Message Processor]
* link:/docs/display/current/The+Verify+Message+Processor[The Verify Message Processor]
* link:/docs/display/current/The+Set+Message+Processor[The Set Message Processor]
* link:/docs/display/current/The+Spy+Message+Processor[The Spy Message Processor]
* link:/docs/display/current/The+Assertion+Message+Processor[The Assertion Message Processor]
* link:/docs/display/current/MUnit+Matchers[MUnit Matchers]
* link:/docs/display/current/MUnit+Database+Server[MUnit Database Server]
* link:/docs/display/current/MUnit+FTP+Server[MUnit FTP Server]
* link:/docs/display/current/MUnit+Maven+Support[MUnit Maven Support]
* link:/docs/display/current/MUnit+Short+Tutorial[MUnit Short Tutorial]
* link:/docs/display/current/Example%3A+Testing+APIKit[Example: Testing APIKit]
* link:/docs/display/current/MUnit+1.0-RC+Migration+Guide[MUnit 1.0-RC Migration Guide]
