= Object Store Module
:keywords: anypoint studio, object store, persist data


The Object Store Module allows you to manipulate object stores within Mule. It can access custom object stores, or the defaults in-memory and persistent object stores. It allows you to store, retrieve and remove objects from the store.
Components in your XML flows can be used with the Mule default implementations or they can reference a custom global configuration element via a `ref` attribute.

[NOTE]
Components in the object store module can be added in Anypoint Studio via the XML editor, they are not currently available or configurable via the Studio GUI.

[width="100%",cols="50%,50%,options="header"]
|===
Namespace |	http://www.mulesoft.org/schema/mule/objectstore
|
Schema Location |	link:http://www.mulesoft.org/schema/mule/objectstore/current/mule-objectstore.xsd[www.mulesoft.org/schema/mule/objectstore/current/mule-objectstore.xsd] |
Schema Version	| 1.0
| Minimum Mule Version |	3.6
|===

== Configuration

To use the this module within a flow, the namespace must include the module as a dependency. The resulting flow will look similar to the following:

[source, xml, linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:objectstore="http://www.mulesoft.org/schema/mule/objectstore"
      xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/core
               http://www.mulesoft.org/schema/mule/core/current/mule.xsd
               http://www.mulesoft.org/schema/mule/objectstore
               http://www.mulesoft.org/schema/mule/objectstore/current/mule-objectstore.xsd">

      <!-- here go your flows and configuration elements -->

</mule>
----


== XML components in the Object Store Module

[width="100%",cols="50%,50%,options="header"]
|===
`<objectstore:config>` |
Configure an instance of this module
| `<objectstore:all-keys>` |
Returns a list of all the keys in the object store.
| `<objectstore:contains>` |
Checks whether the object store contains the given key.
| `<objectstore:dual-store>` |
Stores a value using key, and also store key using value.
| `<objectstore:remove>` |
Remove the object for the respective key.
| `<objectstore:retrieve>` |
Retrieve an object from the object store and make it available in the specified property scope of a Mule Message.
| `<objectstore:retrieve-store>` |
Retrieve and Store in the same operation.
| `<objectstore:retrieve-with-lock>` |
Retrieve the given object with lock from the object store and make it available in the specified property scope of a Mule Message.
| `<objectstore:store>` |
Stores an object in the object store.
|===

=== <objectstore:all-keys>

Returns a list of all the keys in the object store.

[NOTE]
Not all stores support this method. If the method is not supported, a `java.lang.UnsupportedOperationException` is thrown.

==== XML Sample

[source, xml, linenums]
----
<objectstore:all-keys config-ref="config-name"/>
----

==== Attributes

[width="100%",cols="50%,50%,options="header"]
|===
Name	| Description	|
config-ref |		Optional. Specify which configuration to use.
|===

==== Returns

[width="100%",cols="50%,50%,options="header"]
|===
Return Type	| Description |
List<String> |		a java.util.List with all the keys in the store.
|===

=== <objectstore:contains>

Checks whether the object store contains the given key.

==== XML Sample

[source, xml, linenums]
----
<objectstore:contains key="mykey" config-ref="config-name"/>
----

==== Attributes

[width="100%",cols="20%,20%,20%,20%,20%,20%,options="header"]
|===
Name |	Default Value |	Description |	Java Type |	MIME Type | Encoding |
config-ref |	|	Optional. Specify which configuration to use.||||
key | | The identifier of the object to validate.| String |	*/* |	UTF-8
|===

==== Returns

[width="100%",cols="50%,50%,options="header"]
|===
Return Type	| Description |
boolean |	true if the object store contains the key, or false if it doesn't.
|===

=== <objectstore:dual-store>

Stores a value using a key, and also stores a key using a value. If an exception is thrown, it rolls back both operations. This allows an option to indicate if the key would be overwritten or not.

==== XML Sample

[source, xml, linenums]
----
<objectstore:dual-store key="mykey" value-ref="#[payload]" config-ref="config-name"/>
----

==== Attributes

[width="100%",cols="20%,20%,20%,20%,20%,20%,options="header"]
|===
Name |	Default Value |	Description |	Java Type |	MIME Type | Encoding |
config-ref |	|	Optional. Specify which configuration to use.||||
key | | The identifier of the object store| String |	*/* |	UTF-8|
value | | The object to store. If you want this to be the payload, then use value-ref="#[payload]".| Serializable |	*/* ||
overwrite| `False` | True if you want to overwrite the existing object. | boolean| 	*/* |
|===


=== <objectstore:remove>

Remove the object for the respective key. This operation can fail silently based on the value passed in ignoreNotExists.

==== XML Sample

[source, xml, linenums]
----
<objectstore:remove key="mykey" config-ref="config-name"/>
----

==== Attributes

[width="100%",cols="20%,20%,20%,20%,20%,20%,options="header"]
|===
Name |	Default Value |	Description |	Java Type |	MIME Type | Encoding |
config-ref |	|	Optional. Specify which configuration to use.||||
key | | The identifier of the object to remove.| String |	*/* |	UTF-8|
The identifier of the object to remove.| `False` | Indicates if the operation will ignore NotExistsException from ObjectStore. | boolean| 	*/* |
|===

==== Returns

[width="100%",cols="50%,50%,options="header"]
|===
Return Type	| Description |
Object |	The object that was previously stored for the given key. If the key does not exist and `ignoreNotExists` is true, the operation will return a null object.
|===

=== <objectstore:retrieve>

Retrieve an object from the object store and make it available in the specified property scope of a Mule Message.

==== XML Sample

[source, xml, linenums]
----
<objectstore:retrieve key="mykey" defaultValue-ref="#[string:myValue]" config-ref="config-name"/>
----

==== Attributes

[width="100%",cols="20%,20%,20%,20%,20%,20%,options="header"]
|===
Name |	Default Value |	Description |	Java Type |	MIME Type | Encoding |
config-ref |	|	Optional. Specify which configuration to use.||||
key | | The identifier of the object to retrieve.| String |	*/* |	UTF-8|

defaultValue | | 	Optional. The default value if the key does not exist.| Object| */*||
targetProperty| |Optional. The Mule Message property where the retrieved value will be stored 	|String| 	*/*| 	UTF-8|
targetScope| 	INVOCATION| 	The Mule Message property scope, only used when targetProperty is specified |	MulePropertyScope| 	*/*| |
muleMessage |		|Injected Mule Message|MuleMessage| */*|

|===

==== Returns

[width="100%",cols="50%,50%,options="header"]
|===
Return Type	| Description |
Object | The object associated with the given key. If no object for the given key was found this method throws an org.mule.api.store.ObjectDoesNotExistException.
|===


=== <objectstore:retriev-storee>

Retrieve and Store in one single operation.

==== XML Sample

[source, xml, linenums]
----
<objectstore:retrieve-store key="mykey" defaultValue-ref="#[string:myValue]" storeValue-ref="#[string:myValue]" config-ref="config-name"/>
----

==== Attributes

[width="100%",cols="20%,20%,20%,20%,20%,20%,options="header"]
|===
Name |	Default Value |	Description |	Java Type |	MIME Type | Encoding |
config-ref |	|	Optional. Specify which configuration to use.||||
key | | The identifier of the object to retrieve.| String |	*/* |	UTF-8|
defaultValue | | 	Optional. The default value if the key does not exist.| Object| */*||
storeValue | |	The object to store. If you want this to be the payload then use value-ref="#[payload]". |	Serializable | 	*/* | |
targetProperty| |Optional. The Mule Message property where the retrieved value will be stored 	|String| 	*/*| 	UTF-8|
targetScope| 	INVOCATION| 	The Mule Message property scope, only used when targetProperty is specified |	MulePropertyScope| 	*/*| |
muleMessage |		|Injected Mule Message|MuleMessage| */*|

|===

==== Returns

[width="100%",cols="50%,50%,options="header"]
|===
Return Type	| Description |
Object |  	The object associated with the given key. If no object for the given key was found this method returns the defaultValue
|===

=== <objectstore:retriev-retrieve-with-lock>

Retrieve the given object with lock from the object store and make it available in the specified property scope of a Mule Message.

==== XML Sample

[source, xml, linenums]
----
<objectstore:retrieve-with-lock key="mykey" defaultValue-ref="#[string:myValue]" config-ref="config-name"/>
----

==== Attributes

[width="100%",cols="20%,20%,20%,20%,20%,20%,options="header"]
|===
Name |	Default Value |	Description |	Java Type |	MIME Type | Encoding |
config-ref |	|	Optional. Specify which configuration to use.||||
key | | The identifier of the object to retrieve.| String |	*/* |	UTF-8|
defaultValue | | 	Optional. The default value if the key does not exist.| Object| */*||
targetProperty| |Optional. The Mule Message property where the retrieved value will be stored 	|String| 	*/*| 	UTF-8|
targetScope| 	INVOCATION| 	The Mule Message property scope, only used when targetProperty is specified |	MulePropertyScope| 	*/*| |
muleMessage |		|Injected Mule Message|MuleMessage| */*|

|===

==== Returns

[width="100%",cols="50%,50%,options="header"]
|===
Return Type	| Description |
Object |  The object associated with the given key. If no object for the given key was found this method throws an org.mule.api.store.ObjectDoesNotExistException.
|===

=== <objectstore:store>

Stores an object in the object store. This allows an option to indicate if key would be overwritten or not.

==== XML Sample

[source, xml, linenums]
----
<objectstore:store key="mykey" value-ref="#[payload]" config-ref="config-name"/>
----

==== Attributes

[width="100%",cols="20%,20%,20%,20%,20%,20%,options="header"]
|===
Name |	Default Value |	Description |	Java Type |	MIME Type | Encoding |
config-ref |	|	Optional. Specify which configuration to use.||||
key | | The identifier of the object to store.| String |	*/* |	UTF-8|
value | | 	The object to store. If you want this to be the payload then use value-ref="#[payload]".| Serializable| */*||
overwrite| False |True if you want to overwrite the existing object.	|Boolean| 	*/*| |
|===


== See Also

* link:/mule-user-guide/v/3.7/mule-object-stores[Mule Object Stores]
* link:/cloudhub/managing-application-data-with-object-stores[Managing Application Data Storage with Object Stores]
