= Persisting MMC Data On External Databases

By default, the Mule Management Console stores its persistent data on an embedded database on the local host. In this scenario, a catastrophic failure of the host would cause the loss of all data. You can avoid this situation by configuring MMC to store data on an external database, which ideally would reside on a dedicated server.

There are two kinds of data that MMC can store on external databases:

* *Environment data*, such as created alerts, deployments, dashboard portlets configuration
* *Transaction data* (Business Events)

You can configure MMC to store its data on the following database servers:

* link:/mule-management-console/v/3.4/persisting-mmc-data-to-postgresql[PostgreSQL]
* link:/mule-management-console/v/3.4/persisting-mmc-data-to-oracle[Oracle]
* link:/mule-management-console/v/3.4/persisting-mmc-data-to-mysql[MySQL]
* link:/mule-management-console/v/3.4/persisting-mmc-data-to-ms-sql-server[MS SQL Server] _(MMC version 3.4.1 or later only)_

Click the links above for details on setting up MMC to work with each of the listed database servers.
