= Server Groups

== About This Document

This document, as well as the rest of the documents that make up the link:/mule-management-console/v/3.4/rest-api-reference[Mule Management Console REST API Reference Guide], are a technical reference only. This document does not provide contextual information such as instructions, use cases, or scenarios. To understand this document, you should be familiar with link:/documentation/display/MULE3USER/Home[MULE ESB], Server Groups, and the link:/mule-management-console/v/3.4/using-the-management-console-api[REST API]



[width="100%",cols=","]
|===
|*Assumptions:* |*Host* |localhost | |*Port* |8080 | |*Deployed app* |mmc.war | |*User/Password* |admin/admin
|===

For a detailed description of the format used in this document, consult link:/mule-management-console/v/3.4/rest-api-reference[Content Organization and Conventions].

[source, code, linenums]
----
/api/serverGroups
----

[width="100%",cols=","]
|===
|*POST* | |*CREATE*
| | |
|===

Creates a new Server Group.

[tabs]
------
[tab,title="-> Request"]
....
== JSON

[source, code, linenums]
----

{
  "name": "NewGroupName"
}
----

[width="100%",cols=",",options="header"]
|===
|Key |Type |Summary |Child of
|name |string |Name of the Server Group to be created |--
|===

=== Using CURL on Windows

[source, code, linenums]
----
curl --basic -u admin:admin -d "{ \"name\" : \"NewGroupName\" }" --header "Content-Type: application/json" http://localhost:8080/mmc/api/serverGroups
----

=== Using CURL on Linux

[source, code, linenums]
----
curl --basic -u admin:admin -d '{ "name" : "NewGroupName" }" --header 'Content-Type: application/json' http://localhost:8080/mmc/api/serverGroups
----
....
[tab,title=" <- Response"]
....
== JSON

[source, code, linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[width="100%",cols=",",options="header"]
|===
|Key |Type |Summary |Child of
|name |String |Name of the created Server Group |--
|id |String |MMC ID for the Server Group |--
|serverCount |String |Number of servers assigned to the Server Group |--
|href |String |Full link to the Server Group resource on which you can perform an operation |--
|===
....
[tab,title="⬇️ Common Return codes"]
....
[width="100%",cols=","]
|===
|*201* |The request has been fulfilled and resulted in a new Server Group being created.
|*409* |A server group with that name already exists
|*500* |Error while creating a Server Group
|===
....
[tab,title="MMC version"]
....
[width="100%",cols=","]
|===
|*From* |3.2.2
|===
....
------

[width="100%",cols=","]
|===
|*GET* | |*LIST ALL*
| | |
|===

List all available Server Groups.

[tabs]
------
[tab,title="-> Request"]
....
== Using CURL

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/serverGroups
----
....
[tab,title=" <- Response"]
....
== JSON

[source, code, linenums]
----
{
  "total": 1,
  "data": [
    {
      "name": "NewGroupName",
      "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
      "serverCount": 0,
      "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
    }
  ]
}
----

[width="100%",cols=",",options="header"]
|===
|Key |Type |Summary |Child of
|total |Integer |The total number of Server Groups |--
|data |Array |An array of server group types |--
|name |String |The identifying name of the server group |data
|id |String |The server group identifier |data
|serverCount |Integer |The number of servers in the server group |data
|href |String |Full link to the Server Group resource to which you can perform an operation |data
|===
....
[tab,title="⬇️ Common Return codes"]
....
[width="100%",cols=","]
|===
*200* |The operation was successful
|===
....
[tab,title="MMC version"]
....
[width="100%",cols=","]
|===
|*From* |3.2.2
|===
....
------

[source, code, linenums]
----
/api/serverGroups/{serverGroupId}
----

[width="100%",cols=","]
|===
|*GET* | |*LIST*
| | |
|===

List details for specific Server Group.

[tabs]
------
[tab,title="-> Request"]
....
== SYNTAX

[source, code, linenums]
----
GET http://localhost:8080/mmc/api/serverGroups/{serverGroupId}
----

[width="100%",cols=",",options="header"]
|===
|Key |Type |Summary |Child of
|serverGroupdId |String |ID of the server group to be listed. Invoke link:/mule-management-console/v/3.4/server-groups[LIST ALL] to obtain it |--
|===

== Using CURL

[source, code, linenums]
----
curl --basic -u admin:admin http://localhost:8080/mmc/api/serverGroups/37f6cd27-98b3-44b1-97e6-50b75e47f8c1
----
....
[tab,title=" <- Response"]
....
== JSON

[source, code, linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[width="100%",cols=",",options="header"]
|===
|Key |Type |Summary |Child of
|name |String | |--
|id |String |Id of the Server Group |--
|serverCount |Number of servers belonging to the Server Group | |--
|href |String |Full link to the Server Group resource |--
|===
....
[tab,title="⬇️ Common Return codes"]
....
[width="100%",cols=","]
|===
|*200* |The operation was successful
|*404* |A server with that ID was not found
|===
....
[tab,title="MMC version"]
....
[width="100%",cols=","]
|===
|*From* |3.2.2
|===
....
------

[width="100%",cols=","]
|===
|*PUT* | |*RENAME*
| | |
|===

Renames a specific Server Group.

[tabs]
------
[tab,title="-> Request"]
....
== JSON

[source, code, linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[width="100%",cols=",",options="header"]
|===
|Key |Type |Summary |Child of
|name |String |Name of the Server Group to be created |--
|id |String |MMC ID of the Server Group |--
|serverCount |String |Number of servers assigned to the Server Group |--
|href |String |Full link to the Server Group resource on which you can perform an operation |--
|===

=== Using CURL on Windows

[source, code, linenums]
----
curl --basic -u admin:admin -X PUT -d "{\"name\":\"NewName\",\"id\":\"330d9139-4462-4e36-b76c-569776cc3da9\",\"href\": \"http://localhost:8080/mmc/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9\",\"serverCount\":0}" --header "Content-Type:application/json" http://localhost:8080/mmc/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9
----

=== Using CURL on Linux

[source, code, linenums]
----
curl --basic -u admin:admin -X PUT -d '{"name":"NewName","id":"330d9139-4462-4e36-b76c-569776cc3da9","href": "http://localhost:8080/mmc/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9","serverCount":0}' --header 'Content-Type:application/json' http://localhost:8080/mmc/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9
----
....
[tab,title=" <- Response"]
....
== JSON

[source, code, linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[width="100%",cols=",",options="header"]
|===
|Key |Type |Summary |Child of
|name |String |Name of the Server Group to be created |--
|id |String |MMC ID of the Server Group |--
|serverCount |String |Number of servers assigned to the Server Group |--
|href |String |Full link to the Server Group resource on which you can perform an operation |--
|===
....
[tab,title="⬇️ Common Return codes"]
....
[width="100%",cols=",",options="header"]
|===
|*200* |The operation was successful
|*500* |Error while renaming a Server Group
|===
....
[tab,title="MMC version"]
....
[width="100%",cols=","]
|===
|*From* |3.2.2
|===
....
------

[width="100%",cols=","]
|===
|*DELETE* | |*REMOVE*
| | |
|===

Removes a specific server group

[tabs]
------
[tab,title="-> Request"]
....
== SYNTAX

[source, code, linenums]
----
DELETE http://localhost:8080/mmc/api/serverGroups/{serverGroupId}
----

[width="100%",cols=",",options="header"]
|===
|Key |Type |Summary |Child of
|serverGroupdId |String |ID of the server group to be listed. Invoke link:/mule-management-console/v/3.4/server-groups[LIST ALL] to obtain it |--
|===

== Using CURL

[source, code, linenums]
----
curl --basic -u admin:admin -X DELETE http://localhost:8080/mmc/api/serverGroups/37f6cd27-98b3-44b1-97e6-50b75e47f8c1
----
....
[tab,title=" <- Response"]
....
== JSON

[source, code, linenums]
----
200 OK
----
....
[tab,title="⬇️ Common Return codes"]
....
[width="100%",cols=","]
|===
|*200* |The operation was successful
|===
....
[tab,title="MMC version"]
....
[width="100%",cols=","]
|===
|*From* |3.2.2
|===
....
------
