= Upgrading to MMC 3.4.2 with an External Database

*_Enterprise_*

*_MMC Version 3.4.2 and Later_*

== Overview

In version 3.4.2 of the Mule Management Console, the process for link:/mule-management-console/v/3.4/persisting-mmc-data-on-external-databases-in-mmc-3.4.2[persisting MMC data on external databases] has been greatly simplified. The configuration files employed for data persistence have changed, so if you are upgrading to MMC 3.4.2 from a previous version, you will need to migrate your data persistence configuration to the new and simpler configuration files.

Note that you do not need to migrate your database configuration if you are using MMC's default internal databases for data persistence. You are only required to migrate your database configuration if you are persisting MMC environment or tracking data to an external database.

[NOTE]
If your current installation of MMC link:/mule-management-console/v/3.4/persisting-mmc-data-on-external-databases-in-mmc-3.4.2[manages users via LDAP], you will also need to migrate your LDAP configuration. See link:/mule-management-console/v/3.4/upgrading-to-mmc-3.4.2-with-ldap[Upgrading to MMC 3.4.2 with LDAP] for details.

== Assumptions

You have MMC 3.4.1 or earlier installed and configured to persist its environment and/or transaction data to an external database, and are about to link:/mule-management-console/v/3.4/installing-or-upgrading-mule-management-console-3.4.2[upgrade MMC to version 3.4.2].

== Persisting Environment Data

In MMC versions 3.4.1 and earlier, the configuration for persisting environment data on an external database is stored in the following files:

* `<MMC_HOME>/WEB-INF/classes/META-INF/mmc.properties`
* `<MMC_HOME>/WEB-INF/classes/META-INF/jackrabbit-repo.xml`

These files store connection parameters to the external database such as username, password, etc. You will need to adapt these parameters to the new config files, so ensure that you keep a copy of these files before removing your current MMC installation.

Also, for safety, back up your current MMC installation's `mmc-data` directory, which is under the root directory of your Web application server.

After you downloaded and expanded the .war file for 3.4.2, enter your MMC 3.4.2 home directory (the root directory of the expanded .war) and locate the following directory: `<MMC_HOME>/WEB-INF/classes/META-INF/databases`. This directory stores configuration files for database persistence. These files are named in the format: `<type of data>-<database name>.properties`, where:

* `type of data` = `mmc` for environment data, or `tracking-persistence` for transaction data
* `database name` = name of the database server to use, for example `postgres`

For example, the file `mmc-oracle.properties` stores properties for connecting to an Oracle database that stores environment data; the file `tracking-persistence-postgres.properties` stores properties for connecting to a Postgres database that stores tracking data, etc.

These files define the parameters for connecting to the database: driver, user, password, host, port, and others.

To migrate the configuration for persisting environment data, complete these steps:

. In MMC 3.4.2, locate the relevant `mmc-<database>.properties` file according to the database you wish to connect to, and open it for editing.
. In MMC 3.4.1, open the file `mmc.properties` to extract the relevant parameters and values.
. Using the parameters and values from `mmc.properties` in 3.4.1, modify the relevant `mmc-<database>.properties` file in 3.4.2, migrating the values to the new config format according to the table below.
+
[width="100%",cols=",",options="header"]
|===
|Parameter name in old MMC version |Parameter name in MMC 3.4.2 |Notes
|`datasource.username` |`env.username` | 
|`datasource.password` |`env.password` | 
|`datasource.url` |`env.host` a|
From the value of `datasource.url`, extract the host where your database server resides, and assign it as the value of `env.host` in the database config file in 3.4.2.

For example, if your database resides at host `dbserver`, from `datasource.url=jdbc:mysql://dbserver/mmc_persistency_status` extract `dbserver` to `env.host=dbserver` in the 3.4.2 config file.
|`datasource.url` |`env.port` a|
From the value of `datasource.url`, extract the port on which your database server is listening, and assign it as the value of `env.port` in the database config file in 3.4.2.

For example, if your database resides at host `dbserver` port 9155, from `datasource.url=jdbc:mysql://dbserver:9155/mmc_persistency_status` extract `9155` to `env.port=9155` in the 3.4.2 config file.

Note that if the port number is not present in the URL, it probably means that the default port for the database server is being used, for example 1521 for Oracle, 3306 for MySQL, etc.
|`datasource.url` |`env.servicename` (Oracle only.) a|
From the value of `datasource.url`, extract the Oracle service name for your connection, and assign it as the value of `env.servicename` in the database config file in 3.4.2.

For example, if the value of `datasource.url` in 3.4.1 is `jdbc\:oracle\:thin\:MMC_STATUS/mmc123``@dbserver``\:``1521``\:xe`, then the service name is `xe`. Assign it in the new config file with the parameter `env.servicename=xe`.
|===

. In the `jackrabbit-repo.xml` file from your old MMC installation, locate the definitions of the *workspace name* and the *default workspace name*. You can find them in the following section:
+
[source, xml, linenums]
----
<Workspaces rootPath="${rep.home}/workspaces" defaultWorkspace="mmcworkspace"/>
    <!--
        workspace configuration template:
        used to create the initial workspace if there's no workspace yet
    -->
    <Workspace name="mmcworkspace">
----
+
In the example above, both the workspace name and the default workspace name are `mmcworskpace`.

. In MMC 3.4.2, go to the `<MMC_HOME>/WEB-INF/classes/META-INF/jackrabbit` directory, then locate the jackrabbit-repo file relevant for your database, for example `jackrabbit-repo-postgres.xml` if persisting data on Postgres. Open the file for editing.
. Find the workspace name declaration in the 3.4.2 jackrabbit-repo file, and ensure that the *workspace name* and the *default workspace name* coincide between MMC versions 3.4.1 and 3.4.2. Save and close the jackrabbit-repo file.
. In MMC 3.4.2, locate the file `<MMC_HOME>/WEB-INF/web.xml` and open it for editing.
. In the `web.xml` file, locate the section shown below.
+
[source, xml, linenums]
----
<context-param>
<param-name>spring.profiles.active</param-name>
<param-value>tracking-h2,env-derby</param-value>
</context-param>
----

. Replace the string `env-derby` with `env-<database_name>`. For example, if persisting data on postgres, replace it with `env-postgres`.
. After completing the above steps, you can remove your old MMC installation by deleting its home directory in the root directory of your Web app server. However, it is recommended that you keep the backup copies of the old database configuration files until you ensure that MMC 3.4.2 connects properly to the database.

After you have completed configuration, start MMC 3.4.2.

== Persisting Transaction Data

In MMC versions 3.4.1 and earlier, the configuration for persisting transaction data (Business Events) on an external database is stored in the following files:

* `<MMC_HOME>/WEB-INF/classes/META-INF/persistence.xml`
* `<MMC_HOME>/WEB-INF/classes/mmc-persistence.properties`(if present on your installation)
* `<MMC_HOME>/WEB-INF/classes/META-INF/applicationContext-tracking.xml`

These files store connection parameters to the external database such as username, password, etc. You will need to adapt these parameters to the new config files, so ensure that you keep a copy of these files before removing your current MMC installation.

Also, for safety, back up your current MMC installation's `mmc-data` directory, which is under the root directory of your Web application server.

After you downloaded and expanded the .war file for 3.4.2, enter your MMC 3.4.2 home directory and locate the following directory: `<MMC_HOME/WEB-INF/classes/META-INF/databases`. This directory stores configuration files for database persistence. These files are named in the format: `<type of data>-<database name>.properties`, where:

* `type of data` = `mmc` for environment data, or `tracking-persistence` for transaction data
* `database name` = name of the database server to use, for example `postgres`

For example, the file `mmc-oracle.properties` stores properties for connecting to an Oracle database that stores environment data; the file `tracking-persistence-postgres.properties` stores properties for connecting to a Postgres database that stores tracking data, etc.

These files define the parameters for connecting to the database: driver, user, password, host, port, and others.

To migrate the configuration for persisting tracking data, complete these steps:

. In your old MMC installation, open the file `applicationContext-tracking.xml`, then locate the bean `dataSource`, shown below.
+
[source, xml, linenums]
----
<bean id="dataSource" class="org.springframework.jdbc.datasource.DriverManagerDataSource">
    <property name="driverClassName" value="oracle.jdbc.driver.OracleDriver" />
    <property name="url" value="jdbc:oracle:thin:@127.0.0.1:1521:xe" />
    <property name="username" value="TRACKER" />
    <property name="password" value="tracker" />
</bean>
----
+
You will migrate the values in the code above to the database config files in MMC 3.4.2.
+
[NOTE]
Depending on the configuration in your old MMC installation, some of the values displayed in the code above may actually reside in `persistence.xml` or `mmc-persistence.properties`.

. In MMC 3.4.2, locate the relevant `tracking-persistence-<database>.properties` file according to the database you wish to connect to, and open it for editing.
. Using the parameters and values from MMC 3.4.1, modify the relevant `mmc-<database>.properties` file in 3.4.2, migrating the values to the new config format according to the table below.
+
[width="100%",cols=",",options="header"]
|===
|Parameter name in 3.4.1 |Parameter name in 3.4.2 |Notes
|`username` |`mmc.tracking.db.username` | 
|`password` |`mmc.tracking.db.password` | 
|`url` |`mmc.tracking.db.host` a|
From the value of `url`, extract the host where your database server resides, and assign it as the value of `mmc.tracking.db.host` in the database config file in 3.4.2.

For example, if your database resides at host `dbserver`, from `datasource.url=jdbc:mysql://dbserver/mmc_persistency_status` extract `dbserver` to `mmc.tracking.db.host=dbserver` in the 3.4.2 config file.
|`url` |`mmc.tracking.db.port` a|
From the value of `url`, extract the port on which your database server is listening, and assign it as the value of `mmc.tracking.db.port` in the database config file in 3.4.2.

For example, if your database resides at host `dbserver` port 9155, from `datasource.url=jdbc:mysql://dbserver:9155/mmc_persistency_status` extract `9155` to `mmc.tracking.db.port=9155` in the 3.4.2 config file.

Note that if the port number is not present in the URL, it probably means that the default port for the database server is being used, for example 1521 for Oracle, 3306 for MySQL, etc.
|`url` |`mmc.tracking.db.servicename` a|
From the value of `url`, extract the Oracle service name for your connection, and assign it as the value of `mmc.tracking.db.servicename` in the database config file in 3.4.2.

For example, if the value of `url` in 3.4.1 is `jdbc:oracle:thin:MMC_STATUS/mmc123``@dbserver``:``1521``:xe`, then the service name is `xe`. Assign it in the new config file with the parameter `env.servicename=xe`.
|===

. In MMC 3.4.2, locate the file `<MMC_HOME>/WEB-INF/web.xml` and open it for editing.
. In the `web.xml` file, locate the section shown below.
. Replace the string `tracking-h2` with `tracking-<database_name>`. For example, if persisting data on postgres, replace it with `tracking-postgres`.
. After completing the above steps, you can remove your old MMC installation by deleting its home directory in the root directory of your Web app server. However, it is recommended that you keep the backup copies of the old database configuration files until you ensure that MMC 3.4.2 connects properly to the database.

[NOTE]
The exact configuration details in your old MMC installation may vary. Before deleting your old MMC installation, make complete backups of all relevant config files. Bear in mind that aside from the database connection parameters listed in this page, a custom configuration may contain additional parameters not listed here, which you will also need to migrate to the new configuration.

After you have completed configuration, start MMC 3.4.2.

== See Also

* Read an overview of link:/mule-management-console/v/3.4/configuring-mmc-3.4.2-for-external-databases-quick-reference[configuring MMC for external databases], which includes links to detailed instructions for each supported database server.
* Learn how to link:/mule-management-console/v/3.4/upgrading-to-mmc-3.4.2-with-ldap[upgrade to MMC 3.4.2 with LDAP].
