= Upgrading the Management Console

MMC agent and .war files are available through the http://www.mulesoft.com/support-login[MuleSoft Customer Portal]. MMC .war files are backwards-compatible with previous versions of Mule ESB, so downloading the newest available `.war` file is advisable. 

[NOTE]
Starting with Mule ESB 3.4.0, the MMC agent comes bundled with the Mule ESB Enterprise runtime download. 

== Determining Your MMC Version

You can determine what version of the MMC .war file  you are currently running by logging into the console and clicking *About Mule ESB Enterprise* at the bottom right of the screen.

[NOTE]
In all cases, it is strongly recommended to upgrade to the newest version of the Management Console.

== Upgrading to Management Console 3.4.1

If you are upgrading your .war to version 3.4.1, and your Mule ESB version is earlier than 3.4.1, you may need to upgrade your Management Console agent, as described below.

[width="100%",cols=",",options="header"]
|===
|Your Mule ESB version |Your current MMC agent version |You need to upgrade your agent to at least |Agent file name
|3.1.x |3.1.x |3.1.4 |`mmc-agent-mule3-app-3.1.4.zip`
|3.2.x |3.2.x |3.2.4 |`mmc-agent-mule3-app-3.2.4.zip`
|3.x |3.3.2 or above |No action necessary | 
|3.4.x |Any |No action necessary | 
|===

[WARNING]
If you are upgrading to Management Console 3.4, you are not required, but strongly encouraged to take the same steps as if you were upgrading to Management Console 3.4.1 (i.e. follow the table above).

== Upgrading to Management Console 3.4.2

=== Mule Agent

If you are upgrading your .war to version 3.4.2, and your Mule ESB version is earlier than 3.4.1, you may need to upgrade your Management Console agent, as described in the table above (the same table for MMC 3.4.1).

=== MMC 3.4.2 .war Files

MMC 3.4.2 is released in two versions, in two separate .war files:

* `mmc-console-3.4.2.war`
* `mmc-console-sqlserver-3.4.2.war`  – includes support for MS-SQL Server

For full details on which .war file to download, consult link:/mule-management-console/v/3.4/installing-or-upgrading-mule-management-console-3.4.2[Installing or Upgrading Mule Management Console 3.4.2].

=== Data Migration

The .war files for MMC 3.4.2 are *_not_* compatible with the .war files of previous versions of MMC in the following scenarios:

* If the old version of MMC uses LDAP for user authentication
* If the old version of MMC persists environment or tracking data to an external database

In both of the above cases, you need to migrate configuration data in order to retain your settings.

If your current MMC installation does not use LDAP for user authentication and is not configured to persist data on an external database, then you do not need to take further actions for upgrading to MMC 3.4.2.

The following documentation pages provide the steps necessary to migrate data to MMC 3.4.2:

* link:/mule-management-console/v/3.4/installing-or-upgrading-mule-management-console-3.4.2[Installing or Upgrading Mule Management Console 3.4.2]
* link:/mule-management-console/v/3.4/upgrading-to-mmc-3.4.2-with-ldap[Upgrading to MMC 3.4.2 with LDAP]
* link:/mule-management-console/v/3.4/upgrading-to-mmc-3.4.2-with-an-external-database[Upgrading to MMC 3.4.2 with an External Database]
