= Tcat Server 7.1.0 Release Notes

Tcat Server 7.1.0 includes a large number of high priority bug fixes, and new improvements and updates.

==== Performance and Scalability

We spun up hundreds of virtual machines containing managed Tcat instances and registered them with the Console. The Console was really fast, we saw a maximum of 35% CPU usage (with some occasional spikes as the caches were loading) and a top memory usage of 35% of the system. Mostly the CPU consumption was less than 20%. The Tcat console was installed on  a quad-core machine with 4GB of memory on a 64-bit linux server. 

==== Faster UI

User interface is much more snappier and listing of servers and deployments is significantly faster. The Dashboard also now lists all the deployments instead of just 10 per page. 

==== LDAP Integration and multiple databases

Configuring LDAP is now possible through the installer i.e. if you are doing a fresh install of Tcat Server. Similarly, you also have the ability to configure a different backend database for Jackrabbit persistence, although we do recommend the one we ship with by default. 

==== Upgraded backend persistence schema

The backend persistence schema was given a nice little overhaul. A brand new persistence manager bundled with optimized caching and lucene indexing, significantly speeds up queries which in turn positively impacts the UI as well as REST API calls. 

==== Optimized GC configuration and logging (non-windows)

On non-windows systems, Tcat Server now comes with an optimized configuration for the JVM. We have enabled GC logging, set the initial heap size to 1GB and partitioned the memory sections appropriately. We are expecting reduction in long GC pauses. This also helps us get better insight when providing support to our customers.  

==== Upgraded Bundled Tomcat version and JRE

The bundled Tomcat version is now upgraded to 7.0.51 and JRE is upgrade to 7.0.51. 

== Bug

* [https://www.mulesoft.org/jira/browse/TCAT-1141[TCAT-1141]] - Fix to Tcat-1140 breaks Deployment Purge scripts
* [https://www.mulesoft.org/jira/browse/TCAT-1160[TCAT-1160]] - Redeployment does not work properly when multiple artifact are part of the deployment
* [https://www.mulesoft.org/jira/browse/TCAT-1163[TCAT-1163]] - Continuous Deployment Purge Script execution failure: null
* [https://www.mulesoft.org/jira/browse/TCAT-1176[TCAT-1176]] - Log regex alert causing classnotfoundexception
* [https://www.mulesoft.org/jira/browse/TCAT-1177[TCAT-1177]] - Introduce validation for jcr nodes, to void the database corruption
* [https://www.mulesoft.org/jira/browse/TCAT-1182[TCAT-1182]] - If a server group has servers in it, then deleting the group does not remove the group from the server.groups property of the server node in JCR
* [https://www.mulesoft.org/jira/browse/TCAT-1189[TCAT-1189]] - Profiles are currently broken
* [https://www.mulesoft.org/jira/browse/TCAT-1199[TCAT-1199]] - Change copyright information to 2014. Its 2013 right now
* [https://www.mulesoft.org/jira/browse/TCAT-1203[TCAT-1203]] - Jasper API has changed for Tomcat 7, this breaks the JSP files display for server
* [https://www.mulesoft.org/jira/browse/TCAT-1212[TCAT-1212]] - Deployment Status portlet shows the status column twice in the Dashboard
* [https://www.mulesoft.org/jira/browse/TCAT-1217[TCAT-1217]] - If an undeploy fails then the deployment stays "In Progress"

== Improvement

* [https://www.mulesoft.org/jira/browse/TCAT-1088[TCAT-1088]] - Server->Settings->Edit Server Info not working properly
* [https://www.mulesoft.org/jira/browse/TCAT-1144[TCAT-1144]] - Jackrabbit DAO overhaul
* [https://www.mulesoft.org/jira/browse/TCAT-1151[TCAT-1151]] - Replace the custom caching mechanism with spring cache and Ehcache
* [https://www.mulesoft.org/jira/browse/TCAT-1185[TCAT-1185]] - Groovy plugin should get compiled and tested to avoid that changes in the API break them
* [https://www.mulesoft.org/jira/browse/TCAT-1198[TCAT-1198]] - Database and LDAP configuration screen need not be shown during agent+tomcat custom installation option
* [https://www.mulesoft.org/jira/browse/TCAT-1207[TCAT-1207]] - Console treats catalina.out as a binary file, prompting user to agree to open binary file, should just treat it as text file instead
* [https://www.mulesoft.org/jira/browse/TCAT-1214[TCAT-1214]] - Show all servers in the Dashboard instead of the default 50 servers.
* [https://www.mulesoft.org/jira/browse/TCAT-1215[TCAT-1215]] - Remove Paging for Deployment status in the Dashboard thus allowing all deployments to be shown instead of just 10
* [https://www.mulesoft.org/jira/browse/TCAT-1216[TCAT-1216]] - ServerName column should autoexpand to occupy remaining columnar space in table in order to show maximum characters of server name
* [https://www.mulesoft.org/jira/browse/TCAT-1220[TCAT-1220]] - Make CMS Garbage Collector the default, enable GC logging and set 1GB the default heap memory
* [https://www.mulesoft.org/jira/browse/TCAT-1224[TCAT-1224]] - Optimize default settings for backend Jackrabbit persistence

== New Feature

* [https://www.mulesoft.org/jira/browse/TCAT-1148[TCAT-1148]] - Introducing the possibility to upgrade the agent directly from the console
* [https://www.mulesoft.org/jira/browse/TCAT-1161[TCAT-1161]] - The installer should allow you to configure/test ldap connectivity
* [https://www.mulesoft.org/jira/browse/TCAT-1200[TCAT-1200]] - Deployment name should be able to contain colons
* [https://www.mulesoft.org/jira/browse/TCAT-1221[TCAT-1221]] - Migration tool to migrate existing repository to newer configuration using bundle pool persistence managers

== Task

* [https://www.mulesoft.org/jira/browse/TCAT-1110[TCAT-1110]] - Upgrade GWT to version 2.5
* [https://www.mulesoft.org/jira/browse/TCAT-1123[TCAT-1123]] - Upgrade bundled JRE to 1.7.51 and create the missing installers
* [https://www.mulesoft.org/jira/browse/TCAT-1128[TCAT-1128]] - Upgrade Spring libraries to version 3.1.4
* [https://www.mulesoft.org/jira/browse/TCAT-1150[TCAT-1150]] - Upgrade maven plugins to their last version
* [https://www.mulesoft.org/jira/browse/TCAT-1180[TCAT-1180]] - Migrate distributionManagement to the new corporate nexus
* [https://www.mulesoft.org/jira/browse/TCAT-1187[TCAT-1187]] - Create upgrader for changes in deployment and server schema in jackrabbit
* [https://www.mulesoft.org/jira/browse/TCAT-1225[TCAT-1225]] - Upgrade bundled Tomcats to 7.0.53 and 6.0.39 respectively. Upgrade other dependent libraries as well
* [https://www.mulesoft.org/jira/browse/TCAT-1170[TCAT-1170]] - Create a LdapPlugin to update the ldap group configuration
* [https://www.mulesoft.org/jira/browse/TCAT-1172[TCAT-1172]] - Create a repository copier to allow migration from a jcr PersistenceManager to another
* [https://www.mulesoft.org/jira/browse/TCAT-1173[TCAT-1173]] - Introduce the possibility to cluster JCR and quartz
* [https://www.mulesoft.org/jira/browse/TCAT-1197[TCAT-1197]] - Enable closure compiler

= Tcat Server 7.0.2 Release Notes

Sub-task

* [https://www.mulesoft.org/jira/browse/TCAT-1138[TCAT-1138]] - Upgrade bundled version of tomcat to version 7.0.37
* [https://www.mulesoft.org/jira/browse/TCAT-1147[TCAT-1147]] - Upgrade bundled version of tomcat to version 7.0.39

== Bug

* [https://www.mulesoft.org/jira/browse/TCAT-916[TCAT-916]] - Webapps can be deployed to empty Server group.
* [https://www.mulesoft.org/jira/browse/TCAT-987[TCAT-987]] - Slow console/timeouts and continous exceptions
* [https://www.mulesoft.org/jira/browse/TCAT-1027[TCAT-1027]] - On Deployments, you cannot change the name of deployable application from the repo.
* [https://www.mulesoft.org/jira/browse/TCAT-1048[TCAT-1048]] - On Dashboard, Webapp status, checkboxes of deployed webapps are cleared each 10 seconds.
* [https://www.mulesoft.org/jira/browse/TCAT-1145[TCAT-1145]] - ErrorPanel shows link to "Error message details". On clicking it just displays "null"

== Improvement

* [https://www.mulesoft.org/jira/browse/TCAT-45[TCAT-45]] - Support concurrent deployment of applications within a package
* [https://www.mulesoft.org/jira/browse/TCAT-1140[TCAT-1140]] - Console very slow when listing deployments both on the dashboard as well as on the deployments tab
* [https://www.mulesoft.org/jira/browse/TCAT-1143[TCAT-1143]] - Deleting a deployment is not immediately reflected on the deployments list page
* [https://www.mulesoft.org/jira/browse/TCAT-1149[TCAT-1149]] - Allow JmDns disabling via system properties

= Tcat Server 7.0.1 Release Notes

Tcat Server 7.0.1 includes a large number of high priority bug fixes, and new improvements and updates.

==== Parallel Deployments

Tcat now allows you to perform true parallel deployments. Earlier, most of your deployments were added to a queue and if a deployment took too long,  then all subsequent deployments were kept waiting. Now you can setup a thread pool and configure the number of threads you need to spawn, whereby each thread is allocated to one deployment. You can create a galaxy.properties in WEB-INF/classes directory and update the property named deployments.corePoolSize. 

==== Slowness in listing deployments

You should now see improvements in this area. Deployments are now listed slightly faster than before. 

==== Upgraded Bundled Tomcat version

The bundled Tomcat version is now upgraded to 7.0.30. 

==== Less noisy logs

We've tweaked the loggers so as to suppress the noisy Lucene index messages. Your log files will now be smaller and quieter.

=== List of Bug Fixes

* [http://www.mulesoft.org/jira/browse/TCAT-610[TCAT-610]] - Restarts of Tcat Server Agent from startup.sh causes ItemNotFoundException
* [http://www.mulesoft.org/jira/browse/TCAT-658[TCAT-658]] - Files -> New File -> Upload is causing Write access denied error
* [http://www.mulesoft.org/jira/browse/TCAT-1025[TCAT-1025]] - About dialog box should point at 2012 instead of 2011.
* [http://www.mulesoft.org/jira/browse/TCAT-1026[TCAT-1026]] - On Deployments, when creating a new deployment, context path of the webapp disappears after clicking on the field.
* [http://www.mulesoft.org/jira/browse/TCAT-1037[TCAT-1037]] - On Deployments, when creating a deployment, any file can be uploaded as webapp.
* [http://www.mulesoft.org/jira/browse/TCAT-1042[TCAT-1042]] - On Deployments, when creating a new deployment, you can undeploy and redeploy even if no server and/or app is specified.
* [http://www.mulesoft.org/jira/browse/TCAT-1044[TCAT-1044]] - On Administration, Users Group, you can delete a user group even if it has 1 or more users associated to it.
* [http://www.mulesoft.org/jira/browse/TCAT-1049[TCAT-1049]] - On Dashboard, Webapp status, there is only one entry per webapp, no matter if there are different webapp with different status, deployments, etc.
* [http://www.mulesoft.org/jira/browse/TCAT-1051[TCAT-1051]] - On Alerts, destinations, on edit mode, delete button has incorrect label.
* [http://www.mulesoft.org/jira/browse/TCAT-1054[TCAT-1054]] - On Dashboard, Server Metrics, system does not allow to add "Avg Response Time" and/or "Error Count" portlets.
* [http://www.mulesoft.org/jira/browse/TCAT-1057[TCAT-1057]] - Tcat 7.x build on RED because issues with installer module.
* [http://www.mulesoft.org/jira/browse/TCAT-1058[TCAT-1058]] - System does not allow to re pair a server.
* [http://www.mulesoft.org/jira/browse/TCAT-1060[TCAT-1060]] - Server auto-discovering does not work.
* [http://www.mulesoft.org/jira/browse/TCAT-1063[TCAT-1063]] - On Repository, error message when deleting apps used on deploys is incorrect.
* [http://www.mulesoft.org/jira/browse/TCAT-1064[TCAT-1064]] - On Rest API, system does not create server group.
* [http://www.mulesoft.org/jira/browse/TCAT-1069[TCAT-1069]] - On Servers, unable to register a server successfully using IBM JDK.
* [http://www.mulesoft.org/jira/browse/TCAT-1090[TCAT-1090]] - tcat-env.conf not loaded correctly on OSX
* [http://www.mulesoft.org/jira/browse/TCAT-1102[TCAT-1102]] - Connector's stats not showing up
* [http://www.mulesoft.org/jira/browse/TCAT-1109[TCAT-1109]] - Ldap login fails silently
* [http://www.mulesoft.org/jira/browse/TCAT-1115[TCAT-1115]] - MMC exception: This node already exists: /ldapUserMetadata/_x0031_45206
* [http://www.mulesoft.org/jira/browse/TCAT-1118[TCAT-1118]] - Registering a host with domain name replaces the domain name with an IP address
* [http://www.mulesoft.org/jira/browse/TCAT-1122[TCAT-1122]] - Slowness while listing deployments
* [http://www.mulesoft.org/jira/browse/TCAT-1126[TCAT-1126]] - showDashboard property not getting persisted while using ldap
* [http://www.mulesoft.org/jira/browse/TCAT-1132[TCAT-1132]] - Deployments can't be performed while a failed deployments is still in progress
* [http://www.mulesoft.org/jira/browse/TCAT-1133[TCAT-1133]] - Artifact with the same name existing in 2 different repository, only versions of one are prompted.

=== List of Improvements

* [http://www.mulesoft.org/jira/browse/TCAT-1097[TCAT-1097]] - AccessControlManagerImpl.doCreateInitialNodes should not use hardcoded values
* [http://www.mulesoft.org/jira/browse/TCAT-1099[TCAT-1099]] - Upgrade bundled version tomcat to version 7.0.30
* [http://www.mulesoft.org/jira/browse/TCAT-1108[TCAT-1108]] - Increment the request we receive from prospect downloading Tcat
* [http://www.mulesoft.org/jira/browse/TCAT-1125[TCAT-1125]] - Improve redirect after login

= Tcat Server 6.4.5 Release Notes

Tcat Server 6.4.5 includes a large number of high priority bug fixes, and several new improvements and updates.

==== CATALINA_BASE installation creation script for Tcat on non-Windows operating systems

Tcat now includes a script that allows you to install any number of independently operable Tcat Server installations as CATALINA_BASE directories that all run using the same CATALINA_HOME Tcat installation. This script allows Tcat users to take full advantage of the CATALINA_HOME / CATALINA_BASE split feature of Apache Tomcat, combined with the Tcat Server reliable restarts and single command upgrades. The script is named 'tcat-base' (look in the CATALINA_HOME/bin directory).

==== REST API Improvements

* The Tcat console REST API now supports 'Set Profile' REST API calls for individual servers and server groups.
* Deleting files and directories via the REST API now functions as it should.
* Deleting deployments via the REST API now functions as it should.
* Some other misc REST API bugs are now fixed (listed below).

==== Continuous deployment from Maven to Tcat via Ant Tasks/Logic

While implementing Tcat 6.4.5 we also developed some link:/docs/display/TCAT/Integrating+with+Maven[Maven POM format XML] that allows you to have full programmatic control over your continuous deployments to and through the Tcat console. This Maven POM format content lets you store and deploy your webapps into the Tcat Server console when your webapps are built via Maven.

==== Continuous deployment purge script

When you are continuously deploying your webapp(s), many versions of them will accumulate in your Tcat console content repository. You will typically only be deploying these webapps for a period of time, and then older versions of your webapps will no longer be used. These older versions tend to be large binaries that are not deployed anywhere anymore, and it is better to purge those from your repository instead of allowing them to accumulate and use disk space. Tcat 6.4.5 adds a new continuous deployment purge script that you can configure to run periodically to purge the older copies of your webapps from Tcat's repository. This script only purges webapps that are not currently deployed – you may configure how long the script will keep webapps when they are no longer in use. Find the script in Administration > Admin Shell.

[WARNING] |NOTE: Due to one or more security fixes and enhancements, along with several bug fixes, it is important to upgrade your Tcat agent webapp to the 6.4.5 version of the agent. The Tcat 6.4.5 console can still register and control older versions of the Tcat agent, and recent older Tcat console versions can still register and control the new 6.4.5 agent, but it is important to upgrade your agents with the fixes contained in version 6.4.5.

=== Fixed and Implemented Issues

Unknown macro: \{excel}

= Tcat Server 6.4.4 Release Notes

Tcat Server 6.4.4 includes several new improvements, updates, and bug fixes.

==== Tcat Server's console security has been significantly improved

* Fine grained user activity logging was added in this release. Here are the activities that are captured in the activity log, when a user is using the console either from their favorite web browser, or via the console REST API:
** User Login Failed
** User Login Successful
** User Creation
** User Deletion
** User Password Change
** User Permission Change
** Server Register
** Server Unregister
** Server Save
** Server Restart
** Server File Read
** Server File Metadata Read
** Server File Write
** Server Directory Listing
** Deployment Save
** Deployment Deploy
** Deployment Undeploy
** Deployment Redeploy
** Deployment Rollback
** Deployment Delete
* The console now hides sensitive / password attribute values in the JMX browser. The hidden attribute names are configurable, but the default hidden attribute names are:
** password
**keystorePass
** keypass
** trustStorePass
** connectionPassword
** userPassword
** SSLPassword (Tomcat 5.5)
** secret
** passphrase
* The console now times out and invalidates its server session after a configurable duration of inactivity. In previous versions, the GWT heartbeat was preventing inactivity session timeouts.
* A bug was preventing an administrator from changing another user's group membership successfully. That is now fixed.
* By default, the agent is configured to disallow a console user to read/write any files in the tcat-data directory.

==== Deployment status panel improvements

* The Deployment panel now updates more frequently to reflect a more up to date and accurate deployment status.
* There were some edge conditions where the deployment status said Success, but the deployment had failed asynchronously in the background. This is now fixed.
* The console now shows both the last deployment action as well as the current deployment status – two separate / distinct fields of information.

==== REST API Improvements

* The Tcat console REST API now supports creating new directories on the managed Tomcat servers. In previous releases it was possible to create new files on the managed servers via the REST API, but there was no way to create directories.

==== Updated to the latest Tomcat 6.0.32

* Tcat Server now bundles Apache Tomcat 6.0.32, which has security fixes (see http://tomcat.apache.org/security-6.html#Fixed_in_Apache_Tomcat_6.0.32), and other bug fixes (see http://tomcat.apache.org/tomcat-6.0-doc/changelog.html).
* Many other minor bugs are now fixed.

= Tcat Server 6.4.3 Release Notes

Tcat Server 6 R4 P3 includes several new improvements and bug fixes.

==== Server Metrics on Global Dashboard

In addition to viewing server metrics on the server dashboard, portlets can be created on the main dashboard which monitor critical statistics for servers or server groups. This allows you to track statistics like requests/second for a group of servers or put a critical application specific JMX metric front and center on the main dashboard.

==== Alerting improvements

In addition to being able to alert at a per server level, many alerts can now be applied to server groups as well, allowing you to more easily monitor your servers. These include server up/down alerts, log regex alerts, JMX alerts, and web application statistic alerts.

==== Full Support for the Latest Tomcat 7

Tcat now includes full support for the latest version of Tomcat, version 7.0.5 beta. You may mix and match Tomcat versions that are registered with a Tcat Server console, from Tomcat version 5.5.x all the way up to and including the latest Tomcat 7.

==== Solaris Tcat Installer

R4P3 introduces a new automated installer for the Solaris operating system, including supporting multiple Tcat Server installations per Solaris OS installation. The installer offers both GUI installations and "headless" text-only installations, supporting all of the same installation options on Solaris 10 and Solaris 11 as were already available on the Linux and Windows operating systems.

==== Solaris SMF Service Integration / Reliable Tcat Server JVM Restarts

Tcat Server now deeply integrates with the Solaris 10 Service Management Framework (SMF), supporting standard service querying, stops, starts, and restarts. Tcat now supports fully reliable, scriptable, and remote server JVM restarts on Solaris 10 and Solaris 11. The new Tcat Server installer for Solaris also allows installing multiple Tcat Server installations in the same Solaris OS installation, so that you can start, stop, and restart each Tcat instance independently, and have a different service name for each. You may now also create mixed groups of Tcat servers that run on a set of different operating systems including Solaris, Linux, and Windows, and automate remote server restarts across them without dealing with operating system specific details.

==== Server Profiles Improvements

Tcat allows adding to an environment variable by referencing the server's current value. For example if you set JAVA_OPTS in a server profile to "$\{JAVA_OPTS} -DmyProp=true", then when you apply the server profile to a server, the server's existing value for JAVA_OPTS is saved, with "-DmyProp=true" added to the end. This makes it easy to add JVM startup arguments, and generally add to the beginning or the end of environment variables.

Tcat allows referencing system properties in server profile environment variable values. For example, if you set the OS_NAME environment variable to "$\{os.name}" in a server profile, when you apply the server profile to a server, Tcat will insert the agent JVM's "os.name" system property value into the value of the OS_NAME environment variable.

Conditional environment variable value references: You may now use server profiles to conditionally add strings to the server's environment variable settings. For example: if you set the JAVA_OPTS environment variable to "$\{JAVA_OPTS} $\{os.name -sw Windows|-Xmx512m}" in a server profile, when you apply the server profile to a server, Tcat will conditionally add "-Xmx512m" to the value of the server's JAVA_OPTS environment variable only when the agent JVM is running on Windows.

Tcat allows writing a server profile whose environment variable settings are multiplatform, such that the settings will be translated to the agent's server operating system native shell syntax. For example, if you set MY_ENV_VAR in a server profile to "$\{shell:ANOTHER_VAR}/foo/bar", then that setting will be stored in tcat-env.conf as MY_ENV_VAR=%ANOTHER_VAR%\foo\bar on Windows OSs, and $\{ANOTHER_VAR}/foo/bar on non-Windows OSs such as Linux, MacOS, and Solaris.

==== Support for the IBM J9 and Oracle JRockit Java VMs

Tcat R4P3 introduced support for the IBM J9 1.5.0 and 1.6.0 JVMs, as well as the Oracle JRockit 1.6.0 JVM. The IBM J9 1.5.0 JVM can only be used with Tomcat vesions 6.0 and higher (due to a problem with the 1.5.0 J9 JVM not accepting self-signed X.509 certificates), while the IVM 1.6.0 JVM can be used with any version of Tomcat 5.5.x and higher. The JRockit 1.6.0 JVM can be used with any version of Tomcat 5.5.x and higher.

=== Known Issues

* When exporting a server profile, the browser loads a blank page whose URL says "/serverProfileExport.form?serverProfileId=the-id" when it should instead say "/console/serverProfileExport.form?serverProfileId=the-id". After clicking the Export button, add "/console" to the URL after the host and port, and the export will proceed.
* Memory usage can be reported incorrectly if you are running a 32 bit JVM on a 64 bit OS.
* CPU utilization is the utilization reported by the JVM, which is not guaranteed to be correct.
* Upon the very first start of Tcat, this harmless exception may appear in the `catalina.out` log file:

[source]
----
[12-22 14:21:33] WARN  DelegatingMultiEventListener [async-event-thread-1]: Failed to execute <public void com.mulesoft.tcat.server.ServerDataCacheImpl.onServerRegisteredEvent(com.mulesoft.common.server.ServerRegisteredEvent) throws java.lang.Exception> on <com.mulesoft.common.server.ServerRegisteredEvent@1fe1135>java.lang.RuntimeException: org.mule.galaxy.NotFoundException: The item local$b61a5afb-8d9a-4ad8-94d0-9dd18697349b was not found.        at org.mule.galaxy.impl.event.AbstractDelegatingGalaxyEventListener$MethodInvoker.runInTransaction(AbstractDelegatingGalaxyEventListener.java:206)...
----

= Tcat Server 6.4.1 Release Notes

This release includes minor bug fixes only:

* Memory usage was displayed incorrectly for servers on the main dashboard.
* Stock Tomcat Windows services are now detected and restarts are now disabled in the console for them since they are not supported.

=== Known Issues

* Memory usage can be reported incorrectly if you are running a 32 bit JVM on a 64 bit OS.
* CPU utilization is the utilization reported by the JVM, which is not guaranteed to be correct.

= Tcat Server 6 R4P0 Release Notes

Tcat Server 6 R4 includes many major new features for users, including dashboarding, alerting, permissions and more.

==== Dashboards

Tcat now includes global and per server dashboards. The global dashboard allows you to see your overall server health, the status of your deployments, raised alerts (see below) and the status of your web applications. There is also a per server dashboard, where you can view critical information about your server - including deployment information and system metrics. You can also attach different JMX metrics as charts to this dashboard, giving you critical insight into how your servers are performing.

==== Permissions

* Administrators can now lock down Tcat for the different roles in their organization. Permissions are controlled by server group to limit who can view what servers, what information users can view for each server, and what types of actions they can take. Now operations can give read access of their environment to developers or allow certain people to restart servers but not modify anything else.
* Included are a number of predefined user groups including, Administrators, Server Administrators, Deployers and Monitors.

==== Alerting

* Administrators can now define alerts. There are many different alert types supported, including:
** Log regular expression: listen for a regular expression in your log files and be alerted when it matches, allowing you to bubble up things like "SEVERE" log errors to your console easily.
** Web app statistics: Alert based on statistics relating to your webapps like request count, error count, or average response time.
** JMX: you can now create an alert based on any JMX attribute, such as file descriptor usage or cache statistics, allowing you to monitor nearly anything within your application.
** Servers going up or down
** The health of URLs, allowing you to be notified if a public URL becomes unavailable
* Alerts can also be sent to various destinations via SNMP traps or emails

==== JMX Improvements

We now expose our own webapp statistics (request count, average response time, error count) as JMX attributes for customers who already have a monitoring solution and would like to monitor the Tomcat agents directly.

=== Known Issues

* Memory usage can be reported incorrectly if you are running a 32 bit JVM on a 64 bit OS.
* CPU utilization is the utilization reported by the JVM, which is not guaranteed to be correct.

=== Fixed Issues

Unknown macro: \{excel}
