= Anypoint Platform Administration

:keywords: anypoint platform, permissions, configuring

Your link:https://anypoint.mulesoft.com/#/signup[Anypoint Platform account] gives you access to both the services in the Anypoint Platform for APIs – for creating and managing APIs through their entire lifecycle – and to CloudHub – for deploying and managing applications.

[NOTE]
As of November 2014, accounts in both the Anypoint Platform for APIs and CloudHub have been merged. For more information about what this merging of accounts implies and how it's being handled, read Upcoming Changes to Anypoint Platform Accounts.

* link:/anypoint-platform-administration/troubleshooting-anypoint-platform-access[Troubleshooting Anypoint Platform Access]
* link:/anypoint-platform-administration/setting-up-external-identity[Setting Up External Identity]
* link:/anypoint-platform-administration/managing-cloudhub-specific-settings[Managing CloudHub Specific Settings]
** link:/anypoint-platform-administration/managing-cloudhub-environments[Managing CloudHub Environments]
* link:/anypoint-platform-administration/creating-an-account[Creating an Account]
* link:/anypoint-platform-administration/managing-accounts-roles-and-permissions[Managing Accounts Roles and Permissions]
* link:/anypoint-platform-administration/manage-your-organization-and-business-groups[Manage your Organization and Business Groups]

If you have any questions about your account, please visit the  link:/anypoint-platform-administration/community-and-support[support portal]  for assistance. 
