= Troubleshooting Anypoint Platform Access
:keywords: anypoint platform, permissions, configuring

== Can I have multiple accounts with the same email address?

Yes, you can have multiple accounts, either for the same organization or for multiple different organizations, using the same email address. Your username must be unique for each account.

== I created an account, but I need to join an existing organization.

To join an existing organization, please contact an Organization Administrator for the organization that you need to join and ask them to send you an invitation to that organization. Once you receive your invitation, you can create a new account to accept the invitation and associate your account with the organization. Any data that you entered into the organization that you created yourself remains associated with your old organization.

== I have been sent an invitation, but it says I should use an existing account to log in – what account am I supposed to use?

If you have one or more existing MuleSoft community accounts tied to the email address at which you received your invitation, MuleSoft prompts you to use your existing account to sign in and accept the invitation. You can also choose to create a new account by following the Sign Up link at the bottom of the form.

====== I received an invitation to an organization, but I want to use a different email address for my account.

Account invitations are tied to the email address to which the invitation was sent. If you need to use a different email address, accept the invite, then visit your profile to change your email address.

== I received an invitation to an organization, but when I follow the link in the email I receive an error.

Your invitation may have expired or been rescinded. Please contact your Organization Administrator for a new invitation.

== I have an account, but the platform does not recognize my login.

Please check that you are using the correct URL to log in to your organization. If your organization uses an external identity management system, your login URL uses this pattern: *anypoint.mulesoft.com/accounts/login/yourorganizationname*

If your organization is not using an external identity management system and your login credentials are not working, reset your password or consult your Organization Administrator to ensure that your account is still active.

== I accepted an invitation and logged in, but I cannot see anything in the platform.

If you are logged in and cannot see anything on your organization's Developer Portal, this means that either:

* no one in your organization has added any APIs yet, and thus there are no API Portals to display
* you have not been granted Portal Viewer access to any private API Portals (and there are no public API Portals to display)

== I am an API Version Owner, and I want to give other people access to my API version. What do I do?

Navigate to your API Version Details page and click the *Permissions* tab. You can invite other users to access your API here. Note that the user you want to invite must already be a member of the same organization as you. Once you have added users, you can  manage the nature of the permissions (Portal Viewer access or API Version Owner access) that you assign using the drop down in the Permission column. This tab also allows you to view all users who currently have been granted direct permissions to your API. Note that this tab does not display any users that have permissions based on a custom role, because roles cannot be managed from API Version Details pages. Contact your Organization Administrator for information about role-based permissions to your API version.

== I cannot access billing information for my account.

Please contact us directly for billing information.

== I received a notice that my trial is expiring. Help!

Please file a link:https://www.mulesoft.com/support-login[support ticket] or talk to your account representative to request an Enterprise license for your on-premises API Gateway instances or to create a subscription account on CloudHub if you are using cloud API Gateways.

== My organization uses external identity management. How do I log in?

Please log in at *anypoint.mulesoft.com/accounts/login/yourorganizationname* if your organization is using external identity management.

== How do I access the Developer Portal for another organization? +

Log out of your account in order to browse Developer Portals of other organizations. While you are logged in to your own organization, you can only access your own organization's Developer Portal. Note that if you wish to request access to an API of another organization, you need to get an Anypoint Platform account for that organization.

== I have found an API that I would like to use, but I'm not a member of the organization to which that API belongs. How can I request access to this API?

To request access to an API, you must be logged in with an account in the organization to which the API belongs. If you do not have an account with the organization, please review the documentation in the API Portal for information about how to request an account.

== How do I delete my account?

Please file a link:https://www.mulesoft.com/support-login[support ticket] for account deletion or migration. +
