= 1.4 Migration Guide
:keywords: release notes, esb, migration

There are some changes in 1.4 that may break compatibility from 1.3 depending on the way you are using Mule. The following describes those changes and how to migrate.


== Xml Configuration Changes

=== Using Split configuration files

When link:http://www.mulesoft.org/documentation-3.2/display/MULECB/Using+Multiple+Configuration+Files[splitting Mule Configuration] files In Mule 1.3.3 it was possible to put a _<mule-descriptor>_ element in a single mule XML configuration file i.e.

[source, xml, linenums]
----
<mule-configuration>
    <mule-descriptor name="foo" className="org.Foo"/>
</mule-configuration>
----

This no longer works in Mule 1.4 instead you have to declare all _<mule-descriptor>_ elements in a _<model>_ element. i.e.

[source, xml, linenums]
----
<mule-configuration>
    <model type="seda" name="main">
          <mule-descriptor name="foo" className="org.Foo"/>
    </model>
</mule-configuration>
----
If you want to use the same <model> for every <mule-descriptor> across multiple configuration files you can declare the main model (as above) in the first first file to be processed and then use _inherited_ models in the other configuration files, i.e.

[source, xml, linenums]
----
<mule-configuration>
    <model type="inherited" name="main">
          <mule-descriptor name="bar" className="org.Bar"/>
    </model>
</mule-configuration>
----
Notice the only difference is that the _<model>_ type is *inherited* and the _<model>_ name remains the same.

=== Deprecated configuration elements

Some configuration elements and attributes have been deprecated. These will still work in 1.4 but will be removed for Mule 2.0.

* The following attributes have been deprecated on the _<mule-descriptor> _ element: inboundEndpoint, outboundEndpoint, inboundTransformer, outboundTransformer and responseTransformer. +
These should be used within link:http://www.mulesoft.org/documentation-3.2/display/MULEUSER/Message+Routers[here] i.e. <inbound-router> and <outbound-router> elements.
* _<endpoint-identifier>_ elements have been removed in favor of using <global-endpoint> elements since global endpoints allow you to associate not only a logical name to a physical address, but also transaction security and transformer information.

== API Changes

=== Transformers and UMOMessage

Some transformers (e.g. SerializableToByteArray) can handle UMOMessages differently from other objects; this capability could be switched on by setting a common property _sourceType_. This turned out to be confusing; only those transformers that implement this behaviour now have a property *_acceptUMOMessage_* which can be toggled to enable/disable the extra functionality. The _sourceType_ property has been removed. Instead of:
[source, xml, linenums]
----
<property name="sourceType" value="UMOMessage" />
----
use:
[source, xml, linenums]
----
<property name="acceptUMOMessage" value="true"/>
----
when configuring a transformer.

=== Transport changes

The entire transport layer (i.e all classes implementing _UMOConnector_/_UMOMessageDispatcher_ etc.) received a significant overhaul for correctness, ease of use and scalability. Most notably it is now no longer possible to get programmatic access to a connector's message dispatchers; for sending an event programmatically instead of using:

[source,java,linenums]
----
// assume ep is an UMOImmutableEndpoint
ep.getConnector().getDispatcher(ep).dispatch(event);
----
please use the following, much simpler:

[source,java,linenums]
----
// assume ep is an UMOImmutableEndpoint
ep.dispatch(event);
----
Unfortunately not all API changes could be finalized for 1.4.0, which is why we recommend that people with custom transports hold off migrating until 1.4.1. More detailed changes and instructions will be provided in a dedicated transport migration/architecture guide.

http://www.mulesoft.org/documentation/display/MULE3USER/Mule+Application+Architecture[Mule Application Architecture]
