= Anypoint Analytics Release Notes
:keywords: analytics, release, notes

== Compatibility

Anypoint Analytics is compatible with all hardware and software as described in link:/mule-user-guide/v/3.7/hardware-and-software-requirements[Hardware and Software Requirements],
as well as Anypoint Platform for APIs v1.0 and newer.

== Version 1.9 - December 12, 2015

* Performance tuning in the ingest system, providing greater ability to handle burst load from API gateways.
* Improved presentation of empty data ranges for API analytics charts, making it more obvious when no data is available.

== See Also

* link:/release-notes/anypoint-platform-for-apis-release-notes[Anypoint Platform for APIs Release Notes].
* link:/anypoint-platform-for-apis/viewing-api-analytics[Viewing API Analytics].
* link:/anypoint-platform-for-apis/analytics-event-api[Analytics Event API].
* link:http://forums.mulesoft.com[MuleSoft's Forums].
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support].
* mailto:support@mulesoft.com[Contact MuleSoft].
