= Anypoint Analytics Release Notes
:keywords: analytics, release, notes

*January, 2016*

*Guides*:

* link:/anypoint-platform-for-apis/viewing-api-analytics[Viewing API Analytics]
* link:/anypoint-platform-for-apis/analytics-event-api[Analytics Event API]

== Compatibility

Anypoint Analytics is compatible with all hardware and software as described in link:/mule-user-guide/v/3.7/hardware-and-software-requirements[Hardware and Software Requirements],
as well as Anypoint Platform for APIs v1.0 and newer.

== Version 1.10.1 - January 23, 2016

This release includes following feature additions:

* OAuth tokens are now supported in addition to JWT for calling the Anypoint Analytics Query and Reports APIs.
* Going to the analytics homepage directly without a validation token now redirects the user to the Anypoint Platform login page.

=== Fixed Issues

* AS-254 - Analytics page does not load and react accordingly when the user is not logged in.
* AS-560 - Allow API calls using OAuth token (deprecate usage of JWT token.)


== Version 1.10 - December 19, 2015

* To allow correlation between Anypoint Analytics and third-party systems, the `event_id` property
set by the API Gateway (from `message.id`) is now propagated through the system.
* Performing a sign out from the Analytics section of the Anypoint Platform now correctly signs out and redirects to the sign in page.
* OAuth tokens are now supported in addition to JWT for calling the Anypoint Analytics Query and Reports APIs.

== Version 1.9 - December 12, 2015

* Performance tuning in the ingest system, providing greater ability to handle burst load from API gateways.
* Improved presentation of empty data ranges for API analytics charts, making it more obvious when no data is available.

== See Also

* link:/release-notes/anypoint-platform-for-apis-release-notes[Anypoint Platform for APIs Release Notes].
* link:/anypoint-platform-for-apis/viewing-api-analytics[Viewing API Analytics].
* link:/anypoint-platform-for-apis/analytics-event-api[Analytics Event API].
* link:http://forums.mulesoft.com[MuleSoft's Forums].
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support].
* mailto:support@mulesoft.com[Contact MuleSoft].
