= Anypoint Connector DevKit Plugin 1.1.1 Release Notes

== New Features

* Makes it easy to apply the connector testing framework (CTF) to a connector project by scaffolding tests generation. Since tests generation didn’t support CTF previously, developers needed to created CTF compatible test cases manually.
* Adds DevKit 3.7.2 support.
* Enables new DevKit components to be configured while a connector is created.

== Fixed Issues

This release includes several fixes, and the most important ones are:

* Improves an error reporting on WSDL formats SOAP Connect doesn’t support. To be specific, the previous version created a SOAP Connect project with RCP-based WSDLs even if these WSDLs are not supported. A user only saw an error message after he or she put the SOAP Connect-based connector in a mule flow and tried to select an operation. However, this version shows a proper error message for unsupported WSDL formats, and halts a SOAP Connect project creation.
* SOAP Connect supports WSDLs located in folders with whitespace.
* Properly uninstalls a multi-module connector.
