= Anypoint Exchange Release Notes
:keywords: release notes, exchange


We are excited to announce the general availability of a new product on the Anypoint platform: http://anypoint.mulesoft.com/library[Anypoint Exchange]. This brand new product enables Anypoint Platform users to publish and access Mule-related content within their own organization increasing visibility and reuse across organizations.

== Dec 2015 Release

=== Features and Functionality

This Anypoint Exchange release includes the following new features and functionality:

* *WSDL Support*: At the moment WSDL type does not have a Studio integration, however WSDLs can be added and managed via web UI.
* Visual enhancements such as new colors for item types and UX improvements.
* Auto-populated URI when creating new items.
* Automatically resizable description container when editing content.
* Firefox and Internet Explore 11 bugs fixed.

=== Known Limitations

The version of the exchange available with the on-premises installation of the Anypoint Platform comes with an empty library of content, you must populate it with your own content.

== May 2015 Release

=== Features and Functionality

This Anypoint Exchange release includes the following new features and functionality:

* *Ratings:* All content has a rating associated to it. Users can rate only from Exchange in Anypoint Studio (Connectors need to be installed in Studio in order to rate them). Objects have their rating displayed only when they have two ratings or more.
* *Author:* Objects can have the author's name and photo. This can be used for partners or community contributors.  This section is hidden if not filled out.
* *UI Refresh:* Object type indicators have been improved  . Text areas and button sizes have changed to improve readability

=== Known Limitations

To access private content from Anypoint Studio, version 4.2.0 or newer must be used.


== February 2015 Release

=== Features and Functionality

This Anypoint Exchange release includes the following new features and functionality:

* *Create and Publish private content:* Choose between a variety of content types (templates, examples, connectors, etc) to add, describe your asset and publish it in your organization’s exchange. Only the people you choose will have access to create and publish new content.
* *Search for Content*: Users within your organization will be able to find the internally published content (as well as Mulesoft’s public content), increasing the chance of reuse and avoiding redundant work.  Exchange Admins can customize search filters to make internal content easier to find.
* *Seamless Anypoint Studio Integration*: Access your private content seamlessly from Anypoint Studio.  You can open templates or install connectors by opening Anypoint Exchange from Studio and logging into your Anypoint Platform account.

=== Known Limitations

To access private content from Anypoint Studio, version 4.2.0 or newer must be used.

== Support

If you need help using the product, please refer to the link:/mule-fundamentals/v/3.7/anypoint-exchange[documentation for the Anypoint Exchange].  If you have additional questions or want to report a problem, please contact support through the usual channels.
