= Anypoint Studio 5.4 with 3.7.3 Runtime Update Site 1 Release Notes
:keywords: release notes, anypoint studio


*December 17, 2015* +
*Build ID:* 201512161232

== What's New

This release includes many improvements and bug fixes, including:

* Support for auto mapping Map types in DataWeave
* Improved DataWeave error markings
* Studio deadlock fix
* Bug fixes to the new light theme

...And many more


For a complete list, please see the JIRA list below.

== Jira Ticket List


=== Bug Fixes

* [STUDIO-5360] - Autocomplete with ENTER in a dialog, closes the dialog
* [STUDIO-7335] - DW: Warning errors in the DW Script are not marked in the editor
* [STUDIO-7366] - DW: when the script starts to grow (assuming having too many parenthesis) at some point it hangs Studio
* [STUDIO-7368] - DW: auto-mapping of fields does not work for MAP and CSV
* [STUDIO-7384] - [Palette] Hover effect for Munit categories in Light theme
* [STUDIO-7389] - [Palette] Suggestion search shows category without any match.
* [STUDIO-7395] - [Palette] When changing the Runtime of a Project the palette is not refreshed until you filter
* [STUDIO-7406] - [Light Theme] When using security module MPs, Studio visual goes wrong.
* [STUDIO-7407] - Studio fails to open configs when the editor contains a nested element that contains it self
* [STUDIO-7408] - NPE when the palette is reloaded and no mule editor was open before
* [STUDIO-7414] - Drag and drop not working when the script has only warnings
* [STUDIO-7418] - Format in drag and drop after dropping element is not working if there is any selection in the script
* [STUDIO-7419] - [DW-UI] Setting metadata within DW transformer is not saved if using new type
* [STUDIO-7425] - Assign metadata does not work properly
* [STUDIO-7426] - [DW-UI] Drag and drop does not work properly when the output is not payload
* [STUDIO-7431] - [DW-UI] Issue drag xml element to xml attribute
* [STUDIO-7432] - [DW-UI] Preview issue with multiples output
* [STUDIO-7434] - Studio deadlock when starting after a crash
* [STUDIO-7439] - [Palette] When opening palette preferences from Preferences menu, an error is thrown.

=== Improvements

* [STUDIO-1751] - Import the WSDL in Mule Studio in SOAP Component - Option to browse for WSDL
* [STUDIO-6944] - Focus in Finish button in pop-up for nested elements is interfeering with autocompletion



== Support Resources

* Refer to MuleSoft’s http://www.mulesoft.org/documentation/display/current/Home[MuleSoft Documentation] for instructions on how to use the new features and improved functionality in Anypoint Studio with 3.6.0 Runtime.
* Access MuleSoft’s http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal].
