= Anypoint Studio 6.0 Beta With Mule Runtime 3.8-M1 Release Notes

*January 28, 2016* +
*Build ID:*

xref:migration[Skip to Migration Guide]

== Compatibility

*Mule Runtime* +
Version: 3.8.0 EE - M1

*Anypoint Studio* +
Version: 6.6.0 +
Build Id: TBD

*APIkit* +
Versions: 3.8

*SAP Connector* +
Versions: TBD

*DataWeave* +
Version: TBD

This new release features the following improvements:

* Discover APIs to implement directly from API Manager, and easily synchronize API designs across Studio and API Designer projects.
* Support for reading and writing fixed width and other flat files using DataWeave
* The debugger now shows more detailed data for some connectors, such as HTTP and Database, making it easier to debug.
* The Mule 3.8 runtime also includes improved error messages, which allow you to clearly see where the error is coming from and click to navigate to that point in the flow.
* Users can now browse for WSDLs in the exchange and when configuring the WS Consumer.
* Support for Mule 3.8, which creates a single unified runtime for API gateways and integrations, adds additional TLS capabilities, additional tuning parameters for batch, and improved error messages.

== What's New

*
*
*


== Hardware and Software System Requirements

* For most use cases, Anypoint Studio with the 3.8 Runtime does not change hardware or software requirements.

* MuleSoft recommends a minimum of 4GB RAM on a developer workstation. As applications become complex, consider adding more RAM.

* This version of Anypoint Studio requires Java 7.

*Note*: If you are installing Anypoint Studio on a Mac computer with OS X that has no Java installed, the OS may require that you first download and install link:http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase6-419409.html[JDK 1.6]. Install JDK 1.6 first and then install JDK 1.7.

[[migration]]
== Migration Guide

This version is a Beta, there is no migration from a GA version to a Beta.


== Known Issues


== Support

* link:http://forums.mulesoft.com/[MuleSoft’s Forum]
*  link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]

== Deprecated in this Release

Nothing was deprecated in this release.

== Jira Ticket List for Anypoint Studio

=== Bug Fixes


=== Improvements



=== New Tasks

== Jira Ticket List for DataWeave


=== DataWeave Known Issues


=== New Features

=== Bug Fixes


=== Improvements

=== New Tasks


== See Also

* link:http://studio.mulesoft.org/r4/updates[Studio Updates]
* link:http://studio.mulesoft.org/r4/plugin[Studio as Plugin]
* link:http://repository.mulesoft.org/connectors/releases/3.5.0[Anypoint Connectors Update Site]
* link:http://studio.mulesoft.org/r4/devkit[DevKit]
* link:http://studio.mulesoft.org/r4/addons/beta[Incubators]
* link:http://studio.mulesoft.org/r4/apikit[APIkit]
* link:http://studio.mulesoft.org/r4/studio-runtimes[Runtimes]
* link:http://studio.mulesoft.org/r4/api-gateway/[Gateway]
