= Anypoint Platform for APIs Release Notes
:keywords: release notes, apis, anypoint platform for apis, anypoint platform

This page contains the release notes for the link:/anypoint-platform-for-apis[Anypoint Platform for APIs], a multi-tenant end-to-end platform for enterprise API design, implementation, management, and engagement.

For any support issues, contact MuleSoft’s expert support team by signing in to the  https://anypoint.mulesoft.com/accounts/support[Anypoint Platform Portal]. To receive support, you must have an active subscription and an account for the Anypoint Platform. 

//For information on Analytics releases, see the link:/release-notes/anypoint-analytics-release-notes[Anypoint Analytics Release Notes].

=== Hardware and Software Requirements

The API Gateway requires *Java 7*. Refer to the link:/mule-user-guide/v/3.7/hardware-and-software-requirements[hardware and software requirements] for the on-premises API Gateway. Refer to the detailed link:/anypoint-platform-for-apis/configuring-an-api-gateway[configuration instructions] for the API Gateway.

The Anypoint Platform for APIs web application (https://anypoint.mulesoft.com/[https://anypoint.mulesoft.com]) supports the following browsers:

* Firefox (latest version)
* Chrome (latest version)
* Internet Explorer 11 and newer

== January 2016 Release

This release includes the following new features and functionality:

* Redesign of API management page which now makes more information available at a glance and provides a drop-down API version menu for easier access. The analytics panel has been removed, providing more space for the display of API management-related information. To access, you can use the navigation menu towards the top and right of the page.
* New applications management page, the single point of access for all client applications for an organization’s APIs. Explore and manage your client applications from here. To reach it you can use the navigation menu towards the top and right of the API management page.
* From the applications management page, clients can now add or remove owners of an application. This feature makes it
easier to keep information about applications up to date.
* Gateway Awareness and Policy Ordering. Policy configuration is now aware for the set of policies supported by the Gateway tracking your API proxy. Because of this, unsupported policies are not available to be applied, and applied policies that are not supported by the tracking gateway are highlighted so that you can easily detect and correct problems.

There are no new known issues or any changes that impact compatibility or that require migration considerations.

== November 2015 Release

This release has the following updates:

* IP whitelisting and blacklisting policies provide the option to specify a comma-separated list of IPs for bulk edits.
* API owners can modify the configuration of a policy without having to add or remove the policy every time
* Ability to select an API Gateway Cluster as the target of deployment from the API platform proxy auto-deployment window.


== September 2015 Release

This release includes the following new features and functionality:

* link:/anypoint-platform-for-apis/defining-sla-tiers[Layered SLAs]﻿ that can impose multiple limiting policies on the API.
* link:/anypoint-platform-administration/audit-logging[Audit Logging]﻿ of change events made within the API management and platform services capabilities of the Anypoint Platform.
* link:/anypoint-platform-for-apis/adding-terms-and-conditions[Adding Terms and Conditions] ﻿of an API Portal can now be defined in two different ways.
* Files and Attachments can be imported/exported to an link:/anypoint-platform-for-apis/engaging-users-of-your-api[API Portal]﻿.
* Improved API for portal search.

There are no new known issues or any changes that impact compatibility or that require migration considerations.

== April 2015 Release

The April 2015 release of the Anypoint Platform for APIs offers the following new feature:

You can now use *OpenAM* as a SAML 2.0 identity federation provider across the platform. Additionally, you can use OpenAM as an external OAuth 2.0 server if you are using link:/release-notes/gateway-1.3.2-release-notes[API Gateway version 1.3.2] or later. For more information, see link:/anypoint-platform-administration/setting-up-external-identity[Setting up External Identity].

== February 2015 Releases

There were two releases in the February 2015 timeframe for the Anypoint Platform for APIs.

=== February 24th Release

The February 24th release of the Anypoint Platform for APIs offers the following new features and functionality:

* *Improved API Portal Publishing Experience:* We have made improvements to the API portal publishing experience to make it more user-friendly. +
Specifically: 
** Simplified draft editing and publishing
** Ability to bulk publish and delete pages
** Now easier to preview the entire portal

=== February 18th Release

The February 18th release of the Anypoint Platform for APIs offers the following features and functionality:

* *New RAML Console:* We have made significant improvements to the RAML console to drive even greater developer productivity. We’ve redesigned the interface as well as introduced a number of new capabilities that makes using an API easier including the ability to add custom query parameters/headers as well as support for all OAuth 2.0 grant types.
* *Proxy Auto-Deployment to CloudHub Gateways*: As part of the configuration of a proxy, users can now automatically deploy the proxy to CloudHub (within the same organization) thus removing the need for manual configuration.

=== Known Issues in the February Releases

* APIkit's RAML console in Anypoint Studio is not yet updated with the new functionality described above. Updates to Studio can be downloaded by clicking *Help* and then *Check for Updates* in the Studio menu.
* Auto-deployment to CloudHub may fail for some users. If your deployment fails, simply retry the deployment. This issue was fixed shortly after this release.

== November 2014 Release

The November 2014 release of the Anypoint Platform for APIs offers the following new features and functionality:

* API Version deprecation
* Support for API Gateway 1.3
* Custom Terms and Conditions per API version
* Folder support in API Designer
* File import support in API Designer (Beta)
* Swagger file import and conversion in API Designer (Beta)
* Automatic role assignment from external groups via SAML assertion
* Improved SLA tier management workflow
* Improved proxy support for load balancing, shared port, and HTTPS configurations
* API Gateway logging enhancements for improved API request troubleshooting
* Proxy configuration UI enhancements
* Policy violation analytics tracking
* Stacked bar chart support in Analytics

=== Known Issues in the November 2014 Release

The following issues are already being tracked by our development team. See this list before reporting any issues with the platform.

* Custom policies are only supported on API Gateway version 1.3.
* In API Designer, when importing RAML files, an error may indicate that included files are not present. Clicking the included file resolves the error.
* Proxy applications generated prior to November 19th are not compatible with API Gateway version 1.3.
* If an API version that is being managed is deleted and then a new API is created with the same name and version name, the API Gateway must be restarted in order to manage the API version.
* When viewing a public portal for an API in an organization other than the one your user belongs to you, you may be required to login again.

== July 2014 Release

The July 2014 version of the Anypoint Platform for APIs offers the following new features and functionality.

* Single-sign on and all-new shared user interface across the platform.
* Self-sign up for Anypoint Platform organizations.
* link:/anypoint-platform-for-apis/configuring-an-api-gateway[New API Gateway distribution] with enhanced API auto-discovery, including auto-discovery for APIkit projects, and improved HTTP transport performance using an NIO-based transport.
* link:/anypoint-platform-for-apis/proxying-your-api[Automatic proxy generation] for API endpoints defined by HTTP, WSDL, and RAML.
* link:/anypoint-platform-for-apis/managing-users-and-roles-in-the-anypoint-platform[Fine grained permissions and role-based access] support from an administrative dashboard, as well as in-context permissions for API versions.
* link:/anypoint-platform-for-apis/browsing-and-accessing-apis[Streamlined application registration and management] for application developers.
* link:/anypoint-platform-for-apis/viewing-api-analytics[New, robust API Analytics] with customizable charts and dashboards and export capabilities.
* link:/anypoint-platform-administration/setting-up-external-identity[External identity management] support with PingFederate.
* link:/anypoint-platform-for-apis/applying-runtime-policies[Three new governance policies]: PingFederate Access Token Enforcement, JSON Threat Protection, XML Threat Protection.

This release includes selected limitations that you need to be aware of as you create new organizations and populate them with your API metadata.

=== Known Issues in the July 2014 Release

==== Localhost Behavior

Note that defining an endpoint using localhost has important behavior implications for on-premises deployments of APIs and proxies. Refer to link:/anypoint-platform-for-apis/localhost-behavior-on-the-api-gateway[Localhost Behavior on the API Gateway] for details.

==== Limitations

* The REST APIs for the Anypoint Platform for APIs are not currently exposed publicly for customer use.
* It is not possible to visit the Developer Portal or any public API Portals when signed in as a user of a different organization.
* Developers cannot currently revoke their contracts with API Versions, only API Version Owners have the ability to revoke and delete contracts.
* API Portals cannot currently be deleted.
* Throttling and Rate Limiting policies do not currently work for APIs or proxies deployed to multiple API Gateway workers in CloudHub.
* It is only possible to register new applications from a portal for a specific API version rather than globally from the main Developer Portal page.
* Batch approval of applications is not currently supported.
* Copying content from one API Version to another is not currently supported.
* The IP whitelisting and IP blacklisting policies do not function for endpoints defined with the Jetty transport.
* Session timeouts occur after a three-hour window irrespective of user activity.

==== Key Differences for Users Migrating from Previous Versions

If you have an existing Anypoint Platform for APIs account on a previous version, you need to migrate to this version during the migration period. Be aware of the following major differences between the previous versions and the July 2014 release:

* link:/anypoint-platform-for-apis/anypoint-platform-for-apis-glossary[Terminology] has changed to standardize around APIs and applications rather than services and consumers.
* Each API version now has only a single endpoint. 
* The administrative view of your API version (called the API Version Details page) is now accessible only to API Version Owners or Organization Administrators. The Developer Portal, containing the API Portals that you create and share, now acts as the developer-facing view of your API.
* link:/anypoint-platform-for-apis/applying-runtime-policies[Policy application] has been streamlined to a single step for each policy. Contract enforcement and related policies have been replaced with client ID and secret enforcement. SLA-based policies now incorporate client ID and secret enforcement automatically.
* link:/anypoint-platform-for-apis/browsing-and-accessing-apis[Application management] flows have changed. You can now set SLA tiers for automatic approval to reduce your management overhead. Manual approval is also available.
* link:/anypoint-platform-for-apis/viewing-api-analytics[Analytics] are now available only to Organization Administrators.
* Taxonomies, policy characteristic tags, and environments are deprecated.
* API Designer is now accessible through the API Version Details page rather than in the Developer Portal.

== See Also

* link:https://developer.mulesoft.com/anypoint-platform[Mule Community Edition]
* link:https://www.mulesoft.com/platform/studio[Anypoint Studio]
* link:http://forums.mulesoft.com[MuleSoft's Forums]
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]
* mailto:support@mulesoft.com[Contact MuleSoft]
