= Anypoint Platform On-Premises Edition 1.1.0 GA Release Notes
*December 16, 2015* +

== Description
Anypoint Platform On-Premises Edition takes all the power of the platform MuleSoft developed for the Cloud and enables companies to run the platform inside their data centers.  In this release we are releasing solutions for APIs, Runtime Management and Exchange. 

== Features
Anypoint Platform for APIs
The Anypoint Platform for APIs is a multi-tenant end-to-end platform for enterprise API design, implementation, management, and engagement.

=== Anypoint Runtime Manager
The Anypoint Runtime Manager On-Premise Edition enables users to enhance their unified monitoring experience by easily integrating their on-premises Mule servers and API Gateways with third parties’ monitoring tools, such as Splunk & ELK, for monitoring, analytics and governance.

=== Anypoint Exchange
The Anypoint Exchange enables users to publish and access Mule-related content within their own organization increasing visibility and reuse across organizations.

=== Anypoint Access Management
The Anypoint Access Management is an underlying platform solution that allows customers to seamlessly integrate their existing authentication provider for centralized user management.



= System Requirements
Operating system
RHEL 7.1 or greater
CentOS 7.1 or greater
Storage
20 GB for var/lib/docker
1 GB for home directory
Docker
Docker engine 1.6.2 or later
Docker Compose 1.3.1 or later
Identity management provider
OpenAM 11.0 or later
PingFederate  6.10, 7.1 or 7.2
LDAP v3
Network ports
80, 8080, 8081, 443, 8443
Mule Runtime Agent
	Version 1.2.1+


= Release Cadence
We expect to ship a new version of the Anypoint Platform with new features around 6 months apart. 

Given that the Anypoint Platform for On Premises is a snapshot of our Cloud solution, it will most likely not contain all the latest features developed for the cloud until a new version comes out with those. We cannot guarantee that all the Cloud Platform functionality will be available for On Premises, so we will highlight those differences as we have them. 

= Current differences with the Cloud Version
There are some differences between the current On premises release and the Cloud version. 

=== CloudHub/Applications
In the On Premise release, the CloudHub name has been changed to Applications as that is where you will be managing your applications and servers through the Anypoint Runtime Manager. 

=== Anypoint Exchange
This is a private version of Anypoint Exchange, so you will not be able to see the public content available in the Cloud Version. 



= Known issues
AGW-695 Currently the API Gateway 2.1.0 or earlier running on Java 7 will default to TLS 1.0 that will cause a problem to use it with the AnyPoint platform on premise. This issue will not be there if you run it on Java 8, or apply the patch created for this problem. 

