= Anypoint Connector DevKit 3.7.1 Release Notes

== New Features

* Add support for MuleContext injection into @Configs.
* Add support for Studio Containers when using NestedProcessor and List<NestedProcessor>.
* DSQL support for java.lang.Calendar in MEL expressions.
* Allow the usage of @Default() in @ConnectionKey parameters.
* @RunOnlyOn annotation support for disabling test execution on specified test environments.

== Fixed Issues

This release include fix more than 30 fixes. The most important ones are:

* Address the issue that connectors tests could not be executed with  -Pstrict-validation enabled.
* @Handler was not invoked when ProviderAwarePagingDelegate thrown exceptions.
* Compiling a connector using Java 8 fails with a NullPointerException in 3.7.0.
* The new release reports a clear message describing that Java 1.7.0 should be used.
* Several improvements on connection testing framework improving the error messages when parameters could not be serialised in “local” mode.
* Add support in Connector Testing Framework to handle the serialisation of processors parameters such as InputStream and others.
* Add support for test execution using Maven 3.3.
* @Disconnect was not called in the functional tests execution tear down. This could potentially create a connection leak during test execution.
* Include new test utility classes as part of the connector testing framework such as classes for metadata serialisation automation and credentials discovery.
