= Anypoint Studio January 2015 with 3.6.1 Runtime - Update Site 2 Release Notes
:keywords: release notes, anypoint studio


*<<Migration Guide, Skip to Migration Guide>>*

*February 25, 2015*

This January 2015 release is an update to the Studio January 2015 with 3.6.0 runtime, and complements the link:/release-notes/anypoint-studio-january-2015-with-3.6.0-runtime-release-notes[Anypoint Studio January 2015 with 3.6.0 Runtime Release Notes].

== Current Release Versions

[cols="3*", options="header"]
|===
|
| Enterprise Runtime
| Community Runtime

| ESB Runtime
| n/a
| n/a

| Studio
2+^| Version: January 2015 with 3.6.1 Runtime - Update Site 2 +
Build Number:  n/a

| Management Console
| n/a
| n/a

| Mule DevKit
2+^| 3.6.0

|===


== Fixed Issues

This update addresses the following issues:

* Descriptions for fields are now shown in DataSense Explorer.
* Studio no longer deletes SQL queries in a project when deleting global elements.
* A connector configuration now correctly creates in a project when switching between editors.
* The mule-deploy.properties file now updates when launching applications using Maven.
* The *Search RAML library* in an HTTP Connector configuration now correctly opens a new tab in the system browser.
* Fixed: Cannot edit a Run Configuration that has configured a missing Mule runtime.
* Fixed parsing of complex WSDLs for WS Consumer.
* Fixed NullPointerException when resolving Types with duplicate fields in Query Builder.
* Fixed NullPointerException when exporting/running a domain project that uses the Database component.

This release also supports the Mule ESB 3.6.1 runtime which addresses a critical security issue. You can install this by going to *Help* > *Install New Software* and selecting the *Anypoint Studio Update Site* update site.

== Migration Guide

This section presents configuration considerations you may want to adjust when migrating from a previous version of a Mule runtime, or previous version of Studio. mailto:support@mulesoft.com[Contact MuleSoft] if you have a question about a specific migration activity or concern.

To migrate from a previous version of Studio, use *Help* > *Check for Updates.*

== Support Resources

* For further details on Anypoint Studio with 3.6.1 Runtime, see the link:/release-notes/mule-esb-3.6.1-release-notes[Mule ESB 3.6.1 Release Notes]
* Refer to MuleSoft’s http://www.mulesoft.org/documentation/display/current/Home[MuleSoft Documentation] for instructions on how to use the new features and improved functionality in Anypoint Studio with 3.6.1 Runtime.
* Access MuleSoft’s http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal].
