= Anypoint Partner Manager 1.0.0 Release Notes
:keywords: partner, manager, 1.0.0

*January 2016*

Anypoint Partner Manager (APM) provides a single web-based user interface for managing link:/anypoint-b2b/anypoint-partner-manager#partner-settings[Partner Settings] and viewing B2B link:/anypoint-b2b/anypoint-partner-manager#message-tracking[Message Tracking] data for all B2B transactions between you and your trading partners.

== Compatibility

[width="100%",cols="50%,50%",options="header",]
|===
|Application/Service |Version
|Mule Runtime |Mule 3.6.0 and newer
|===

== Features and Functionality

* Integration into the Anypoint Platform top navigation bar.
* Support for Anypoint Permissions, Environments, Business Groups, and Entitlements.
* Added execution ID to expand ability to correlate multiple B2B-related events.
*- Local caching of partner manager settings.

== See Also

* link:http://forums.mulesoft.com[MuleSoft's Forums]
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]
* mailto:support@mulesoft.com[Contact MuleSoft]
