= Anypoint Partner Manager 1.0.0 RC1 Release Notes
:keywords: anypoint partner manager, b2b, portal, release notes

*November, 2015*

== Features

*  Style changes to conform better with MuleSoft UI style guides
*  Made field layouts in forms all single column
*  Eliminated collapsable sections of forms
*  Added lazy loading for pagination instead of paging controls for long lists (partners, transmissions)
*  Set default values where possible on partner settings forms to make quick setup easier
*  Added support for creating specialized setting for different transactions
*  Fixed bugs in metadata searching
*  Fixed bugs in correlation of acknowledgments for X12 and Edifact
*  Extended partner settings resolution logic to allow dynamically determining send/receive partner Ids and Message types from EDI message to support a single flow that processes messages from multiple partners
*  Simplified entry of  sender/receiver identifiers for X12/Edifact by allowing user to configure single Identifier of each type and filling in the send/receive id's automatically

For more information, please see 
link:/anypoint-b2b/anypoint-partner-manager[Introduction to Anypoint Partner Manager].

== Compatibility

[width="100%",cols="50%,50%",options="header",]
|===
|Application/Service |Version
|Mule Runtime |Mule 3.6.0 and above
|===

== Known Issues

* Anypoint Platform permissions, environments and business groups are not yet supported
