= Anypoint Service Registry R2 Release Notes
:keywords: release notes, service registry

April 22, 2013 

Welcome to Anypoint Service Registry, MuleSoft's multitenant service registry/repository and SOA governance tool. Read more about Anypoint Service Registry link:/documentation/display/current/Anypoint+Service+Registry[here].

== Document Revision History

April 22, 2013, v.1.0 initial publication.

May 23, 2013, v.1.1 revision to reflect minor release updates. 

*Updates in this revision:*

* Bug fixes
* Editing now disabled on endpoint URIs after initial creation
* Service Analytics screen is now visible to all users for all services, but users who are neither the service owner nor an organization owner will not be able to view consumer information on the analytics screen.

== New Features and Functionality

In R2, we introduce the following new features and upgraded functionality:

* *Embedded agent in Mule 3.4.* Mule 3.4 comes with support for Anypoint Service Registry out of the box, so there's no need to install anything during the setup process.
* *CloudHub support*. R2 offers out-of-the-box support between Anypoint Service Registry and CloudHub. More information.
* *Dynamic routing support for new Anypoint Service Registry endpoint.* Mule now supports dynamic routing of messages according the rules defined within the Service Registry using the new Anypoint Service Registry endpoint. 
* *Service analytics.* A new service analytics screen provides historical utilization data and graphs for service owners. link:/documentation/display/current/Service+Analytics[More information].
* *Contract approval workflow.* Contract requests now initiate a workflow approval process in which an owner of the service must approve or reject a new contract with a consumer. link:/documentation/display/current/Contract+Management[More information].
* *Social functionality.* The registry now offers the ability to leave reviews and ratings for services, giving developers more information by which to evaluate services. 
* *Custom environments.* Organization owners can configure organization-wide standard environment names. link:/documentation/display/current/Managing+Your+Organization+Settings#ManagingYourOrganizationSettings-ManagingEnvironments[More information].

== Hardware and Software System Requirements

Please refer to the detailed setup instructions in the setup guide for ESB on-premise or the setup guide for CloudHub.

Supported browsers for the Anypoint Service Registry application (https://registry.mulesoft.com%29/[https://registry.mulesoft.com)] are as follows:

* Firefox (latest version)
* Chrome (latest version)
* IE 9 (10 is preferred)

== Important Notes and Known Issues in this Release

This list covers some of the known issues with Anypoint Service Registry. Please read this list before reporting any issues you may have spotted.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|JIRA |Issue |Workaround
|HABITAT-247 |Once SLA tiers are defined for a service, the registry does not permit contracts unless a tier is selected. |Service owner can delete existing tiers, allow the contract to be requested while no tiers are defined, and then reinstate the tiers after the contract request has been made. Any contracts that were made on the tiers before their deletion will not be affected.
|HABITAT-300 |When an endpoint URI is edited, policy characteristics persist but you can no longer see or edit the policy that is applied. |If you have policies applied at the endpoint level and need to change the endpoint, add a new endpoint with the new URI, apply the policies there, then delete the old endpoint.
|HABITAT-333 a|
The registry does not recognize endpoints of http proxies using `inboundAddress` and `outboundAddress` elements.

 a|
Define a proxy using the following method:
[source,xml, linenums]
----
pattern:http-proxy name="http-proxy-sample">
  <http:inbound-endpoint address="http://localhost:8090/stockQuoteSearch" />
  <http:outbound-endpoint address="http://query.yahooapis.com/v1/public/yql" />
</pattern:http-proxy>
----

|HABITAT-346 |When performing dynamic lookup using contractId, metadata is not taken into account |None.
|  |Users running Mule ESB Standalone in a non-clustered Windows environment may encounter a bug while using Service Analytics. |Download a patch from your http://www.mulesoft.com/support-login[customer portal].
|===

== Support Resources

Please refer to the following resources for assistance using Anypoint Service Registry.

=== Documentation

Refer to the link:/documentation/display/current/Anypoint+Service+Registry[documentation] for instructions on how to use Anypoint Service Registry.

=== Getting Help

To access MuleSoft’s expert support team, log in to the http://www.mulesoft.com/support-login[Customer Portal].

=== Sending Feedback

Send MuleSoft feedback about Anypoint Service Registry by clicking the *Send Feedback* link in the lower right corner of any screen in the application.
