= Anypoint Connector DevKit Studio Plugin 1.1.1 Release Notes
:keywords: devkit plugin, release notes, connector, ctf

== New Features

* Makes it easy to apply the connector testing framework (CTF) to a connector project by scaffolding test generation. Since test generation didn’t support CTF previously, developers needed to create CTF-compatible test cases manually. Please see link:/anypoint-connector-devkit/v/3.7/developing-devkit-connector-tests[Developing DevKit Connector Tests] for more information.
* Adds DevKit 3.7.2 support.
* Enables new DevKit components to be configured while a connector is created.

== Fixed Issues

This release includes several fixes, and the most important ones are listed here:

* Improves error reporting on WSDL formats that SOAP Connect doesn’t support. The previous version let developers create a SOAP Connect project with RCP-based WSDLs even if these WSDLs were not supported. A user only saw an error message after he or she put the SOAP Connect-based connector in a Mule flow and tried to select an operation. DevKit Plugin version 1.1.1 now shows a proper error message for unsupported WSDL formats, and halts creation of the SOAP Connect project.
* SOAP Connect supports WSDLs located in folders with whitespace in the path name.
* Properly uninstalls a multi-module connector.
