:keywords: arm, runtime manager, release notes

= Anypoint Runtime Manager 1.3.1 Release Notes

The Anypoint Runtime Manager, V1.3.1, is a minor release that includes performance enhancements, bug fixes, and native support for Splunk’s http event collector in our handler.

[NOTE]
This release is only available for the cloud version of the Runtime Manager, accesible online through the link:https://anypoint.mulesoft.com/#/signin[Anypoint Platform]. It's not yet available for the link:/anypoint-platform-on-premises/v/1.0/[On Premises version] of the Runtime Manager.

== Hardware and Software Requirements

No change.

== Compatibility


Agent plugins integrations is compatible with the following runtime versions:

[cols="2*a"]
|===
|Mule | 3.6.x and above
|API GateWay | 2.x and above for API Analytics
|Mule Agent | 1.1.0 and above, 1.3.0 and above for Clustering visibility improvements.
|===


== Features and Functionality

* *Splunk handler enhancement*: Added support for Splunk’s TCP and HTTP Event Collector, so Splunk users can easily and securely send events from MuleSoft’s platform into Splunk.
* *JMX handler enhancements*.


== Deprecated Features or Functionality

None.

== Resolved Issues

Includes usability, performance enhancements, and bug fixes.

* CHHYBRID-591: Applications in “Failed” state can now be started
* CHHYBRID-963: User can no longer create Server Groups or Clusters if servers have different agent versions
* CHHYBRID-1107: Behavioral improvements while redeploying of domains in the Mule Agent
* CHHYBRID-1135: Server deletion enhancements.
* CHHYBRID-1176: Users with no permission to see the “Servers” page will now be re-directed.
* CHHYBRID-1180: Ability to upload large applications without affecting performance.
* CHHYBRID-1198: Memory optimization while deploying an app
* CHHYBRID-1209: Fixed ability to configure Plugins when Event Tracking Level is None.
* CHHYBRID-1218: Fixed error when a user wants to perform an action in the deployment
* CHHYBRID-1223: Fixed enabling the agent plugin for Mule Agent versions that are greater than 1.2.0
* CHHYBRID-1226: Clusters created in 1.2.0 cannot be deleted in 1.3.0
* CHHYBRID-1233: Correct positioning of Failed message when an application fails

== Migration Guidance

No migration required.
