= Anypoint Service Registry R1 Release Notes
:keywords: release notes, service registry

February 22, 2013

We are excited to announce the availability of Anypoint Service Registry, MuleSoft's multitenant service registry/repository and SOA governance tool. Access the full details in our link:/documentation/display/current/Anypoint+Service+Registry[Anypoint Service Registry documentation].

== Document Revision History

February 22, 2013, v.1.0 initial publication.

== Hardware and Software System Requirements

To run Anypoint Service Registry, you need a valid *Enterprise Edition* license for *Mule ESB 3.3.2* as well as an additional license and login credentials for Anypoint Service Registry, which you can obtain from mailto:support@mulesoft.com[MuleSoft] during your installation process. Please refer to the setup guide for detailed setup instructions.

[NOTE]
====
Note that at this time, Anypoint Service Registry is fully supported with *Mule ESB EE 3.3.2 standalone only*. You can build applications in Mule Studio, but to deploy them for integration with Anypoint Service Registry, export them as zip files and deploy them from Mule ESB 3.3.2 standalone.

Runtime integration with CloudHub is not yet supported in this release. If you are interested in using Anypoint Service Registry with CloudHub, please mailto:support@mulesoft.com[contact us] to participate in the Beta program.
====

The Anypoint Service Registry application (https://registry.mulesoft.com) is compatible with the following browsers:

* Firefox ESR 17.0.1+
* Chrome 20+
* IE 9 (10 is preferred)


== Important Notes and Known Issues in this Release

This list covers some of the known issues with Anypoint Service Registry. Please read this list before reporting any issues you may have spotted.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|JIRA |Issue |Workaround
|HABITAT-79 |Setting a throttling or rate limiting policy to 0 requests per time period causes errors. |Set throttling or rate limiting policies to 1 request or greater.
|HABITAT-84 |If you edit or delete an SLA tier on which a contract has already been based, the contract terms will not change, but neither the consumer owner or service owner will have access to the details of the contract terms. |Do not edit the terms or delete SLA tiers that have active consumer contracts. Instead, create a new tier with the revised information desired and edit the old tier only to change the description field to indicate it is a deprecated tier.
|HABITAT-94 |Editing a service summary from the service main screen by adding a very long string causes the edit button to disappear. |Restrict summaries to 150 characters. Put longer descriptions in the Description field.
|HABITAT-115 |The same taxonomy may be applied multiple times to the same service. |Delete extra occurrences as needed.
|HABITAT-117 a|

When adding metadata to endpoints in the New Service wizard, metadata is not persisted.

When editing endpoint fields in via the Edit dialog, the Update Endpoint button sometimes does not function and changes are not persisted. Upon returning to main screen, the edit icon for that endpoint is unclickable until screen refresh.

 a|
Create endpoints or edit metadata after the service is registered.

Refresh the screen and try again.
|===


== Support Resources

Please refer to the following resources for assistance using Anypoint Service Registry.

=== Documentation

Refer to the link:/documentation/display/current/Anypoint+Service+Registry[documentation] for instructions on how to use Anypoint Service Registry.

=== Getting Help

To access MuleSoft’s expert support team, log in to the http://www.mulesoft.com/support-login[Customer Portal].

=== Sending Feedback

Send MuleSoft feedback about Anypoint Service Registry by clicking the *Send Feedback* link in the lower right corner of any screen in the application.
