= Anypoint Data Gateway Release Notes
:keywords: release notes, data gateway


== Support

* To obtain support for this product, please send an email to datagatewaysupport@mulesoft.com
* You may also refer to the link:/anypoint-data-gateway/v/1.3.0/index[Anypoint Data Gateway].
* For known issues and workarounds, see link:/anypoint-data-gateway/v/1.3.0/troubleshooting-data-gateway[Troubleshooting Data Gateway].

== December 5, 2015 Release


*_Version 1.3.1_*

We are excited to announce the next release of Anypoint Data Gateway. This release adds tighter integration with the Anypoint Platform, adding trials and enterprise users controls. It also features many UI improvements including an all new copy objects feature.

=== Features and Functionality

==== Copy Objects feature

Data Gateway allows you to copy an object from one gateway to another. This feature is especially useful when working with multiple environments that you wish to maintain in a similar state, such as a development and a production environment.

==== Cloud Extender authenticated proxy support

Cloud Extender has been enhanced to support authenticated or transparent proxies, making it possible to expose your internal datasources through Data Gateway in an easy and friendly way.

==== UI improvements

The latest release includes several UI improvements such as:
* Empty states indicators.
* Environment dropdown changes.
* Link to the subscription page.

==== Self service

Now the users can request a subscription through a link in the left navigation bar.

==== Link to Support

A new link to request support has been included in the top navigation bar, allowing enterprise users to request support through the support portal in just one click.

=== Known Limitations

The same limitations of v1.2.1 apply to this version.

For more information, see the product link:http://www.mulesoft.com/press-center/anypoint-data-gateway[announcement].



== May 13, 2015 Release


*_Version 1.1.0_*

=== Features and Functionality

==== Cloud Extender

Cloud Extender is an agent that enables you to connect to your on-premise data source during the trial period without undergoing VPC configuration to evaluate the product. Cloud Extender relays data between Data Gateway and the data source within the private network through an SSH over HTTP tunnel. The advantage of Cloud Extender is that it eliminates the need to open ports in your firewall and that it configures itself automatically — all you have to do is run it.

==== UX/UI improvements

Several minor UI/UX fixes and improvements:

* Object edition buttons were moved into the object details view
* Synchronization against Salesforce is performed only for the profiles assigned to the current user
* Improved connection creation experience

==== Support for Mule ESB 3.6.1

This version works on top of the latest version of the Mule ESB.

==== Known Limitations

The same limitations of <<February 25, 2015 Release>> apply to this version.

For more information, see the product http://www.mulesoft.com/press-center/anypoint-data-gateway[announcement].

== March 11, 2015 Release

*_Version 1.0.1_*

Following the initial (1.0.0) release of Anypoint Data Gateway on February 25th, we have released version 1.0.1, incorporating user feedback, minor bug fixes and enhancements including:

* Improved Object creation and management:
** Support for assigning a primary key to an object when a primary key doesn't exist
** Fix around identifying primary keys when building objects on Oracle DB
** New validation logic to prevent creating 2+ objects with identical names (which would cause an error within Salesforce Lightning Connect)
* Improved Connections management:
** Ability to delete a connection
** Fix for Oracle DB connectivity issues

For all other known issues, prerequisites and product functionality, see the next section.

== February 25, 2015 Release
[1.0.0]
*_Version 1.0.0_*

We are excited to release the first version of Anypoint Data Gateway, built for link:https://www.youtube.com/watch?v=OZWneVt_1Mk[Salesforce Lightning Connect]! You can install this product from link:https://appexchange.salesforce.com[Salesforce AppExchange].

== Hardware and Software Requirements

* Salesforce Lightning Connect Integration - Winter ‘14 release

== Compatibility

* Salesforce metadata API version 34+

== Features and Functionality

* Read-only connectivity and virtualization of SAP R/3 data by Remote Function Call (RFC)
* Read-only connectivity and virtualization of OracleDB, SQL Server, DB2, and MySQL
* Anypoint Gateway Designer: a browser interface for:
** Configuring connections to application and database sources.
** Creating gateways to connect to Salesforce.
** Designing External Objects for use in Salesforce forms, search, workflow, and reporting.
* Automated configuration of External Data Sources and External Objects within Salesforce Lightning Connect admin settings.
* Support for seamless and secure connectivity to on-premises data sources through use of Virtual Private Cloud (VPC).
* Ability to secure and throttle Data Gateway services through integration to the MuleSoft Anypoint Platform, and API Management functionality

== Known Issues - All Versions

For known issues, see link:/anypoint-data-gateway/v/1.3.0/troubleshooting-data-gateway[Troubleshooting Data Gateway].
