= Anypoint Studio 5.3 with 3.7.2 Runtime Update Site 1 Release Notes
:keywords: studio, release, notes

*September, 2015*

This update includes a number of bug fixes and performance enhancements. For API Gateway users, this also includes enhancements to auto-create a local API gateway domain for projects which need to share HTTP connector configurations.


== Current Release Versions

[width="100%",cols="40a,30a,30a",options="header"]
|===
| |Enterprise Runtime|Community Runtime
|ESB Runtime|3.7.2 EE|3.7.0 CE
|Anypoint™ Studio
2+|Version: 5.2.1 +
Build Number:
|Management Console
2+|n/a
|Mule DevKit
2+|3.7.0
|APIkit
2+|version: 1.7.0
|===


== Migration Guide

This section presents configuration considerations you may want to adjust when migrating from a previous version of a Mule runtime, or previous version of Studio. Contact MuleSoft if you have a question about a specific migration activity or concern.

From the previous versions of Studio 5.1.0, 5.1.1, 5.2.0, 5.2.1, to 5.3.0 there is no special migration needed, but when opening a previous Workspace with projects that were created with Studio 5.1.0 or older, and which has metadata stored in disk, Studio asks you to perform an update to all the projects so that the New Metadata Manager can handle the types and to show the types in your project.

[NOTE]
Studio as an Eclipse plugin only works with Eclipse 4.3 or 4.4 due to an SWT dependency.


== Hardware and Software System Requirements

* This release does not change the hardware and software system requirements established by the 3.6.1 Runtime.

* MuleSoft recommends a minimum of 4 GB RAM on a developer workstation. As applications become complex, consider adding more RAM. mailto:support@mulesoft.com[Contact MuleSoft] with any questions you have about system requirements.

* This version of Anypoint Studio requires Java 7.
*Note*: If you are installing Anypoint Studio on a Mac computer with OS X that has no Java installed, the OS may require that you first download and install link:http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase6-419409.html[JDK 1.6]. Install JDK 1.6 first and then install JDK 1.7.

== Deprecated in this Release

* Nothing was deprecated in this release.

== Bug Fixes

* [STUDIO-6906] - When running the APIKit scaffolder without changes in the raml file, xml content is duplicated.
* [STUDIO-6987] - Support for having multiple projects that implement the same domain (api-gateway default domain)
* [STUDIO-7040] - Metadata: when searching for a JSON sample, the file browser filters for schemas.
* [STUDIO-7045] - Error when creating a new project: Resource main folder is not found.
* [STUDIO-7062] - [External References] Test Connection of an imported database configuration is not working.
* [STUDIO-7067] - Apikit NPE when trying to get RAML file location.
* [STUDIO-7068] - [SE-1957] mule-deploy.properties set to ignore in .gitignore file.
* [STUDIO-7069] - NPE when importing a project using General Import.
* [STUDIO-7070] - Datasense is not working with Schemas in APIkit.
* [STUDIO-7071] - [External References] External references not correctly refreshed when
 adding a jar via maven.
* [STUDIO-7072] - When importing a project, it cannot be built because of missing files.
* [STUDIO-7094] - Validation with DataWeave freezes studio.
* [STUDIO-7099] - When right clicking on ErrorLog/Problems/Console views, the options for "Apikit" and "Domain" appear.
* [STUDIO-7107] - [DataWeave] Editor has significant delays when autocompleting content.
* [STUDIO-7110] - [DataWeave] Preview does not work with Gateway Server.

== See Also

* link:https://developer.mulesoft.com/anypoint-platform[Mule Community Edition]
* link:http://studio.mulesoft.org[Anypoint Studio]
* link:http://forums.mulesoft.com/[MuleSoft Forums]
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]
