= API Gateway Runtime 2.0.2 Release Notes
:keywords: api gateway, connector, release notes

MuleSoft is pleased to announce the 2.0.2 release of the API Gateway runtime. This release mainly includes bug fixes and performance improvements.

== Compatibility

* ESB Runtime 3.7
* APIKit 1.7
* Anypoint Studio 5.2

== New Features

* AGW-500: New variable named _agwTokenContext available after the token has been validated against any of the federated policies.

== Fixed In This Release

* AGW-491: Example WSDL proxy is not working with gzipped payloads
* AGW-486: UnsupportedOperationException when there is an error sending the policy violations to analytics
* AGW-397: External AES: NullPointerException when running in offline mode


== Migration Guide From 1.3.x

Refer to link:/release-notes/gateway-2.0-release-notes[API Gateway Runtime 2.0 Release Notes]


== See Also

* Learn more about the link:/anypoint-platform-for-apis/api-gateway-101[API Gateway Runtime]
* link:/release-notes/api-gateway-2.0-release-notes[API Gateway Runtime 2.0 Release Notes]
