= API Gateway Runtime 2.1.0 Release Notes
:keywords: api gateway, connector, release notes

MuleSoft is pleased to announce the 2.1.0 release of the API Gateway runtime. This release mainly includes bug fixes and performance improvements.

== Compatibility

* ESB Runtime 3.7.2
* APIKit 1.7.2
* Anypoint Studio 5.2

== New Features

* AGW-185: Implement policies support for connectors.
* AGW-249: Put a limit (anypoint.platform.analytics_batch_size) on the analytics events batch events count.
* AGW-412: On link:/anypoint-platform-for-apis/api-auto-discovery[API Auto-Discovery], add a flag to allow the possibility to disable API creation.
* AGW-421: Add a unique key to the Analytics event data
* AGW-434: link:/anypoint-platform-for-apis/defining-sla-tiers[Layered Policies]
* AGW-496: Ability to configure CORS on an link:/anypoint-platform-for-apis/building-an-external-oauth-2.0-provider-application[External OAuth 2.0 Provider Application]
* AGW-500: Save token context after successfully validated against any of the federated policies
* AGW-501: Add property to enable analytics in wrapper.conf
* AGW-511: Analytics Events available for external consumption
* AGW-556: When there is a Parse exception when a policy is applied, policy should remain on policies folder.
* SE-2100: Add debug logging info to trace communication with Ping Federate


== Fixed in This Release

* AGW-406: Ping Federate logging improvement
* AGW-407: OpenAM logging improvement
* AGW-429: Stacktrace should not be shown when validating user credentials
* AGW-470: Client App client ID and secret are shown in logs when using SLA based policies.
* AGW-485: Trim properties values in wrapper.conf
* AGW-541: Rate Limit reset header should always shown the remaining window time.
* AGW-551: Analytic events are not sent when client is validated online
* SE-2581/AGW-567: java.lang.IllegalStateException in APIPlatformValidateClientFilter.handleError()
* AGW-570: Throttling and Rate Limiting policies are not applied to the correct pointcut
* AGW-587: OAuth's client store is not populating the client name
* AGW-589: Gateway logs: "Unexpected error occurred. Reason: null"


== Migration Guide From 1.3.x

Refer to link:/release-notes/api-gateway-2.0-release-notes[API Gateway Runtime 2.0 Release Notes]

== Troubleshooting
* `com.mulesoft.module.client.autodiscovery.AutoDiscoveryDeploymentListener: "uriTemplate" parameter is null.`: When using an older version of the wrapper.conf, one of the 3 URLs for connecting to Anypoint Platform might be missing (In 2.1.0 they are required). Check the wrapper.conf file and make sure that the following properties are set as follows (default distribution configuration):
** `wrapper.java.additional.15=-Danypoint.platform.platform_base_uri=https://anypoint.mulesoft.com/apiplatform`
** `wrapper.java.additional.16=-Danypoint.platform.coreservice_base_uri=https://anypoint.mulesoft.com/accounts`
** `wrapper.java.additional.17=-Danypoint.platform.analytics_base_uri=https://analytics-ingest.anypoint.mulesoft.com`


== See Also

* Learn more about the link:/anypoint-platform-for-apis/api-gateway-101[API Gateway Runtime]
* link:/release-notes/api-gateway-2.0.2-release-notes[API Gateway Runtime 2.0.2 Release Notes]
