= API Gateway Runtime to Mule 3.8.0-M1 Migration Guide
:keywords: api, gateway, mule, migration guide

As a result of the unification of the API Gateway Runtime with the link:release-notes/mule-runtime-3.8.0-m1-release-notes[Mule Runtime 3.8.0-M1] and several usability issues reported in previous Gateway versions, the default API Gateway domain is no longer bundled with the distribution. For the GA release of 3.8, a strategy will be provided for those users that still want to make use of the domain for sharing resources as they currently do. At the time of this milestone release, however, the auto generated proxies that can be downloaded from an API Version page in the Anypoint Platform still do reference a domain. Therefore, one of the following actions is required:

. Copy or link:_attachments/api-gateway.zip[download] the link:anypoint-platform-for-apis/api-gateway-domain[api-gateway domain] into the '<API-Gateway-home>/domains' folder.

. Modify the auto generated proxy to include a 'listenerconf' global element within the proxy itself, instead of referencing the one declared in the domain. You should include the following line:
+
[source,xml,linenums]
----
<http:listener-config name="http-lc-0.0.0.0-8081" host="0.0.0.0" port="8081" protocol="HTTP"/>
----

When doing this you must also modify the domain in the 'mule-deploy.properties' file to reference the *mule default domain* instead of the *api-gateway domain*, which no longer exists.

[NOTE]
For the milestone release 3.8-m1, the 1 click deploy to CloudHub is not available due to the manual steps necessary to resolve the problem with domains.


== See Also

* Learn more about the link:/anypoint-platform-for-apis/api-gateway-101[API Gateway Runtime]
* link:/anypoint-platform-for-apis/configuring-an-api-gateway[Configuring an API Gateway]
* link:/anypoint-platform-for-apis/api-gateway-domain[API Gateway Domain]
* link:/mule-user-guide/v/3.7/shared-resources[Shared Resources]
* link:http://forums.mulesoft.com[MuleSoft's Forums]
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]
* mailto:support@mulesoft.com[Contact MuleSoft]
