= API Gateway 2.2.0 Release Notes
:keywords: api, gateway, 2.2.0, release notes

== Compatibility

[cols=",,",options="header"]
|===
|Software |Version
|Mule ESB Runtime |3.7.3
|APIkit |1.7.3
|Anypoint Studio |5.4.1
|ARM |1.3.1
|===

== New Features

* AGW-695: API Gateway client for API Platform needs to be able to connect in Java 7 only supporting TLS 1.1 and 1.2
* AGW-663: GW should track all response codes in Analytics
* AGW-646: Refactor to improve scalability by adding a new API to retrieve the contracts
* AGW-633: Add new policies to add and remove HTTP request and response headers (available on Exchange)
* AGW-603: Improve logs to include API name and version name
* AGW-514: As an API owner, I would like to be able to set the order of execution so that I can control which policy is applied in which order
* AGW-414: Gateway proxies should return “504 Gateway timeout” when HTTP outbound throws timeout exception
* AGW-154: Add wrapper option to prevent client_ip address from going to Analytics
* AGW-98: Implement request caching policy (available on Exchange)
* AGW-202: Add fast deploy for Gateway on Cloudhub
* AGW-636: Support DataWeave in custom policies


== Fixed in This Release

* AGW-708: Analytics are not being sent when using a RAML proxy
* AGW-702: XSD Schema not found when hosted locally in SOAP API Proxy
* AGW-700: Performance degradation when analytics is enabled
* AGW-699: Property placeholder not being passed to encryption module
* AGW-694: ClassCastException when using multiple X-Forwarded-For headers with IP filtering policy and MEL
* AGW-692: Id attribute in auto-discovery is required
* AGW-691: Splunk Events showing wrong status code when policy is violated
* AGW-676: Analytics not being sent when the request has multiple values for X-Forwarded-For
* AGW-668: Sometimes policy changes are detected
* AGW-665: Non-SLA Rate Limiting and throttling policies don’t update the limit value for GW in Cluster
* AGW-644: Enricher in custom policy fails when enricher element has no target attribute
* AGW-660: WSDL Proxy not using default 443 port when service is https
* AGW-625: Gateway removing policies when is unable to parse its contents correctly
* AGW-615: Custom policies are not picking up common beans defined in the default-mule-config.xml
* AGW-605: Message access violation when using enricher in custom policy
* AGW-602: Platform error on the log
* AGW-599: Some headers are removed when a response is caught by an exception strategy
* AGW-598: Endpoint protected with Basic Authentication policy doesn’t generate policy violations
* AGW-594: null error when running a project with auto-discovery
* AGW-593: Gateway keeps logging error: “The template variable ‘orgId’ has no value”
* AGW-557: If a tracked API is deleted from API Platform an unexpected error logs indefinitely
* AGW-502: Content-Length should not be propagated as is by the proxy (this reverts a change in 2.1.0 to propagate it)
* AGW-616: Wrong error message when API Platform URLs are not configured in wrapper.conf
* AGW-614: There is no log when a policy was correctly applied/un-applied
* AGW-608: Analytics is not working when running Gateway on Windows

== Security Improvements in This Release

* AGW-734: Remove TLS v1.0 support from tls-default.conf

== Known Issues

* On premises 1.1.0 or earlier have no support for the new Contract Service improvement included in this version. This means that policies that are contract based are not going to work on premises for these versions. 


== Migration Guide from 1.3.x

For information on migrating from previous releases, see:

* link:/release-notes/api-gateway-2.1.0-release-notes[API Gateway Runtime 2.1.0 Release Notes]
* link:release-notes/api-gateway-2.0-release-notes[API Gateway 2.0 Release Notes].

== See Also

* Learn more about the link:/anypoint-platform-for-apis/api-gateway-101[API Gateway Runtime]
* link:/anypoint-platform-for-apis/configuring-an-api-gateway[Configuring an API Gateway]
* link:/anypoint-platform-for-apis/api-gateway-domain[API Gateway Domain]
* link:http://forums.mulesoft.com[MuleSoft's Forums]
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]
* mailto:support@mulesoft.com[Contact MuleSoft]
