= APIKit 2.0 Beta 1 (with OData Extension 0.9) Release Notes

October 28, 2015

We are excited to release APIKit 2.0 Beta 1. This release features a new APIKit extension, which allows you to easily create data-oriented RESTful APIs and expose OData endpoints. Following a few simple steps, you can define your data model in Anypoint Studio, then use APIKit to generate the full REST API and expose the OData endpoint. You can then register and manage this API within the Anypoint Platform. Furthermore, OData endpoints feature complete support for Salesforce Lightning connect through the OData API, as well as any other OData consumer.

== Hardware and Software Requirements

* Mule 3.7.x runtime or later
* The latest version of link:https://www.mulesoft.com/platform/studio[Anypoint Studio]
* APIKit with OData Extension, which you download from within Studio (see the link:anypoint-platform-for-apis/creating-an-odata-api-with-apikit[instructions] for details)
* The latest version of link:https://maven.apache.org/download.cgi[Maven]

== Features and Functionality

* Define your data model and scaffold your API. From your data model, APIKit generates a full API with a corresponding RAML file and flows, and also automatically generates API documentation for the RAML file.
* Support for both REST and OData endpoints through the same APIKit component and HTTP/HTTPS endpoint.
* Support for Salesforce Lightning Connect, as well as any other OData consumer.

== Known Issues

* Currently, this release is only supported on Mule 3.7. It does not yet support API Gateway. API Gateway support is planned for the next release of APIKit.
* This Beta only supports dates in the ISO Format (i.e. `yyyy-MM-dd HH:mm:ss.S`). Extended support for custom formats is planned for the General Availability (GA) release.
* Fields within query string parameters are not validated within APIKit, but passed to the implementation for handling. Adding field name validation within APIKit is planned for the GA release.
* Mule ESB does not attach reason messages to the HTTP status codes. This may lead to some browsers (i.e. Chrome) to fill the blank with an “OK” even when there was a 4xx or 5xx status code. When dealing with HTTP responses, only the status code should be taken as the effective response for the request; the attached reason should be discarded.

== Support
See the product link:anypoint-platform-for-apis/creating-an-odata-api-with-apikit[documentation].
