:keywords: arm, runtime manager, release notes

= Anypoint Runtime Manager Sep 2015 (V1.2) Release Notes

The Anypoint Runtime Manager On-Premise Edition September 2015 release enables users to enhance their unified monitoring experience by easily integrating their on-premises Mule servers and API Gateways with third parties’ monitoring tools, such as Splunk & ELK, for monitoring, analytics and governance.

== Hardware and Software Requirements

No change.

== Compatibility

Agent plugins integrations is compatible with the following runtime versions:

* Mule Agent 1.2.0 and above
* Mule 3.6.x and above
* API GW 2.1.x for API Analytics

== Features and Functionality

=== Agent Plugins Integration (Splunk & Log)

Users will now have the ability to monitor their applications with an out-of-the box integration experience for monitoring tools such as Splunk & ELK. This enables the user to have a unified view of all applications, servers, etc.

=== API Gateway Integration

Users now have the ability to integrate their API Gateway with Agent/ARM and pass API Metrics for analytics and governance.

=== Deprecated Features or Functionality

None.

=== Resolved Issues

* Bug fixes for error while deleting servers
* Reconnection strategy for Agent
* Usability improvements while creating server groups

== Migration Guidance

See link:/mule-agent/v/1.1.1/installing-mule-agent#agent-update-process[updating the Agent].

== Known Issues

* No way to configure buffering support for Splunk from the UI.

*Workaround*: Use YAML file for configuration.

== Support

No change.
