= CloudHub Connector Release Notes
:keywords: cloudhub, connector, release notes

_Community_

The CloudHub connector provides the ability to interact with Mule CloudHub from within a Mule application. There are operations to deploy, start, stop, and update applications as well as send notifications from your Mule application to CloudHub.

== Version 2.0 - July 30, 2015

The CloudHub connector 2.0 is compatible with:

Software|Version
MuleSoft Runtime|3.5.3, 3.6.2, and 3.7.x

== Version 2.0 - Upgrading to Version 2.0 of the Connector

When a new version of a connector is released, Anypoint studio displays a popup in the bottom right corner of you screen with the following message: Updates Available.

To upgrade to version 2.0 of the CloudHub connector:

. Click the popup and check for the available updates.
. Select the CloudHub Connector 2.0 checkbox and click Next.
. Follow the instructions provided by the user interface.
. Restart Studio when prompted.
. After restarting, if you have several versions of the connector installed, Mule asks you for the version of the connector you like to use.

=== Version 2.0 - Features and Fixes

* Added multi configuration support:
** Basic Authentication: Authenticates using username and password.
** Inherited Token Authentication (for CloudHub only): Doesn't require configuration; retrieves the token from the CloudHub instance.
* Added the following new processors:
** Create Application: Creates an application without deploying a Mule application.
** Create And Deploy Application: Creates and deploys a Mule application.
** Change Notification Status: Changes the status (Read or Unread) of a notification.
** Change Application Status: Changes the status (Start or Stop) of an application.
** Get Notification: Retrieves a notification by their ID.
** Retrieve Application Log: Retrieves the log from an application.
* CloudHub connector as a Source: Added the operation to pool for notifications.
* Deleted the following processors:
** Start application: Migrated to Change Application Status processor.
** Stop application: Migrated to Change Application Status processor.
** Dismiss notification: Migrated to Change Notification Status.
* Modified the following processors:
** Create notification: Now the domain needs to be provided. To have the same behavior for CloudHub instances, use `${domain}` place holder.
** Create tenant: Now the Tenant configuration can only be filled by reference.
** Deploy application: Now only deploys application, and cannot modify anymore CloudHub configuration. To modify a CloudHub configuration, use Update Application.
** List notifications: Now the domain needs to be provided. To have the same behavior for CloudHub instances, use the `${domain}` place holder.
** List tenants: Now the Tenant configuration can only be filled by reference.
** Update application: Modified to comply with the existing CloudHub API.

=== Version 2.0 - Known Issues

The use of application Domain has become mandatory in many operations. This breaks backwards compatibility with older applications, but it’s due to a CloudHub requirement and cannot be removed.

== See Also

* Learn how to Install Anypoint Connectors using Anypoint Exchange.
Access MuleSoft’s Forum to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, subscribe to Mule ESB Enterprise and log into MuleSoft’s Customer Portal.
