= CloudHub Release Notes
:keywords: release notes, cloudhub, cloud hub

In addition to these release notes, see the complete link:/cloudhub[CloudHub] documentation.

== November 2015 R45

The CloudHub November 2015 (R45) release features static IP self service, whereby CloudHub users will be able to assign static IP addresses to their applications. CloudHub users will also be able to pre-allocate static IP addresses to an application before it’s deployed (for example, in a different region). 

=== Hardware and Software Requirements

No change.

=== Compatibility

All supported Mule and API Gateway runtimes will have this new feature. 

=== Features and Functionality

* *Static IP Self Service*: CloudHub users will be able to assign static IP addresses to their applications, including pre-allocation of static IP addresses before an application is deployed. This will enable customers to set up network security rules for an application before it’s deployed.   
* *New Logs Screen Improvements*: Various improvements in the UI for enhanced log infrastructure.
* *Enhancements to Log Aggregator Services*

=== Deprecated Features or Functionality
None.

===	Resolved Issues

* SE-2892: vCores cannot be changed on a running application in a Business Group 
* SE-2406: Console logs not updated after the last restart
* SE-2874: Priority for alerts getting reset
* ION-4625: Accounts Expiration - search in Enhanced Logs with expired account gives 403 response
* ION-4626: Enhanced Logs search - searched term not highlighted

=== Migration Guidance

No migration required. 


== August 2015 R44 Update 2

The CloudHub August 2015 (R44) Update 2 release includes the Anypoint Runtime Manager (ARM) 1.2. This release enables users to enhance their unified monitoring experience by easily integrating their on-premises Mule servers and API Gateways with third parties’ monitoring tools, such as Splunk & ELK, for monitoring, analytics and governance.

=== Hardware and Software Requirements

No change.

=== Compatibility

Agent plugins integrations is compatible with the following runtime versions:

* Mule Agent 1.2.0 and above
* Mule 3.6.x and above
* API GW 2.1.x for API Analytics

=== Features and Functionality

==== Agent Plugins Integration (Splunk & ELK)

Users will now have the ability to monitor their applications with an out-of-the box integration experience for monitoring tools such as Splunk & ELK. This enables the user to have a unified view of all applications, servers, etc.

==== API Gateway Integration

Users now have the ability to integrate their API Gateway with Agent/ARM and pass API Metrics for analytics and governance.
R44 Update 2 fixes:

* Bug fixes for error while deleting Servers
* Reconnection strategy for Mule Agent
* Usability improvements while creating Server Groups



=== Deprecated Features or Functionality

None.

=== Resolved Issues

* Bug fixes for error while deleting servers
* Reconnection strategy for Agent
* Usability improvements while creating server groups

=== Migration Guidance

See link:/mule-agent/v/1.1.1/installing-mule-agent#agent-update-process[updating the Agent].

=== Known Issues
No way to configure buffering support for Splunk from the UI. Workaround: Use YAML file for configuration.

=== Support

No change.


== August 2015 R44 Update 1

The CloudHub August R44 Weekly 1 release on 25 August 2015 provides these features:

* Enabled enhanced log management by default for new applications created under Mule 3.5.3, 3.6.2, 3.7.0, and API Gateway 2.0.3 (and newer)
* Added tooltip over disabled versions
* Improved performance of logs scroll function

* Back to search automatically scrolls to last search result
* Reduced logs font
* Thread name to the log line info

R44 W1 fixes:

* SE-2628: Fixed apiFabric entitlement and settings for business groups
* SE-2608: Users with read only access can still see settings

== August 2015 R44

The CloudHub August (R44 on 15 August 2015) release features an upgrade to the  log infrastructure  featuring higher limits for log storage, and a new improved UI. Anypoint Management Center also now supports on-premise clusters.


=== August 2015 Compatibility

The new log infrastructure supports the following (and newer) runtimes:

* Mule 3.5.3
* Mule 3.6.2
* Mule 3.7.1
* API Gateway 2.0.3

Clustering in Anypoint Management Center supports the following (and newer) runtimes:

* Mule 3.7.x
* API GW 2.0.2

=== August 2015 Features and Functionality

This release provides the following features and functionality.

==== August 2015 Enhanced Logging

With the August 2015 Release of CloudHub, you can use an improved logging infrastructure for select Mule and API Gateway runtimes. The new logging infrastructure features higher log retention - 100 MB or 30 days worth of logs per application, whichever limit is hit first - as well as a new and improved UI. For more information, see link:/cloudhub/viewing-log-data[Viewing Log Data].

==== August 2015 Clustering Support

With this release, you csn configure your on-premises Mule or API Gateway runtimes for high availability using clustering, from the CloudHub server management console. For more information, see link:/cloudhub/creating-and-managing-clusters[Creating and Managing Clusters].

=== August 2015 Deprecated Features or Functionality

None.

=== August 2015 Resolved Issues

* SE-2471 - Mule 3.6.2 applications no longer time out after upgrade from Mule 3.5.1
* SE-1949 - Mule 3.6.0 and 3.6.1 applications now permit log settings to be adjusted
* SE-2015 - Enhanced logging introduced to enable more log storage for Mule features

=== August 2015 Migration Guidance

No migration required. Enterprise customers automatically receive the new functionality.

=== August 2015 Known Issues

When an application that hosts APIs (including API proxies) is stopped, the API’s status within the API version details page appears as “active” even though it is stopped.
With enhanced logging enabled, to access an application’s log history past the most immediate 100 log lines, the instance logs need to be downloaded.

=== August 2015 Support

No change.

== June 2015 R43

The CloudHub June 2015 (R43) release features support for Business Groups and Hybrid management, with a single panel for managing applications and servers running in the cloud or on-premises.

=== June 2015 R43 - Compatibility

The Hybrid management functionality on CloudHub requires the new Mule Agent - which requires the Mule 3.6 or newer runtime, or the API Gateway 2.0 or newer.

Features and Functionality

=== June 2015 R43 - Hybrid Management

With the June 2015 Release of CloudHub, you can manage applications and runtimes both in the cloud and on-premises from a single management panel. You can now register on-premise servers with the Anypoint Management Center console, and these servers are then available as deployment targets. You can also configure Server Groups for application deployment to multiple servers. For more information, see Managing Applications and Servers in the Cloud and On Premises.

=== June 2015 R43 - Business Groups - Sub-Organizations

With this release, you can configure Business Groups within your main Anypoint account for delegating administrative access as well as dividing up platform entitlements to sub-organizations within your main organization. For more information, see Manage your Organization and Business Groups.

=== June 2015 R43 - Migration Guidance

No migration required. Enterprise customers automatically receive the new functionality. Changes to the user interface are described in the current MuleSoft documentation, as well as a blog post and training video to be released the week after June 13, 2015.

=== June 2015 R43 - Known Issues

A user must have “add server” permissions to create a server group.

== April 2015

* Unified view of environments across Anypoint Platform (CloudHub and APIs). 
* You can now use *OpenAM* as a SAML 2.0 identity federation provider across the platform.

== January 2015

* Infrastructure upgrade - More instance sizes are supported for application deployment. Five instance sizes (0.1 vCores, 0.2 vCores, 1 vCore, 2 vCores, 4 vCores) are available for selection.
* Data at rest encryption for persistent queues.

=== January 2015 Known issues

*  After enabling encryption for persistent queues, the application  needs to be restarted.

== R40 - October 25, 2014

* Unification with the Anypoint Platform for APIs has resulted in significant changes to the link:/cloudhub/deploying-a-cloudhub-application[user interface], link:/anypoint-platform-administration/managing-accounts-roles-and-permissions[roles and permissions], link:/anypoint-platform-administration/managing-cloudhub-environments[environments], and more. For more information on migrating from R39 to R40, see link:/release-notes/cloudhub-r40-migration-guide[CloudHub R40 Migration Guide].

=== R40 Known issues

* If you deploy a newly created application from Studio to CloudHub, and then view the Settings page for that application, you may get a blank page. This can be remedied by creating your application in CloudHub first and then deploying from Studio.
* If a browser window is zoomed to less than 100%, checkboxes in the user interface may not be visible. Change the zoom to 100% or higher to fix this issue.

== R39 - July 30, 2014

* *_Beta_* Improved UI unified with the link:/anypoint-platform-for-apis[Anypoint Platform for APIs]
* *_Beta_* New monitoring capabilities, statistics on worker CPU and memory use
* Fixed a bug that made applications deploy unreliably with static IPs
* Automatic worker restart is now enabled by default

Read our FAQ about Anypoint Platform for APIs and CloudHub unification

== R38 - May 10, 2014

* Performance improvements for the link:/cloudhub/managing-application-data-with-object-stores[CloudHub ObjectStore]
* Increased limits of ObjectStore to 100K keys and 1 GB of data per application
* Support for a link:/cloudhub/virtual-private-cloud[VPC] per CloudHub environment

== R37 - March 8, 2014

* Performance improvements for link:/cloudhub/cloudhub-fabric[persistent queues].

== R36 - February 1, 2014

* link:/cloudhub/managing-queues[Queues tab] provides runtime visibility into persistent queues.
* link:/cloudhub/worker-monitoring[Worker monitoring] enabled by default on all newly deployed applications in supported runtimes.

== R35 - December 8, 2013

* Enterprise link:/cloudhub/virtual-private-cloud[Virtual Private Cloud] for high-throughput use cases.
* link:/cloudhub/managing-schedules[Schedule management] now generally available to all accounts, including support for Cron expressions.
* Support for link:/mule-user-guide/v/3.7/batch-processing[batch processing].

== R34 - November 2, 2013

* New link:/cloudhub/deploying-a-cloudhub-application[worker sizing] capabilities for accounts that have link:/cloudhub/cloudhub-fabric[CloudHub Fabric] enabled.
* Support for link:/cloudhub/worker-monitoring[worker monitoring and automatic restarts], including a link:/cloudhub/alerts-and-notifications[new alert type] based on a nonresponsive worker.
* Support for link:/cloudhub/secure-application-properties[secure environment variables].

== R33 - September 29, 2013

* Support for link:/anypoint-platform-administration/managing-cloudhub-environments[moving an application between environments].

== R32 - August 26, 2013

* Support for link:/cloudhub/cloudhub-fabric[persistent queuing].
* Bug fixes for sandbox environments, scheduling, and logging.

== R31 - July 20, 2013

* Introduced link:/anypoint-platform-administration/managing-cloudhub-environments[CloudHub Sandbox environments]. Customers now have ability to create multiple development environments to accommodate the full lifecycle of an application, such as Development, QA and Production.
* Introduced pricing changes. CloudHub is switching to a mix of connector- and API-worker-based pricing. 
* Improved SaaS edition customer management with various improvements and fixes based on user feedback.

== R30 - June 22, 2013

* Significant improvements in application deployment time.


== R29 - May 18, 2013

* Per-tenant runtime management capabilities in multi-tenanted applications (Beta)

== R28 - April 14, 2013

* Support for customer management in multi-tenanted applications (Beta)
* Support for link:/cloudhub/managing-schedules[schedule management]
* Support for link:/cloudhub/deploying-a-cloudhub-application[global deployment] 
* Mule 3.4 support

== R27 - March 16, 2013

* Improved Insight dashboard with new link:/cloudhub/cloudhub-insight[Events Filter]

== R26 - February 15, 2013

* Ability to access the link:/cloudhub/community-and-support[support portal]

== R25 - January 19, 2013

* Bug fixes

== R24 - December 20, 2012

* Transaction view for application logs
* Ability to download log files
* Mule 3.3.2 support

== R23 - November 19, 2012

* Message replay for CloudHub Insight

== R22 - October 19, 2012

* Bug fixes

== R21 - September 27, 2012

* CloudHub Insight for integration analytics and root cause analysis

== R20 - July 31, 2012

New features in this release:

* Specify the Reply-To address and create custom email bodies for email alerts.
* link:/cloudhub/managing-application-data-with-object-stores[Store custom application data] using ObjectStores for storage of OAuth tokens, synchronization state, and more.

== R19 - July 8, 2012

* We're now known as http://blogs.mulesoft.com/introducing-cloudhub-formerly-mule-ion/[CloudHub]!
* SDG client is updated and properties that start with "ion" in the name have been renamed to not include "ion" in the name.
* Update CLI tools to have cloudhub in the name

Bugs fixed in this release:

* SDG can now connect during the deployment phase of the application

== R18 - June 28, 2012

New features in this release:

* link:/anypoint-platform-administration/managing-accounts-roles-and-permissions[Role Based Access Control] - add multiple users to your CloudHub account, set their roles, and collaborate on application development.

Bugs fixed in this release:

* Chunked HTTP messages were not being processed correctly by the CloudHub load balancer

See http://blogs.mulesoft.org/role-based-access-controls-on-ion/[announcement] for more information.
