= EDI Module 1.0-beta-2 Release Notes

#Premium#

*March 24, 2015*

This is the second release of the EDI module. This release contains many improvements and bug fixes:

* The segment ID is now always used as the key in the EDI message structure. This may affect your mappings or code - see the migration notes below.
* Added configuration of delimiters and segment line endings for write, character encoding for both write and read
* Added configuration of interchange/group/transaction set control number handling, including options to reject any duplicates
* Added checking of configuration options when set, where possible, for earlier error reporting +
997 and TA1 acknowledgments now always generated by parser and included in message data
* Improved both input and output error reporting, including logging of errors
* Fixed issue with repeating nested loops not parsing correctly
* Implemented checking for duplicate interchange/group/set numbers
* Implemented support for different Interchange Control Version Numbers (previously 005010 only)
* Read and write multiple interchanges from/to a single stream (for output, transaction sets are grouped by functional group and interchange sender/receiver identifiers)
* Implemented checks for valid characters in string values, based on X12 character set selection
* Corrected errors in handling wrapped loops and composite values
* Implemented TA1 generation
* Added support for writing java.util.Date values for X12 date types, as an alternative to java.util.Calendar
* Changed writer handling of time values to only output seconds if non-zero
* Write out transaction sets in the order they appear in the passed-in list (shouldn't matter, but makes it easier to compare
* input with regenerated output)
* Added root-level keys for TA1s received when parsing, or to be sent when writing, and changed the generated TA1s key for clarity
* Implemented pruning of BIN/BDS segments from transaction set schemas so transactions can be used as long as these segments aren't needed
* Correct handling of multiple transaction types included in write
* Added full interchange/group/set number verification to parser
* Corrected 997 AK1 and AK2 formats if not using 005010 schema

For more information, such as how to install or use the module, please see the link:/anypoint-b2b/anypoint-b2b[Anypoint B2B] and link:/docs/display/current/EDI+Module[EDI Module] pages.

== Compatibility

[width="100%",cols="50%,50%",options="header",]
|===
|Application/Service |Version
|Mule Runtime |Mule 3.6.0 and above
|===

== Migration

* Metadata structures have changed from the beta-1 release. You will need to clear your DataSense metadata and regenerate any data mappings. To clear metadata, go to the Connections Explorer, find the EDI module for your project, right click on it and select Clear DataSense Metadata.
* The update site has changed to install the connector to 
https://edi-module-update-site.s3.amazonaws.com/beta-updates. To change it, go to the Help menu and select Install New Software. Then click Available Software Sites, select the EDI Module update site, click edit, and enter in the new URL. Then click OK to go back to the install software screen. Then select the EDI Module update site and follow the instructions to install the new version.
* The EDI Module no longer allows duplicate interchnage control numbers by default. To disable duplicate checking, set the "Require Unique Interchange Control Numbers" flag to false.

== Known Issues

* Binary segments are not supported - they will be ignored.
