= Microsoft SharePoint 2013 Connector Release Notes
:keywords: release notes, connectors, sharepoint

*Select*

*Guide*: link:/mule-user-guide/v/3.7/microsoft-sharepoint-2013-connector[Microsoft SharePoint 2013 Connector]

== Version 2.1.2 - Jan XX, 2016

- Supporting object's names (in addition to IDs) at list queries.
- Fixed memory issue when uploading big files.
- Allowing to use datetime values at query filters.

== Version 2.1.9 - Oct 19, 2015

Changes in this release:

- Added compatibility for Online and Claims authentication when using Java 8 (Mule 3.7+ only).
- Added support again for older Mule runtimes (3.5+), Java 7 or greater is required for all Mule versions.

== Version 2.1.7 - June 3, 2015

Fixed in this release:

* When the global redirector returned a URL containing an unencoded space character, an exception occurred during connection testing and while establishing connectivity with SharePoint online. The content of the redirect location is not required by the connector, so it is no longer followed.

== Version 2.1.6 - May 12, 2015

Fixed in this release: 

* Fixed an issue where the HTTP proxy settings defined for a Mule instance were not being honored by the SharePoint connector.

== Version 2.1.5 - May 8, 2015

Fixed in this release:

* Fixed an issue where authenticating against sub site collections was not working.
* Fixed an issue where unknown attributes in JSON responses were preventing successful deserialization.

*Note*: Versions 2.1.3 - 2.1.4 released internally with no changes to the product.

== Version 2.1.2 - May 7, 2015

Fixed in this release:

* Fixed an issue when connecting to SharePoint online where unknown fields were causing responses to not be parsed correctly
* Fixed a compatibility issue between the connector and Studio 5.1.2 due to library version conflicts
* Renamed connector description in Studio palette to differentiate between SharePoint 2013 and 2010 versions
* Moved connector into new Select category from Standard

== Version 2.1.1 - April 3, 2015

This release has the same compatibility and features of version 2.1.0.

Fixed in this release:

Fields returned by queries to SharePoint Online that are new and therefore unexpected by the response schema no longer cause exceptions during deserialization.

== Version 2.1.0 - February 4, 2015

Release Notes for the Microsoft SharePoint 2013 connector Version 2.1.

=== Version 2.1.0 Compatibility

The Microsoft SharePoint 2013 connector is compatible with:

[width="100",cols="50,50",options="header"]
|===
|Application/Service |Version
|Mule Runtime |3.6 and later
|Anypoint Studio |January 2015
|Microsoft SharePoint |2013
|===

=== Version 2.1.0 Features

Added support for Anypoint Studio 3.6 release, allowing the user interface for each supported authentication scheme to be specialized, and exposing only the configuration properties required for that scheme.

=== Version 2.1.0 Fixed in this Release

Improved help-text for claims authentication configuration to aid understanding of configuration.

=== Version 2.1.0 Known Issues

Improved help-text for claims authentication configuration to aid understanding of configuration.

== Version 2.0 - December 1, 2014

Release Notes for Microsoft SharePoint 2013 Connector Version 2.0.

=== Version 2.0 Compatibility

The Microsoft SharePoint 2013 connector is compatible with:

[width="100%",cols="50%,50%",options="header"]
|===
|Application/Service |Version
|Mule Runtime |3.5.X
|Anypoint Studio |October 2014
|Microsoft SharePoint |2013
|===

=== Version 2.0 Features

* *SharePoint 2013 API* - Broad support for the SharePoint 2013 REST API, including specific operations for Lists & List Items, and Files & Folders. Flexibility to invoke any other API method using the ResolveObject and ResolveCollection operations.
* **Lists & List** *Items* - Ability to query and manipulate Lists or any List-derived type such as Document Libraries, Picture Lists, and to manage the items within those lists.
* *Files & Folders* - Manage folders and files in any SharePoint library, including the ability to perform advanced workflow operations such as check-out, check-in, publish, unpublished, and recycle.
* *DataSense and DSQL Support* - Full support for DataSense to expose the input and output schema of operations for entities, making it simple to discover the API during development.
* *Improved Test Connection Troubleshooting* - Provides more robust Test Connection functionality in the connector including detailed and helpful error messages for the most common configuration and connectivity problems.
* *Claims Authentication* - Provides support for claims-based authentication, allowing flexibility of the authentication model choice for ADFS-enabled enterprises.
* *NTLM Authentication* - NTLM authentication is now more robust and widely compatible with more domain controller configurations.

=== Version 2.0 Fixed in this Release

There are no bug fixes in this release.

=== Version 2.0 Known Issues

There are no known issues in this release.

== See Also

* Learn how to link:/mule-fundamentals/v/3.7/anypoint-exchange[Install Anypoint Connectors] using Anypoint Exchange.
* Access MuleSoft’s http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal].
