= Migrating Mule 2.x CE to EE
:keywords: release notes, esb


If you are a Mule Community user and want to use the Mule Enterprise Edition, follow these steps to start using the Enterprise Edition.

. Make a backup of your existing Mule Community directory.
. Install `mule-<version>-EE` into a new directory (see link:/mule-user-guide/v/3.7/installing[Installing Mule]). Do not overwrite your existing Mule Community installation.
. Set the environment variable MULE_HOME to point to the `mule-<version>-EE` installation directory, such as `export MULE_HOME=/usr/local/mule/mule-2.2.1-EE`.
. If you use Maven to build your application, edit the `pom.xml` file and change the `muleVersion`property value to <version>-EE. For example:
+
[source, xml, linenums]
----
<properties>
     <muleVersion>2.2.1-EE</muleVersion>
 </properties>
----
. If your application uses custom classes, copy your JAR files to the `${MULE_HOME}/lib/user` directory. If you are migrating from Mule 1.x Community to Mule 2.x Enterprise, note that the API and configuration files have changed, so your configuration files and possibly your classes will require modifications. See link:/release-notes/migrating-mule-1.x-to-2.0[Migrating Mule 1.x to 2.0] for more details. If you have purchased Mule Enterprise, you can use the Migration Tool on the http://mulesupport.mulesource.com/portal/login.mule[customer portal] to migrate your files.
. If you downloaded and installed any additional community plug-ins, reinstall them for the Mule Enterprise version. Note that plug-ins provided by the Mule community have not been tested against Mule Enterprise and are not officially supported by MuleSource.
