= MongoDB Connector Release Notes

Mule ESB supports MongoDB integration by using http://mongodb.github.io/mongo-java-driver/[MongoDB Java Driver].

== August 11th, 2015

=== Contents

- Compatibility
- Features
- Fixed in this Release
- Known Issues
- Support Resources

Release Notes for version 4.0.0 of the MongoDB connector.

=== Compatibility
The MongoDB connector is compatible with:

|===
|Application/Service|Version

|Mule Runtime| 3.6.0 or higher
|MongoDB| 3.0 or higher
|Java version| 1.7 or higher
|===

=== Features
- Upgraded MongoDB Java Driver - Now exposing the new APIs available in Mongo Java Driver v3.0. Older (2.x) APIs have been removed.
- SSL support - Added SSL support to encrypt all network traffic. Now both secure and non-secure options are available.
- Multi-port support - Added multi-port support for replica sets. Each host now can contain a particular port, rather than having one port for all hosts.

=== Fixed in this Release
- Exception handling in Mongo Object Store - Exceptions thrown in MongoObjectStore were not in line with the other ObjectStore implementations. It has now been updated as per ObjectStore API documentation.
- Object Store configurable default partition name - It is now possible to configure the default partition name within Mongo Object Store.
- Update operations results - The results of an update operation are now returned to the user.

=== Known Issues
- None.

=== Support Resources

- Learn how to link:/mule-user-guide/v/3.7/installing-connectors[Install Anypoint Connectors] using Anypoint Exchange.
- Access MuleSoft’s MuleForge http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
- To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal].
