= MongoDB Connector Release Notes
:keywords: mongo db, release notes, connector

*Guide:* link:/mule-user-guide/v/3.7/mongodb-connector[MongoDB Connector User Guide]

Mule ESB supports MongoDB integration by using http://mongodb.github.io/mongo-java-driver/[MongoDB Java Driver].

== Version 4.1.0 - January 20th, 2016

Release Notes for version 4.1.0 of the MongoDB connector.

This is a minor release which includes some new features.

[NOTE]
Support for the new GridFS CRUD API is slated for the next release.

=== Features

* Upgraded MongoDB Java Driver - Now compatible Mongo Java Driver v3.2.
* New processors - FindAndUpdateDocument which is an implementation of Mongo *Find and Modify* operation. The other new processor is UpdateDocumentsByFunctions, which will let you provide a set of MongoDB operators instead of just one as before.

== Version 4.0.2 - December 14th, 2015

Release notes for version 4.0.2 of the MongoDB connector.

This is a minor release with a few bug fixes.

=== Fixed in this Release

- Fixed issue where if DataWeave output was set as JSON, MongoDB Connector could not transform it into the required input for the next processor.
- Fixed an issue with DataWeave, where static metadata could not let you use file manipulation processors.
- Added support for implicit transformers when running Mule ESB 3.6.X.
- Fixed documentation issues.

== Version 4.0.1 - September 24th, 2015

Release Notes for version 4.0.1 of the MongoDB connector.

This is a minor release with only one bug fix.

=== Fixed in this Release

- Fixed transformer resolution bug
- When using DataWeave for creating a payload with an object to insert into MongoDB, an implicit transformer
should take place and create the Document object that is passed on to the Insert Document processor. This creation was not picked up and it was not working.

== Version 4.0.0 - August 11th, 2015

=== Contents

- Compatibility
- Features
- Fixed in this Release
- Known Issues
- Support Resources

Release Notes for version 4.0.0 of the MongoDB connector.

=== Compatibility
The MongoDB connector is compatible with:

|===
|Application/Service|Version

|Mule Runtime| 3.6.0 or higher
|MongoDB| 3.0 or higher
|Java version| 1.7 or higher
|===

=== Features
- Upgraded MongoDB Java Driver - Now exposing the new APIs available in Mongo Java Driver v3.0. Older (2.x) APIs have been removed.
- SSL support - Added SSL support to encrypt all network traffic. Now both secure and non-secure options are available.
- Multi-port support - Added multi-port support for replica sets. Each host now can contain a particular port, rather than having one port for all hosts.

=== Fixed in this Release
- Exception handling in Mongo Object Store - Exceptions thrown in MongoObjectStore were not in line with the other ObjectStore implementations. It has now been updated as per ObjectStore API documentation.
- Object Store configurable default partition name - It is now possible to configure the default partition name within Mongo Object Store.
- Update operations results - The results of an update operation are now returned to the user.

=== Known Issues
- None.

=== Support Resources

- Learn how to Install and Configure Anypoint Connectors in Anypoint Studio.
- Access MuleSoft’s MuleForge forum to pose questions and get help from Mule’s broad community of users.
- To access MuleSoft’s expert support team, subscribe to Mule ESB Enterprise and log in to MuleSoft’s Customer Portal.
