= MSMQ Connector Release Notes

:keywords: release notes, esb

Microsoft Message Queueing connector.

*Guides:*

* link:/mule-user-guide/v/3.7/msmq-connector[MSMQ Connector]
* link:/mule-user-guide/v/3.7/msmq-connector-faqs[MSMQ Connector FAQs]
* link:/mule-user-guide/v/3.7/msmq-connector-user-guide[MSMQ Connector User Guide]
* link:/mule-user-guide/v/3.7/windows-gateway-services-guide[Windows Gateway Services Guide]

[NOTE]
*Important*: Install the link:/mule-user-guide/v/3.7/windows-gateway-services-guide[Windows Gateway Service] first before installing and configuring MSMQ.

== Version 1.7 - October 12, 2015

In this release:

* Fixed an issue where public MSMQ queues in Active Directory could not be read.
* See link:/mule-user-guide/v/3.7/windows-gateway-services-guide[Windows Gateway Services Guide] for the latest installation software.

== Version 1.5 - April 28, 2015

New in this release:

* Upgraded Jersey libs to 2.11 to prevent conflict with internal version used by Mule server.
* Fixed an issue where the polling interval specified in the UI was not honored by the dequeuing service in the gateway.
* Tweaked performance to provide consistent response time under heavy load.

== Version 1.4 - March 12, 2015

=== Version 1.4 Compatibility

The Microsoft Message Queuing (MSMQ) connector is compatible with:

[width="100%",cols="50%,50%",options="header",]
|===
a|
Application/Service

 a|
Version

|Mule Runtime |3.5 and 3.6
|Anypoint Studio a|
* Mule 3.6 - January 2015 Studio, version 5.0.n
* Mule 3.5 - October 2014 Studio

|.NET Framework |4.0
|JRE |1.6 if using Mule 3.5 and JRE 1.7 if using Mule 3.6
|===

=== Version 1.4 Fixed In This Release

As part of the update of the MSMQ Connector and Windows Gateway Services, the following issues are fixed in 1.4 release of the MSMQ Connector:

* If a queue name was not specified at the global element level, an error message would be reported repeatedly stating `org.mule.modules.msmq.MsmqException: Queue not found:"null"` even if the connector instance defined a queue name that overrode this global queue setting. The queue connectivity test is no longer run if the global element does not specify a queue name to use.

* In Studio 5.0.2 and ESB 3.6, an error was reported with Test Connection stating that the test failed due to `java.lang.NoClassDefFoundError: com/sun/jersey/api/client/config/ClientConfig. `This was caused by a Jersey version in the connector being out of sync with Studio and ESB server.

* If a Mule app was hot-redeployed in Studio or ESB Server, the MSMQ connector would report an error stating that ` Receiving Thread ERROR org.mule.modules.msmq.MsmqConnector - Error while trying to process response. Cannot process event as "applicationName" is stopped (org.mule.api.lifecycle.LifecycleException).` This was caused by the stop callback never being invoked.

[IMPORTANT]
This release requires an upgrade to version 1.4 of the Anypoint Gateway Service for Windows. For more information, see the link:/mule-user-guide/v/3.7/windows-gateway-services-guide[Windows Gateway Services Guide].

=== Version 1.4 Download Site

Download the Anypoint Gateway for Windows installer from link:https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/mule/modules/anypoint-windows-gateway-service/1.4.0/anypoint-windows-gateway-service-1.4.0.zip[here], unzip the software distribution, and follow the instructions in link:/mule-user-guide/v/3.7/msmq-connector[MSMQ Connector] .

== Version 1.3 - February 4, 2015

=== Version 1.3 Compatibility

The Microsoft Message Queuing (MSMQ) connector is compatible with:

[width="100%",cols="50%,50%",options="header",]
|===
a|
Application/Service

 a|
Version

|Mule Runtime |3.5 and 3.6
|Anypoint Studio a|
* Mule 3.6 - January 2015 Studio
* Mule 3.5 - October 2014 Studio

|.NET Framework |4.0
|JRE |1.6 if using Mule 3.5 and JRE 1.7 if using Mule 3.6
|===

=== Version 1.3 Download Site

Download the Anypoint Gateway for Windows installer from link:https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/mule/modules/anypoint-windows-gateway-service/1.3.0/anypoint-windows-gateway-service-1.3.0.zip[here], unzip the software distribution, and follow the instructions in link:/mule-user-guide/v/3.7/msmq-connector[MSMQ Connector].

Download the MSMQ connector from Studio as described in  link:/mule-user-guide/v/3.7/msmq-connector[MSMQ Connector].

=== Version 1.3 Changes in This Release

* Performance tuning: The performance of the connector has been improved for high transaction volumes where message payloads exceed 1kB.
* Default port change: The default listener port of the Anypoint Gateway Service that provides MSMQ connectivity has been changed to 9333 to prevent conflict with Service Bus which runs on port 9000.

=== Version 1.3 Bug Fixes

None.

=== Version 1.3 Known Issues

None.

== Version 1.2 - November 12, 2014

=== Version 1.2 Compatibility

The Microsoft Message Queuing (MSMQ) connector is compatible with:

[width="100%",cols="50%,50%",options="header",]
|===
a|
Application/Service

 a|
Version

|Mule Runtime a|
* 3.5.X
* 3.4.1

|Anypoint Studio |October 2014
|.NET Framework |4.0
|JRE |1.6
|===

=== Version 1.2 Download Site

Download the Anypoint Gateway for Windows installer from link:https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/mule/modules/anypoint-windows-gateway-service/1.2.0/anypoint-windows-gateway-service-1.2.0.zip[here].

Unzip the software distribution. For more information, see link:/mule-user-guide/v/3.7/msmq-connector[MSMQ Connector].

=== Version 1.2 New Features

None.

=== Version 1.2 Bug Fixes

Remote-queue reliable messaging support: Fixes a bug that prevented the successful dequeue of messages from a remote queue due to an interaction with the reliable-messaging features using sub-queues.

FormatName queue address notation is supported as of MSMQ 1.1 for remote queues. Previously, an exception was thrown if an attempt was made to use DIRECT or another FormatName when connecting to a remote queue.

=== Version 1.2 Known Issues

There are no reported issues that are unresolved in this release.

== Version 1.1 - October 7, 2014

=== Version 1.1 Compatibility

The Microsoft Message Queuing (MSMQ) connector is compatible with:

[width="100%",cols="50%,50%",options="header",]
|===
a|
Application/Service

 a|
Version

|Mule Runtime a|
* 3.5.X
* 3.4.1

|Anypoint Studio |October 2014
|.NET Framework |4.0
|JRE |1.6
|===

=== Version 1.1 Download Site

Download the Anypoint Gateway for Windows installer from link:https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/mule/modules/anypoint-windows-gateway-service/1.1.0/anypoint-windows-gateway-service-1.1.0.zip[here].

Unzip the software distribution. For more information, see link:/mule-user-guide/v/3.7/msmq-connector[MSMQ Connector].

=== Version 1.1 Features

The MSMQ Connector now supports: 

*  *Message exception management*: Errors occurring during the process of sending or receiving queued messages now always raise an exception directly in the flow. This allows the built-in logging and error routing support within Mule to leverage automatically. Where no exception management strategy is defined, messages are returned to the dead-letter-queue as specified in the instance config, or the system dead-letter-queue of the machine where the target queue lives.
*  *Exactly-once in-order support:* When the `message-processing-strategy` of a flow is set to synchronous, messages that are processed from MSMQ queues are guaranteed to be presented to the flow in exactly the order that they were sent, and to be received once and only once.

*  *CloudHub support*: The MSMQ connector now has to be certified for use on CloudHub. You can deploy your Mule application to CloudHub. Ensure that the connector configuration points to the Anypoint Gateway Windows Service running on-premises. The Anypoint Gateway Windows Service provides the interface into the MSMQ infrastructure in your enterprise, so it must be installed and verified as working prior to deploying.

*  *Message timeouts*: You can now set the number of seconds for the *timeToBeReceived* and *timeToReachQueue* property settings. When either of these timeouts occur, messages are moved to a dead-letter-queue that exists as a sub-queue of the origin. You can customize the location of the dead letter queue using the instance properties of the connector. Both properties default to zero (0), which indicates that the property never times out.

*  *Message acknowledgement*: Messages that are not normally MSMQ messages are now surfaced in the flow, allowing an alternative sub-flow to handle conditions such as correlation on ACK or retry on NACK. These messages can be identified by the message properties. You can set a Choice control flow shape using custom recovery or journaling logic. 
*  *Zero-message-loss to bus*: When using transactional queues, the MSMQ connector now guarantees zero-message-loss while the message is delivered to the bus. Only after the message is successfully received by Mule can it be removed from the origin queue. Users don’t need to perform additional configuration other than selecting an MSMQ queue that is marked as transactional. Mule manages a reliable dequeue behind the scenes.


=== Version 1.1 Bug Fixes

FormatName queue address notation is now supported for remote queues. Previously, an exception was thrown if an attempt was made to use DIRECT or another FormatName when connecting to a remote queue.

=== Version 1.1 Known Issues

There are no reported issues that are unresolved in this release.

== Version 1.0 - July 23, 2014

=== Version 1.0 Compatibility

The MSMQ connector is compatible with:

[width="100%",cols="50%,50%",options="header",]
|===
|Application/Service |Version
|Mule Runtime a|
* 3.5.X
* 3.4.1

|Anypoint Studio |July 2014
|.NET Framework |4.5
|===

=== Version 1.0 Fixed in this Release

There are no bug fixes in this release.

=== Version 1.0 Known Issues

There are no reported issues that are unresolved in this release.

== See Also

* Learn how to link:/mule-fundamentals/v/3.7/anypoint-exchange[Install Anypoint Connectors] using Anypoint Exchange.
* Access MuleSoft’s http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal].
