= Mule Maven Plugin 2.0 Release Notes	

MuleSoft is pleased to announce the release of the Mule Maven Plugin 2.0, a Maven plugin for deploying Mule applications, enabling continuous deployment, and running integration tests. This release provides a unified way to deploy/undeploy Mule applications to different deployment targets. It includes support for deploying to Mule standalone instances, Mule cluster instances, CloudHub, Anypoint Runtime Manager*, and the Mule agent.

(*) Anypoint Runtime Manager is the upcoming name for all deployment and management capabilities, and the general framework to deploy on-premises applications through the Anypoint Platform. The name change to Anypoint Runtime Manager will be made in the product and documentation over the coming months.
  
== Hardware and software requirements	

* *JDK*: JRE 1.7.0 (recommended JRE 1.7.0_79/80), JRE 1.8
* *Maven*: Maven 3.2, Maven 3.3
  
== Compatibility

* Compatible with Mule 3.5.x, 3.6.x, 3.7.x
  
== Features and Functionality	
=== New Features or Functionality
  
* Support for deploying to Mule standalone instances, Mule cluster instances, CloudHub, Anypoint Runtime Manager and the Mule agent
* Support for attaching to different lifecycle stages of Maven, so you can use the plugin for both integration tests and continuous deployment
* One single goal for all deployment types	
* CPAL 1.0 license	

=== Deprecated Features or Functionality
* Deprecated the `muleDistribution` parameter to configure the Mule distribution Maven artifact (now the official Maven coordinates are used)
  
== Resolved Issues	

* Fixed Deployment to CloudHub	
  
== Migration Guide	
The plugin now only supports two goals: `deploy` and `undeploy`. To configure where you want to deploy you need to specify the deployment type, for example `<deploymentType>cloudhub</deploymentType>`.

By default the plugin now deploys to a local Mule server, downloading the distribution from configured Maven repositories. 	

Only one application is deployed. For multiple applications, you need to configure one plugin execution for each.	

The package has moved to `org.mule.tools.maven.mule.plugin`.	
  
== Known Issues	

* Local Mule clusters don't work properly in Windows
  
== Support	

* Access the link:http://forums.mulesoft.com[MuleSoft forums] to pose questions and get help from MuleSoft's broad community of users.	
* To access MuleSoft's expert support team, link:mailto:sales@mulesoft.com[subscribe to Mule ESB Enterprise] and log in to MuleSoft's Customer Portal.
