= Mule Maven Plugin 2.1 Release Notes

MuleSoft is pleased to announce the release of the Mule Maven Plugin 2.1. This release adds support for deploying applications to Business Groups and to Anypoint Runtime Manager On-premises Edition.

== Hardware and software requirements
JRE 1.7.0 (Recommended JRE 1.7.0_79/80), JRE 1.8, Maven 3.x

== Compatibilities
* Core Services API 1.0
* ARM Rest API 1.1
* CloudHub API 1.0
* Mule Agent API 1.0
* Mule Kernel, Mule 3.x

== Features and Functionality
=== New Features or Functionality

Support for deploying to Anypoint Runtime Manager On-premises Edition. You can point to a specific installation by simply configuring the `uri` attribute. If your instance of Anypoint Runtime Manager uses HTTPS without a certificate signed by a trusted authority, you can disable HTTP certificate validation by using the `armInsecure` attribute.

Support for Business Groups when deploying to Anypoint Runtime Manager and CloudHub. You can configure the target business group by configuring the `businessGroup` property. Use a backslash (\) to configure parent\child business groups.


== Support

* Access the link:http://forums.mulesoft.com[MuleSoft forums] to pose questions and get help from MuleSoft's broad community of users.
* To access MuleSoft's expert support team, link:mailto:sales@mulesoft.com[subscribe to Mule ESB Enterprise] and log in to MuleSoft's Customer Portal.
