= Mule ESB 3.4.0 Early Preview Release Notes
:keywords: release notes, esb


December 3, 2012

We are excited to announce the availability of an **early preview release of Mule ESB 3.4.0 with Studio**. We have made this release available to the Mule community to get valuable feedback on our latest and greatest features. Access the http://blogs.mulesoft.org/introducing-mule-studio-3-4-early-preview/[blog post] which contains text and video introductions to the freshly-baked features included in this release. Please note that this Early Preview no longer available for download; download Early Preview 2  – link:http://www.mulesoft.org/download-mule-esb-community-edition[3.4(M3)]  – to explore new 3.4 features. 

[NOTE]
Please keep in mind that this is a *pre-Beta version* of Mule ESB. Explore, discover and play, but do not use it to develop Mule apps for use in production.

== Document Revision History

December 11, 2012, v1.0 Initial Publication +
January 11, 2013, v1.1 Early Preview no longer available for download, replaced by Early Preview 2. 

== Current Release Version

[width="100%",cols="34%,33%,33%",options="header",]
|===
|  |
Mule ESB
Enterprise Edition |Mule ESB
 Community Edition

|ESB Runtime|
 |3.4 (M2)
|Studio
2+<|3.4 (M2)
|Management Console |n/a | n/a
|===

== New Features and Functionality

* *Visual Flow Debugger* allows you to place break points on any element within a flow, then execute your flow in debug mode. Mule stops the thread of execution as soon as it hits a break point. In the Debugger pane, you have visibility into the content and structure of the Mule message payload and properties.
* *Anypoint DataMapper's FlowRef* can acquire content by executing a separate flow instead of looking it up within a lookup table. This functionality allows you to make a call to one or more flows within your Mule app, then use the result within your data mapping.
* *Anypoint DataMapper's support for fixed-width content* facilitates integration with legacy systems. Data in fixed-width format is positioned in specified character positions within each line, and is commonly used by legacy systems.
* *Anypoint DataMapper's auto-generated data structure* automatically produces the data structure for input or output of a data mapping.
* *Connection Explorer* lists all of the endpoints in your flow, displaying a single view of all of your external connections. This enables you to change the configuration of any connection and test its connectivity. (As part of this early availability release, Mule supports connection testing for database endpoints and Salesforce, Mongo DB, and Twitter Connectors. Also note that in this preview release you can only test connections of database elements on database nodes, not on data sources directly.)
* *Export Mule Studio Documentation* generates an HTML document that captures details of a project’s flows. The generated documentation contains an HTML report that describes the overall flow and provides details about each element within the flow.
* *Single Studio Distribution* allows you to extend a single Studio installation with different runtimes using the Eclipse install updates function. Read more about "One Studio" on our http://blogs.mulesoft.org/one-studio/[blog].
* *Performance Improvements* improve Studio's ability to handle large projects.
* *Marquee* component enhances Studio’s refactoring capability. With the Marquee component you can select multiple processors then rename, wrap, or extract them as a group.
* *Transaction Demarcation* scope creates transaction delimitations

== Feedback

The primary goal of this early preview release is to get the product into the hands of our community users so you can play around with the new features and offer some feedback. Please mailto:beta@mulesoft.com[email us] your thoughts. We look forward to hearing about your experience with this early release of our new version.
