= Mule 1.3-RC2
:keywords: release notes, esb

The Mule team are pleased to announce the release of Mule 1.3-RC2! +


There have been a number of bug fixes and feature enhancements since the RC1 release. Noteworthy are -

* Session information is now supported. Transports can plug in their own Session handler so that Http Cookies or ServletSessions can be used transparently. Mule also defines its own session header that can be used by transports that support headers but have no notion of a session in its protocol.

* XFire support has been improved and now supports the Mule soap headers.

* Under heavy load ConcurrentModificationExceptions could occur. These have now been eradicated.

* API Changes +
There were a couple of minor API changes made in this release that were necessary. These should not have a big impact on your code.
. It is no longer possible to obtain a properties map directly from a MuleMessage (interface: UMOMessage). Users must obtain a PropertyNames Set from the message.
. MuleMessage (interface: UMOMessage) does not expose a PropertyNames Iterator. Now a set is returned.
. MuleMessage (interface: UMOMessage) does not expose a AttachmentNames Iterator. Now a set is returned.
. UMOMessageDispatcher.receive(UMOEndpoint endpoint, long timeout) has been added. This is so that transaction and filtering information can be passed when doing a receive.
. UMOMessageDispatcher.receive(UMOEndpointURI endpointUri, long timeout) has been deprecated.
. All property accessor and mutator methods on UMOEvent and UMOEventContext have been deprecated. Instead you should obtain the UMOMessage from the UMOEvent or UMOEventContext and access the properties through the message.

Big thanks to the Mule community for providing all their feedback, patches and bug reports!
