= Mule Studio Release Notes - March 21 2012
:keywords: release notes, anypoint studio


== Introduction

Mule Studio is the graphical design tool for Mule. It's the easiest and most accessible way to build integration applications.

Mule Studio comes bundled with Mule 3.2.2, Enterprise Edition. This version incorporates new features such as support for Enterprise-level functionality related to JDBC, WMQ, and FTP.

== Current Release Version

[width="100%",cols="34%,33%,33%",options="header",]
|===
|  |Enterprise Edition |Community Edition
|ESB |  | 
|Mule Management Console |  | 
|Studio |x | 
|===

== New Features and Functionality

* This release features new JDBC, FTP and WMQ endpoints (and connectors), as well as new transformers that are typically employed with JDBC and WMQ.
* A pop up will advise you if your project contains one or more flows with errors. In any case, you can still deploy the project, errors and all, both locally and on Mule iON (now known as CloudHub).
* When you try to run a Mule instance, Mule now informs you if another Mule instance is already running so that you don't start the new instance without being aware of the first running instance.
* The Salesforce Connector Properties pane has been improved.
* The References tab Properties for all the endpoints pane has been enhanced with a new transformer references section so that you can add and reference global transformers.
* The Echo template has been updated.
* New and improved icons have been introduced throughout the Studio interface.
* The release comes bundled with a Mule EE 3.2.2 runtime server module not intended for deployment to a production environment. It operates for 12 hours continuously, then shuts down. The Studio interface, including both editors, continues to work, and you can always restart the server and run it for another 12 hours.
* This release fixes more than 50 bugs.

== Known Issues in this Release

Issue: Inability to configure datasources in Studio Enterprise (STUDIO-1375). +
Workaround: There are two workarounds for this issue: If you want to configure your datasource from the global elements pane, you can use Studio CE. If you don't want to change to Studio CE, just create a bean with Studio Enterprise. +
Issue: You can use reconnection strategies in a Jetty global endpoint but not in a Jetty connector since doing so throws an error when you run the flow (MULE-6112). +
Workaround: If you need to use reconnection strategies in Jetty, create a Jetty global endpoint and configure the reconnection strategy there. +
Issue: For reconnection strategies, neither the reconnect notifier nor the reconnect custom notifier are yet available in Mule Studio (STUDIO-1385). +
Workaround: Add a reconnect notifier or reconnect a custom notifier by manually editing the XML configuration file. +
Issue: Links located in the context-sensitive help system do not work consistently for Studio running on Mac OS X. (STUDIO-1288). +
Workaround: Copy the link of the page you are interested in and paste it in a new browser. +
Issue: When you configure any of the JDBC datasources (e.g., MySQL, Oracle, etc), the driver is not added. (STUDIO-1217) +
Workaround: Add the driver manually by right-clicking project root > Build Path > Add External Libraries > Browse, then adding the appropriate .jar file. +
Issue: For certain JDBC datasources, Mule requires that 'user' and 'password' not be configured in the URL; instead, they must be specified through separate attributes. Although these attributes are not required, and technically, at least, the credentials should be configurable through the URL, you must, in any case, set them through attributes. +
Workaround: If you have a blank password, you must open Studio's XML confguration view and edit the password attribute so that password="". +
Issue:HTTP/HTTPS Polling Connector cannot be referenced using the Properties pane in the Message Flow view. (STUDIO-1077) +
Workaround: You need to insert the reference manually using Studio's XML configuration view by adding this:

[source, xml]
----
ref="HTTP_Polling"
----

Issue: When you remove a Request-Response endpoint or replace it with a One-Way endpoint in the Message Flow view, the response element is not removed from the XML configuration file. (STUDIO-866) +
Workaround: Delete the Response element manually from the configuration file using Studio's XML configuration editor. +
Issue: Unable to add a response element when creating a second flow within a single mflow file. (STUDIO-459) +
Workaround: Add the response element manually in the XML configuration file. +
Issue: For request-response endpoints embedded in a composite source within a subflow, icons do not show the proper exchange pattern. +
Workaround: This is only a matter of visual aesthetics within the graphical interface; if you set the correct exchange pattern through the Properties pane, the flow should work as intended, appearances on the Message Flow canvas not withstanding. +
Issue: The Description field does not persist when you switch back and forth between the Message Flow and XML configuration views. This issue may appear in the examples bundled with Mule Studio. (STUDIO-162). Currently, there is no way to populate the Description field using the graphical interface. +
Workaround: Once your application is complete and you are sure that you don't need to use the Message Flow view any more, copy the description and insert it into the configuration file using the XML editor. +
Issue: When you create a project from an existing template, the Problems pane may display errors such as the following: +
"Unable to find type 'org.ordermgmt.OrdersView' on build path of project order_f." +
Workaround: From the main menu, navigate to \{\{Project > Clean... }}, then select *clean all projects*. This re-compiles all your projects, so that these errors no longer appear. +
Issue: When you install the Windows 64-bit version of Mule Studio with the IBM JDK, then create a project using the Order Discounter template, the Problems pane may display errors such as the following: +
"Attribute key is not defined as a valid property of object Element:Objects is not allowed to be child of element Object". +
Workaround: Ignore the errors and run your application. It will run successfully.
