= Mule IDE 1.4.3 Release Notes
:keywords: release notes, ide


Mule IDE 1.4.3 is available at the update site:  http://dist.muleforge.org/mule-ide/updates/

See the IDE Home page for installation instructions and how to create and run sample projects.

Mule IDE was tested with the Europa version of the link:http://www.eclipse.org/downloads/[Eclipse IDE for Java Developers] running on a Java 5 JRE.

A couple of the sample projects included in the 1.4.3 Mule distribution could not be successfully created by the New Project wizard and are excluded from the sample project choices:  the Loan Broker BPM Example and the Webapp Example.

When adding Mule module and transports in the Mule Libraries Configure dialog, Mule IDE will attempt to automatically add all dependency libraries to the project build path.  However some third-party jars may not included in the Mule distribution and/or may not be referenced in the manifest classpath of jars in the distribution.  These libraries will need to be added manually.  In the Project menu, select Properties.  Go to the Java Build Path properties page, click on the Libraries tab and use the "Add External Jars..." to add the jars to the project.

The default Mule launch configuration has the application working directory set to the Eclipse project root directory.  Thus before running sample projects from Eclipse, you may need to edit relative paths in the configuration files.  For example, in the Error Handler sample project, the conf directory needs to be added to the email.properties and error-beans.xml paths:

[source, xml, linenums]
----
<environment-properties>
        <file-properties location="conf/email.properties" />
    </environment-properties>

    <container-context className="org.mule.extras.spring.SpringContainerContext">
        <properties>
            <property name="configFile" value="conf/error-beans.xml"/>
        </properties>
    </container-context>
----


http://mule.mulesource.org/jira/browse/MULEIDE-41[MULEIDE-41]  Mule IDE's configuration file validator is not properly resolving bean references in the mule-descriptor implementation attribute.  For example, in the Error Handler sample project, class not found errors marked on the "errorManager" and "businessErrorManager" bean references can be ignored.  They do not affect the ability to run the application.

http://mule.mulesource.org/jira/browse/MULEIDE-38[MULEIDE-38]  Mule IDE's configuration file validator does not automatically run after changes to the project's build path.  After adding Mule module or transports or Referenced Libraries, use Project | Clean... to refresh error markers.

http://mule.mulesource.org/jira/browse/MULEIDE-27[MULEIDE-27] Changing the Mule distribution in the Preferences dialog will not re-compute the classpath.
