= Mule IDE 1.3 Release Notes
:keywords: release notes, ide


Mule IDE 1.3 is now available at the update site: `http://dist.codehaus.org/mule/muleide/updates/`

The changes since the beta a few weeks ago are listed in JIRA (below).

Compared to version 1.2.1, the IDE no longer distributes Mini Mule along with it. Instead, the IDE uses an existing Mule distribution through a classpath container where you get to choose which Mule modules you want, and it will compute the 3rd party libraries needed for you, and reference those. It will no longer copy the jars into your project (you can still do this, but then you won't need the Mule classpath container).

The Create Project wizard has been enhanced so that it takes the code and config files from the Mule distribution itself (and extracts dependencies as well), rather than relying on samples shipped with the IDE. But beware, you may have to specify some dependencies yourself, since some implicit dependencies are not picked up (e.g. MuleServer requiring module-builders and module-tcp for the stock examples)

Tested with Mule 1.3.3, should work with older releases, at least back to 1.3.1. It is possibly to support it further backwards, but we'd need help for that.

Prerequisites:

* Eclipse 3.1 or later
* *Mule IDE requires EMF*. You need a version of EMF which matches the Eclipse version, i.e. it mustn't be too new (e.g. EMF 2.2.2 will not work on Eclipse 3.2.1)
* J2SE 1.4.2 or later

Notes:

* All samples are importable. Some samples will give run-time issues fixable by adding missing modules or jars to the class path.
* Some samples need activation.jar and some other Sun jars to function. By starting Mule from the command line, these jars are downloaded into the lib/user folder, where Mule IDE can pick them up as needed.
