= Mule IDE 1.3 Beta 1 Release Notes
:keywords: release notes, ide


The first beta of Mule IDE 1.3 is available at the update site: `http://dist.codehaus.org/mule/muleide/updates/`

Instead, the IDE uses an existing Mule distribution through a classpath container where you get to choose which Mule modules you want, and it will compute the 3rd party libraries needed for you, and reference those. It will no longer copy the jars into your project (you can still do this, obviously).

The Create Project wizard has been enhanced so that it takes the code and config files from the Mule distribution itself (and extracts dependencies as well), rather than relying on samples shipped with the IDE. But beware, you may have to specify some dependencies yourself, since some implicit dependencies are not picked up (e.g. MuleServer requiring module-builders and module-tcp for the stock examples)

Tested with Mule 1.3.3, should work with older releases, at least back to 1.3.1. It is possibly to support it further backwards, but we'd need help for that.

This is a beta for a number of reasons:

* Lacks blue animal graphics in places
* Not rigourously tested with all samples.
* Not tested on Eclipse 3.1, expect breakage there.
* Tested with J2SE 1.4.2 and JRE 1.5, though.

At the same time, we've been working on some more features for Mule IDE, notably in the area of editing Config "semantically", allowing drag-and-drop. This is in Subversion, for anyone wanting a closer look, but won't make it into a 1.3, it has too many rough edges yet.
