= Mule ESB Console 2.2.5 Release Notes
:keywords: release notes, esb


The new version of the Mule ESB Management Console replaces the console formerly known as Mule HQ. While Mule HQ was built on technology from Hyperic, the new version of the management console was built from the ground up and reflects significant feedback from our customers.

The Mule ESB Management Console gives you deep visibility and control into your Mule environment and services during development and production.

== Current Release Version

[width="100%",cols="34%,33%,33%",options="header",]
|===
|  |Enterprise Edition |Community Edition
|ESB |  | 
|Management +
 Console |x | 
|===

== Feature Highlights

The following is a list of feature highlights of this new version of the management console:

* Provides a centralized view of multiple ESB servers from within an intuitive console
* Provides fine-grained control at the servers, services, and end-point levels
** Start/stop/restart ESB resources
** Remote access of configurations
** Dynamically tune server pools for the different services
* Provides deep diagnostics information for the following:
** Memory, CPU utilization, and system resources
** Threads
** Service level events and error key metrics
** Service level queues and execution time
* Provides auditing of in-flight message flows
** Incoming and outgoing message payload
** Message properties information across the service flow stages
* Provides intelligent alerting through the following:
** Intuitive interface
** Console is both extensible and customizable with scripts
** Ability to escalate alerts via email or SNMP traps

== Supported Platforms and Deployment

Mule ESB Management Console has been tested with and supports the following platforms:

* Tcat 6.2.1
* Tomcat 6.x
* JBoss 4.x
* WebSphere Application Server

MuleSoft is working on extending their platform support to include WebLogic Server (WLS) and JBoss in the near future.

Mule with the Management Console agent has been tested with the following application servers:

* WebLogic Server
* WebSphere Application Server
* Tcat 6.2.1
* Tomcat 5.5 and 6.0

== Known Issues

The following are the known issues with the current release of the console:

* Deploying the Mule Management Console WAR in WebLogic Server is known not to work at this time.
* Deploying the Mule Management Console WAR in JBoss is known not to work at this time.
* XsltTransformer does not work in Hot Deployment. The XsltTransformer cannot load an xsl file when Mule is deployed in an EAR outside the WAR.
* Migrating the early access 2 (EA2) release to the current GA 2.2.5 release. This migration requires extra steps. Please see the link:http://www.mulesoft.org/display/mmc/Trouble+Shooting+Tips#TroubleShootingTips-MigratingfromEA2ReleasetoGARelease[Trouble Shooting Tips].
* Mule Management Console does not work properly when Mule ESB is installed as a service.
