= Mule ESB 3.4.0 Early Preview 2 Release Notes
:keywords: release notes, esb


January 11, 2013

We are pleased to announce the availability of the **Early Preview 2 release of Mule ESB 3.4.0 with Studio**. We have made this release available to the Mule community to get valuable feedback on our latest and greatest features. Access the http://blogs.mulesoft.org/introducing-mule-studio-3.4-early-preview-2/[blog post] which elaborates on the improvements in this release.

[NOTE]
Please keep in mind that this is a *pre-Beta version* of Mule ESB. Explore, discover and play, but do not use it to develop Mule apps for use in production.

http://www.mulesoft.org/download-mule-esb-community-edition[Download the early preview 2 of Mule ESB 3.4.0 Enterprise Edition] (3.4 M3 under the Milestone releases section) to explore some of the features that Mule ESB 3.4.0 will have to offer.

== Document Revision History

January 11, 2012, v1.0 Initial Publication

== Current Release Version


[width="100%",cols="34%,33%,33%",options="header",]
|===
|  |
Mule ESB
Enterprise Edition |Mule ESB
 Community Edition

|ESB Runtime|
 |3.4 (M3)
|Studio
2+<|3.4 (M3)
|Management Console |n/a | n/a
|===


== Improved Features and Functionality


* *Upgraded Eclipse version* for Studio which now runs on Eclipse 3.8.(All previous Studio versions were used Eclipse 3.6).
* *Support for JDK 7* on Mac OSX, and a formal fix for the junit launcher in Windows.
* *Visual Flow Debugger with Remote Debugging* to enable you debug your application on a Mule Standalone server using the Remote Mule Application configuration.
* *Enhancements for Maven* which enable you to use Maven to build your project. In Studio, you can now run/debug the application as you would with the mvn command line.
* *Default scripting language for Anypoint DataMapper*, originally based on CTL, now defaults to Mule Expression Language (MEL).
* *Concrete Instances in DataMapper output* are now possible by either creating bindings or defining a POJO factory. +

== Feedback

The primary goal of this second early preview release is to get the product into the hands of our community users so you can play around with the new features and offer some feedback. Please mailto:beta@mulesoft.com[email us] your thoughts. We look forward to hearing about your experience with this early release of our new version.
