= Mule Studio Release Notes - January 24 2012
:keywords: release notes, anypoint studio


Mule Studio is the design-time environment for creating integration applications for both Mule ESB and Mule iON (now known as CloudHub). Mule Studio embeds Mule ESB so you can easily run and test you applications.

== Current Release Version

[width="100%",cols="34%,33%,33%",options="header",]
|===
|  |Enterprise Edition |Community Edition
|ESB |  | 
|Mule Management Console |  | 
|Studio |  |x
|===

== Highlights

* Mule Studio GA comes with Mule CE 3.2.1 bundled.
* Studio provides a rich environment for modeling, running, debugging, and testing Mule applications.
* Studio facilitates the importation and exportation of Mule applications.
* Studio supports two-way editing, so you can choose between graphical and XML-based editors, then switch back and forth, with all changes synchronized instantly between the two modes.
* Studio supports single-click deployment of your integration applications to Mule iON (formerly known as CloudHub)
* Studio bundles Connectors to integrate with the Web APIs from Facebook, Amazon, amd Mongo DB, etc.

== List of Bugs fixed in this release:

* STUDIO-42 - HTTP inbound port allows out-of-range values
* STUDIO-125 - Modified config
* STUDIO-650 - Files and folders (other than external referenced libraries) added by hand are lost when importing an exported project in Studio
* STUDIO-665 - Import "Open" zip file dialog box not configured correctly
* STUDIO-958 - Using <long> element in contribution xmls does not seem to work
* STUDIO-1022 - Missing DisplayName attribute in all Connecotrs
* STUDIO-1040 - Twilio connector - NPE org.mule.module.twilio.TwilioClient
* STUDIO-1042 - Twilio connector - Dialogue box incorrect title "Convert Lead"
* STUDIO-1089 - Wrong query key validation in JDBC endpoit
* STUDIO-1092 - Can not create the 'Mule MQ' connector from a JMS endpoint
* STUDIO-1098 - Custom Evaluator is not hidden for Expression Transformer - return arguments and also I can enter rubbish that is not validated at all
* STUDIO-1105 - No error validation displayed when the flow name doesn't have a name
* STUDIO-1111 - Jython and JRuby engines not supported by CE unless we add the scripting pack in Mule Studio
* STUDIO-1115 - Report an error when the flow does not start with an inbound endpoint
* STUDIO-1121 - Palette Search (Filter) not finding components when adding a space
* STUDIO-1123 - Two-way editing not working when changing the flow name in the configuration XML
* STUDIO-1136 - Error thrown when adding an expression in the First Successful
* STUDIO-1140 - Problem with Connector's classpath when updating STUDIO
* STUDIO-1141 - Problem with the mule-project.xml
* STUDIO-1142 - JMS endpoint without configuration is throwing an error and a Warning
* STUDIO-1143 - Connector's jars get duplicated after update Studio and export\import a project
* STUDIO-1144 - Problem with JDBC query value
* STUDIO-1146 - Fiter should not take into account brackets
* STUDIO-1152 - Wrong validation message in JDBC endpoint and connector
* STUDIO-1158 - Problem with return arguments in Expression Transformer
* STUDIO-1159 - Problem with return arguments in Expression Transformer
* STUDIO-1161 - Change Jetty endpoint configuration window UI
* STUDIO-1162 - Validation issue in Jetty endpoint
* STUDIO-1164 - Error when exporting a project that has classpath problems
* STUDIO-1167 - JDBC - Query key drop down list selection is not persisted - option selected is unselected
* STUDIO-1174 - Add the import icon again for SOAP and include the WSDL import feature
* STUDIO-1178 - Move the Java Transformer Class to the top of the Transformer Settings section of the Java Transformer
* STUDIO-1179 - Move Script Reference drop down list to the bottom for Script Component and Script Transformer
* STUDIO-1181 - Add link should be disabled when a radio button is not selected
* STUDIO-1188 - HTTP outbound-endpoint thinks the default method is GET
* STUDIO-1191 - Unable to open Java component editor once the class has been already selected - it throws an error in the error log
* STUDIO-1193 - Default scope for message properties transformer should be outbound instead of invocation
* STUDIO-1195 - CC extensions are lost (No referenced libraries displayed) when Importing a project that was exported previously which contained CC extensions
* STUDIO-1196 - JDBC endpoint: Blank queries are created when clicking cancel in the Query key editor
* STUDIO-1199 - Problem with window size when using expression editor
* STUDIO-1202 - Unable to export a project to an external disc - Getting Failed to write error
* STUDIO-1205 - Problem when importing projects that have folders with files in src/main/resources or src/test/resources
* STUDIO-1206 - Problem with the build path when importing a project that has referenced libraries
* STUDIO-1210 - Project description does not get imported properly
* STUDIO-1211 - Two-Way Editing: Display name is lost when going to the XML view
* STUDIO-1213 - Problem with the RMI endpoint configuration window

== Known issues

* *Issue:* When you configure any of the JDBC datasources (e.g., MySQL, Oracle, etc), the driver is not added. (STUDIO-1217) +
 *Workaround:* Add the driver manually by right-clicking on `project root > Build Path > Add External Libraries > Browse` , then adding the corresponding *. jar* file.

* *Issue:* For certain JDBC datasources, Mule requires that 'user' and 'password' not be configured in the URL; instead, they must be specified through separate attributes. Although these attributes are not required, and technically, at least, the credentials can be configured through the URL, you must, in any case, set them through attributes. +
 *Workaround:* If you have a blank password, you must go to the XML view and edit the password attribute so that `password=""`.

* *Issue:* The payload cannot be passed as an argument to Salesforce `upsert`, `insert`, etc. (STUDIO-1221). +
 **Workaround:**Go to the XML configuration file and add the payload reference as follows:
+
[source,xml, linenums]
----
<sfdc:upsert type="Account" externalIdFieldName="InternalAccountCode" doc:name="Salesforce">
            <sfdc:objects>
                <sfdc:object ref="#[payload]"/>
            </sfdc:objects>
</sfdc:upsert>
----
* *Issue:* When dragging a Connector message source (i.e., Salesforce (Streaming) or Twitter (Streaming)) from the Palette and dropping it onto the canvas, an error announces that the flow should start with an inbound endpoint. (STUDIO-1224) +
 *Workaround:* Disregard the error, since the Connector message source is, in fact , an inbound endpoint.

* *Issue:* Neither the HTTP nor HTTPS Polling Connectors can be referenced using the Properties pane in the Message Flow view. (STUDIO-1077) +
 *Workaround:* You need to make the reference using the XML configuration view by adding this: `ref="HTTP_Polling"`

* *Issue:* When you remove a Request-Response endpoint or replace it with a One-Way endpoint in the Message Flow view, the response element is not removed from the XML configuration file. (STUDIO-866) +
 *Workaround:* Delete the Response element manually from the configuration file using the XML editor.

* *Issue:* When you add the schema `namespace` and `location` manually using the XML configuration view, then switch to the Message Flow view to continue working, those two elements are not persisted. (STUDIO-487) +
 *Workaround:* Try to use the graphical mode. However, when you encounter an element that you want to use but is not there, go to the configuration XML view and add it manually. Try to do this when all your flows are almost complete, and you no longer need to use the graphical editor. Make sure that you save the project frequently.

* *Issue*: Unable to add a response element when creating a second flow within a single mflow file. (STUDIO-459) +
 *Workaround*: Add the response element manually in the XML configuration.

* *Issue*: For request-response endpoints embedded in a composite source within a subflow, icons do not show the proper exchange pattern. +
 *Workaround:* This is only a matter of visual aesthetics within the graphical interface; if you set the correct exchange pattern through the Properties pane, the flow should work as intended, despite appearances on the Message Flow canvas.

* *Issue*: The *Description* field is not persisted when you switch back and forth between the Message Flow and XML configuration views. This issue may appear in the bundled examples that are included in Mule Studio. (STUDIO-162). Currently, there is no way to populate the *Description* field using the graphical interface. +
 *Workaround:* Once your application is complete and you are sure that you don't need to use the Message Flow view any more, copy the description and insert it into the configuration file using the XML editor.

* *Issue:* When you create a project from an existing template, the *Problems* pane may display errors such as the following: +
 "Unable to find type 'org.ordermgmt.OrdersView' on build path of project order_f +
 *Workaround:* From the main menu, navigate to \{\{Project > Clean... }}, then select *clean all projects*. This re-compiles all your projects, so that these errors no longer appear.

* *Issue:* When you install the Windows 64-bit version of Mule Studio with the IBM JDK, then create a project using the Order Discounter template, the *Problems* pane may display errors such as the following: +
 "Attribute key is not defined as a valid property of object Element:Objects is not allowed to be child of element Object" +
 *Workaround:* Ignore the errors and run your application. It will run successfully.

Find the complete list of known issues http://www.mulesoft.org/jira/secure/IssueNavigator.jspa?reset=true&jqlQuery=project+%3D+STUDIO+AND+fixVersion+not+in+%28%22Preview+Release+3%22%2C+%22Private+Beta%22%2C+%22Public+Beta%22%2C+%22Public+Beta+%28iON+Support%29%22%2C+%22Beta+Milestone+2%22%2C+%22Beta+Milestone+3%22%2C+%22Beta+Milestone+4%22%2C+%22Beta+Milestone+5%22%2C+%22RC+1%22%2C+%221.0+GA%22%29+ORDER+BY+priority+DESC%2C+key+DESC[here]
