= Paypal Connector Release Notes
:keywords: paypal, connector
:source-highlighter: prettify

[green]#Community#

The PayPal Connector facilitates connections between Mule integration and PayPal. The PayPal Connector v3.0 lets you perform the operations in PayPal's link:https://developer.paypal.com/docs/classic/api/[NVP and SOAP API Reference]. The connector as of now only supports Signature API credential type of authentication.

*Connector Guide*: link:/mule-user-guide/v/3.7/mule-paypal-anypoint-connector[PayPal Anypoint Connector]

=== Version 3.0.1

=== Version 3.0.1 Features

None.

=== Version 3.0.1 Fixes

None.

=== Version 3.0.1 Known Issues

None.

== Version 3.0 - July 31, 2015

=== Version 3.0 Compatibility

The PayPal connector 3.0 is compatible with the following applications:

[width="100",cols="50,50",options="header"]
|===
|Application/Service |Version
|Mule Runtime |3.7.0 or later
|PayPal |Classic SOAP API version 2.0
|===

=== Version 3.0 Features

* Added support for all the standard operations and SOAP endpoints as per PayPal's link:https://developer.paypal.com/docs/classic/api/[NVP and SOAP API Reference]. Use of the API depends on the PayPal account being used.
* Added support for Signature API credentials. The API Signature is infused into the SOAP header for every call.

This version of the connector uses a SOAP Connect feature in 3.7.0 and is not backward compatible with the earlier version of the connector.

=== Version 3.0 Fixes

None.

=== Version 3.0 Known Issues

As of now authentication is only supported using Signature API credentials. The Certificate API credentials is not supported. Refer to PayPal's link:https://developer.paypal.com/docs/classic/api/apiCredentials/[Creating and managing NVP/SOAP API credentials] for more details.

== See Also

* See link:/mule-user-guide/v/3.7/installing-connectors[Installing Connectors].
* See the http://mulesoft.github.io/paypal-connector/3.0.0/java/packages.html[Javadoc for this connector].
