= Mule 1.0-RC2 Release Notes
:keywords: release notes


The latest release of Mule introduces Axis integration, J2SE 5.0 Jmx support, Jmx remoting and statistics MBeans, Tighter integration with external IoC containers such as Spring or Pico, XA Transaction support, Improved Spring Events integration, Internal Server events, Cleaner endpoint configuration, generic and transport-specific Endpoint Filtering and lots of Bug fixes. Download Now.


== *Axis Transport Provider*


Developers can now expose their services and invoke services using Axis. There is no servlet engine or wsdd required; a service can be exposed simply by associating an Axis endpoint URI!



== *Cleaner Endpoint Configuration and Filtering*

There is now a much cleaner and more intuitive endpoint configuration syntax. +
Filters can now be applied to endpoints to control inbound traffic. Filters can either be generic or specific to the underlying transport such as Jms selectors or filename filters.


== *Jmx enhancements*


* Support for J2SE 5.0 build-in jmx support
* Support for jmx remoting
* Decoupled jmx agent from http adaptors
* Support for Log4j jmx management
* Support for statistics as beans

== *Internal Server Events*

Applications can subscribe to Mule server events to be notified about state change or management events. +


== *Tighter integration with IoC/DI containers* +

New configuration elements allow properties on any Mule object (connectors, agents, transformers, etc) to be configured from a Container such as Spring or Pico.



==  *Improved Spring events Support*

Simplified approach for hooking Mule into Springs eventing means your JavaBeans can subscribe to and publish Mule events without needing to configure Mule. +
Read More...



== *XA Transaction support*

Mule now supports XA transactions. Mule can share a transaction manager with Spring so that transactions can be used across Mule and Spring resources.

 

==  *Bug fixes, Tests and Documentation*


There have been loads of bug fixes and new tests added to Mule. Plus new and updated <<Bug fixes, Tests and Documentation>>.


I would like to send out a BIG to thank everyone who reported issues and ideas and helped fix bugs. Please keep the feedback/ideas/fixes coming :)
