= Mule 1.3-RC1
:keywords: release notes, esb

The Mule team are pleased to announce the release of Mule 1.3-RC1! +



*JavaSpaces*

* Mule now has specific support for JavaSpaces, and ships with integration of the http://www.gigaspaces.com[GigaSpaces] implementation of the JavaSpaces spec.

*XFire STaX-based SOAP support*

* XFire is a next generation soap stack using a stream based service model for efficiency and low memory usage. Mule now supports Xfire soap endpoints that are interchangable with the existing Glue and Axis endpoints. +
Note: This is a beta release of this transport.

*Spring Remoting*

* Mule services can now invoke Spring Remoting services or be invoked using spring remoting.

*HiveMind Support*

* The new HiveMind container context allows you to obtain objects from a HiveMind registry to use as your UMO components or to wire other Mule objects such as connectors, transformers, agents, etc.

*Transaction Managers*

* Mule now supports a lot more transaction managers including Weblogic, Websphere, JRun, JBoss, Resin and Generic Jndi-based support.

*Performance*

* The Http transport has been rewritten to handle requests more efficiently and now supports message chunking as well.
* Jms improvements have been introduced to manage receiver threads and session caching.

*Encoding*

* Message encoding can now be controlled on the event, endpoint or Mule instance level. All default encoding operations have been removed ensuring that Mule can be configured to run on non-european operating systems.

*Bug Fixes and Documentation*

* We've added lots of new documentation and fixed the bugs/improvements listed below.
