= Mule 1.0-RC1 Release Notes
:keywords: release notes, esb


The latest version of Mule 1.0-rc1 is available here. The release contains the following new features and enhancements.


== *Web Services*

A new Soap provider enables your components to be automatically exposed as webservices. There is support for Axis and Glue. +


== *Scriptable Components*

You can now have Mule managed scripting components that can be automatically reloaded when the script changes. There is a Groovy Script component implementation.


== *Improved Jmx Management and Statistics*

Added even more routing and compoennt statisics via Jmx with Html reporting. Added Jmx services more controlling components, the model and the manager.

== *Message Correlation support*

We've added a new range of routers that that enable components to define message groups that can then be split, joined, resequenced and aggregated.


== *New Sample Applications*

Echo Example is a simple component example that demostrates how to expose a component over multiple transports. +
Loan Broker Example is a comprehensive application based on the example presented in the Enterprise Integration Patterns book. +
Mule Examples Webapp provides an interface to some of the examples here such as the LoanBroker, Hello World and Echo examples. It also provdes examples of accessing Mule using REST style service calls and is itself an example of how to embed Mule in a webapp.


== *Bugfixes, Tests and Documentation*

* Loads of new test cases.
* Lots of bugs fixes and enhancements, thanks to everyone who reported and/or fixed bugs.
* Lots of new and updated documentation
