= MUnit 1.0.0 Release Notes
:version-info: 3.7.0 and later
:keywords: munit, testing, unit testing, release notes

MuleSoft is pleased to announce the release of version 1.0.0 of the MUnit testing framework. This release features important changes including versioning, explained below.

== New MUnit Structure

In the past, versions of MUnit matched the current version of Mule ESB. This did not allow for scalability and added complexity to development and usability of the product. As of this release, MUnit follows its own versioning. MUnit is bridged to Mule ESB by the new Mule MUnit Support Module, which does follow Mule ESB versioning.

[source, xml, linenums]
----
<dependency>
    <groupId>com.mulesoft.munit</groupId>
    <artifactId>mule-munit-support</artifactId>
    <version>${mule.munit.support.version}</version>
    <scope>test</scope>
</dependency>
----

In future releases, each Mule ESB version should have a single MUnit Support Module. For example:

`mule-munit-support:3.6.0` should work with Mule ESB 3.6.0, 3.6.1, 3.6.x.
`mule-munit-support:3.7.0` should work with Mule ESB 3.7.0, 3.7.1, 3.7.x.

Nevertheless, if circumstances demand, it is possible that revision versions of MUnit Support Module will be released.

The new structure means that MUnit is now a product on its own, and follows its own versioning. Versioning is starting from scratch with version 1.0.0.

The groupId of all MUnit Maven artifacts has also changed, from `org.mule.munit` to `com.mulesoft.munit`.


== Compatibility Information

MUnit is compatible with the Mule 3.6 and 3.7 runtimes. When running in Mule 3.6.x, the following items are not supported:

* link:https://www.mulesoft.org/jira/browse/MU-262[MU-262]: ForEach loop cannot transform back from XML
* link:https://www.mulesoft.org/jira/browse/MU-352/[MU-352]: Problem with duplicated transformers in classpath when running a test

== See Also

* link:/munit/v/1.0.0[MUnit 1.0.0]
* link:/munit/v/1.1.1[MUnit 1.1.1]
* link:http://forums.mulesoft.com[MuleSoft's Forums]
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]
* mailto:support@mulesoft.com[Contact MuleSoft]
