= NetSuite Connector Release Notes 
:keywords: release notes, netsuite, connector

_Select_

*Guide*: link:/mule-user-guide/v/3.7/netsuite-connector[NetSuite Connector]

The Anypoint Connector for NetSuite synchronizes data and automates business processes between NetSuite and third party applications, either on-premise or in the cloud.

== Version 6.0.1 - July 30, 2015

=== Version 6.0.1 Compatibility

The NetSuite connector 6.0.1 is compatible with:

[width="100%",cols="50a,50a",options="header"]
|===
|Application/Service|Version
|Mule Runtime|3.5 and later
|API|SuiteTalks 2015_1
|===

=== Version 6.0.1 Features

None.

=== Version 6.0.1 Fixes

* Fixed an issue where only one custom field was being passed on the webservice request.
* Fixed an issue where the DataSense MetaData Category keys for the Search Category were duplicated.

=== Version 6.0.1 Known Issues

None.

=== Version 6.0.1 Migrating From an Older Version

When you upgrade to NetSuite Connector 6.0.1, reload Metadata during design time as certain records have made changes to the Metadata.

In this release, we have upgraded the connector to DevKit 3.6.1. Users are now presented with multiple Global Elements, each representing a different way of authenticating to NetSuite.

Global Configuration prior to version 6.0.0:

[source,xml,linenums]
----
<netsuite:config name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" authenticationType=${authenticationType} />
----

New Global Configurations (from version 6.0.0):

[source,xml,linenums]
----
<netsuite:config-login-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" />

<netsuite:config-request-level-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" />

<netsuite:config-sso-login-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" />
----

== Version 6.0.0 - July 10, 2015

=== Version 6.0.0 Compatibility

The NetSuite connector v6.0.0 is compatible with:

[width="100%",cols="50a,50a",options="header"]
|===
|Application/Service|Version
|Mule Runtime|3.5 and later
|API|SuiteTalks 2015_1
| |SuiteTalks 2015_2
|===

=== Version 6.0.0 Features

* Upgraded the connector to use DevKit 3.6.
* Introduced support for HTTP proxy.
* Started using Metadata Categories, thus making the Search and Async-search operations Metadata aware.
* Added a new authentication type that allows Single sign-on logins.
* Migrated the connector to CXF 2.7.15.

=== Version 6.0.0 Fixes

* Stopped using `XMLGregorianCalendar` in various record type attributes, handling these using Calendar now.
* Metadata keys for customizations (except Custom Record Types) are no longer generated with the internalId as part of the key.
* getSavedSearch operation now shows the appropriate record types.
* Metadata for the custom fields has been improved. Record types with noticeable changes to custom field placement are:
** ASSEMBLY_BUILD
** EXPENSE_REPORT
** ITEM_FULFILLMENT
** ITEM_RECEIPT
** JOURNAL_ENTRY
** LES_ORDER
** OPPORTUNITY
** PURCHASE_ORDER
** TRANSFER_ORDER
** WORK_ORDER
* Missing fields on the AssemblyItem entity, such as intercoIncomeAccount and intercoCogsAccount, have been added.

=== Version 6.0.0 Known Issues

None.

=== Version 6.0.0 Migrating From an Older Version

When you upgrade to NetSuite Connector 6.0.0, reload Metadata during design time as certain records have made changes to the Metadata.

In this release, we have upgraded the connector to DevKit 3.6.1 and introduced Connection Strategies. The user is now presented with multiple Global Elements, each representing a different way of authenticating to NetSuite.

Previous Global Configuration:

[source,xml,linenums]
----
<netsuite:config name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" authenticationType=${authenticationType} />
----

New Global Configurations:

[source,xml,linenums]
----
<netsuite:config-login-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" />

<netsuite:config-request-level-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" />

<netsuite:config-sso-login-authentication name="NetSuite" email="${email}" password="${password}" account="${account}" roleId="${roleId}" />
----


== Version 5.0.0 - April 15, 2015

=== Version 5.0.0 Compatibility

The NetSuite connector v5.0.0 is compatible with:

[cols=",",options="header",]
|===
|Application/Service |Version
|Mule Runtime |3.5 and later
|API |SuiteTalks 2015_1
|===

=== Version 5.0.0 Features

* Upgraded the connector to SuiteTalks API version 2015_1. 
* The `get-deleted-records` operation no longer has any limit on the number of records to retrieve. This operation now makes use of a page index as per the new changes to the SuiteTalks API.

=== Version 5.0.0 Fixes

* WSDLs and XSDs have been excluded from the connector distribution.

=== Version 5.0.0 Known Issues

None. 

== Version 4.0.11 - November 28, 2014

=== Version 4.0.11 Compatibility

The NetSuite connector v4.0.11 is compatible with:

[cols=",",options="header",]
|===
|Application/Service |Version
|Mule Runtime |3.5.2
|Anypoint Studio |October 2014
|API |SuiteTalks 2014_1
|===

=== Version 4.0.11 Features 

* Added an option to switch from login authentication to sending authentication information with every request, to achieve concurrency. Any existing apps built with older versions of this connector do not fail when updating to the new version, as a default value is configured for the login authentication of such apps.   +

=== Version 4.0.11 Fixes

The following issues have been fixed in this release:

[cols=",",options="header",]
|===========================
|Fix |Description
|Replaced dependencies |Replaced some unnecessary dependencies in the pom.xml file with updated dependencies from the DevKit parent.
|Replaced demo |Replaced the existing sample demo with a new demo for NetSuite CRUD operations.
|Fix for null point exceptions |Fix to avoid null point exceptions when retrieving metadata.
|===========================

=== Version 4.0.11 Known Issues

None.

== See Also

* Learn how to link:/mule-fundamentals/v/3.7/anypoint-exchange[Install Anypoint Connectors] using Anypoint Exchange.
* Access MuleSoft’s http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log into MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal].
