= Salesforce Analytics Cloud Connector Release Notes
:keywords: release notes, salesforce, analytics, cloud, connector


The Anypoint Connector for Salesforce Analytics Cloud lets you connect to the Salesforce Analytics Cloud application using SOAP API. The connector exposes convenient methods for creating data sets in Salesforce Analytics Cloud from different data sources, such as XML, CSV, and a list of Map objects.

== *Version 1.1 - April 17, 2015*

=== Version 1.1 Compatibility 

The Salesforce Analytics Cloud connector is compatible with:

[width="100%",cols="50%,50%",options="header",]
|===
a|
Application/Service

 a|
Version

|*Mule Runtime* |3.5.0 or later
|*Salesforce API* |v31
|*SOAP API* |v31
|===

=== Version 1.1 Features

Added the following operations:

* **Create data set: **Create a new data set in the Salesforce Analytics Cloud system.
* *Upload external data:* Upload data into an existing data set in the Salesforce Analytics Cloud system.
* **Start processing data:** Start processing the data in a data set.
* *Upload external data into new data set and start processing:* Create a new data set, upload data into it, and start processing the data, all in one step.

=== Version 1.1 Fixes

None.

=== Version 1.1 Known Issues

None.

== See Also

* Learn how to link:/mule-fundamentals/v/3.7/anypoint-exchange[Install Anypoint Connectors] using Anypoint Exchange.
* Access the link:http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from MuleSoft's user community.
* To access MuleSoft’s expert support team, link:http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal]. +
