= Salesforce Analytics Cloud Connector Release Notes
:keywords: release notes, salesforce, analytics, cloud, connector


The Anypoint(TM) Connector for Salesforce Analytics Cloud lets you connect to the Salesforce Analytics Cloud application using link:https://developer.salesforce.com/docs/atlas.en-us.bi_dev_guide_ext_data.meta/bi_dev_guide_ext_data/[External Data API]. The connector exposes convenient methods for creating and populating data sets into Salesforce Analytics Cloud system.

== Version 2.0.1 - November 06, 2015

Release notes for version 2.0.1 of the Salesforce Analytics Cloud connector. These Release Notes accompany the
link:/mule-user-guide/v/3.7/salesforce-analytics-cloud-connector[Salesforce Analytics Cloud Connector User Guide].

=== Version 2.0.1 Compatibility

The Salesforce Analytics Cloud connector is compatible with:

[width="80%",options="header"]
|===
|Application/Service |Version
|Mule Runtime | 3.5.0 and higher
|External Data API | v34.0
|===

=== Version 2.0.1 Features

This is a minor release and it contains only fixes.

=== Version 2.0.1 - Fixed in this Release

* When metadata was being sent to the server the "fiscalMonthOffset" was sent as a string instead of an integer, which is what the server expects.
* Fixed an issue in previous versions of the connector, where the login error response was parsed incorrectly.

=== Version 2.0.1 Known Issues

None.

== Version 2.0 - August 28, 2015

Release Notes for version 2.0 of the Salesforce Analytics Cloud connector. These Release Notes accompany the
link:/mule-user-guide/v/3.7/salesforce-analytics-cloud-connector[Salesforce Analytics Cloud Connector User Guide].

=== Version 2.0 Compatibility

The Salesforce Analytics Cloud connector is compatible with:

[width="80%",options="header"]
|===
|Application/Service |Version
|Mule Runtime | 3.5.0 and higher
|External Data API | v34.0
|===

Please note that this is a Major version release which breaks backwards compatibility.

=== Version 2.0 Features

* Added new field "Operation" on "Create data set"/"Upload external data into new data set and start processing" operations which provides the ability to choose the operation executed against the data set. Accepted values: OVERWRITE, APPEND, UPSERT, DELETE.
* Added new field "Notification Sent" on "Create data set"/"Upload external data into new data set and start processing" operations which provides the ability to choose when to get email notifications based on processing results. Accepted values: ALWAYS, FAILURES, WARNINGS, NEVER.
* Added new field "Notification Email" on "Create data set"/"Upload external data into new data set and start processing" operations which provides the possibility to choose the email where notifications to be sent.

=== Version 2.0 Fixed in this Release

* Added "Authorization URL" to "Basic Authentication" configuration in order to provide the ability to change login server. So now you can point the connector to a Salesforce environment of your choosing
* Added "Token Endpoint" to "OAuth 2.0 SAML Bearer"/"OAuth 2.0 JWT Bearer" configurations in order to give the ability to change the token provider server.
* Removed support for multiple formats of metadata file, so removed "Metadata File Type" from all the configurations.
* Added a warning message for when the data provided to a batch commit step is bigger than the maximum allowed size (10 MB) to upload one chunk into the Analytics Cloud using the InsightsExternalDataPart objects. This will help the user to maximize performance of the connector. For more details, please refer to the API documentation link:https://developer.salesforce.com/docs/atlas.en-us.bi_dev_guide_ext_data.meta/bi_dev_guide_ext_data/bi_ext_data_add_data.htm[Add the Data].

=== Version 2.0 Known Issues

None.

== Version 1.1 - April 17, 2015

Release Notes for version 1.1 of the Salesforce Analytics Cloud connector. These Release Notes accompany the link:/mule-user-guide/v/3.7/salesforce-analytics-cloud-connector[Salesforce Analytics Cloud Connector User Guide].

=== Version 1.1 Compatibility

The Salesforce Analytics Cloud connector is compatible with:

[width="80%",options="header"]
|===
|Application/Service |Version
|Mule Runtime | 3.5.0 and higher
|External Data API | v31.0
|===

=== Version 1.1 Features

* *Create data set* - This operation provides the ability to create a schema in the Analytics cloud for data ingestion
* *Upload external data* - This operation uploads the data into an existing data set in the Analytics Cloud.
* *Start processing data* - This operation communicates with Salesforce to start the processing of uploaded data to enable data visualizations and other features within Wave.
* *Upload external data into new data set and start processing* - This operation combines the aforementioned three operations into a single operation.

=== Version 1.1 Fixed in this Release

First version.

=== Version 1.1 Known Issues

None.

== See Also

* Learn how to link:/mule-fundamentals/v/3.7/anypoint-exchange[Install Anypoint Connectors] using Anypoint Exchange.
* Access the link:http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from MuleSoft's user community.
* To access MuleSoft(TM)'s expert support team, link:http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft(TM) link:http://www.mulesoft.com/support-login[Customer Portal].
