= Salesforce Connector Release Notes
:keywords: release notes, salesforce, connector

*_Select_*

*Connector Guide*: link:/mule-user-guide/v/3.7/salesforce-connector[Salesforce Connector]

== Salesforce Connector 6.2.3 - July 23, 2015

=== Version 6.2.3 Fixed in This Release

* Fixed an error where session expiration would not be handled correctly even with a reconnection strategy set, in operations that returned a SalesforcePagingDelegate (query, queryall).

== Salesforce Connector 6.2.2 - July 22, 2015

=== Version 6.2.2 Fixed in This Release

* A bug that logged warning messages as errors once a session expired even if you had reconnection on has been fixed.
* Support for session concurrency in multi-threaded applications has now been improved.

== Salesforce Connector 6.2.1 - June 19, 2015

=== Version 6.2.1 Compatibility

The Version 6.2.1 Salesforce connector is compatible with:

[width="100%",cols="50a,50a",options="header"]
|===
|Application/Service|Version
|Mule Runtime|3.5.2 and newer
|Salesforce|v31.0 to v32.0
|===

=== Version 6.2.1 Migrating From Older Versions of the Connector

If you’re using an older version of the connector, a small popup appears in the bottom right corner of Anypoint Studio that says Updates Available.

. Click that popup and check for available updates.
. Click the Salesforce Connector version 6.2.1 check-box, click Next, and  follow the instructions provided by the user interface.
. Restart Studio.
. After the restart, when creating a flow and using the Salesforce Connector, if you have several versions of the connector installed, you might be asked which version you would like to use. Choose the version you would like to use.
. Keep Mule and Studio updated.

=== Version 6.2.1 Fixed in this Release

* IDENTITY_URL_TEMPLATE hardcoded to login.salesforce.com breaks sandbox requests - there was no way of differentiating the test sandbox from the production environment (this is done through the URL the user is logged in to).
Renamed in the SalesforceBasicAuthConfig the parameter URL to Authentication Url
* Added to JWT and SAML configurations the parameter Token Endpoint
ObjectStore callback attributes are not properly loaded - fields instanceId , userId , and accessToken were renamed
* Re-added fields instanceId, userId, and accessToken taken from ObjectStore provided by user
* "remoteUserId" variable is not set any more in the postAuthorize
Re-added the remoteUserId flow variable in postAuthorize

=== Version 6.2.1 Known Issues

* Connector v6.2.1 does not work with versions v28.0, v29.0, and v30.0 of the Salesforce API.
* Connector v6.2.1 does not support for Apex Rest the following data types:
** Custom Types
** Lists of Lists or Maps
** Maps of Lists or Maps
** Object (not able to perform DataSense on it)
** Blob (not supported by Salesforce Rest methods as input/output)
* For versions v28.0, v29.0 of the Salesforce API use version v5.4.12 of the connector.

== Salesforce Connector 6.2.0 - June 9, 2015

=== Version 6.2.0 Compatibility

Salesforce connector 6.2.0 is compatible with:

[width="100%",cols="50a,50a",options="header"]
|===
|Application/Service|Version
|Mule Runtime|3.5.2 or newer
|Salesforce|v31.0 to v32.0
|===

=== Version 6.2.0 Updating to Version 6.2.0 of the Connector

When a new version of a connector is released, Anypoint studio displays a popup in the bottom right corner of you screen with the following message: Updates Available.

To upgrade to the newer version of the Salesforce connector:

. Click the popup and check for the available updates.
. Select the Salesforce connector 6.2 checkbox and click Next.
. Follow the instructions provided by the user interface.
. Restart Studio when prompted.
. After restarting, if you have several versions of the connector installed, Mule asks you for the version of the connector you like to use.

=== Version 6.2.0 Features

* Salesforce APEX REST API: The connector now supports the following Apex operation:
** Invoke Apex Rest method: Lets you invoke an operation from an Apex class that has previously been created in your organization. The operations from the Apex class have to be exposed as a REST service.
* OAuth 2.0 JWT Bearer Token Flow: Allows you to authenticate salesforce via OAuth 2.0 JWT Bearer Token Flow.
* OAuth 2.0 SAML Bearer Assertion Flow: Allows you to authenticate salesforce via OAuth 2.0 SAML Bearer Assertion Flow.

=== Version 6.2.0 Fixes

* Created getServerURL operation to return the URL of the server.
* Added support for  Proxy configuration for all authentication types.
* Added Fetch All Apex SOAP Metadata checkbox (The connector tries to perform Datasense for all Apex SOAP classes  only if this checkbox is selected. )
* NullPayloadToXMLStreamReader is hidden from the Studio as it is for internal use only.
* SubscribeTopic operation now  supports topic names without leading /'.
* Added support for CSV batch uploads (when contentType is set to CSV).
Renamed the invokeApexMethod operation to invokeApexSoapMethod.

=== Version 6.2.0 Known Issues

* This version is not compatible with Salesforce API v28.0, v29.0 and v30.0.
* It doesn't support the following data types for Apex Rest:
** Custom Types
** Lists of Lists or Maps
** Maps of Lists or Maps
** Object (not able to perform DataSense on it)
** Blob (not supported by Salesforce Rest methods as input/output)

== Salesforce Connector 6.1.0 - March 31, 2015

=== Version 6.1.0 Compatibility Information

* Mule Runtime: 3.5.2 and later
* Anypoint Studio: October 2014
* Salesforce: v32.0

=== Version 6.1.0 Features

* Salesforce Apex API - the connector now supports the following Apex operation: +
** *invokeApexMethod* - invokes any operation from an Apex class that is exposed as SOAP web service.
* Added Query Builder for querySingle and queryAll operations.
* Added payload as default value for the Ids input for retrieve() and emptyRecycleBin() operations.

=== Version 6.1.0 Fixes

None.

=== Version 6.1.0 Known Issues

None.

== Salesforce Connector 6.0.1 - February 25, 2015

Fixes an issue where the Salesforce 6.0.0 connector didn't work with Java 6. The connector now works correctly with Java 6 and 7. Everything else is the same as Salesforce 6.0.0.

== Salesforce Connector 6.0.0 - February 23, 2015

=== Version 6.0.0 Compatibility Information

* Mule Runtime: 3.5.2 and later
* Anypoint Studio: October 2014
* Salesforce: v30.0 to v32.0

=== Version 6.0.0 Migrating From Older Versions

If you’re currently using an older version of the connector, a small popup appears in the bottom right corner of Anypoint Studio appears as Updates Available. Click that popup and check for available updates. Click the Salesforce Connector version 6.0.0 checkbox, click *Next*, and follow the instructions provided by the user interface. When prompted, restart Studio.

When creating a flow and using the Salesforce Connector, if you have several versions of the connector installed, you might be asked which version you would like to use. Choose the version you would like to use.

=== Version 6.0.0 Features

Salesforce Metadata API - the connector now supports the following Metadata operations:

* *createMedatada* - Adds one or more new metadata components to your organization.
* *deleteMetadata* - Deletes one or more metadata components from your organization given an object's API names.
* *describeMetadata* - Retrieves the metadata which describes your organization. This information includes Apex classes and triggers, custom objects, custom fields on standard objects, tab sets that define an app, and many other components.
* *deployMetadata* - Use this call to take file representations of components and deploy them into an organization by creating, updating, or deleting the components they represent.
* *listMetadata* - Retrieves property information about metadata components in your organization.
* *readMetadata* - Returns one or more metadata components from your organization for one or more object's API Names.
* *renameMetadata*  - Renames a metadata component in your organization, given its old API name and the new name.
* *retrieveMetadata*  - This call retrieves XML file representations of components in an organization.
* *updateMetadata* - Updates one or more metadata components in your organization.
* *upsertMetadata* - Creates or updates one or more metadata components in your organization.

=== Version 6.0.0 Fixes

* Security token is not required when IP restrictions apply.
* Made API version configurable for OAuth connections.
* Added ability to set readTimeout and connectionTimeout.
* Fixed: Issue regarding missing fields on EXO created through the connector.
* This connector no longer throws NullPointerException when an object to retrieve by ID has been deleted in Salesforce.
* The useDefaultRule option now is passed in a SOAP request message.
* Exposed operation to get SessionID from Salesforce connector.

=== Version 6.0.0 Known Issue

This version is not backward compatible with Salesforce API versions v28.0 and v29.0.

== Salesforce Connector 5.4.12 - March 11, 2015

* Security token is not required when IP restrictions apply.
* Made API version configurable for OAuth connections.
* Added ability to set readTimeout and connectionTimeout.
* Fixed: issue regarding missing fields on EXO created through the connector.
* Fixed: SFDC connector throws NullPointerException when object to retrieve by Id has been deleted in Salesforce.
* Fixed: useDefaultRule option not been passed in soap request message.
* Exposed operation to get SessionID from Salesforce connector.
* Support for the SAML "bearer assertion flow".

=== Version 5.4.12 Compatibility Information

* Mule Runtime: 3.5.2 and later
* Anypoint Studio: October 2014
* Salesforce: v28.0 to v29.0

=== Version 5.4.12 Migration Information

If you currently use an older version of the connector (5.4.10 for example):

. In Anypoint Studio, click the *Updates Available* popup, which appears in the lower right corner of Studio.
. Click the *Salesforce Connector Version 5.4.12* checkbox. 
. Click *Next* and then follow the instructions provided by the user interface. When prompted, restart Studio.
. After restarting, when creating a flow and using the Salesforce Connector, if you have several versions of the connector installed, you may be asked which version you would like to use. Choose the version you would like to use.

MuleSoft recommends that you install the latest version of Studio.

== Salesforce Connector 5.4.10 - October 28, 2014

* Fixed a critical bug related to URL population in the connector
* Updated DevKit version support
* Bug fix: Problem with retrieving metadata when a URL is not specified in a connector configuration.
* Compatibility: +
** Mule Runtime and DevKit: 3.5.1
** Anypoint Studio: October 2014
** Salesforce SOAP, Bulk, and Streaming API: 3

== Salesforce Connector 5.4.9 - September 18, 2014

Features:

* Updated Salesforce SOAP, Bulk, and Streaming APIs to support version 31
* Validated and documented support for SAML assertion flows using SFDC configuration
* Tested and validated the Salesforce Connector for use with CloudHub
* Added guidelines for connector version migration
* Fixed issue related order-by in a query operation
* Fixed bug related to importing a working cascade SFDC project

== Salesforce Connector 5.4.7

* Added Salesforce SOAP API headers support
* Added new exception handling for REST and SOAP API
* Removed Paginated Query operation (since AutoPaging for Query and QueryAll)
* DevKit 3.5.0

== Salesforce Connector 5.4.6

* Added NonPaginatedQuery operation for backwards compatibility since
* Query uses Mule 3.5 AutoPaging
* Added batchSize for queries
* DevKit 3.5.0

== Salesforce Connector 5.4.4

* Fixed new Jetty dependencies for Mule 3.5.0
* Fixes for authorizationUrl and accessTokenUrl in OAuth
* DevKit 3.5.0

== Salesforce Connector 5.4.3

* Added compatibility with the new Mule Batch module
* Added configurable for MAX_DEPTH for BULK API
* DevKit 3.5.0

== Salesforce Connector 5.4.2

* Added getServerTimestamp operation
* New exception handling for reconnection strategy
* Fixed issues with proxies

== Salesforce Connector 5.4.1

* Added Mule 3.5 AutoPaging support for Query and QueryAll
* Added DSQL support
* Added operation to retrieve JobInfo
* Added a way to allow empty security tokens
* Fixed Date values for Nested SObjects in Bulk API
* Fixed QueryResultStream issue when service return more than one page
* DevKit 3.5.0

== Salesforce Connector 5.4.0

* Moved force-wsc as a dependency
* Added support for API v28
* Added support for recursive SObjects
* Added sessionId and serviceUrl parameters on connection
* Fixes for streaming API reconnection
* Added support for reference types that differ from the field name
* DevKit 3.5.0

== Salesforce Connector 5.3.1

* Upgraded DevKit to 3.4.0
* Added support for streaming with OAuth
* Fixes for streaming API

== Salesforce Connector 5.3.0

* Upgraded DevKit to 3.4.0
* Added Mule 3.4 metadata support

== Salesforce Connector 5.2.0

* Upgraded to API v26
* Added setPassword operation
* Fixed documentation issues

== Salesforce Connector 5.1.3

* Upgraded to DevKit 3.3.2
* Added paging capabilities with paginated-query method
* Added support for Object Search queries using SOSL
* Fixed SessionTimedOutException INVALID_SESSION_ID when doing
* Fixed several concurrent requests with a timed out session
* Fixed get-deleted and get-updated operations
* Fixed blocking account when trying to disconnect if credentials are wrong
* Updated documentation and fixed documentation issues

== Salesforce Connector 5.1.2

* Fixed issue related to ObjectStoreManager injection and get-updated-objects.

== Salesforce Connector 5.1.1

* Fixed issue related to URL transformer with DevKit 3.3.1.

== See Also

* Learn how to http://www.mulesoft.org/documentation/display/current/Anypoint+Exchange#AnypointExchange-InstallingaConnectorfromAnypointExchange[Install Anypoint Connectors] using Anypoint Exchange.
* Access MuleSoft’s link:http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal].
