= SAP Connector Release Notes
:keywords: java connector, jco, release notes, sap

Mule ESB supports SAP integration through our Anypoint Connector for SAP, which is an SAP-certified Java connector that leverages the SAP Java Connector (JCo) libraries.

*Guide:* link:/mule-user-guide/v/3.7/sap-connector[SAP Connector]
////
== Contents

.xref:sap-connector-228[SAP Connector 2.2.8 - January 19, 2016]
* xref:sap-connector-228-compatibility[Version 2.2.8 Compatibility]
* xref:sap-connector-228-features[Version 2.2.8 Features]
* xref:sap-connector-228-fixes[Version 2.2.8 Fixes]
* xref:sap-connector-228-known-issues[Version 2.2.8 Known Issues]

.xref:sap-connector-227[SAP Connector 2.2.7 - July 1, 2015]
* xref:sap-connector-227-compatibility[Version 2.2.7 Compatibility]
* xref:sap-connector-227-features[Version 2.2.7 Features]
* xref:sap-connector-227-fixes[Version 2.2.7 Fixes]
* xref:sap-connector-227-known-issues[Version 2.2.7 Known Issues]

.xref:sap-connector-226[SAP Connector 2.2.6 - June 17, 2015]
* xref:sap-connector-226-compatibility[Version 2.2.6 Compatibility]
* xref:sap-connector-226-features[Version 2.2.6 Features]
* xref:sap-connector-226-fixes[Version 2.2.6 Fixes]
* xref:sap-connector-226-known-issues[Version 2.2.6 Known Issues]

.xref:sap-connector-225[SAP Connector 2.2.5 - November 28, 2014]
* xref:sap-connector-225-compatibility[Version 2.2.5 Compatibility]
* xref:sap-connector-225-features[Version 2.2.5 Features]
* xref:sap-connector-225-fixes[Version 2.2.5 Fixes]
* xref:sap-connector-225-known-issues[Version 2.2.5 Known Issues]
////
[[sap-connector-228]]
== SAP Connector 2.2.8 - January 28, 2016

[[sap-connector-228-compatibility]]
=== Version 2.2.8 Compatibility

The MuleSoft Enterprise Java Connector for SAP connector is compatible with:

|===
|Application/Service|Version

|Mule Runtime|3.5.x or higher
|SAP R/3|Release 3.1 or higher
|SAP ERP|6.0 EhP 7 (SAP_APPL 607) or higher
|Java|1.7.0_x
|Anypoint Studio|5.x
|===

[[sap-connector-228-features]]
=== Version 2.2.8 Features

* None

[[sap-connector-228-fixes]]
=== Version 2.2.8 Fixes

* Java's UTF-8 encoding had not been recognizing initial character BOM (Byte Order Marker).

* Metadata retrieval in DataSense for BAPI names containing slashes ("/"), e.g. "/DSD/ME_GETLIST_TR", is fixed.

[[sap-connector-228-known-issues]]
=== Version 2.2.8 Known Issues

* Destination Provider reference gets lost after hot redeploy of an application (i.e. modifying the mule-config.xml)

[[sap-connector-227]]
== SAP Connector 2.2.7 - July 1, 2015

[[sap-connector-227-compatibility]]
=== Version 2.2.7 Compatibility

The MuleSoft Enterprise Java Connector for SAP connector is compatible with:

|===
|Application/Service|Version

|Mule Runtime|3.5.x or higher
|SAP R/3|Release 3.1 or higher
|SAP ERP|6.0 EhP 7 (SAP_APPL 607) or higher
|Java|1.7.0_x
|Anypoint Studio|5.x
|===

[[sap-connector-227-features]]
=== Version 2.2.7 Features

* None

[[sap-connector-227-fixes]]
=== Version 2.2.7 Fixes

* Compatibility issue with Anypoint Studio 5.2: when making a BAPI call or sending an IDoc, the SAP outbound endpoint could not parse an XML input built with a DataWeave Message Transformer.

* XML version 2 parser displayed confusing ERROR messages expected when defining the record type.

* The "MINIMAL" metadata mode now generates sample rows for tables.

[[sap-connector-227-known-issues]]
=== Version 2.2.7 Known Issues

* Destination Provider reference gets lost after hot-redeploy of an application (i.e. modifiying the mule-config.xml)

[[sap-connector-226]]
== SAP Connector 2.2.6 - June 17, 2015

[[sap-connector-226-compatibility]]
=== Version 2.2.6 Compatibility

The MuleSoft Enterprise Java Connector for SAP connector is compatible with:

|===
|Application/Service|Version

|Mule Runtime|3.5.x or higher
|SAP R/3|Release 3.1 or higher
|SAP ERP|6.0 EhP 7 (SAP_APPL 607) or higher
|Java|1.7.0_x
|Anypoint Studio|5.x
|===

[[sap-connector-226-features]]
=== Version 2.2.6 Features

* Added demo examples to public site, available for download at http://mulesoft.github.io/sap-transport/

* Extended multi-tenancy support to all the connection parameters (jcoAsHost, jcoUser, jcoLang, jcoClient, jcoPasswd & jcoSysnr) so that the connections can be defined dynamically in runtime. This way, the connector can now be used in real multi-tenant scenarios within Data Gateway.

* Set the correct mimeType for payload to each message created by the SAP Transport in order to be fully compatible with the new Data Framework.

[[sap-connector-226-fixes]]
=== Version 2.2.6 Fixes

* Operation timeout cannot be configured for SAP Inbound Endpoint.

* XML definition not removed from config file after deletion from Studio GUI.

* NullPointerException when using Scallable Node Controller (SNC) and the password attribute is null. The SNC connection mode uses digital certificates to execute the authentication and hence no username and password are required.

* Defective IDoc to XML conversion after upgrading to SAPJCo 3.0.13 and SAPidoc 3.0.12.

[[sap-connector-226-known-issues]]
=== Version 2.2.6 Known Issues

* Destination Provider reference gets lost after hot-redeploy of an application (i.e. modifiying the mule-config.xml)

[[sap-connector-225]]
== SAP Connector 2.2.5 - November 28, 2014

[[sap-connector-225-compatibility]]
=== Version 2.2.5 Compatibility
The MuleSoft Enterprise Java Connector for SAP connector is compatible with:

|===
|Application/Service|Version

|Mule Runtime|3.5.x or higher
|SAP R/3|Release 3.1 or higher
|SAP ERP|6.0 EhP 7 (SAP_APPL 607) or higher
|Java|1.7.0_x
|Anypoint Studio|5.x
|===

[[sap-connector-225-features]]
=== Version 2.2.5 Features

* Full-featured SAP Editor - SAP Editor includes more options to browse SAP objects (IDocs & Functions), display complete details of the selected SAP Object metadata (XML Template and/or XSD) and export the data to the desired directory. DataSense has also been improved in order to reload metadata whenever any of the following changes: SAP Object, Type (IDoc / Function), Output XMl, XML Version.

* Support for IDoc Extensions - Is is now possible to generate the metadata structure for a custom IDoc.

* Support for XML version 2 - It is set as the default XML version to configure a BAPI request.

* Improved DataSense metadata discovery - for SAP Objects, Type (IDoc/Function), Output XML and XML Version. It also provides better coverage of failure messages.

[[sap-connector-225-fixes]]
=== Version 2.2.5 Fixes

* Inbound endpoint support for qRFC doesn't work with IDocs.

* Nested BAPI structures cannot be parsed when trying to convert from XML to JCoFunction.

* When parsing a JCo response with empty tables using XML version 2, an empty row is attached to them.

* Failure to convert a BAPI result to XML.

* Object finder doesn't return inbound IDocs, only outbound.

* XML parsers cannot process IDocs or BAPIs with slash (/) character in their name.

* BAPI tables with name-less fields cannot be processed.

* Inbound endpoint fails in some Mule Cluster configurations.

* JCo library generates classloader leaks (only when JCo dependencies and the SAP connector lib are in the application lib directory and the latter is redeployed).

[[sap-connector-225-known-issues]]
=== Version 2.2.5 Known Issues

* Operation timeout cannot be configured for SAP Inbound Endpoint.

* Destination Provider reference gets lost after hot-redeploy of an application (i.e. modifiying the mule-config.xml)
