= SAP Connector Release Notes
:keywords: sap, connector, release notes

Mule ESB supports SAP integration through our Anypoint Connector for SAP, which is an SAP-certified Java connector that leverages the SAP Java Connector (JCo) libraries.

== SAP Connector 2.2.7 - July 1, 2015

=== Version 2.2.7 Compatibility

The SAP connector 2.2.7 is compatible with:

[width="80",cols="50,50",options="header"]
|===
|Application/Service |Version
|Mule Runtime |3.5.0 or later
|SAP R/3 |Release 3.1 or later
|SAP ERP |6.0 EhP 7 (SAP_APPL 607) or later
|Java |1.7.0_x
|Anypoint Studio |5.x
|===

=== Version 2.2.7 Features

* None.

=== Version 2.2.7 Fixes

The following issues have been fixed in this release:

* Compatibility issue with Anypoint Studio 5.2: when making a BAPI call or sending an IDoc, the SAP outbound endpoint wasn't able to parse an XML input built with a DataWeave message transformer.
* XML version 2 parser displays confusing error messages that are expected when defining the record type.
* The Minimal Metadata mode does not generate sample rows for tables.

=== Version 2.2.7 Known Issues

* Destination Provider reference gets lost after hot-redeploy of an application (such as, modifying the `mule-config.xml`).

== SAP Connector 2.2.6 - June 17, 2015

=== Version 2.2.6 Compatibility

The SAP connector 2.2.6 is compatible with:

[width="80",cols="50,50",options="header"]
|===
|Application/Service |Version
|Mule Runtime |3.5.0 or later
|SAP R/3 |Release 3.1 or later
|SAP ERP |6.0 EhP 7 (SAP_APPL 607) or later
|Java |1.7.0_x
|Anypoint Studio |5.x
|===

=== Version 2.2.6 Features

* Added demo examples to the public site available for download at http://mulesoft.github.io/sap-transport/.
* Extended multi-tenancy support to all the connection parameters (jcoAsHost, jcoUser, jcoLang, jcoClient, jcoPasswd, and jcoSysnr) so that the connections can be defined dynamically during run time. By doing this, the connector can be used in real multi-tenant scenarios within Data Gateway.
* Set the correct mimeType for payload to each message created by the SAP Transport to be fully compatible with the new Data Framework.

=== Version 2.2.6 Fixes

These issues have been resolved in this release:

* Operation timeout cannot be configured for SAP Inbound Endpoint.
* XML definition is not removed from config file after it is deleted from Studio GUI.
* `NullPointerException` when using Scalable Node Controller (SNC) and the password attribute is null. The SNC connection mode uses digital certificates to execute the authentication and hence username and password aren't required.
* Defective IDoc to XML conversion after upgrading to SAPJCo 3.0.13 and SAPidoc 3.0.12.

=== Version 2.2.6 Known Issues

* Destination Provider reference gets lost after hot-redeploy of an application (such as, modifying the `mule-config.xml`).

== SAP Connector 2.2.5 - November 28, 2015

=== Version 2.2.5 Compatibility

The SAP connector 2.2.5 is compatible with:

[width="80",cols="50,50",options="header"]
|===
|Application/Service |Version
|Mule Runtime |3.5.0 or later
|SAP R/3 |Release 3.1 or higher
|SAP ERP |6.0 EhP 7 (SAP_APPL 607) or higher
|Java |1.7.0_x
|Anypoint Studio |5.x
|===

=== Version 2.2.5 Features

* *Full-featured SAP Editor* - SAP Editor includes more options to browse SAP objects (IDocs & Functions), display complete details of the selected SAP Object metadata (XML Template and/or XSD), and export the data to the desired directory. DataSense has also been improved to reload metadata due to any change in the following: SAP Object, Type (IDoc / Function), Output XMl, XML Version.
* *Support for IDoc Extensions* - It is now possible to generate the metadata structure for a custom IDoc.
* *Support for XML version 2* - It is set as the default XML version to configure a BAPI request.
* *Improved DataSense metadata discovery* - for SAP Objects, Type (IDoc/Function), Output XML, and XML Version. It also provides better coverage of failure messages.

=== Version 2.2.5 Fixes

* Inbound endpoint support for qRFC doesn’t work with IDocs.
* Nested BAPI structures cannot be parsed when trying to convert from XML to JCoFunction.
* When parsing a JCo response with empty tables using XML version 2, an empty row is attached to them.
* Failure to convert a BAPI result to XML.
* Object finder doesn’t return inbound IDocs, only outbound.
* XML parsers cannot process IDocs or BAPIs with slash (/) character in their name.
* BAPI tables with name-less fields cannot be processed.
* Inbound endpoint fails in some Mule Cluster configurations.
* JCo library generates classloader leaks (only when JCo dependencies and the SAP connector lib are in the application lib directory and the latter is redeployed).

=== Version 2.2.5 Known Issues

* Operation timeout cannot be configured for SAP Inbound Endpoint.
* Destination Provider reference gets lost after hot-redeploy of an application (i.e. modifiying the mule-config.xml).

== See Also

* Learn how to link:/docs/display/current/Installing+Connectors[Install and Configure Anypoint Connectors] in Anypoint Studio.
* Access MuleSoft’s http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal]. 
