= SuccessFactors Connector Release Notes
:keywords: release notes, connector, sap, successfactors

_Select_

*Connector Guide:* link:/mule-user-guide/v/3.7/successfactors-connector[SuccessFactors Connector]

The Anypoint Connector for SuccessFactors provides full support to query, create, update and delete entities using the **SFAPI** API exposed by SuccessFactors. For more information about the product, visit link:https://help.sap.com/cloud4hr[SuccessFactors HCM Suite site].

== Version 2.0.0 - December 29, 2015

The release notes for version 2.0.0 of the SuccessFactors Connector accompany the link:/mule-user-guide/v/3.7/successfactors-connector[SuccessFactors Connector guide].

=== Version 2.0.0 Compatibility

The SuccessFactors Connector is compatible with:

|===
|Application/Service|Version

|*Mule Runtime* |3.7.0 or higher
|*Anypoint Studio* |5.3.1 or higher
|*Java* |7
|===

=== Features

- List all the entities in your company instance.
- Obtain entities metadata.
- Insert/Update/Upsert/Delete entities.
- Query the SuccessFactors platform using SFQL (SuccessFactors Query Language).
- Submit, list and cancel asynchronous query jobs, get their statuses and results.

=== Known Issues

Due to API limitations, fetching metadata for all entities is a slow process. In order to reduce the wait time, make sure that the "Fetch all entities" checkbox is unchecked, and complete the "Entity List" with an abridged list of entity names. If you need a list of all available entities in your organization to do this, you can obtain it via the "List entities" operation.

== See Also

* Learn how to link:/mule-fundamentals/v/3.7/anypoint-exchange[Install Anypoint Connectors] using Anypoint Exchange.
* Access MuleSoft’s link:http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, link:http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s link:http://www.mulesoft.com/support-login[Customer Portal].
