= X12 and EDIFACT Modules 1.0.1 Release Notes
:keywords: b2b, x12, edifact

*_Premium_*

*November 10, 2015*

== New in This Release

This release contains the following fixes:

* Fixed dead lock when acquiring lock to increment control number
* Writing now correctly fails when writing invalid characters and repeating values outside defined limits
* New icons for the connector

For more information, such as how to install or use these modules, see
link:/anypoint-b2b/anypoint-b2b[Anypoint B2B], link:/anypoint-b2b/edifact-module[EDIFACT Module], and link:/anypoint-b2b/x12-module[X12 Module].

== Migration Guide

No application changes are needed from 1.0.0.

== Compatibility

[width="100%",cols=",,",options="header"]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and newer
|===

== Known Issues and Limitations

* X12 binary segments are not supported, are not included in schema definitions, and cause errors.
* EDIFACT packages (containers for binary data) are not supported, and cause errors if you attempt to use them.
* EDIFACT interactive exchanges (using UIB header segment and UIZ trailer segment) are not supported.
* Code values are not currently verified for either reading or writing.
* X12 syntax rules and EDIFACT dependency notes are not currently enforced for either reading or writing.
* EDIFACT groups are not supported.
