= X12 and EDIFACT Modules Release Notes

_Premium_

== Version 1.0 RC 2 - July 21, 2015

This release contains many improvements, including:

* Better message validation when writing messages
* Duplicate checking is now disabled by default
* EDIFACT:
** Support for D93A and D00A standards
** Fixed several schema issues from ambiguous EDIFACT table data
** Fixed issue with sender/receiver ids being reversed in writer
** Improved handling and detection of default delimiters, and added configuration support for changing the defaults for receive messages

For installation information on Anypoint B2B, EDIFACT, and X12,
see <<See Also>>.

=== Version 1.0 RC 2 - Compatibility

* Mule Runtime: Mule 3.6.0 and newer

=== Version 1.0 RC 2 - Known Issues

* X12 binary segments are not supported, are not included in schema definitions and cause errors.
* EDIFACT packages (containers for binary data) are not supported, and  cause errors if you attempt to use them.
* EDIFACT interactive exchanges (using UIB header segment and UIZ trailer segment) are not supported.
* Code values are not currently verified for either reading or writing.
* X12 syntax rules and EDIFACT dependency notes are not currently enforced for either reading or writing.
* EDIFACT groups are not supported

== Version 1.0 RC 1 - June 23, 2015

This release contains many improvements, including

EDIFACT:

* Support for CONTRL acknowledgements
* D.02A support
* New flag to control whether a UNA segement
* Fixed problems with UNS segment handling in reading/writing

X12:

* Initial support for 999 functional acknowledgements
* Support for the upcoming B2B management portal
* Fixed JAR conflict between APIkit and EDIFACT/X12 modules
* Exponential values are now supported
* Improved configuration labels
* Many bug fixes

For installation information on Anypoint B2B, EDIFACT, and X12,
see <<See Also>>.

=== Version 1.0 RC 1 - Compatibility

Mule Runtime: Mule 3.6.0 and newer

=== Version 1.0 RC 1 - Known Issues

* X12 binary segments are not supported, are not included in schema definitions and cause errors.
* EDIFACT packages (containers for binary data) are not supported, and  cause errors if you attempt to use them.
* EDIFACT interactive exchanges (using UIB header segment and UIZ trailer segment) are not supported.
* Code values are not currently verified for either reading or writing.
* X12 syntax rules and EDIFACT dependency notes are not currently enforced for either reading or writing.
* EDIFACT groups are not supported.

== Version 1.0 Beta 3 - May 6, 2015

This release launches the first version of the EDIFACT module, allowing you to read, validate, and write d96a, d98b, and d01a EDIFACT documents.

This release also contains a number of other improvements and bug fixes:

* The previous module was renamed to the X12 Module which co-exists with the EDIFACT module. Along with this, the namespace has changed. See <<Version 1.0 Beta 3 - Migration>> for more details.
* The keys used for segments and loops/groups now include the position within the transaction set or message, so that their DataSense display order matches the transaction set or message definition, for example,  "0100 PO1". The displayed information for values within a segment is also ordered to match the actual segment layout.
* 997 acknowledgements generated by X12 receive processing have been relocated to "FunctionalAcksGenerated" on the message to ensure clarity and consistency with the EDIFACT module.
* The EDI schema language has changed to allow a wider variety of formats, adopting more common terms like "structures" instead of "transactions". For more information, see <<Version 1.0 Beta 3 - Migration>>.

=== Version 1.0 Beta 3 - Compatibility

* Mule Runtime: Mule 3.6.0 and newer

=== Version 1.0 Beta 3 - Migration

Metadata structures have changed from the beta-2 release. You need to clear your DataSense metadata and regenerate any data mappings.

To clear metadata, go to the Connections Explorer, right-click the EDI module for your project, and click  *Clear DataSense Metadata*.

The namespace used for the X12 module configuration has changed from `http://www.mulesoft.org/schema/mule/edi` to `http://www.mulesoft.org/schema/mule/x12-edi`, and the schema location for this namespace has changed from `http://www.mulesoft.org/schema/mule/edi/1.0/mule-edi.xsd` to `http://www.mulesoft.org/schema/mule/x12-edi/1.0/mule-x12-edi.xsd`.

Some of the EDI Schema Language (ESL) key names have changed. The key used for basic message unit definitions, called "transaction sets" in X12, has changed from "transactions" to "structures". The key used for the X12 transaction set/structure functional group code has changed from "group" to "class". The key used for substructures of a message unit, known as "loops" in X12 terminology, has changed from "loopId" to "groupId", and references to these (used in overlay schema definitions) has changed from "loopIdRef" to "groupIdRef".

=== Version 1.0 Beta 3 - Known Issues

X12 binary segments are not supported - they are ignored. EDIFACT packages (containers for binary data) are not supported, and cause errors if you attempt to use them.

EDIFACT interactive exchanges (using UIB header segment and UIZ trailer segment) are not supported.

Exponential notation for decimal numbers is not currently supported.
Code values are not currently verified for either reading or writing.
X12 syntax rules and EDIFACT dependency notes are not currently enforced for either reading or writing.

EDIFACT groups are not supported in this initial EDIFACT release. Error handling and CONTRL acknowledgement generation is also incomplete.

== See Also

For more information, such as how to install or use the modules described in this guide, see the
link:/anypoint-b2b/anypoint-b2b[Anypoint B2B], link:/anypoint-b2b/edifact-module[EDIFACT Module], link:/anypoint-b2b/x12-module[X12 Module] guides.
