= X12 and EDIFACT Modules 1.0.0 Release Notes
:keywords: b2b, x12, edifact

*_Premium_*

*Sept 21, 2015*

== New in This Release

This release contains many improvements, including:

* Support for reading/writing multiple versions of the same transaction type within a single message
* Additional EDIFACT message types d03A and d95B
* Improved structure usability with DataWeave and MEL by including "Loop" in the key name for loops and using underscores instead of spaces.. You will need to update your integrations appropriately for this (see below).
* Improved validation logic on writing.
* Many bug fixes

For more information, such as how to install or use these modules, see
link:/anypoint-b2b/anypoint-b2b[Anypoint B2B], link:/anypoint-b2b/edifact-module[EDIFACT Module], and link:/anypoint-b2b/x12-module[X12 Module].

== Migration Guide

All of your transformations and expressions that references parts of the EDI message structure must be updated for the following changes:

* The "Transactions" list has been changed to "TransactionSets" and now has an additional level for the version of the transactions.
** Example: payload.Transactions."850" now becomes payload.TransactionSets.v5010."850"
* All keys no longer have spaces - instead they have underscores
** Example: payload."0100 PO1" becomes payload."0100_PO1"
* Any segment that is a loop
** Example: payload.Detail."0100 PO1" becomes payload.Detail."0100_PO1_Loop"

== Compatibility

[width="100%",cols=",,",options="header"]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and newer
|===

== Known Issues and Limitations

* X12 binary segments are not supported, are not included in schema definitions, and cause errors.
* EDIFACT packages (containers for binary data) are not supported, and cause errors if you attempt to use them.
* EDIFACT interactive exchanges (using UIB header segment and UIZ trailer segment) are not supported.
* Code values are not currently verified for either reading or writing.
* X12 syntax rules and EDIFACT dependency notes are not currently enforced for either reading or writing.
* EDIFACT groups are not supported.
