= X12 and EDIFACT Modules 1.0-beta-3 Release Notes
:keywords: b2b, x12, edifact, d96a, d98b, d01a, 997

*_Premium_*

*May 6, 2015*

== New in This Release

This release launches the first version of the EDIFACT module, allowing you to read, validate, and write d96a, d98b, and d01a EDIFACT documents. This release also contains a number of other improvements and bug fixes:

The previous module was renamed to the X12 Module which co-exists with the EDIFACT module. Along with this, the namespace has changed. Please see the migration guide for more details.

The keys used for segments and loops and groups now include the position within the transaction set or message, so that their DataSense display order matches the transaction set or message definition, for example, `0100 PO1`. The displayed information for values within a segment is also ordered to match the actual segment layout.

997 acknowledgements generated by X12 receive processing have been relocated to "FunctionalAcksGenerated" on the message to ensure clarity and consistency with the EDIFACT module.

The EDI schema language has changed to allow a wider variety of formats, adopting more common terms like "structures" instead of "transactions". Please see the migration guide for more details.

For more information, such as how to install or use these modules, see
link:/anypoint-b2b/anypoint-b2b[Anypoint B2B], link:/anypoint-b2b/edifact-module[EDIFACT Module], and link:/anypoint-b2b/x12-module[X12 Module].


== Compatibility

[width="100%",cols=",,",options="header"]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and newer
|===

== Migration

Metadata structures have changed from the beta-2 release. You need to clear your DataSense metadata and regenerate any data mappings. To clear metadata, go to the Connections Explorer, find the EDI module for your project, right click on it and select Clear DataSense Metadata.

The namespace used for the X12 module configuration has changed from "http://www.mulesoft.org/schema/mule/edi" to "http://www.mulesoft.org/schema/mule/x12-edi", and the schema location for this namespace has changed from "http://www.mulesoft.org/schema/mule/edi/1.0/mule-edi.xsd" to "http://www.mulesoft.org/schema/mule/x12-edi/1.0/mule-x12-edi.xsd"

Some of the EDI Schema Language (ESL) key names have changed. The key used for basic message unit definitions, called "transaction sets" in X12, has changed from "transactions" to "structures". The key used for the X12 transaction set/structure functional group code has changed from "group" to "class". The key used for substructures of a message unit, known as "loops" in X12 terminology, has changed from "loopId" to "groupId", and references to these (used in overlay schema definitions) has changed from "loopIdRef" to "groupIdRef".

== Known Issues

* X12 binary segments are not supported - they are ignored. EDIFACT packages (containers for binary data) are not supported, and cause errors if you attempt to use them.
* EDIFACT interactive exchanges (using UIB header segment and UIZ trailer segment) are not supported.
* Exponential notation for decimal numbers is not currently supported.
Code values are not currently verified for either reading or writing.
* X12 syntax rules and EDIFACT dependency notes are not currently enforced for either reading or writing.
* EDIFACT groups are not supported in this initial EDIFACT release. Error handling and CONTRL acknowledgement generation is also incomplete
