= Fixing Common Problems
:keywords: tcat, problems, workarounds, issues

If you are experiencing issues, review the following common problems and workarounds for Tcat Server.

== Unable to Communicate with Tcat Server

When servers are registered, they are registered with a specific IP address. If you are testing on a laptop with a wireless connection and you move from one location to another, your IP address might change, and the servers  no longer are able to communicate with Tcat Server.

=== Workaround

In this case, you must un-register and re-register the servers with the current IP address.

== Main Screen Does Not Appear

If you are running Internet Explorer 7 on Windows 2008, you can log in to Tcat Server but the main screen does not appear.

=== Workaround

To work around this, choose File > Add this site to... > Trusted Sites.

== Deployment Is Interrupted

If you navigate to another tab while a package is being deployed, the deployment is interrupted.

=== Workaround

To work around this issue, wait for a package to be deployed before navigating elsewhere.

== Monitoring and Diagnostic Screens Disappear

If you increase the font size on Mozilla Firefox, the monitoring and diagnostic screens disappear.

=== Workaround

Leave the font size set to the default.

== Filename Parentheses in Firefox

If you download the installer more than once, Firefox appends parentheses to the file name, which causes problems when you try to run the installer.

=== Workaround

If you must download the installer again, delete the original file first so that Firefox leaves the original name intact

== SSL/TLS Handshake Exception

APR Connector Failure using Tomcat 5.5 with Tcat

Errors such as "javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake" may result from limitations within the Tcat Server Administration Console, which cannot currently pair with SSL/TLS connectors under certain conditions.

=== Workarounds

* Configure the Tomcat servers with an HTTP (non-SSL) connector on a port that the firewall blocks from the public internet, but not from the console.
* Configure the Tomcat servers with an AJP (non-SSL) connector on a port that the firewall blocks from the public internet, but not from the console.

== Tcat Fails to Start on Windows

Tcat Server service on Windows fails to start

=== Workaround

Solution: Open a terminal window and navigate to the Tcat Server installation/bin directory. Type tcatserver6w and examine the contents under Java tab. Make sure both JAVA_HOME and JRE_HOME are pointing to the right path
