= Creating Remote Workspaces

Remote workspaces are workspaces that exist in another Tcat Server instance. Tcat Server allows you to attach these workspaces to your local Tcat Server instance so you can browse them and perform actions such as replication.

Searching across remote workspaces is not currently supported.

==== To attach a remote workspace:

. On the Administration tab, click *Remote Workspaces* in the left navigation pane, and then click *New*.
. Enter the information described below.
+
[width="100%",cols="50%,50%",options="header",]
|===
|Field |Description
|Local Workspace Name |The name that will appear locally for the remote workspace.
|Attach to Workspace |The local workspace in which you are attaching the remote workspace. As you type a name, local workspaces will be listed. To create a top-level workspace, leave this field blank.
|URL a|
The URL of the remote workspace's Atom feed, using the format

http://HOST/api/registry/PATH

, where HOST is the remote Tcat Server instance and PATH is the workspace, such as

http://acme.com:8080/api/registry/Services/Accounting

|Username |The user name in the remote Tcat Server instance that will be used to access the information.
|Password |The password for the above user.
|===
. Click *Save*.

link:/docs/display/TCAT/Working+with+Server+Profiles[<< Previous: *Working with Server Profiles*]

link:/docs/display/TCAT/Monitoring+Repository+Activity[Next: *Monitoring Repository Activity* >>]
