= Scheduling the Usage Statistics Script

By default, instances of Tcat Server run the Usage Statistics script ever thirty minutes. This script sends a randomly generated ID to enable MuleSoft to track the number of Tcat Server administration console instances in use. It does *not* contain any identifying information such as IP addresses, and it does not track the number of Tcat Server agents that are installed (just administration console instances). If you are behind a firewall, this script does not do anything, and it does not generate any errors or disrupt service in any way.

If you want to change or disable this script, do the following:

. On the Administration tab in the Tcat Server administration console, click *Utility* in the left-hand navigation pane, and then click *Scheduler*.
. Click *Usage Statistics Job*.
. To change the frequency of the pings (default is every 30 minutes), change the link:/docs/display/TCAT/Automating+Tasks#AutomatingTasks-cron[cron command], and then click *Save*.
. If you do not want this script to run, click *Delete*.

link:/docs/display/TCAT/Applying+Your+Tcat+Server+License[<< Previous: *Applying Your Tcat Server License*]

link:/docs/display/TCAT/Working+with+Logs[Next: *Working with Logs* >>]
