= Upgrading to Tcat Server 6 R4

If you have an older version of Tcat Server installed, the new installer will retain all paired servers, new web applications, user roles, server profiles, and environment variables you have saved.

If you are using a version of Tcat Server 6 earlier than R3, you need to follow the upgrade path to link:/docs/display/TCAT/Upgrading+to+6.3[R3 first].

[WARNING]
====
*NOTE*

The Tcat Server 6.4.5 console is not backward-compatible with agents from older releases of Tcat.
This means you must upgrade each agent webapp to the 6.4.5 release or newer before starting up the new Tcat Server console. Doing this does not require any interruption of regular web service from your Tcat or Tomcat server instances.

Follow these steps:

* Copy any webapps/agent/WEB-INF/truststore.jks file to a backup location.
* Delete the webapps/agent.war file.
* Wait about ten seconds and the agent will be automatically undeployed.
* Copy the new agent.war into your webapps/ directory to deploy the new copy.
* Move your backed-up truststore.jks back into the webapps/agent/WEB-INF directory.
====

Download the Tcat Server installer for Windows (.exe), Linux and Solaris (.sh), and Mac OS (.dmg) from http://www.mulesoft.com/download-tcat-server-enterprise-tomcat.

== Run the Installer

. Run the Installer
+
image:/docs/plugins/servlet/confluence/placeholder/unknown-macro?name=table-plus&locale=en_GB&version=2[image]
+
. Point to the existing application install directory
. The installer retains all your existing settings.

[WARNING]
====
*NOTE*

After upgrading Tcat Server, and *before* logging into the Tcat Server console in your web browser again, make sure that you *clear your browser's file cache*. Without doing clearing your browser cache, the console web application will run without incident, but the older version of Tcat's console code that is still resident in your web browser will not match the new server side of the console, and this will cause errors in the Tcat console logs, and erratic behavior in the web browser.
====

== What the Installer Does

The Tcat Server 6 R4 installer is designed to perform the following tasks:

. Back up the agent web application (copies webapp/agent to tcat-backup/agent) and unpack the new one
. Back up the console web application (copies webapp/console to tcat-backup/console) and unpack the new one
. Back up any user-modified Tomcat configuration files in the conf directory tree (copies conf to tcat-backup/conf)
. Preserve old agent.properties which defines which port the agent is listening on
. Preserve agent truststore.jks used to provide security settings associated with the agent

Once the installer has completed the upgrade, you should compare the new Tcat Server configuration files in the conf directory with the older configuration files in tcat-backup/conf to determine which of your changes you want to carry forward into the new Tcat Server configuration.

link:/docs/display/TCAT/Installation[<< Previous: *Installation*]

link:/docs/display/TCAT/Installing+Multiple+Tcat+Instances+on+a+Single+Machine[Next: *Multiple Instances on a Single Machine* >>]
