= Working with Applications

The application API allows you to list, create, update, and delete applications. All resources or methods that return or accept a type (except where noted) use the application JSON type. As an example, here's data you might receive, in JSON format, in response to a request to get an application:

[source]
----
{
  "domain":"hello",
  "fullDomain":"hello.cloudhub.io",
  "workers":1,
  "hasFile":false,
  "filename": "myapp.zip",
  "muleVersion", "3.3.0"
  "properties": {
    "foo":"bar"
  },
  "status":"STARTED",
  "workerStatuses":[
     {
       "id":"",
       "host":"xxx.xxx.xxx.xxx",
       "port":8081,
       "status":"STARTED"
     }
   ],
   "secureDataGateway": {
     "connected": false
   },
}
----


== Application Properties

The following are the properties for applications.

[width="100",cols="50,50",options="header"]
|===
|Property |Description
|domain |The short domain name of the application.
|fullDomain |The long domain name of the application.
|hasFile |Whether or not an application file has been supplied for this application.
|muleVersion |The Mule version for this application. Either 3.1.2 or 3.2.0.
|properties |A set of environment variables that get set when the application is started.
|workers |The number of workers associated with this application.
|status |The status of the application. STARTED, DEPLOYING, UNDEPLOYED, DEPLOYED_FAILED are valid values.
|secureDataGateway |Whether or not the data gateway is connected, and how long it's been connected.
|===

== Operations for Applications

The following is a summary of the operations you can perform on your application and the resource you specify for each.

[width="100a",cols="33a,33a,33a",options="header"]
|===
|Operation |Resource |Description
|link:/docs/display/current/List+All+Applications[GET] |/api/applications |Lists all applications.
|link:/docs/display/current/Create+Application[POST] |/api/applications |Creates an application.
|link:/docs/display/current/Get+Application[GET] |/api/applications/\{domain} |Gets an application.
|link:/docs/display/current/Deploy+Application[POST] |/api/applications/\{domain}/deploy |Deploys a Mule application file.
|link:/docs/display/current/Update+Application+Metadata[PUT] |/api/applications/\{domain} |Updates the metadata for an application.
|link:/docs/display/current/Delete+Application[DELETE] |/api/applications/\{domain} |Deletes an application.
|===

[TIP]
Check out the https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal] of the CloudHub API to see an interactive reference of all the supported resources, methods, required properties and expected responses.
