
= Mule ESB and CloudHub 

CloudHub and Mule ESB share a single runtime, ensuring that building applications for both is easy. However, there are some differences as you move to the cloud. CloudHub provides more out of the box functionality, such as load balancing, and also has some limitations to which you may need to adapt your application. 

[NOTE]
====
*Notes*

* CloudHub and Mule ESB rely on the new Mule Agent. See http://mulesoft.github.io/mule-agent/[Mule Agent Documentation] for more information.
* Mule Agent requires Anypoint API Gateway version 2.0, which is forth coming.
====

== Ports and Hosts

CloudHub provides infrastructure for DNS and load balancing for your applications. This means you must configure your applications in a specific way to utilize this information. CloudHub provides two hosts for you: 

* myapplication.cloudhub.io - routes information to the CloudHub load balancer
* mule-worker-myapplication.cloudhub.io - routes information directly to your CloudHub application, bypassing the load balancer. If you have multiple workers, then this will DNS round-robin between them.

To utilize the load balancer, your application must use specific ports that CloudHub allocates for your HTTP and HTTPS endpoints. See link:/docs/display/current/Developing+a+CloudHub+Application[Developing a CloudHub application] for more details.

== Disk Persistence

CloudHub does not guarantee that writing to disk will survive hardware failures. Instead, you must use an external storage mechanism to store information. For small amounts of data, you can use the Object Store. For applications that have large data storage requirements, we recommend use of a cloud service such as Amazon S3. For temporary storage, the File connector is still available and can be used with the /tmp directory.

== High Availability

Mule ESB offers high availability capabilities through the clustering of Mule instances with link:/docs/display/current/Mule+High+Availability+HA+Clusters[distributed shared memory]. This shared memory is used to provide persistent VM queues, transactions, and cluster-wide data storage.

CloudHub provides high availability through link:/docs/display/current/CloudHub+Fabric[CloudHub Fabric].  CloudHub Fabric provides a combination of load balancing, persistent message queues, and horizontal scaleout. In addition, the platform also actively monitors services and workers for problems. For example, in the case of hardware failure, CloudHub will auto-migrate the application to a different worker using link:/docs/display/current/Managing+CloudHub+Applications#ManagingCloudHubApplications-UpdatingYourApplication[CloudHub zero downtime updates], minimizing down time.

== Logging

While on-premise applications can use custom log4j properties files, CloudHub provides a logging service for allowing logs to be searched, downloaded, or log levels to be customized. See link:#[Viewing Log Data_OLD] for more details.

== ObjectStore

CloudHub provides an implementation of the user object store. It places limits on the usage of this to avoid abuse. These are detailed on the http://www.mulesoft.org/documentation/display/current/Managing+Application+Data+with+Object+Stores[Object Store] page.

== Domains and Shared Resources

When deploying on premises, it's possible to create 'Domain' mule projects that don't hold any flows, but do hold a set of global configuration elements to share among other apps deployed to the same server. link:/docs/display/current/Shared+Resources[Read more]. This is not currently supported in CloudHub.

== JDK Versions

The version of JDK that CloudHub implements for all apps built with Mule runtime 3.5.1 or greater is **JDK 1.7**. Mule runtime 3.6.0 also requires JDK 1.7.

Apps built with runtime 3.5.0 or older are deployed with JDK 1.6.

== Other Components

There are also a few components which CloudHub has limited support for currently:

* Distributed locks: currently, CloudHub will not coordinate invocations of FTP and File endpoints across multiple workers.
* Idempotent routers will work with in memory stores and according to the limitations of the CloudHub ObjectStore if you configure it to use it. If those options do not fit your needs, you can use another ObjectStore.

 
