= Working with Notifications
:keywords: cloudhub, cloudhub api, manage, cloud, enterprise, notifications, get, post, put

The notifications API allows you to list notifications, create notifications and mark as read. All resources or methods that return or accept a type (except where noted) use the application JSON type. As an example, here's an example of what the result from the notifications resource looks like.

[source, json]
----
{
"data":
  [
    {
      "domain" : "myapp",
      "username" : "joecloud",
      "priority" : "INFO",
      "message" : "Something happened",
      "createdAt" : "2015-05-10T23:42:53.010Z",
      "read" : false,
      "readOn" : "2015-02-12T19:51:34.428Z",
      "href" : "https://prod.anypoint.mulesoft.com/cloudhub/api/notifications/518d85fde4b00795a6ec3394"},
      "transactionId": "2a097804-f0d5-11e2-b4d2-9dd46521a02d",
      "properties": {
         "recordId" : "1234"
      }
  ],
  "total": 1
}
----

== Notification Object Properties

The following are the properties for applications.

[width="100a",cols="50a,50a",options="header"]
|===
|Property |Description
|createdAt |The time the notification was created in ISO8601 format.
|domain |The application that the notification is associated with, if any.
|href |The URL of the notification. This can be used as the URL to update the notification status.
|message |The notification message.
|priority |The priority - INFO, WARN, ERROR
|properties |A map of custom properties associated with this notification. These are supplied by an application when creating the notification.
|read |Whether or not the notification has been read.
|readOn |The time the notification was read in ISO8601 format.
|tenantId |The ID of the tenant that the notification is associated with.
|transactionId |The ID of the transaction that this notification is associated with.
|username |The user who created the notification.
|===

== Operations for Notifications

The following is a summary of notification related operations:

[width="100a",cols="34a,33a,33a",options="header",]
|===
|Operation |Resource |Description
|link:/docs/display/current/List+Notifications[GET] |/api/notifications |Lists notifications for all applications
|link:/docs/display/current/Create+Notification[POST] |/api/notifications |Create a new notification.
|link:/docs/display/current/Update+All+Notifications[PUT] |/api/notifications |Mark all notifications as read.
|link:/docs/display/current/Update+Notification[PUT] |/api/notifications/\{id} |Update the status of a notification.
|=== 

[TIP]
====
Check out the https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal] of the CloudHub API to see an interactive reference of all the supported resources, methods, required properties and expected responses.
====
