= Update Application Metadata

The PUT method, specified with the /api/applications/\{domain} resource (where \{domain} is the application domain), updates your application metadata, including the number of workers and system properties. You can also use it to update an existing application. For information on how to update you application, see link:/docs/display/current/Managing+CloudHub+Applications#ManagingCloudHubApplications-UpdatingYourApplication[Updating Your Application].

The update operation can update the workers, properties, muleVersion and filename properties. Properties which are not specified are not updated.

Example Request:

[source]
----
PUT https://anypoint.mulesoft.com/cloudhub/api/applications/yourdomain
Content-Type: application/json

{
  "workers" : 1,
  "properties" : {
     "your.system.property" : "some.value"
  },
  "muleVersion" : "3.6.0",
  "filename" : "myapp.zip"
}
----

Example Response:

[source]
----
200
Content-Type: application/json
Location: https://anypoint.mulesoft.com/cloudhub/api/applications/yourdomain

{
  "workers":1,
  "domain":"yourdomain",
  "fullDomain":"yourdomain.cloudhub.io",
  "hasFile":false,
  "muleVersion":"3.6.0",
  "properties" : {
     "your.system.property" : "some.value"
  },
  "status":"DEPLOYED"
}
----

[TIP]
====
Check out the https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal] of the CloudHub API to see an interactive reference of all the supported resources, methods, required properties and expected responses.
====
