= MUnit
:version-info: 3.7.0 and later
:keywords: munit, testing, unit testing

== Overview

MUnit is a Mule application testing framework that allows you to easily build automated tests for your integrations and APIs. It provides a full suite of integration and unit test capabilities, and is fully integrated with Maven and Surefire for integration with your continuous deployment environment.

With MUnit you can:

* Create your Mule test by writing Mule code
* Create your Mule test by writing Java code
* Disable flow inbound endpoints
* Disable endpoint connectors
* Mock outbound endpoints
* Mock message processors
* Spy any message processor
* Verify message processor calls
* Create not only unit tests but also integration tests in a local environment -- MUnit allows you to start a local FTP/SFTP, DB server or mail server
* Call the Mule client from Mule code
* Assert flow exceptions
* Enable or disable particular tests
* See assertion/error reports with Mule stack trace
* Extend the MUnit framework with plugins
* Check visual coverage in Studio
* Debug your tests with Studio

== MUnit Versions

The current release of MUnit is *1.1.0*. It's the only MUnit version required independently of the Mule version being tested.
Please take a look at the https://docs.mulesoft.com/release-notes/munit-1.1.0-release-notes[Release Notes] 
of the current version to see what's new.

TIP: Since MUnit version 1.0.0, MUnit works for all Mule versions since 3.6.0 (for 3.6.x minor limitations applies please check https://docs.mulesoft.com/release-notes/munit-1.0.0-release-notes#compatibility-information[this link]). 

=== For Users of MUnit 1.0-RC

Some things have change in what regards to the Maven configuration in MUnit 1.0.0.
For an overview of the changes in the Maven configuration, see the link:/mule-user-guide/v/3.8-m1/munit-1.0.0-migration-guide[MUnit 1.0.0 Migration Guide]. For a list of bug fixes and new features, see the link:/release-notes/munit-1.0.0-release-notes[MUnit 1.0.0 Release Notes].

=== For Users of MUnit BETA

If you're coming from the BETA version, you should also check the change in syntax, see the link: https://docs.mulesoft.com/mule-user-guide/v/3.8-m1/munit-1.0-rc-migration-guide[MUnit 1.0-RC Migration Guide]

[[studio]]
== MUnit and Anypoint Studio

MUnit is fully integrated with Anypoint Studio, allowing you to create, design and run MUnit tests just like you would Mule applications. You can also use Anypoint Studio's link:/mule-user-guide/v/3.8-m1/studio-visual-debugger[Studio Visual Debugger] to debug your MUnit tests.

For an overview of MUnit in Anypoint Studio, see link:/mule-user-guide/v/3.8-m1/using-munit-in-anypoint-studio[Using MUnit in Anypoint Studio].

== What You'll Find in These Docs

The pages listed below provide an overview of MUnit features including simple examples. Topics include the MUnit message processors, the DB and FTP servers provided by MUnit, Maven support and more. For a short step-by-step guide to creating a test, see the link:/mule-user-guide/v/3.8-m1/munit-short-tutorial[MUnit Tutorial].

TIP: The examples you'll find in these pages are XML-only; however, as stated <<studio,above>>, you can also use MUnit via Anypoint Studio's graphical interface. See link:/mule-user-guide/v/3.8-m1/using-munit-in-anypoint-studio[Using MUnit in Anypoint Studio] for details.

* link:/mule-user-guide/v/3.8-m1/using-munit-in-anypoint-studio[Using MUnit in Anypoint Studio]
* link:/mule-user-guide/v/3.8-m1/the-munit-suite[The MUnit Suite]
* link:/mule-user-guide/v/3.8-m1/the-mock-message-processor[The Mock Message Processor]
* link:/mule-user-guide/v/3.8-m1/the-verify-message-processor[The Verify Message Processor]
* link:/mule-user-guide/v/3.8-m1/the-set-message-processor[The Set Message Processor]
* link:/mule-user-guide/v/3.8-m1/the-spy-message-processor[The Spy Message Processor]
* link:/mule-user-guide/v/3.8-m1/the-assertion-message-processor[The Assertion Message Processor]
* link:/mule-user-guide/v/3.8-m1/munit-matchers[MUnit Matchers]
* link:/mule-user-guide/v/3.8-m1/munit-database-server[MUnit Database Server]
* link:/mule-user-guide/v/3.8-m1/munit-ftp-server[MUnit FTP Server]
* link:/mule-user-guide/v/3.8-m1/munit-maven-support[MUnit Maven Support]
* link:/mule-user-guide/v/3.8-m1/munit-short-tutorial[MUnit Short Tutorial]
* link:/mule-user-guide/v/3.8-m1/run-and-wait-scope[Run And Wait Scope]
* link:/mule-user-guide/v/3.8-m1/example-testing-apikit[Example: Testing APIKit]
* link:/mule-user-guide/v/3.8-m1/munit-1.0.0-migration-guide[MUnit 1.0.0 Migration Guide]
