= Team Development with Mule

Topics in these books have addressed your local workstation, and a single project with a single configuration file. When working on a team, a Mule project increases in size, increases in its number of developers, and must run in other environments, such as test and production. Here are some practices that make such growth possible.

The different approaches to modularizing Mule configurations and applications are all opportunities for splitting work across teams, whether these teams work on the same overarching project or on different projects with an accent put on reuse.

Download a PDF version of this section link:_attachments/team-development-with-mule.pdf[here].

* link:/mule-user-guide/v/3.8-m1/modularizing-your-configuration-files-for-team-development[Modularizing Your Configuration Files for Team Development]
* link:/mule-user-guide/v/3.8-m1/using-side-by-side-configuration-files[Using Side-by-Side Configuration Files]
* link:/mule-user-guide/v/3.8-m1/using-modules-in-your-application[Using Modules In Your Application]
* link:/mule-user-guide/v/3.8-m1/sharing-custom-code[Sharing Custom Code]
* link:/mule-user-guide/v/3.8-m1/sharing-custom-configuration-fragments[Sharing Custom Configuration Fragments]
* link:/mule-user-guide/v/3.8-m1/sharing-custom-configuration-patterns[Sharing Custom Configuration Patterns]
* link:/mule-user-guide/v/3.8-m1/sharing-applications[Sharing Applications]
* link:/mule-user-guide/v/3.8-m1/sustainable-software-development-practices-with-mule[Sustainable Software Development Practices with Mule]
