= Using Maven in Mule
:keywords: studio, maven, esb, version control, dependencies, libraries

The pages in this section detail how to use maven outside of Anypoint Studio, working directly with Mule. You can use Mule plugins to develop your Mule applications within Maven, and to control Mule ESB instances from within a Maven environment.

To work with Maven outside Studio, you need to modify your Maven installation to enable it to work with Mule. These modifications entail adding support for Mule plugins and adding the MuleSoft community or Enterprise repositories.

This section contains the following pages:

* link:/mule-user-guide/v/3.8-m1/maven-tools-for-mule-esb[Maven Tools for Mule ESB] – Describes the Mule plugin that allows you to develop Mule applications in Maven
* link:/mule-user-guide/v/3.8-m1/mule-maven-plugin[Mule Maven Plugin] - Describes the Mule plugin that allows you to control Mule ESB from within Maven
* link:/mule-user-guide/v/3.8-m1/configuring-maven-to-work-with-mule-esb[Configuring Maven to Work with Mule ESB] – Details how to modify your Maven configuration to work with Mule plugins and add Mule repositories
