= Anypoint Studio July 2014 with 3.5.1 Runtime - Update Site 2 Release Notes
:keywords: release notes, anypoint studio


July 31, 2014

This July 31 2014 release is an update to the Studio July 2014 with 3.5.1 runtime, and complement the link:/documentation/display/current/Anypoint+Studio+July+2014+with+3.5.1+Runtime+Release+Notes[Anypoint Studio July 2014 with 3.5.1 Runtime Release Notes].

== Current Release Versions

[cols="3*", options="header"]
|===
|
| Enterprise Runtime
| Community Runtime

| ESB Runtime
| n/a
| n/a

| Studio
2+^| Version: July 2014 with 3.5.1 Runtime - Update Site 2 +
Build Number:  201407311443

| Management Console
| n/a
| n/a

| Mule DevKit
2+^| n/a

|===


== Improvements

* Fixed a bug in Maven Support which caused the classpath not to be updated if the user edited the pom.xml file manually in some cases (STUDIO-5363). 
* Fixed a performance issue that would end up in the properties editor taking a long time to render. 
* Fixed metadata generation for some BAPIs that represented corner cases in SAP (field names with special characters). 
* Fixed a bug with the numberOfConsumers attribute in the ActiveMQ connector which would cause it to disappear. 
* Fixed an issue which would cause the General tab of the CXF element not to be drawn (STUDIO-5340). 
* Fixed a bug regarding Batch references or Flow references when the referencing element is in a file located in a different folder than the referenced element (STUDIO-5343) . 
* Fixed a bug regarding data mapping which would cause the pipe delimiter not to be respected if it was the original separator when providing an example (STUDIO-5337). 
* Fixed an issue with User defined Lookup Tables in DataMapper (STUDIO-5367) 
* Fixed an issue with BigDecimal precision in DataMapper that would cause it to default to 2 d.p. +


== Migration Guide

This section presents configuration considerations you may want to adjust when migrating from a previous version of a Mule runtime, or previous version of Studio. mailto:support@mulesoft.com[Contact MuleSoft] if you have a question about a specific migration activity or concern.

To migrate from a previous version of Studio, use *Help > Check for Updates.*


== Support Resources

* For further details on Anypoint Studio with 3.5.1 Runtime, see the link:/documentation/display/current/Anypoint+Studio+July+2014+with+3.5.1+Runtime+Release+Notes[Anypoint Studio July 2014 with 3.5.1 Runtime Release Notes].
* Refer to MuleSoft’s http://www.mulesoft.org/documentation/display/current/Home[MuleSoft Documentation] for instructions on how to use the new features and improved functionality in Anypoint Studio with 3.5.1 Runtime.
* Access MuleSoft’s http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal].
