= Microsoft SharePoint 2010 Connector Release Notes

Guide: link:/mule-user-guide/microsoft-sharepoint-2010-connector[Microsoft SharePoint 2010 Connector]

== Version 1.0 - May 8, 2015

=== Version 1.0 Compatibility

The Microsoft SharePoint 2010 connector is compatible with:

[width="100%",cols="20a,80a",options="header"]
|===
|Application/Service
|Version
|Mule Runtime	|3.5.n
|Anypoint Studio	|January 2015
|Microsoft SharePoint	|2010
|===

=== Version 1.0.0 Features

* SharePoint 2010 API - Broad support for the SharePoint 2010 SOAP API, including specific operations for Lists and List Items, and Files & Folders.
* Lists and List Items - Ability to query and manipulate Lists or any List-derived type such as Document Libraries, Picture Lists, and to manage the items within those lists.
* Files and Folders - Manage folders and files in any SharePoint library, including the ability to perform advanced workflow operations such as check-out, check-in, publish, unpublished, and recycle.
* DataSense and DSQL Support - Full support for DataSense to expose the input and output schema of operations for entities, making it simple to discover the API during development.
* Flexible Authentication - Provides support for claims-based authentication, NTLM based authentication, and Kerberos authentication.
