= Mule 1.0-RC3 Release Notes
:keywords: release notes, esb


Mule 1.0-RC3 includes a New Security infrastucture, new transports such as Jdbc, Ssl and Xmpp (Jabber) an improved transaction managament, new routing capabilities, and a load of new enhancements and bug fixes. +
You can download the latest release here.

==  *Security Manager (beta)*

Mule has a new security infrastucture that enables endpoint authentication and UMO Component level authorisation. There is a default Security implementation that uses http://acegisecurity.sourceforge.net[Acegi] security for Spring that supports JAAS, LDAP, CAS (Central Authentication Server and DAO mechanisms. Also, More support for encryption and encoding has been added. +


==  *Jdbc Provider* +

the Jdbc Provider introduces Mule Endpoint-style access for any Jdbc compliant database. It also supports User and Xa transactions. +


==  *Ssl Transport Provider* +

The Ssl transport enables secure socket communications. +


==  *Xmpp (Jabber) Transport Provider* +

The Xmpp transport enables events to be sent and received over the Jabber protocol. +


==  *Transaction Management* +

Mule transaction management has been rewritten to simplify Transaction configuration including XA transactions. +


==  *Plexus Support* +

The http://plexus.codehaus.org[Plexus container] can now be used to wire your UMO Components and provide services to other Mule object. +
Read More... +
 +

==  *Response Router* +

A Response router is a new type of router that can be used to introduce asynchronous processing to request/response calls. Events can be fired concurrently and the Response router will aggregate results before returning a response. Read More... +
 +

==  *Http Improvements*

* Https is now supported
* The Http receiver supports HTTP 1.1 Keep-Alive meaning that sockets can be kept open over multiple requests. +
Read More... +
 +

==  *Axis Improvements*

* We have optimised Axis Http for Asynchronous requests
* Support for Doc/Lit style services
* Can control WSDL generation by setting WSDL properties on the UMOComponent
* http://www.apache.org/dyn/closer.cgi/ws/axis/1_2RC3[Axis 1.2-RC3] supports proper Auto type mapping, which is enabled by default in Mule. +
Read More... +
 +

==  *Bug fixes, Tests and Documentation* +

There have been loads of bug fixes and new tests added to Mule. Plus new and updated <<Bug fixes, Tests and Documentation>>.


I would like to thank everyone who reported issues and ideas and helped fix bugs. Special thanks go to

* link:/documentation/display/~gnt[Guillaume Nodet] for all his work on transaction managment and Jdbc support.
* link:/documentation/display/~topping[Brian Topping] for helping the move to http://www.codehaus.org[codehaus] and for the Plexus support.
* link:/documentation/display/~bob[bobo bob] for hosting Mule at the codehaus.
* Peter Braswell for the Xmpp Transport.
