= Mule 1.4 Release Notes
:keywords: release notes, esb


Mule 1.4 marks a rich feature release for the leading open source ESB and integration platform. The Mule team would like to thank the user community for all their input, patches and ideas that contributed to this release. Keep 'em coming!

*  The new BPM Connector enables Mule to interact with BPM engines. The first such engine to be supported is http://www.jboss.com/products/jbpm[JBoss jBPM].  See it in action with the new LoanBroker BPM example.

*  Support for streaming is now available. Streaming allows for efficient reading and processing of very large files without reading them into memory. Streaming is currently supported for TCP, FILE, HTTP and SOAP (XFire).  This is an Beta release for the new Streaming model.

*  The new Nested Router allows developers to bind Mule endpoints to interface methods on their service objects allowing 'callouts' to remote services simply by calling a method in the service object.

*  The transports code base has had a bit of an overhaul and now using much more efficient state handling and concurrency management.

*  It is now possible to define more than one service model in your Mule Xml configuration. This means you can mix and match different processing models such as Streaming, SEDA, pipeline, etc.

*  There are a host of JMX Management improvements, namely Remote restart and remote stop of Mule nodes, multi-NIC servers support for RMI-based JMX-remoting, MX subsystem has been refactored for ease of use and Mule look n' feel for bundled MX4J web console.

*  JMS Improvements

** Much improved JMS 1.0.2b backwards compatibility
** Dedicated support for Weblogic 8.x destinations
** Dedicated support for WebsphereMQ for smoothing some of its wrinkles
** connection strategy retry improvements for Jms

*  There are some API and configuration changes that may affect your upgrade to Mule 1.4. Please take at the 1.4 Migration Guide if you are upgrading your Mule.

*  A boatload of bug fixes and improvements have been made. These are listed below.

== Notes

This release ships without the Mule webapp example. We discovered the bug fairly late in the release process and didn't want to hold back the release because of that. See http://mule.mulesource.org/jira/browse/MULE-1604[MULE-1604] for details.
