= Mule 1.1 Release Notes
:keywords: release notes, esb


The Mule team are pleased to announce the release of Mule 1.1!

This release sees a huge number of features such as JBI integration, BPEL support, new EJB and RMI features, improved SOAP features and lots of smaller improvements and bug fixes.

We'd like to send out a big thanks to all the Mule user who have been submitting patches, new features and providing suggestions and support on the mailing list. +


== Mule 1.1


* Mule Transports, Components and Transformers can be used inside any Jbi compliant container. Additionally, Mule components can interact with Jbi containers using the new Jbi binding.

*WS-BPEL*

* Mule integrates with http://www.fivesight.com[FiveSight's] http://www.fivesight.com/pxe.shtml[PXE] WS-BPEL execution engine. To run PXE inside Mule you just need to point the Pxe componet to a BPEL deployment archive.

*EJB*

* Ejb Session beans can be managed as Mule components. Mule will load the beans from an existing container.
* A new Ejb Transport has been introduced so that events from Mule can be dispatched to Ejbs.

*New Transports*

* Rmi Transport can be used to invoke remote objects.
* Quartz Transport Introduces scheduling featured to Mule.
* Ftp Transport Allows Mule events to be sent and received over ftp.

*Other Noteworthy Improvements*

* You can now make soap requests using Axis over any Mule transport such as Jms, Vm or Xmpp (Jabber). To plug in a new transport for a soap request simply change the http protocol to jms, vm, etc.
* Soap Named Parameter support and Wsdl generation have been improved to make it much eaiser to invoke non-Java Web services.
* Xmpp (Jabber) Transport has been improved to support group chats and different message types such as Presence.
* A new Stock Quote Example demonstrates how to invoke .Net web services and use Mule transformers to return the result as a Java object.
* Routing configuration has been simplified in the MuleXml dtd. It is now much clearer to see how to setup reply-to endpoints and response routers.
* The Spring Event Multicaster now supports Asynchronous messaging.
* New routers such as the ExceptionBasedRouter have been added.
* New OGNL filters and transformers.
* Mule now supports attachments for any transport that understands attachments such as Soap and Smtp
* Improved Xml transformers so that Mule events can be easily sent over lower-level protocols such as tcp where headers are not supported.
* A REST service wrapper component that allows a remote service to be used as a local Mule service.
* Components and endpoints can now be started in a stopped state and can be started programmatically or via Jmx.
* Jmx Remote support.
* Improvements have been made for dynamically updating the server state at runtime such as adding/removing a component, endpoints, etc.
