= Mule 1.4.2 Release Notes
:keywords: release notes, esb


The Mule Team are pleased to announce the release of version 1.4.2. This is a maintenance release that sees nearly 100 reported issues closed. The highlights of this release are -

* Out-of-the-box support for calling component methods without any arguments.
* An easy to use JVM debug switch - just add _-debug_ on the command line.
* Mule Config Visualizer is now bundled with Mule
* JRockit irregularities have been resolved, Mule standalone works on all versions of this JVM now.
* In addition to the existing release packages we also supply Enterprise Archives (EARs) now. They come in two flavors: one generic version which should work with any application server and one specific version for JBoss that works around packaging issues on JBoss. See the JBoss Integration page for details.
* Upgrades of various dependencies for modules and transports.

As always, many thanks to our community for submitting bug reports, patches and improvements to Mule.
