= Mule 0.9.2 Release Notes
:keywords: release notes, esb


There is a whole load of new goodies in this release, including Spring events integration, a new Servlet provider, a powerful mule client, improved routing support, groovy transformer support and more. Not to mention a lot of bug fixes and improvements.

=== Mule Events in Spring

The mule manager can now server as a Spring event broker. Spring beans can send and receive Mule events over jms, smtp, pop3, http or any other mule transport using the Spring events api. Read more...

=== Servlet Provider for REST style services

Is a new provider for sending and receiving events via servlets. There is also a servlet implementation that uses the Servlet provider to enable REST style services access.

=== Mule Client

The <<Mule Client>> is a simple but powerful client for communicating with a mule server. It allows any client such as Jsp, scripting or plain old java to send and receive events through a Mule server.

=== Improved Routing support

Routing has been improved adding standard inbound and outbound router implementations such as -

* Selective Consumer - Filter based message consumption
* Idempotent Receiver - ensure every message received is unique
* Content-based Router - route message based on it's content using filters.
* Message Splitter - Routing message parts to different recipients
* Recipient List - Routing the same message to multiple recipients
* Broadcast Router - Routing the same message over multiple transports +
Of course, it is very easy to implement your own.

=== Spring Autowiring Configuration

Simplified Mule configuration using Springs auto wire functionality. Read more...

=== Improved Jms Synchronous Support

Event chaining from synchronous calls are now propagated across Jms servers using the replyTo feature.

=== Fine Grained Thread pool tuning

More control over threading options for connectors and components. Threading for Message Receivers and Dispatchers can now be controlled separately per connector. +
Thread Pooling now uses the http://gee.cs.oswego.edu/dl/classes/EDU/oswego/cs/dl/util/concurrent/intro.html[oswego] concurrent library.

=== Sample webapp

The http://cvs.sourceforge.net/viewcvs.py/mule/mule/src/samples/mule-webapp/webapp/[sample mule webapp] is a simple demonstration of how to embed mule into a webapp. It also provides an example for using the Servlet provider.

=== Groovy support

You can now transform messages using Mule's new Groovy transformers, thanks to link:/documentation/display/~iandebeer[Ian de Beer].

=== Support for multiple configuration files

You can now split up your mule configurations into smaller units i.e. one config file per component.

=== Support for wildcard endpoints

It is now possible to use wildcard endpoints for receiving events, for example, the following would match 'mule.event.queue' -

* *.event.queue
* mule.*
* \*.event.*

=== Synchronicity can be controlled per event

It is now possible to mix synchronous and asynchronous event calls. Even if the Mule server is running asynchronously, it is now possible to make synchronous event calls.
