= Mule 1.0 Release Notes
:keywords: release notes, esb


The Mule team is very pleased to announce that version 1.0 has been released! +
Mule is a highly scalable object broker and messaging framework that builds on the principals of Enterprise Service Bus (ESB) architecture. +
This release provides a JCA Resource Adapter, IBM AS400 Data Queue support, PGP security and improved exception management. As well lots of minor enhancements and bug fixes. +
 +
Big thanks go out to everyone who gave feedback, submitted patches, fixes and new features for this release! +
 +




==  *JCA Resource Adapter* +

Allows Mule to be easily deployed to a J2EE Application Server or JCA container. +


==  *AS400 Data Queue Support +

Mule can now communication with IBM AS400 data queues in the same way as all other transports making mainframe integration much eaiser. +


==  *PGP Support* +

PGP security for message encryption and signing can now be configured using the Mule security layer. +


==  *Improved Exception Management* +

The Exception hierary has been re-worked to allow for easier exception management and automation. Exception reporting has also be improved. +
Improvements have also been made to Exception Strategies (pluggable exception listener). +


==  *Internationalisation* +

Introduced a simple internationalisation mechanism that is used to internationalise exception messages or any string message and can also be use utilised by Mule extensions. +
