= Release Notes for Mule IDE 2.1.0
:keywords: release notes, mule, ide


This is the first release of Mule IDE featuring support for Mule 3.

New projects can be created from the examples bundled with the Mule release. This feature was rewritten to match examples layout in Mule 2.2.x as well as in Mule 3. You'll notice that we copy over the entire example now (minus a few files that do not make sense in an Eclipse project, such as build files). If the example requires additional jar files, those will be downloaded into the project - a `lib` folder will be created to host those additional jars - and added to the project's classpath.

=== Get it!

In order to prevent confusion with older Mule IDE versions, the update site URL has changed. If you have previously installed Mule IDE from the 2.0 update site you should register a new update site to get Mule IDE 2.1. See the Installation Guide for instructions how to install.

=== Fixed issues

Error rendering macro 'jiraissues' : Unable to determine if sort should be enabled.
