= Setting Up External Identity
:keywords: anypoint platform, permissions, configuring

The Anypoint Platform can be integrated with your organization's external federated identity system. Opting to use federated identity management for the Anypoint Platform gives your users single sign-on access and facilitates OAuth security for APIs using the same identity management system.

MuleSoft currently supports https://www.pingidentity.com/en/products/pingfederate.html[PingFederate] and https://forgerock.org/openam/[OpenAM] for external identity management.

For further information about setup steps, please file a ticket in the support portal by clicking *Support* on the top navigation bar of the Anypoint Platform.

== Instructions for Configuration of PingFederate

The instructions in this document allow you to configure your Anypoint Platform organization with PingFederate so as to federate identity (using SAML 2.0) and use PingFederate as an OAuth 2.0 provider. There are two steps to follow:

. Configure your PingFederate environment to set up your Anypoint Platform organization as a Service Provider.
. Submit the appropriate information about your PingFederate environment and the Service Provider you configured (in the first step) to MuleSoft by completing https://docs.google.com/a/mulesoft.com/forms/d/16ZQjXcLmuXO8140svkjUxywzkZjv01GTgbf_3kfEebQ/viewform[the following form] (for further details, see link:#SettingUpExternalIdentity-form[below]).
. When your organization is converted to use external identity management, any existing applications that were previously created through the Developer Portal will need to be recreated to work with the PingFederate Access Token Enforcement policy.

=== Configuring your PingFederate Environment

Follow the instructions within the http://documentation.pingidentity.com/display/PF610/Identity+Provider+SSO+Configuration[PingFederate documentation] to create a new PingFederate service provider. When configuring the service provider, ensure that you set these specific parameters as follows:

. Choose the Browser SSO Profiles connection template.
. Choose the Browser SSO as the only option that is applied to the connection.
. Configure the “Partner Entity ID (Connection ID)” as <organization domain name>.anypoint.mulesoft.com. You can find the value of <organization domain name> by navigating (as a user within the organization owner role) to the organization information page within the Anypoint Platform Web UI (click gear button on top right).
. Configure the Browser SSO as follows: +
.. For the SAML Profiles associated with your Service Provider connection, ensure that “IdP-Initiated SSO” and “IdP-Initiated SLO” are enabled.
.. From the “Assertion Creation” step, select “Configure Assertion Creation”. +
... Set the “SAML_SUBJECT” value to “urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
... Extend the contract for each of the following (new) fields, and set their format to be “urn:oasis:names:tc:SAML:2.0:attrname-format:basic”: email, company, lastname, firstname
.. Configure your adapter to map the appropriate values to the fields listed in the step above.
. Within the “Protocol Settings” step:
...  Set the “Assertion Consumer Service URL” as follows.
... Keep default values except for binding, where the value must be “POST”.
... Set the “Endpoint URL” to “https://anypoint.mulesoft.com/accounts/login/receive-id”.
.. Ensure that the “Signature Policy” setting has the “Always sign the SAML Assertion” property checked.
.. Ensure that the “Encryption Policy” is set to “None”.
. Configure the Credentials.
.. Choose the Digital Signature Settings.
.. Pick a “Signing Certificate” to use for the digital signature.
... Export the certificate for use when submitting your information to MuleSoft through the PingFederate configuration form.
.. Select “RSA SHA1” as the signing algorithm.

=== Providing MuleSoft the Information Required to Configure Your Anypoint Platform Organization

Work with your MuleSoft account representative to ensure that we are aware of your needs for configuring your organization with PingFederate. Complete https://docs.google.com/a/mulesoft.com/forms/d/16ZQjXcLmuXO8140svkjUxywzkZjv01GTgbf_3kfEebQ/viewform[the following form]. Once you have completed this form, we will get back to you within 48 hours with either the completion of the configuration or follow-up questions to complete the configuration.

== Instructions for Configuration of OpenAM

As with PingFederate, configuring your Anypoint Platform organization for use with OpenAM entails two steps:

. Configure your OpenAM environment to set up your Anypoint Platform organization as a Service Provider.
. Submit the appropriate information about your OpenAM environment and the Service Provider you configured (in the first step) to MuleSoft by completing https://docs.google.com/a/mulesoft.com/forms/d/1ZvNUWU3u0lzLk6H5R3lKcEN2Dcyg1zekc1HYtYIcZP0/viewform?edit_requested=true[the following form] (for further details, see link:#SettingUpExternalIdentity-formOpenAM[below]).
. When your organization is converted to use external identity management, any existing applications that were previously created through the Developer Portal will need to be recreated to work with the OpenAM Access Token Enforcement policy.

=== Configuring your OpenAM Environment

Follow the instructions within the http://openam.forgerock.org/doc/webhelp/admin-guide/set-up-federation.html[OpenAM documentation] to create a new remote service provider. Then, perform the following steps:

. In the XML configuration file for the Service Provider, ensure that the SAML 2 metadata includes the following: +
.. `entityID`: The name of your organization, which you will provide to MuleSoft. The naming convention is `<organization domain name>.anypoint.mulesoft.com`. You can find the value of `<organization domain name>` by navigating (as a user within the organization owner role) to the organization information page within the Anypoint Platform Web UI (click gear button on top right).
.. Look for `AssertionConsumerService`, and set its values to the following:
+

[source,xml]
----
<AssertionConsumerService index="0" isDefault="true" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://anypoint.mulesoft.com/accounts/login/receive-id"/>
----

. Configure the Remote Service Provider as follows: +
.. In *Federation*, select the Service Provider you want to configure. Ensure
 the *NameID Format* list includes the following value: 
+

[source,xml]
----
urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified
----

.. In *Assertion Processing*, configure the Attribute Mapper to map the following attributes to their proper values: `firstname`, `lastname`, `email`, `memberOf` (optional).
.. Ensure the Assertion Consumer Service marked as default is of type `HTTP-POST`, and its Location set to `https://anypoint.mulesoft.com/accounts/login/receive-id` as defined in Step 1b. +

. Configure the identity provider to include the the user ID in the SAML assertion, e.g. by including the following in the NameId Value Map of the identity provider:


[source,xml]
----
urn:oasis:names:tc:SAML:2.0:unspecified=uid
----

. Export the certificate used in your identity provider, which you will provide to MuleSoft through the link:#SettingUpExternalIdentity-formOpenAM[OpenAM configuration form].

=== Providing MuleSoft the Information Required to Configure Your Anypoint Platform Organization

Work with your MuleSoft account representative to ensure that we are aware of your needs for configuring your organization with OpenAM. Complete https://docs.google.com/a/mulesoft.com/forms/d/1ZvNUWU3u0lzLk6H5R3lKcEN2Dcyg1zekc1HYtYIcZP0/viewform?edit_requested=true[the following form]. Once you have completed this form, we will get back to you within 48 hours with either the completion of the configuration or follow-up questions to complete the configuration.

== See Also

* Learn more about link:/docs/display/current/Managing+Accounts+Roles+and+Permissions[managing accounts, roles and permissions].
