= Installing Anypoint Runtime Manager On Premises Edition
:keywords:anypoint runtime manager, arm, on premises
// Insert the download link at line ~193
// Insert the agent download link at line ~319

== Assumptions

This page assumes you have at least a basic understanding of Unix-based systems and networking, and are familiar with the command line.

== Overview

Anypoint Runtime Manager is available to download and install on premise by obtaining the installation ZIP file from MuleSoft. Currently, ARM On-Premises Edition is run via link:https://docs.docker.com/installation/[Docker], an open-source virtualization platform. Docker uses _containers_ to wrap applications in a complete filesystem with everything needed to run, including runtime and configuration data. MuleSoft provides Docker images that contain the different components of ARM On-Premises Edition – complete with configuration – which you can run on Docker.

Docker runs natively on Linux, but you can use it on OS X and Windows via a Linux virtual machine. You can create your own virtual machine with a Linux distribution supported by Docker, or download and use Docker Toolbox, which contains both Docker Machine and Docker Compose. Docker Machine works as a wrapper around a virtual linux machine on which docker runs.

This document contains a brief section to provide orientation on installing Docker on your operating system, and complete instructions for downloading and running ARM on your Docker container.

=== System Requirements

[cols="2*a"]
|===
.2+|Operating system
|RHEL 7.1 or greater
|CentOS 7.1 or greater
.2+|Storage
|20 GB for `var/lib/docker`
|1 GB for home directory
.2+|Docker
|Docker engine 1.6.2 or later
|Docker Compose 1.3.1 or later
.2+|Identity management provider
|OpenAM 11.0 or later
|LDAP v3
|Network ports|80, 8080, 8081, 443, 8443
|===

=== Architecture of ARM on Docker

[TIP]
For a more detailed explanation of Docker, see the link:https://docs.docker.com/introduction/understanding-docker/[Docker documentation].

Docker uses a server-client architecture. It runs as a daemon on a Linux host, where the docker _images_ are stored. A docker image is a template that contains an environment and applications. Using a client application, you tell the Docker daemon to run a _container_ from a specific image. A container is a virtual operating system, built at runtime from the template provided by the image you specified. The container runs the image's applications, for example a Web server.

ARM on premise is a _multi-container application_, i.e. its modules occupy more than one container. ARM uses link:https://docs.docker.com/compose/[Docker Compose], a tool that allows you to bring up or shut down a multi-container application with a single command. If you're using the Docker Toolbox, Docker Compose comes included within it.

To run ARM on premise, you need to:

* Install Docker v1.6 or later, natively or on a virtual machine
* Install Docker Compose
* Subscribe and login to the MuleSoft Docker repo, to download the Docker images for ARM
* Run ARM
* Run a command to seed the authentication database with an initial set of users
* Login to ARM

These steps are detailed below.

== Downloading and Installing Docker

link:http://www.docker.com[Docker] runs natively on Linux, including Debian, Ubuntu, Red Hat, CentOS, Oracle and others.

Docker can also run on OS X (10.6 "Snow Leopard" and above) and Windows (7 and 8.1) using Docker Toolbox. However, we only recommend using Mac or Windows for demonstration purposes. The links to download instructions for OS X and Windows use Docker Toolbox.

Instructions for installing Docker:

* link:https://docs.docker.com/installation/[Linux] (check the link for supported distributions)
* link:https://docs.docker.com/installation/mac/[OS X] (10.6 "Snow Leopard" and above)
* link:https://docs.docker.com/installation/windows/[Windows] (7 and 8.1)

Other resources:

* link:https://docs.docker.com/userguide/[Docker User Guide]

=== Installing Docker Compose

Once you have Docker running, login as root to the Docker host machine, then run the following commands to install Docker Compose:

[code,bash,linenums]
----
curl -L https://github.com/docker/compose/releases/download/1.3.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
----

The above commands download Docker Compose to `/usr/local/bin`, then make the `docker-compose` binary executable.

== Setting Up Connectivity for ARM

This section details connection parameters and recommended settings for connecting to your ARM On-Premises Edition installation. You can complete the steps in this section before or after installing ARM, or you can use your own custom network configuration.

=== Network Parameters

==== Ports

ARM listens for connections on the following ports:

* 80
* 443
* 8080
* 8080
* 8443

Ports 80 and 443 are for the Web interface; ports 8080 and 8443 are used to register Mule servers. These ports must be open for incoming TCP connections on the machine where your ARM installation resides.

Additionally, you must give the ARM host IP address a DNS entry for `anypoint.mulesoft.local`, which is the default domain name for the installation (this can be changed if desired).

=== Host Name (Running Natively)

If you are running Docker natively, you will connect to ARM via `localhost`. You do need to ensure that the ARM ports are open, and that client possess the ARM host's IP address or network host name as described above.

[TIP]
For details on how Docker handles networking on the host OS, see the Docker link:https://docs.docker.com/articles/networking/[Network Configuration] page.

Other clients on your network can connect to your on-premise ARM installation using the network address of the host where ARM resides.

[[host]]
=== Host Name (Running on a Virtual Machine)

If you are running Docker on a virtual machine (as you do when using Docker Machine),  you need to obtain the virtual machine's IP address. This is the IP address that you will use to connect to the ARM instance that you will install on the virtual machine.

==== Using Docker Machine

If you are using Docker Machine, to find out the IP address of your virtual machine, open a terminal on your host machine and run:

[code, bash, linenums]
----
docker machine ip
----


This should return the IP address of the virtual machine.

==== Using a Custom Virtual Machine

If your Docker installation resides on a virtual machine that isn't created through Docker Machine (for example, you have created your own virtual machine with a Linux OS), you will probably need to login to the virtual machine to find out the IP address. If the virtual machine does not have a network interface facing the host OS, you need to create one.

For example, if you are using VirtualBox, it is possible that your virtual machine has a single network interface, used for NAT. NAT stands for Network Address Translation, which allows your virtual machine to access the Internet using the network interface on your host OS. But you need another network interface on your local machine, to enable direct network communications between the host OS and the virtual machine. After you set up this interface, you will use it to connect to your on-premise ARM.

There are several possible ways to set up host OS-virtual OS network communication, which are beyond the scope of this document. The example below describes how to set up network communications when using the https://www.virtualbox.org/[VirtualBox] virtual machine emulator.

==== Example Using VirtualBox

If you created a virtual machine in VirtualBox, by default it will have only one network interface, used for NAT. To see whether this is the case, perform the following steps:

. In VirtualBox Manager, click the virtual machine in the left-hand list, then select *Network* from the settings.
. VirtualBox Manager displays a list of interfaces. *Adapter 1* is probably dedicated to NAT. Check if there is another active interface, and if it is attached to a **Host-only Adapter**. If this is the case, you can skip to step 6.
. If no active interfaces are attached to a Host-only Adapter, select and inactive interface, for example by clicking *Adapter 2* if it is not in use (if the virtual machine is running, you need to shut it down first).
. In the menu for the adapter that you are going to activate, select *Host-only Adapter* in the **Attached to:** drop-down menu.
. Click *OK*, then start your virtual machine. VirtualBox should create a private network on the 192.168.* range and assign an IP to your virtual machine.
. Login to your virtual machine, and check its network interfaces for the "host-only" address. For example, run:
+
[code, bash, linenums]
----
ifconfig -a | grep 192
----
+
Output should be similar to the following:
+
[code, bash, linenums]
----
inet addr:192.168.56.103  Bcast:192.168.56.255  Mask:255.255.255.0
----
+
In this example, the address for your virtual machine is 192.168.56.103.

When you install ARM, you can connect to ARM from your host machine using this address. We recommend, however, that you set up a host name for the IP address, as explained below.

==== Setting Up a Host Name for Your Docker Machine

On your host system (OS X or Windows), open the `hosts` file and add the following line:
+
[code, bash, linenums]
----
<IP address> anypoint.mulesoft.local
----


This maps the Docker virtual machine's IP address to the URL `anypoint.mulesoft.local`.

[TIP]
On OS X, the hosts file is `/etc/hosts`; on Windows, `C:\Windows\System32\Drivers\etc\hosts`.

[NOTE]
Modifying your OS's `hosts` file only provides a network address for your virtual machine on the host OS, i.e. the OS where the `hosts` file resides. To allow other clients to connect to your ARM installation, you should set up name resolution for your network using DNS.

== Installing ARM

Once you have Docker and Compose installed, you need to perform the following steps:

* Download the Anypoint Docker Setup package
* Login
* Run the Docker Compose script to start the system

=== Downloading the Anypoint Docker Setup Package

The package is a .zip file that contains all of the configuration and installation scripts needed to run ARM.

* To obtain the installation ZIP file for Anypoint Docker Setup, contact MuleSoft support.

=== Downloading the ARM Docker Images

==== The Docker User

[TIP]
In these instructions, the "Docker machine" is the Linux host your Docker installation resides on.


Log in to your Docker machine as the root user, or as a user authorized to run Docker commands. In this machine, user `docker` is authorized to run Docker commands. The default password for the user is `tcuser`.

[TIP]
====
In virtual machines you can run Docker commands as a non-root user by adding the user to the `docker` group. To add a user to the `docker` group, run (as root):

[code, bash, linenums]
----
usermod -a -G docker <user>
----

Then log out and back in for the setting to take effect.
====

Running Docker commands as a non-root user is recommended for the commands for logging into Docker Hub and downloading the Docker images.

==== Downloading the Images

On your Docker machine, login to your Docker Hub account.

[code, bash, linenums]
----
docker login -e <email> -p <password> -u <username>
----

This creates a file with your credentials in `~/.docker/config.json` (Docker 1.7) or `~/.dockercfg` (Docker 1.6).

Uncompress the Anypoint Docker Setup .zip file to your Docker machine. The contents expand to a directory, `anypoint-runtime-manager`.

[TIP]
====
Docker Machine is set up to use VirtualBox https://www.virtualbox.org/manual/ch04.html#sharedfolders[shared folders] to enable file transfers between your host OS and the Docker machine. In a normal Docker Machine installation, your home folder should be shared by default to `docker-machine`, and you should see it on the Docker machine by running the `df` command. The output below shows the OS X folder `/Users` mounted on a docker-machine virtual machine.

[code, bash, linenums]
----
Filesystem                Size      Used Available Use% Mounted on
tmpfs                     1.8G    115.3M      1.6G   6% /
tmpfs                  1001.3M      2.6M    998.7M   0% /dev/shm
/dev/sda1                18.2G      8.1G      9.2G  47% /mnt/sda1
cgroup                 1001.3M         0   1001.3M   0% /sys/fs/cgroup
none                    111.0G     97.3G     13.7G  88% /Users
/dev/sda1                18.2G      8.1G      9.2G  47% /mnt/sda1/var/lib/docker/aufs
----

In this case, if the setup file resides on the host OS path `/Users/mary/anypoint-docker-setup.zip`, simply run `unzip /Users/mary/anypoint-docker-setup.zip`.

Another option is to copy the setup file to the Docker machine using `scp` or, if on Windows, `scp.exe` (included in Git for Windows) or https://winscp.net/[WinSCP]. In this case, login as user `docker`, password `tcuser`.
====

Using a terminal, navigate to the `anypoint-runtime-manager` directory. Here you will run the script that downloads the MuleSoft ARM images. The script is `pull-docker-images.sh`.

Run the script as root:

[code, bash, linenums]
----
./pull-docker-images.sh
----

[TIP]
`pull-docker-images.sh` is a http://www.gnu.org/software/bash/[Bash] script. If your Linux installation does not have Bash, open the script with a text editor and modify the first line, from `#!/bin/bash` to `#!/bin/sh`.

The script should begin downloading the appropriate images. The ARM installation weighs approximately 6 GB, so it may take a while to download.

=== Running Docker Compose

After downloading is finished, from `anypoint-runtime-manager` directory run:

[code, bash, linenums]
----
docker-compose up -d
----

This starts up Docker Compose and the ARM containers. Startup can take a few minutes, during which your terminal displays startup messages. Once Docker Compose is up and running, it will occupy the terminal foreground.

NOTE: You need to disable SELinux and iptables if they are enabled on your host OS.

=== Populating the ARM Database

After startup completes, you need to seed the platform database with an initial set of users.On the Docker machine, open another terminal and run the following command while in the ARM folder:

[code, bash, linenums]
----
./seed-database.sh
----

At this point, ARM on premise should be up and running.

== Logging Into ARM

To log in to ARM for the first time, point your browser to the following URL:

[code, bash, linenums]
----
https://anypoint.mulesoft.local/accounts/#/setup
----

Ensure to use `https` instead of `http`, or login will not work.

NOTE: For the above address to work, you need to have set up a DNS entry with this address. For details on how to find out the IP address and set up a network host name, see <<host,above>>.

When you login to ARM for the first time, ARM prompts you to create an organization and user.

After you create an organization and user, to log in to ARM you will be prompted to login using the user account you just created.

Subsequently, to login to ARM you can go to `https://anypoint.mulesoft.local`.

At this point you can begin creating organizations, adding servers, inviting users, etc.

For details on managing API Platform, see link:/anypoint-platform-administration/index[Anypoint Platform Administration].

== Adding a Server to Your ARM On-Premises Edition

[[download_agent]]
=== Downloading Mule Agent for ARM On-Premises Edition

Mule servers communicate to ARM using the link:/cloudhub/the-mule-agent[the Mule agent]. To add a server to your on-premise ARM, you need to https://s3.amazonaws.com/mulesoft-fileshare/onprem-test/agent-setup-onPrem.jar[download] and install the on-premise version of the agent.

The on-premise agent download consists of an installer script, `agent-setup-onPrem.jar`. Place this file in `<MULE_HOME>/bin`. You will run it from this location after completing the required steps in API Platform, as described below.

=== Obtaining the Token for Your Server

For a full description of the steps outlined in this section, see the *Add a Server* section in link:/cloudhub/managing-applications-and-servers-in-the-cloud-and-on-premises[Managing Applications and Servers in the Cloud and On Premises].

In your ARM On-Premises Edition installation, click *Applications* in the navigation bar and select your environment. Then, select *Servers* in the left-hand menu.

ARM provides you with a generic command to install Mule agent on a Mule server and pair the server with ARM. This command includes a token, indicated with the `-H` parameter.

A sample command looks like:

[code, bash, linenums]
----
java -jar agent-setup.jar -H 9658e868-[redacted]-d84e1116b585---1 server-name
----

Copy the _token_ (not the full command) to your clipboard. On the machine where your Mule server resides open a terminal and go to `$MULE_HOME/bin`. Here you should have placed your copy of the Mule agent on-premise installer, `agent-setup-onPrem.jar` (see <<download_agent,above>>).

In the `$MULE_HOME/bin` directory, run the following command:

[code, bash, linenums]
----
java -jar agent-setup-onPrem.jar  -A http://<ARM host>:8080/hybrid/api/v1 -W "wss://<ARM host>:8443/mule" -C https://<ARM host>/accounts -H <token> <server name>
----

Where:

* `<ARM host>`: The IP address or network host name of the machine where ARM resides
* `<token>`: The token provided by ARM for your server
* `<server name>`: The desired name for your server on the ARM platform

For example, the command listed below adds server `testsrv1` to the ARM On-Premises Edition residing on `anypoint.mulesoft.local`:

[code, bash, linenums]
----
java -jar agent-setup-onPrem.jar  -A http://anypoint.mulesoft.local:8080/hybrid/api/v1 -W "wss://anypoint.mulesoft.local:8443/mule" -C https://anypoint.mulesoft.local/accounts -H 9658e868-[redacted]-d84e1116b585---1 testsrv1
----

After you run the command, your server and server status should be listed in ARM's *Servers* page (CloudHub -> <environment> -> Servers).

== Basic Admin Operations with ARM

These commands are run on the Docker machine, as root or as a user authorized to run Docker commands. On Docker Machine, user `docker` is authorized to run Docker commands (for details, see <<The Docker User,above>>).

=== Starting and Stopping ARM On-Premises Edition

On the Docker machine, go to the `full-anypoint-platform` directory, which contains the configuration file for ARM on premise, `docker-compose.yml`. From this directory, run:

[code, bash, linenums]
----
docker-compose stop
----

[code, bash, linenums]
----
docker@docker-machine:/home/docker/full-anypoint-platform# docker-compose stop
Stopping fullanypointplatform_mcm_1...
Stopping fullanypointplatform_nginx_1...
Stopping fullanypointplatform_apiplatform_1...
Stopping fullanypointplatform_hybridrest_1...
Stopping fullanypointplatform_hybriddb_1...
...
----

This command sends a SIGTERM to all running containers. There is a timeout of ten seconds, after which the SIGKILL signal is sent to any remaining running containers. You can modify the timeout value with the `-t` parameter:

[code, bash, linenums]
----
docker-compose stop -t 30
----

To start all ARM containers, use `docker-compose start`.

=== Checking Status of Docker Containers

[code, bash, linenums]
----
docker ps -a
----

The output below shows the listing for a full running ARM On-Premises Edition installation (only the first five columns are displayed).

[code, bash, linenums]
----
CONTAINER ID        IMAGE                                  COMMAND                CREATED             STATUS
4ce947f1da77        mulesoft/mcm                           "catalina.sh run"      2 days ago          Up 2 days
016733805c63        mulesoft/nginx:0.0.4                   "nginx -g 'daemon of   2 days ago          Up 2 days
e236e8814e56        mulesoft/api-platform:0.0.4            "/bin/sh -c 'npm run   2 days ago          Up 2 days
38f21e928e38        mulesoft/hybrid-rest                   "catalina.sh run"      2 days ago          Up 2 days
e7c82f3c2d0a        mulesoft/hybrid-db                     "/docker-entrypoint.   2 days ago          Up 2 days
155f1f630ae0        cogniteev/echo                         "/bin/echo -n"         2 days ago          Exited (0) 2 days ago
d07280c13367        mulesoft/cs-ui:0.0.2                   "/bin/sh -c 'cd dist   2 days ago          Up 2 days
c6a4404d8a7c        mulesoft/authentication-server:0.0.1   "/bin/sh -c 'npm sta   2 days ago          Up 2 days
e141cd747a74        kiyoto/docker-fluentd                  "/usr/local/bin/flue   2 days ago          Up 2 days
f28f7aa1bfba        mulesoft/authentication-db:0.0.1       "/docker-entrypoint.   2 days ago          Up 2 days
8b61593ba351        cogniteev/echo                         "/bin/echo -n"         2 days ago          Exited (0) 2 days ago
a7e85de09521        postgres:9.3                           "/docker-entrypoint.   2 days ago          Up 2 days
ad4384954a6d        mulesoft/object-store                  "npm start"            2 days ago          Up 2 days
dc4fa6ee2ac0        cogniteev/echo                         "/bin/echo -n"         2 days ago          Exited (0) 2 days ago
f285234e8209        mulesoft/mulesoft-shared-ng:0.0.1      "/bin/sh -c 'cd dist   2 days ago          Up 2 days
50deb5cd6763        mulesoft/object-store-db               "/docker-entrypoint.   2 days ago          Up 2 days
2cb910cc6d21        cogniteev/echo                         "/bin/echo -n"         2 days ago          Exited (0) 2 days ago
25876b80a972        cpuguy83/docker-grand-ambassador       "/usr/bin/grand-amba   2 days ago          Up 2 days
----

=== Viewing Logs

Docker stores logs in the directory `<Docker user's home>/dockerlogs`, where `<Docker user's home>` is the home directory of the user who runs Docker commands. If you are running Docker commands as user `docker` on docker-machine, the home directory is `/home/docker`.

Docker log files begin with the date they were created.

[code, bash, linenums]
----
docker@docker-machine:~/dockerlog# ls -l
total 1200
-rw-r--r--    1 root     root        252592 Aug  5 00:10 20150804_0.log
-rw-r--r--    1 root     root        588542 Aug  6 17:37 20150805_0.log
-rw-r--r--    1 root     root        381747 Aug  7 16:30 20150807.b51cbaf472f07e28d.log
----

To view the files, you can use a terminal pager such as `less`:

[code, bash, linenums]
----
less 0150807.b51cbaf472f07e28d.log
----

(Hit <Tab> after typing the first characters of the log filename for auto-completion.)

To search in the log, use `/<string>`. To scroll, use the arrows; to exit, pres `q`. Other commands are available; check this basic http://www.mcsr.olemiss.edu/unixhelp/tasks/display1.3.1.html[online reference] for details.

The `dockerlogs` directory contains logs of startup, shutdown and other events including user operations such as accessing different pages of the ARM Web interface.

=== Obtaining Help With Docker Commands

Running `docker` without parameters prints a help message with options and commands.

[code, bash, linenums]
----
docker@docker-machine:~$ docker
Usage: docker [OPTIONS] COMMAND [arg...]
A self-sufficient runtime for linux containers.
Options:
  --api-cors-header=                   Set CORS headers in the remote API
  -b, --bridge=                        Attach containers to a network bridge
  --bip=                               Specify network bridge IP
...
----

For further details on running and handling Docker containers, see the link:http://docs.docker.com[Docker documentation].
