= Glossary

Provides short definitions of the most commonly used terms across the documentation pages.

* Access Token: a value used by the Consumer to gain access to the Protected Resources on behalf of the User, instead of using the User’s Service Provider credentials.

* APT: an acronym for Annotation Processing Tool for Java. It allows to plug code in to handle annotations in a source file as the code compilation is occuring.

* @Connector: class level annotation used to signal whenever a particular Java class will will export its functionality as a Mule Cloud Connector.

* @Default: parameter or field annotation used to specify a default value to the parameter or field if is not assigned explicitly.

* DevKit: annotation processing tool that increases developer productivity by automatically generating a lot of the boiler plate code and xml required for writing Mule modules. The DevKit enables you to build modules from “plain old Java objects” (POJOs).

* @Module: class level annotation used to signal whenever a particular Java class will participate in Mule as a module.

* @Configurable: field annotation used on instance variables to flag that variable on your POJO as being configurable by the outside world. In order to work properly a public setter for this instance variable is needed.

* Consumer: a website or application that uses OAuth to access the Service Provider on behalf of the User.

* Consumer Developer: an individual or organization that implements a Consumer.

* Consumer Key: a value used by the Consumer to identify itself to the Service Provider.

* Consumer Secret: a secret used by the Consumer to establish ownership of the Consumer Key.

* HttpCallback:

* @Optional: parameter or field annotation used to signal that it is not mandatory to assign a value to it explicitly.

* POJO: an acronym for Plain Old Java Object. The name is used to emphasize that a given object is an ordinary Java Object, not a special object.

* @Processor: method annotation that will hint the processor that a particular method can be consumed as a [http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/processor/MessageProcessor.html[MessageProcessor]].

* Protected Resource(s): Data controlled by the Service Provider, which the Consumer can access through authentication.

* Request Token: a value used by the Consumer to obtain authorization from the User, and exchanged for an Access Token.

* Service Provider: a web application that allows access via OAuth.

* @Source: method annotation. Similar to _@Processor_, in the sense that instead of generating a [http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/processor/MessageProcessor.html[MessageProcessor]] it will instead hint the generation of a [http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/source/MessageSource.html[MessageSource]]capable of producing messages instead of consuming them.

* SourceCallback:

* Token Secret: a secret used by the Consumer to establish ownership of a given Token.

* @Transformer: method annotation to signal the generation of a wrapper [http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/transformer/Transformer.html[Transformer]] around the method of the POJO. This annotation requires a specific method signature and will not work on every method.

* User: OAuth terminology that referes to an individual who has an account with the Service Provider.
