= Writing Custom Cloud Connectors

Adding special annotations to a standard Java class will expose it as a Mule extension, making it possible to use it within Mule ESB. These annotations will be processed by the DevKit's annotations processing tool that will generate all the necessary Mule specific code. The DevKit provides a special class level annotation that tells the Annotation Processor to export the POJO functionality as a Cloud Connector.

== Prerequisites

In order to develop Cloud Connectors and Mule extensions in general using the Mule DevKit, the following are required:

* Java JDK 1.6+
* Maven 3.x

== The `@Connector` Annotation

The class level annotation `@Connector` indicates that a Java class needs to be processed by the DevKit Annotation Processing Tool and considered as a Cloud Connector.

The `@Connector` annotation defines the following annotation type element declarations:

[width="99",cols="10,70,10,10",options="header"]
|===
|Annotation type element |Description |Required/Optional |Default value
|name |defines the name of the Cloud Connector |REQUIRED | 
|schemaVersion |the version of the schema that will be generated by the DevKit |OPTIONAL |1.0
|namespace |the namespace of the Cloud Connector |OPTIONAL |http://www.mulesoft.org/schema/mule/name
|schemaLocation |the location of the schema file that will be written to the spring.schemas file |OPTIONAL |http://www.mulesoft.org/schema/mule/name/schemaVersion/mule-name.xsd and http://www.mulesoft.org/schema/mule/name/current/mule-name.xsd
|minMuleVersion |the minimum Mule version for which the Cloud Connector is to be used. This will be checked in runtime during the initialize phase of the lifecycle. |OPTIONAL |3.2
|===

== Mule Version Verification

The `minMuleVersion` annotation parameter value is compared at runtime against the version of Mule where it is deployed. This check is done during the Initialization phase and in case the version of the Mule instance is older than `minMuleVersion` the extension will fail to initialize and a proper error message will be logged.

The goal of this verification is to prevent possible runtime errors when the extension is executed in an older Mule version than the one the extension was originally developed for.

== Restrictions

Some restrictions apply to types annotated with `@Connector`:

* Cannot be applied to interfaces
* Cannot be applied to final classes
* Cannot be applied to parametrized classes
* Cannot be applied to non-public classes
* Must contain exactly one method annotated with `@Connect`
* Must contain exactly one method annotated with `@Disconnect`
